"use client";
import { useEffect, useState } from "react";
import { confirmProposalDeposit,getProposalDeposit,refreshProposalDepositInstructions,reopenProposalDeposit,resendProposalDepositInstructions,reverseProposalDeposit } from "@/lib/services/proposalDeposits";
import type { ProposalDepositWithActor } from "@/lib/services/proposalDeposits";

export function AgreementDepositPanel({proposalId,onChange}:{proposalId:string;onChange?:()=>void}){const[deposit,setDeposit]=useState<ProposalDepositWithActor|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);async function load(){setDeposit(await getProposalDeposit(proposalId))}useEffect(()=>{void load().catch(()=>undefined)},[proposalId]);async function run(action:()=>Promise<unknown>){setBusy(true);setError(null);try{await action();await load();onChange?.()}catch(cause){setError(cause instanceof Error?cause.message:"Deposit operation failed.")}finally{setBusy(false)}}if(!deposit)return null;return <div className="mt-3 rounded-lg border border-[#d4af37]/40 bg-[#fffdf4] p-3 text-sm"><b>Required deposit: {money(deposit.required_amount)} · {deposit.status}</b><p>{deposit.payment_method} to {deposit.recipient_name} · {phone(deposit.recipient_phone)}</p><p>Memo: {deposit.rendered_memo}</p>{deposit.received_at&&<p>Confirmed by {deposit.received_by_name||"Management"} on {new Date(deposit.received_at).toLocaleString()}{deposit.received_reference_number?` · ${deposit.received_reference_number}`:""}</p>}<div className="mt-2 flex flex-wrap gap-1">{deposit.status==="Required"&&<><button disabled={busy} className={button} onClick={()=>void run(()=>confirmProposalDeposit(proposalId,{receivedDate:new Date().toISOString().slice(0,10),referenceNumber:window.prompt("Zelle reference number (optional)")||undefined,notes:window.prompt("Confirmation notes (optional)")||undefined}))}>Confirm Deposit Received</button><button disabled={busy} className={button} onClick={()=>void run(()=>refreshProposalDepositInstructions(proposalId))}>Refresh Instructions</button><button disabled={busy} className={button} onClick={()=>void run(()=>resendProposalDepositInstructions(proposalId))}>Resend Instructions</button></>}{deposit.status==="Received"&&<button disabled={busy} className={button} onClick={()=>{const reason=window.prompt("Reason for reversing this deposit confirmation");if(reason?.trim())void run(()=>reverseProposalDeposit(proposalId,reason))}}>Reverse Confirmation</button>}{deposit.status==="Reversed"&&<button disabled={busy} className={button} onClick={()=>void run(()=>reopenProposalDeposit(proposalId))}>Return to Required</button>}</div>{deposit.status!=="Received"&&deposit.status!=="Applied To Invoice"&&<p className="mt-2 font-semibold text-amber-800">Deposit confirmation required before this Agreement can be sent.</p>}{error&&<p className="mt-2 text-red-700">{error}</p>}</div>}
const button="rounded-lg border px-2 py-1 text-xs font-bold text-[#143d1a] disabled:opacity-50";
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);
const phone=(value:string)=>value.length===10?`(${value.slice(0,3)}) ${value.slice(3,6)}-${value.slice(6)}`:value;
