"use client";
import { useEffect, useState } from "react";

type Status = { sync_status:string; event_html_link?:string|null; attendee_warnings?:string[]; last_sync_error?:string|null };

export function JobCalendarStatus({ jobId }: { jobId:string }) {
  const [value,setValue]=useState<Status|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
  async function load(){const response=await fetch(`/api/integrations/google-calendar/jobs/${jobId}/status`),body=await response.json();if(!response.ok)throw new Error(body.error||"Calendar status could not be loaded.");setValue(body)}
  useEffect(()=>{let active=true;void fetch(`/api/integrations/google-calendar/jobs/${jobId}/status`).then(async response=>({response,body:await response.json()})).then(({response,body})=>{if(!response.ok)throw new Error(body.error||"Calendar status could not be loaded.");if(active){setValue(body);setError(null)}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Calendar status could not be loaded.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[jobId]);
  async function sync(){setBusy(true);setError(null);try{const response=await fetch(`/api/integrations/google-calendar/jobs/${jobId}`,{method:"POST"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Calendar sync failed.");await load()}catch(cause){setError(cause instanceof Error?cause.message:"Calendar sync failed.")}finally{setBusy(false)}}
  return <section className="mt-6 rounded-xl border bg-white p-4"><h3 className="font-extrabold text-[#143d1a]">Google Calendar</h3>{loading?<p className="mt-1 text-sm text-neutral-600">Loading Calendar status…</p>:value?<><p className="mt-1 text-sm"><b>{value.sync_status}</b>{value.last_sync_error?` — ${value.last_sync_error}`:""}</p>{value.attendee_warnings?.map(warning=><p key={warning} className="mt-1 text-xs text-amber-700">{warning}</p>)}</>:null}{error&&<p role="alert" className="mt-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{error}</p>}{!loading&&value&&<div className="mt-3 flex gap-2"><button disabled={busy} onClick={()=>void sync()} className="rounded-lg border px-3 py-2 text-sm font-bold">{busy?"Syncing…":"Sync Now / Retry"}</button>{value.event_html_link&&<a target="_blank" rel="noreferrer" href={value.event_html_link} className="rounded-lg border px-3 py-2 text-sm font-bold">Open Calendar Event</a>}</div>}</section>
}
