"use client";
import{useEffect,useState}from"react";import{createQualityCallback,finalizeScopeCompletion,getJobQualityEvidence,recordCustomerFeedback,saveInspection}from"@/lib/services/jobQuality";import{INSPECTION_CATEGORIES,INSPECTION_RESULTS,QUALITY_SEVERITIES,type JobQualityEvidence}from"@/types/jobQuality";
import{JobPerformanceEvidencePanel}from"@/components/jobs/JobPerformanceEvidencePanel";
const field="rounded-lg border border-neutral-300 px-3 py-2 text-sm";const button="rounded-lg bg-[#143d1a] px-3 py-2 text-sm font-bold text-white disabled:opacity-50";
export function JobQualityPanel({jobId,jobNumber,close}:{jobId:string;jobNumber:string;close:()=>void}){const[data,setData]=useState<JobQualityEvidence|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);const[item,setItem]=useState({category:"Scope Completion",result:"Pass",severity:"",notes:""});
 async function load(){setError(null);try{setData(await getJobQualityEvidence(jobId))}catch(e){setError(message(e))}}useEffect(()=>{void load()},[jobId]);async function run(action:()=>Promise<unknown>){setBusy(true);setError(null);try{await action();await load()}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><section className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase text-[#9a7a17]">Job {jobNumber}</p><h2 className="text-xl font-extrabold text-[#143d1a]">Quality evidence</h2></div><button className={field} onClick={close}>Close</button></div><p className="mt-2 text-sm text-neutral-600">Quality evidence is independent from labor efficiency. No score or employee discipline is generated here.</p>{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!data?<p className="mt-5">Loading…</p>:<div className="mt-5 grid gap-4 lg:grid-cols-2">
 <Card title="Inspection"><form onSubmit={e=>{e.preventDefault();void run(()=>saveInspection(jobId,{notes:item.notes,items:[{...item,severity:item.severity||null}],finalize:true}))}} className="grid gap-2"><select className={field} value={item.category} onChange={e=>setItem(x=>({...x,category:e.target.value}))}>{INSPECTION_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select><select className={field} value={item.result} onChange={e=>setItem(x=>({...x,result:e.target.value,severity:["Pass","Not Applicable"].includes(e.target.value)?"":x.severity}))}>{INSPECTION_RESULTS.map(x=><option key={x}>{x}</option>)}</select>{["Needs Attention","Fail"].includes(item.result)&&<select required className={field} value={item.severity} onChange={e=>setItem(x=>({...x,severity:e.target.value}))}><option value="">Select severity</option>{QUALITY_SEVERITIES.map(x=><option key={x}>{x}</option>)}</select>}<textarea className={field} placeholder="Inspection notes" value={item.notes} onChange={e=>setItem(x=>({...x,notes:e.target.value}))}/><button disabled={busy} className={button}>Finalize inspection</button></form><Records rows={data.inspections.map(x=>`${x.inspection_status}: ${x.items.map(y=>`${y.category} — ${y.result}${y.severity?` (${y.severity})`:""}`).join(", ")}`)}/></Card>
 <CallbackCard jobId={jobId} busy={busy} run={run} rows={data.callbacks.map(x=>`${x.severity} ${x.category}: ${x.status} · ${x.attribution}`)}/><ScopeCard jobId={jobId} busy={busy} run={run} rows={data.scopeCompletion.map(x=>`${x.result} · ${x.attribution}${x.explanation?` — ${x.explanation}`:""}`)}/><FeedbackCard jobId={jobId} busy={busy} run={run} rows={data.customerFeedback.map(x=>`${x.rating}/5 · ${x.source}${x.feedback?` — ${x.feedback}`:""}`)}/>
 </div>}{data&&<JobPerformanceEvidencePanel jobId={jobId} quality={data}/>}</section></div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border p-4"><h3 className="mb-3 font-extrabold text-[#143d1a]">{title}</h3>{children}</section>}function Records({rows}:{rows:string[]}){return <ul className="mt-3 space-y-1 text-xs text-neutral-600">{rows.length?rows.map((x,i)=><li key={i} className="rounded bg-neutral-50 p-2">{x}</li>):<li>No evidence recorded.</li>}</ul>}
function CallbackCard({jobId,busy,run,rows}:{jobId:string;busy:boolean;run:(x:()=>Promise<unknown>)=>void;rows:string[]}){const[v,setV]=useState({source:"Customer",severity:"Minor",category:"",notes:""});return <Card title="Callbacks"><form className="grid gap-2" onSubmit={e=>{e.preventDefault();run(()=>createQualityCallback(jobId,v))}}><select className={field} value={v.source} onChange={e=>setV(x=>({...x,source:e.target.value}))}>{["Customer","Management Inspection","Internal Quality Review","Other"].map(x=><option key={x}>{x}</option>)}</select><select className={field} value={v.severity} onChange={e=>setV(x=>({...x,severity:e.target.value}))}>{QUALITY_SEVERITIES.map(x=><option key={x}>{x}</option>)}</select><input required className={field} placeholder="Operational category" value={v.category} onChange={e=>setV(x=>({...x,category:e.target.value}))}/><textarea className={field} placeholder="Notes (no sensitive personal details)" value={v.notes} onChange={e=>setV(x=>({...x,notes:e.target.value}))}/><button disabled={busy} className={button}>Record callback</button></form><Records rows={rows}/></Card>}
function ScopeCard({jobId,busy,run,rows}:{jobId:string;busy:boolean;run:(x:()=>Promise<unknown>)=>void;rows:string[]}){const[v,setV]=useState({result:"Complete",attribution:"Not Applicable",explanation:""}),incomplete=["Partially Complete","Not Complete"].includes(v.result);return <Card title="Scope Completion"><form className="grid gap-2" onSubmit={e=>{e.preventDefault();run(()=>finalizeScopeCompletion(jobId,v))}}><select className={field} value={v.result} onChange={e=>setV(x=>({...x,result:e.target.value}))}>{["Complete","Partially Complete","Not Complete","Not Applicable"].map(x=><option key={x}>{x}</option>)}</select><select className={field} value={v.attribution} onChange={e=>setV(x=>({...x,attribution:e.target.value}))}>{["Not Applicable","Job Execution","Approved / External Circumstance"].map(x=><option key={x}>{x}</option>)}</select><textarea required={incomplete} className={field} placeholder={incomplete?"Operational explanation required":"Optional explanation"} value={v.explanation} onChange={e=>setV(x=>({...x,explanation:e.target.value}))}/><button disabled={busy} className={button}>Finalize scope evidence</button></form><Records rows={rows}/></Card>}
function FeedbackCard({jobId,busy,run,rows}:{jobId:string;busy:boolean;run:(x:()=>Promise<unknown>)=>void;rows:string[]}){const[v,setV]=useState({rating:5,feedback:"",source:"Direct Customer",receivedAt:new Date().toISOString().slice(0,16)});return <Card title="Customer Feedback"><form className="grid gap-2" onSubmit={e=>{e.preventDefault();run(()=>recordCustomerFeedback(jobId,{...v,receivedAt:new Date(v.receivedAt).toISOString()}))}}><input className={field} type="number" min={1} max={5} step={1} value={v.rating} onChange={e=>setV(x=>({...x,rating:Number(e.target.value)}))}/><select className={field} value={v.source} onChange={e=>setV(x=>({...x,source:e.target.value}))}>{["Direct Customer","Follow-Up","Survey","Public Review","Other"].map(x=><option key={x}>{x}</option>)}</select><input required className={field} type="datetime-local" value={v.receivedAt} onChange={e=>setV(x=>({...x,receivedAt:e.target.value}))}/><textarea className={field} placeholder="Original feedback" value={v.feedback} onChange={e=>setV(x=>({...x,feedback:e.target.value}))}/><button disabled={busy} className={button}>Record feedback</button></form><Records rows={rows}/></Card>}
function message(e:unknown){return e instanceof Error?e.message:"Quality evidence could not be saved."}
