import { hasPermission } from "@/lib/auth/permissions";
import { getCurrentProfile } from "@/lib/services/auth";
import { getJobs } from "@/lib/services/jobs";
import { getProposals } from "@/lib/services/proposals";
import { getAgreements } from "@/lib/services/agreements";
import { getInvoices } from "@/lib/services/invoices";
import { getAllClientCommunications } from "@/lib/services/clientCommunications";
import { getOpenTimeEntries } from "@/lib/services/timeEntries";
import { getBusinessSettings } from "@/lib/services/businessSettings";
import { getWalkthroughs } from "@/lib/services/walkthroughs";
import { getSupabaseClient } from "@/lib/supabase/client";
import type { AttentionItem, AttentionStateRecord, AttentionSummary, AttentionView } from "@/types/attention";
import { getPublicSiteUrl } from "@/lib/publicSiteUrl";
import type { CommunicationComposerContext } from "@/types/clientCommunication";
import { isRecurringFrequency } from "@/lib/scheduling/frequency";

export async function getAttentionItems(view: AttentionView = "Active"): Promise<AttentionItem[]> {
  const profile = await getCurrentProfile();
  if (!profile?.is_active) throw new Error("An active StudioScrubz profile is required.");
  const canManageCommunications = hasPermission(profile, "communications.view") && hasPermission(profile, "communications.create");
  const [jobs, walkthroughs, proposals, agreements, invoices, communications, timeEntries, states, settings] = await Promise.all([
    hasPermission(profile, "jobs.view") ? getJobs() : Promise.resolve([]),
    hasPermission(profile, "walkthroughs.view") ? getWalkthroughs() : Promise.resolve([]),
    hasPermission(profile, "proposals.view") ? getProposals() : Promise.resolve([]),
    hasPermission(profile, "agreements.view") ? getAgreements() : Promise.resolve([]),
    hasPermission(profile, "invoices.view") ? getInvoices() : Promise.resolve([]),
    hasPermission(profile, "communications.view") ? getAllClientCommunications() : Promise.resolve([]),
    hasPermission(profile, "timeClock.view") ? getOpenTimeEntries() : Promise.resolve([]),
    getAttentionItemStates(),
    getBusinessSettings().catch(() => null),
  ]);
  const clock = businessClock(settings?.timezone ?? null);
  const today = clock.date, inSeven = addDays(today, 7), inThirty = addDays(today, 30), items: AttentionItem[] = [];
  const routedProposalIds = new Set([...jobs.map((row) => row.proposal_id), ...agreements.map((row) => row.proposal_id)].filter((id): id is string => Boolean(id)));

  for (const walkthrough of walkthroughs.filter((row) => row.status === "New" && !row.walkthrough_date && !row.archived_at && row.measurements.requestSource === "Public Estimate")) {
    const requestedAt = walkthrough.measurements.requestedAt ?? walkthrough.created_at;
    const client = walkthrough.client?.company_name || [walkthrough.client?.first_name, walkthrough.client?.last_name].filter(Boolean).join(" ") || walkthrough.contact_name || "Deleted Client";
    const property = walkthrough.property ? [walkthrough.property.address, walkthrough.property.city].filter(Boolean).join(", ") : "Deleted Property";
    const service = walkthrough.measurements.serviceType || walkthrough.estimate?.service_name || "Service";
    const estimateNumber = walkthrough.measurements.estimateNumber || walkthrough.estimate?.estimate_number || "Estimate";
    const contact = walkthrough.measurements.preferredContactMethod || "Not specified";
    items.push(item(`walkthrough:${walkthrough.id}:requested`, "Walkthrough Requested", "Attention", "Walkthroughs", "Walkthrough requested", `${client} · ${property} · ${service} · ${estimateNumber} · Prefers ${contact} · Requested ${friendlyDate(requestedAt.slice(0, 10))}`, "Walkthrough", walkthrough.id, walkthrough.client_id, estimateNumber, null, null, requestedAt, `/walkthroughs?walkthroughId=${walkthrough.id}`, "Open Walkthrough"));
  }

  for (const job of jobs) {
    const label = job.job_number;
    if (job.status === "Completed") items.push(item(`job:${job.id}:invoice`, "Completed Job Needs Invoice", "Urgent", "Invoices", "Completed job needs an invoice", `${label} - ${job.service_name || "Service"} - ${job.client_name || "Deleted Client"}`, "Job", job.id, job.client_id, label, null, job.scheduled_date, job.created_at, `/jobs?jobId=${job.id}`, "Create Invoice"));
    if (job.status === "Ready to Schedule" && !job.scheduled_date) items.push(item(`job:${job.id}:unscheduled`, "Unscheduled Job", "Attention", "Jobs", "Job needs scheduling", `${label} · ${job.service_name || "Service"} — ${job.client_name || "Deleted Client"}`, "Job", job.id, job.client_id, label, null, null, job.created_at, `/jobs?jobId=${job.id}`, "Schedule Job"));
    if (["Scheduled", "Ready to Schedule"].includes(job.status) && job.scheduled_date && !job.assigned_crew_id) items.push(item(`job:${job.id}:crew`, "Job Needs Crew", "Attention", "Jobs", "Job needs crew assignment", `${label} · ${job.service_name || "Service"} — ${job.client_name || "Deleted Client"}`, "Job", job.id, job.client_id, label, null, job.scheduled_date, job.created_at, `/jobs?jobId=${job.id}`, "Assign Crew"));
    if (job.scheduled_date && job.scheduled_date >= today && job.scheduled_date <= inSeven && !["Completed", "Cancelled", "Archived"].includes(job.status) && !job.archived_at) items.push(item(`job:${job.id}:upcoming`, "Upcoming Job", "Info", "Jobs", "Upcoming job", `${label} · ${job.service_name || "Service"} — ${job.client_name || "Deleted Client"}`, "Job", job.id, job.client_id, label, null, job.scheduled_date, job.created_at, `/jobs?jobId=${job.id}`, "Open Job"));
    if (canManageCommunications && job.client_id && job.scheduled_date && withinReminderWindow(job.scheduled_date, job.start_time, clock.now) && !["Completed", "Cancelled", "Archived"].includes(job.status) && !job.archived_at && !reminderWasSent(communications, "Job", job.id, job.scheduled_date)) {
      const date = friendlyDate(job.scheduled_date), time = job.start_time ? friendlyTime(job.start_time) : null, location = job.property?.address ?? job.property_name;
      items.push(item(`service-reminder:${job.id}:${job.scheduled_date}`, "Service Reminder Due", "Info", "Communications", "Service reminder due", `${label} · ${job.service_name || "Service"} — ${job.client_name || "Deleted Client"}`, "Job", job.id, job.client_id, label, null, job.scheduled_date, job.created_at, `/jobs?jobId=${job.id}`, "Open Job", composer({ clientId: job.client_id, propertyId: job.property_id, jobId: job.id, communicationType: "Service Reminder", client: job.client, fallbackName: job.client_name, email: job.client?.email, phone: job.client?.phone, subject: `Reminder: ${job.service_name || "StudioScrubz Service"} — ${date}`, message: `Hello ${greeting(job.client, job.client_name)},\n\nThis is a reminder that your StudioScrubz ${job.service_name || "service"} is scheduled for ${date}${time ? ` at ${time}` : ""}${location ? ` at ${location}` : ""}.\n\nIf you need to make any changes, please contact us.\n\nThank you,\nStudioScrubz`, sourceType: "Job", sourceId: job.id, metadata: { source: "Job", source_id: job.id, scheduled_date: job.scheduled_date, service_name: job.service_name || "Service" } })));
    }
  }
  for (const proposal of proposals.filter((row) => !row.archived_at && row.status !== "Archived")) {
    if (proposal.status === "Accepted" && proposal.accepted && !routedProposalIds.has(proposal.id)) {
      const recurring = isRecurringFrequency(proposal.frequency);
      items.push(item(`proposal:${proposal.id}:route`, "Accepted Proposal Needs Routing", "Urgent", "Proposals", recurring ? "Accepted proposal needs a Service Agreement" : "Accepted proposal needs a Job", `${proposal.proposal_number} - ${proposal.client_name || "Deleted Client"}`, "Proposal", proposal.id, proposal.client_id, proposal.proposal_number, null, null, proposal.accepted_at ?? proposal.created_at, `/open-proposals?proposalId=${proposal.id}`, recurring ? "Create Agreement" : "Create Job"));
    }
    if (proposal.approval_status === "Pending Approval") items.push(item(`proposal:${proposal.id}:approval`, "Proposal Awaiting Approval", "Attention", "Proposals", "Proposal awaiting approval", `${proposal.proposal_number} · ${proposal.client_name || "Deleted Client"}`, "Proposal", proposal.id, proposal.client_id, proposal.proposal_number, null, null, proposal.created_at, `/open-proposals?proposalId=${proposal.id}`, "Review Proposal"));
    if (proposal.approval_status === "Approved" && ["Approved", "Sent", "Viewed"].includes(proposal.status) && !proposal.accepted) items.push(item(`proposal:${proposal.id}:client`, "Proposal Awaiting Client", "Attention", "Proposals", "Proposal awaiting client acceptance", `${proposal.proposal_number} · ${proposal.client_name || "Deleted Client"}${lastFollowup(communications, "proposal_id", proposal.id)}`, "Proposal", proposal.id, proposal.client_id, proposal.proposal_number, proposal.expiration_date, null, proposal.created_at, `/open-proposals?proposalId=${proposal.id}`, "Open Proposal", composer({ clientId: proposal.client_id, propertyId: proposal.property_id, proposalId: proposal.id, communicationType: "Proposal", client: proposal.client, fallbackName: proposal.client_name, email: proposal.customer_email ?? proposal.client?.email, phone: proposal.customer_phone ?? proposal.client?.phone, subject: `Follow-Up: StudioScrubz Proposal ${proposal.proposal_number}`, message: `Hello ${greeting(proposal.client, proposal.client_name)},\n\nWe wanted to follow up regarding your StudioScrubz proposal for ${proposal.result.serviceName}.\n\nPlease let us know if you have any questions or would like to move forward.\n\nThank you,\nStudioScrubz`, sourceType: "Proposal", sourceId: proposal.id, metadata: { proposal_number: proposal.proposal_number } })));
  }
  for (const agreement of agreements) {
    const label = agreement.agreement_number, client = agreement.client?.company_name || [agreement.client?.first_name, agreement.client?.last_name].filter(Boolean).join(" ") || "Deleted Client";
    if (agreement.status === "Sent" && !agreement.client_signed_at) { const validToken = agreement.client_access_token && (!agreement.client_access_token_expires_at || Date.parse(agreement.client_access_token_expires_at) > Date.now()); const reviewUrl = validToken ? `${getPublicSiteUrl()}/agreement/${agreement.client_access_token}` : null; items.push(item(`agreement:${agreement.id}:signature`, "Agreement Awaiting Signature", daysSince(agreement.sent_at) >= 5 ? "Attention" : "Info", "Agreements", "Agreement awaiting signature", `${label} · ${client}${agreement.sent_at ? ` · Sent ${daysSince(agreement.sent_at)} days ago` : ""}${lastFollowup(communications, "agreement_id", agreement.id)}${!validToken ? " · Secure link must be refreshed from Agreement Resend" : ""}`, "Service Agreement", agreement.id, agreement.client_id, label, null, null, agreement.created_at, `/agreements?agreementId=${agreement.id}`, "Open Agreement", validToken ? composer({ clientId: agreement.client_id, propertyId: agreement.property_id, agreementId: agreement.id, communicationType: "Service Agreement", client: agreement.client, fallbackName: client, email: agreement.sent_to ?? agreement.client?.email, phone: agreement.client?.phone, subject: `Reminder: StudioScrubz Service Agreement ${label}`, message: `Hello ${greeting(agreement.client, client)},\n\nThis is a friendly reminder that your StudioScrubz Service Agreement is awaiting your review and signature.\n\nPlease use your secure agreement link to review and sign the agreement.\n\nThank you,\nStudioScrubz`, handoffSuffix: reviewUrl ? `\n\nReview & Sign Agreement:\n${reviewUrl}` : null, sourceType: "Service Agreement", sourceId: agreement.id, metadata: { agreement_number: label, follow_up: true, secure_link_included: true } }) : null)); }
    if (agreement.status === "Accepted") items.push(item(`agreement:${agreement.id}:activate`, "Agreement Accepted Not Active", "Attention", "Agreements", "Accepted agreement needs activation", `${label} · ${client}`, "Service Agreement", agreement.id, agreement.client_id, label, null, null, agreement.created_at, `/agreements?agreementId=${agreement.id}`, "Activate Agreement"));
    if (agreement.status === "Active" && !agreement.auto_renew && agreement.end_date && agreement.end_date >= today && agreement.end_date <= inThirty) items.push(item(`agreement:${agreement.id}:expiring`, "Agreement Expiring", "Attention", "Agreements", "Service Agreement expires soon", `${label} · ${client}`, "Service Agreement", agreement.id, agreement.client_id, label, agreement.end_date, null, agreement.created_at, `/agreements?agreementId=${agreement.id}`, "Open Agreement"));
  }
  for (const invoice of invoices.filter((row) => !row.archived_at && row.balance_due > 0 && !["Paid", "Cancelled", "Archived"].includes(row.status))) {
    const reminderContext = invoice.due_date ? composer({ clientId: invoice.client_id, propertyId: invoice.property_id, invoiceId: invoice.id, communicationType: "Payment Reminder", client: invoice.client, fallbackName: invoice.client_name, email: invoice.customer_email ?? invoice.client?.email, phone: invoice.customer_phone ?? invoice.client?.phone, subject: `Reminder: StudioScrubz Invoice ${invoice.invoice_number}`, message: `Hello ${greeting(invoice.client, invoice.client_name)},\n\nThis is ${invoice.due_date < today ? "a reminder" : "a friendly reminder"} that StudioScrubz Invoice ${invoice.invoice_number} has an outstanding balance of ${money(invoice.balance_due)} and ${invoice.due_date < today ? "was" : "is"} due on ${friendlyDate(invoice.due_date)}.${invoice.due_date < today ? "\n\nPlease contact us if you have any questions regarding your invoice." : ""}\n\nThank you,\nStudioScrubz`, sourceType: "Invoice", sourceId: invoice.id, metadata: { invoice_number: invoice.invoice_number, follow_up: true } }) : null;
    if (invoice.due_date && invoice.due_date < today) items.push(item(`invoice:${invoice.id}:overdue`, "Overdue Invoice", "Urgent", "Invoices", "Invoice overdue", `${invoice.invoice_number} · ${money(invoice.balance_due)} outstanding · ${invoice.client_name || "Deleted Client"}${lastFollowup(communications, "invoice_id", invoice.id)}`, "Invoice", invoice.id, invoice.client_id, invoice.invoice_number, invoice.due_date, null, invoice.created_at, `/invoices?invoiceId=${invoice.id}`, "Open Invoice", reminderContext));
    else if (invoice.due_date && invoice.due_date <= inSeven) items.push(item(`invoice:${invoice.id}:due`, "Invoice Due Soon", "Info", "Invoices", "Invoice due soon", `${invoice.invoice_number} · ${money(invoice.balance_due)} outstanding · ${invoice.client_name || "Deleted Client"}${lastFollowup(communications, "invoice_id", invoice.id)}`, "Invoice", invoice.id, invoice.client_id, invoice.invoice_number, invoice.due_date, null, invoice.created_at, `/invoices?invoiceId=${invoice.id}`, "Open Invoice", reminderContext));
  }
  for (const communication of communications.filter((row) => row.status === "Failed" && !row.archived_at && !communications.some((retry) => retry.status === "Sent" && retry.metadata.retry_of_communication_id === row.id))) items.push(item(`communication:${communication.id}:failed`, "Failed Client Communication", "Urgent", "Communications", "Client communication failed", `${communication.communication_number} · ${communication.subject || communication.communication_type}`, "Communication", communication.id, communication.client_id, communication.communication_number, null, null, communication.created_at, communication.client_id ? `/clients?clientId=${communication.client_id}` : "/clients", "View Client", { clientId: communication.client_id, propertyId: communication.property_id, estimateId: communication.estimate_id, proposalId: communication.proposal_id, agreementId: communication.agreement_id, invoiceId: communication.invoice_id, communicationType: communication.communication_type, channel: communication.channel, clientName: "Client", recipientEmail: communication.recipient_email, recipientPhone: communication.recipient_phone, subject: communication.subject ?? "", messageBody: communication.message_body ?? "", sourceType: "Communication Retry", sourceId: communication.id, metadata: { retry_of_communication_id: communication.id } }));
  for (const entry of timeEntries.filter((row) => row.status === "Open" && !row.clock_out && !row.archived_at)) items.push(item(`time:${entry.id}:open`, "Open Time Entry", "Attention", "Time", "Time entry is still open", `${entry.time_entry_number} · ${entry.employee ? [entry.employee.first_name, entry.employee.last_name].filter(Boolean).join(" ") : "Deleted Employee"}`, "Time Entry", entry.id, null, entry.time_entry_number, null, entry.work_date, entry.created_at, "/time-clock", "Open Time Clock"));
  const actionableKeys = new Set(items.map((entry) => entry.id));
  const activeStates = states.filter((state) => actionableKeys.has(state.attention_key));
  await removeResolvedAttentionStates(profile.id, states.filter((state) => !actionableKeys.has(state.attention_key)));
  const stateMap = new Map(activeStates.map((state) => [state.attention_key, state]));
  return items.map((entry) => ({ ...entry, attention_state: effectiveState(stateMap.get(entry.id), clock.now) }))
    .filter((entry) => view === "All" || (view === "Active" ? !entry.attention_state : entry.attention_state?.state === view))
    .sort((a, b) => rank(a.severity) - rank(b.severity) || (a.due_date ?? a.scheduled_date ?? "9999").localeCompare(b.due_date ?? b.scheduled_date ?? "9999") || b.created_at.localeCompare(a.created_at));
}

export async function getAttentionSummary(): Promise<AttentionSummary> { const all = await getAttentionItems("All"), active = all.filter((item) => !item.attention_state); return { ...summarizeAttention(active), snoozed: all.filter((item) => item.attention_state?.state === "Snoozed").length }; }
export function summarizeAttention(items: AttentionItem[]): AttentionSummary { return { urgent: items.filter((x) => x.severity === "Urgent").length, attention: items.filter((x) => x.severity === "Attention").length, info: items.filter((x) => x.severity === "Info").length, total: items.length, snoozed: items.filter((x) => x.attention_state?.state === "Snoozed").length }; }
export async function getAttentionItemStates(): Promise<AttentionStateRecord[]> { const { data, error } = await getSupabaseClient().from("attention_item_states").select("*").order("updated_at", { ascending: false }); if (error) throw new Error(`Attention state could not be loaded: ${error.message}`); return data as AttentionStateRecord[]; }
export async function snoozeAttentionItem(attentionKey: string, until: string): Promise<void> { if (Date.parse(until) <= Date.now()) throw new Error("Choose a future snooze time."); await saveState(attentionKey, "Snoozed", until); }
export async function dismissAttentionItem(attentionKey: string): Promise<void> { await saveState(attentionKey, "Dismissed", null); }
export async function restoreAttentionItem(attentionKey: string): Promise<void> { const profile = await getCurrentProfile(); if (!profile) throw new Error("Authentication is required."); const { error } = await getSupabaseClient().from("attention_item_states").delete().eq("user_id", profile.id).eq("attention_key", attentionKey); if (error) throw new Error(`Attention item could not be restored: ${error.message}`); }
async function saveState(attentionKey: string, state: "Snoozed" | "Dismissed", until: string | null) { const profile = await getCurrentProfile(); if (!profile) throw new Error("Authentication is required."); const { error } = await getSupabaseClient().from("attention_item_states").upsert({ user_id: profile.id, attention_key: attentionKey, state, snoozed_until: state === "Snoozed" ? until : null, dismissed_at: state === "Dismissed" ? new Date().toISOString() : null }, { onConflict: "user_id,attention_key" }); if (error) throw new Error(`Attention state could not be saved: ${error.message}`); }
async function removeResolvedAttentionStates(userId: string, states: AttentionStateRecord[]) { if (!states.length) return; const { error } = await getSupabaseClient().from("attention_item_states").delete().eq("user_id", userId).in("attention_key", states.map((state) => state.attention_key)); if (error) throw new Error(`Resolved attention state could not be cleared: ${error.message}`); }
function item(id: string, type: AttentionItem["type"], severity: AttentionItem["severity"], category: AttentionItem["category"], title: string, description: string, record_type: string, record_id: string, client_id: string | null, entity_label: string | null, due_date: string | null, scheduled_date: string | null, created_at: string, action_url: string, action_label: string, communication_context: CommunicationComposerContext | null = null): AttentionItem { const dismissible = type === "Upcoming Job" || type === "Service Reminder Due" || type === "Failed Client Communication" || severity === "Info"; return { id, type, severity, category, title, description, record_type, record_id, client_id, entity_label, due_date, scheduled_date, created_at, action_url, action_label, metadata: {}, snoozable: true, dismissible, attention_state: null, communication_context }; }
function localDate(date = new Date()) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function addDays(value: string, days: number) { const date = new Date(`${value}T12:00:00`); date.setDate(date.getDate() + days); return localDate(date); }
function daysSince(value: string | null) { return value ? Math.max(0, Math.floor((Date.now() - Date.parse(value)) / 86400000)) : 0; }
function rank(value: AttentionItem["severity"]) { return value === "Urgent" ? 0 : value === "Attention" ? 1 : 2; }
function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value); }
function effectiveState(state: AttentionStateRecord | undefined, now: Date) { if (!state) return null; if (state.state === "Snoozed" && (!state.snoozed_until || Date.parse(state.snoozed_until) <= now.getTime())) return null; return state; }
function withinReminderWindow(date: string, time: string | null, now: Date) { const scheduled = new Date(`${date}T${time?.slice(0, 5) || "09:00"}:00`); const delta = scheduled.getTime() - now.getTime(); return delta >= 0 && delta <= 48 * 60 * 60 * 1000; }
function reminderWasSent(rows: Awaited<ReturnType<typeof getAllClientCommunications>>, source: string, sourceId: string, scheduledDate: string) { return rows.some((row) => row.communication_type === "Service Reminder" && row.status === "Sent" && row.metadata.source === source && row.metadata.source_id === sourceId && row.metadata.scheduled_date === scheduledDate); }
function businessClock(timeZone: string | null) { const now = new Date(); if (!timeZone) return { now, date: localDate(now) }; try { const parts = new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(now); const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value ?? "00"; const date = `${get("year")}-${get("month")}-${get("day")}`; return { date, now: new Date(`${date}T${get("hour")}:${get("minute")}:00`) }; } catch { return { now, date: localDate(now) }; } }
function composer(input: { clientId: string | null; propertyId?: string | null; proposalId?: string; agreementId?: string; invoiceId?: string; jobId?: string; communicationType: CommunicationComposerContext["communicationType"]; client: { first_name: string | null; last_name: string | null; company_name: string | null; email: string | null; phone: string | null } | null; fallbackName: string | null; email?: string | null; phone?: string | null; subject: string; message: string; handoffSuffix?: string | null; sourceType: string; sourceId: string; metadata: CommunicationComposerContext["metadata"] }): CommunicationComposerContext { return { clientId: input.clientId, propertyId: input.propertyId, proposalId: input.proposalId, agreementId: input.agreementId, invoiceId: input.invoiceId, jobId: input.jobId, communicationType: input.communicationType, channel: "Email", clientName: displayName(input.client, input.fallbackName), recipientEmail: input.email ?? null, recipientPhone: input.phone ?? null, subject: input.subject, messageBody: input.message, handoffSuffix: input.handoffSuffix, sourceType: input.sourceType, sourceId: input.sourceId, metadata: input.metadata }; }
function displayName(client: { first_name: string | null; last_name: string | null; company_name: string | null } | null, fallback: string | null) { return client?.company_name || [client?.first_name, client?.last_name].filter(Boolean).join(" ") || fallback || "Client"; }
function greeting(client: { first_name: string | null; company_name: string | null } | null, fallback: string | null) { return client?.first_name?.trim() || client?.company_name?.trim() || fallback || "Client"; }
function friendlyDate(value: string) { return new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" }).format(new Date(`${value}T12:00:00`)); }
function friendlyTime(value: string) { const [h, m] = value.slice(0, 5).split(":").map(Number); return new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit" }).format(new Date(2000, 0, 1, h, m)); }
function lastFollowup(rows: Awaited<ReturnType<typeof getAllClientCommunications>>, field: "proposal_id" | "agreement_id" | "invoice_id", id: string) { const found = rows.find((row) => row[field] === id && row.status === "Sent"); return found ? ` · Last follow-up ${friendlyDate((found.sent_at ?? found.created_at).slice(0, 10))}` : ""; }
