import{getSupabaseClient}from"@/lib/supabase/client";import type{EmployeePerformanceReview,EmployeePerformanceWorkflow}from"@/types/employeePerformance";
function normalize(x:EmployeePerformanceReview){return{...x,measured_points:Number(x.measured_points),measured_max_points:Number(x.measured_max_points),overall_score:x.overall_score===null?null:Number(x.overall_score)}}
export async function calculateEmployeePerformance(employeeId:string,days:30|90,end:string){const{data,error}=await getSupabaseClient().rpc("calculate_employee_performance_review",{p_employee_id:employeeId,p_period_days:days,p_period_end:end});if(error)throw error;return normalize(data)}
export async function finalizeEmployeePerformance(id:string){const{data,error}=await getSupabaseClient().rpc("finalize_employee_performance_review",{p_review_id:id});if(error)throw error;return normalize(data)}
export async function getEmployeePerformanceReviews(employeeId?:string|null){const{data,error}=await getSupabaseClient().rpc("get_employee_performance_reviews",{p_employee_id:employeeId??null});if(error)throw error;return(data??[]).map(normalize)}
export async function getEmployeePerformanceWorkflow(employeeId?:string|null){const{data,error}=await getSupabaseClient().rpc("get_employee_performance_workflow",{p_employee_id:employeeId??null});if(error)throw error;const x=data as unknown as EmployeePerformanceWorkflow;return{...x,reviews:x.reviews.map(normalize)}}
export async function respondToPerformanceReview(id:string,response:"Acknowledged"|"Disputed",comment:string){const{error}=await getSupabaseClient().rpc("respond_to_employee_performance_review",{p_review_id:id,p_response:response,p_comment:comment});if(error)throw error}
export async function createCoachingRecord(input:{employeeId:string;reviewId:string|null;type:string;category:string;summary:string;expectations:string;evidenceContext:string;startDate:string;followUpDate:string|null;targetReviewDate:string|null}){const{error}=await getSupabaseClient().rpc("create_employee_coaching_record",{p_employee_id:input.employeeId,p_review_id:input.reviewId,p_type:input.type,p_category:input.category,p_summary:input.summary,p_expectations:input.expectations,p_evidence_context:input.evidenceContext,p_start_date:input.startDate,p_follow_up_date:input.followUpDate,p_target_review_date:input.targetReviewDate});if(error)throw error}
export async function respondToCoaching(id:string,response:"Acknowledged"|"Disputed",comment:string){const{error}=await getSupabaseClient().rpc("respond_to_employee_coaching",{p_coaching_id:id,p_response:response,p_comment:comment});if(error)throw error}
export function performanceBand(score:number|null){return score===null?"Insufficient Evidence":score>=90?"Excellent":score>=80?"Strong":score>=70?"Needs Attention":"Performance Review Required"}
export function performanceTrend(values:Array<number|null>){const measured=values.filter((x):x is number=>x!==null);if(measured.length<2)return"Insufficient Evidence" as const;const delta=measured[0]-measured[1];return delta>=2?"Improving" as const:delta<=-2?"Declining" as const:"Stable" as const}
