import {getSupabaseClient} from "@/lib/supabase/client";import type {Expense,ExpenseCategorySummary,ExpenseInput,ExpenseSummary,ExpenseUpdate,ExpenseWithRelations} from "@/types/expense";
const select="*,client:clients!expenses_client_id_fkey(*),property:properties!expenses_property_id_fkey(*),job:jobs!expenses_job_id_fkey(*),employee:employees!expenses_employee_id_fkey(*)";
export async function getExpenses():Promise<ExpenseWithRelations[]>{const{data,error}=await getSupabaseClient().from("expenses").select(select).order("expense_date",{ascending:false});if(error)throw error;return data as ExpenseWithRelations[]}
export async function getExpenseById(id:string):Promise<ExpenseWithRelations>{const{data,error}=await getSupabaseClient().from("expenses").select(select).eq("id",id).single();if(error)throw error;return data as ExpenseWithRelations}
export async function createExpense(input:ExpenseInput):Promise<Expense>{for(let i=0;i<5;i++){const{data,error}=await getSupabaseClient().from("expenses").insert({...input,expense_number:number()}).select().single();if(!error)return data;if(error.code!=="23505")throw error}throw new Error("A unique expense number could not be generated.")}
export async function updateExpense(id:string,input:ExpenseUpdate):Promise<Expense>{const{data,error}=await getSupabaseClient().from("expenses").update(input).eq("id",id).select().single();if(error)throw error;return data}
export const voidExpense=(id:string)=>updateExpense(id,{status:"Voided"});export const archiveExpense=(id:string)=>updateExpense(id,{status:"Archived",archived_at:new Date().toISOString()});
export async function getExpensesForDateRange(start:string|null,end:string|null){let q=getSupabaseClient().from("expenses").select(select).eq("status","Active").is("archived_at",null);if(start)q=q.gte("expense_date",start);if(end)q=q.lte("expense_date",end);const{data,error}=await q;if(error)throw error;return data as ExpenseWithRelations[]}
export function getExpenseSummary(rows:Expense[]):ExpenseSummary{const active=rows.filter(x=>x.status==="Active"&&!x.archived_at),now=new Date(),month=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`,year=String(now.getFullYear());const total=(x:Expense[])=>x.reduce((s,v)=>s+Number(v.amount),0);return{thisMonth:total(active.filter(x=>x.expense_date.startsWith(month))),thisYear:total(active.filter(x=>x.expense_date.startsWith(year))),average:active.length?total(active)/active.length:0,taxDeductible:total(active.filter(x=>x.is_tax_deductible)),largest:Math.max(0,...active.map(x=>Number(x.amount)))}}
export function getExpensesByCategory(rows:Expense[]):ExpenseCategorySummary[]{const active=rows.filter(x=>x.status==="Active"&&!x.archived_at),total=active.reduce((s,x)=>s+Number(x.amount),0),map=new Map<string,number>();for(const x of active)map.set(x.category,(map.get(x.category)??0)+Number(x.amount));return[...map].map(([category,value])=>({category,total:value,percentage:total?value/total*100:0})).sort((a,b)=>b.total-a.total)}
function number(){const d=new Date();return`EXP-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}-${String(Math.floor(Math.random()*10000)).padStart(4,"0")}`}
