import { getSupabaseClient } from "@/lib/supabase/client";
import { getJobById } from "@/lib/services/jobs";
import type { Invoice, InvoiceLineItem, InvoiceStatus, InvoiceUpdate, InvoiceWithRelations } from "@/types/invoice";

const select = "*, job:jobs!invoices_job_id_fkey(*, proposal:proposals!jobs_proposal_id_fkey(*), client:clients!jobs_client_id_fkey(*), property:properties!jobs_property_id_fkey(*)), proposal:proposals!invoices_proposal_id_fkey(*), client:clients!invoices_client_id_fkey(*), property:properties!invoices_property_id_fkey(*)";

export async function getInvoices():Promise<InvoiceWithRelations[]>{const{data,error}=await getSupabaseClient().from("invoices").select(select).order("created_at",{ascending:false});if(error)throw error;return data as InvoiceWithRelations[]}
export async function getInvoiceById(id:string):Promise<InvoiceWithRelations>{const{data,error}=await getSupabaseClient().from("invoices").select(select).eq("id",id).single();if(error)throw error;return data as InvoiceWithRelations}
export async function getInvoiceForJob(jobId:string):Promise<InvoiceWithRelations|null>{const{data,error}=await getSupabaseClient().from("invoices").select(select).eq("job_id",jobId).is("archived_at",null).maybeSingle();if(error)throw error;return data as InvoiceWithRelations|null}
export async function getInvoicedJobIds():Promise<string[]>{const{data,error}=await getSupabaseClient().from("invoices").select("job_id").is("archived_at",null);if(error)throw error;return[...new Set((data??[]).map(x=>x.job_id))]}
export async function createInvoiceFromJob(jobId:string):Promise<InvoiceWithRelations>{const job=await getJobById(jobId);if(job.status!=="Completed")throw new Error("Only completed Jobs can be invoiced.");const existing=await getInvoiceForJob(jobId);if(existing)return existing;const amount=Math.max(job.proposal?.result?.perVisitTotal??job.price,0);const item:InvoiceLineItem={id:crypto.randomUUID(),description:job.service_name||"StudioScrubz service",quantity:1,rate:amount,amount};const issue=localDate();const input={job_id:job.id,proposal_id:job.proposal_id,client_id:job.client_id,property_id:job.property_id,client_name:job.client_name,property_name:job.property_name,customer_phone:job.proposal?.customer_phone??null,customer_email:job.proposal?.customer_email??null,service_name:job.service_name,status:"Open" as InvoiceStatus,issue_date:issue,due_date:addDays(issue,15),line_items:[item],subtotal:amount,discount:0,tax:0,total:amount,amount_paid:0,balance_due:amount,notes:job.internal_notes,terms:"Payment due within 15 days."};for(let attempt=0;attempt<5;attempt++){const{data,error}=await getSupabaseClient().from("invoices").insert({...input,invoice_number:invoiceNumber()}).select(select).single();if(!error)return data as InvoiceWithRelations;if(error.code==="23505"){const duplicate=await getInvoiceForJob(jobId);if(duplicate)return duplicate;continue}throw error}throw new Error("A unique invoice number could not be generated.")}
export async function updateInvoice(id:string,input:InvoiceUpdate):Promise<Invoice>{const{data,error}=await getSupabaseClient().from("invoices").update(input).eq("id",id).select().single();if(error)throw error;return data as Invoice}
export async function saveInvoice(id:string,input:{line_items:InvoiceLineItem[];discount:number;taxRate:number;issue_date:string;due_date:string|null;notes:string|null;terms:string|null}){const subtotal=round(input.line_items.reduce((sum,x)=>sum+Math.max(x.quantity,0)*Math.max(x.rate,0),0));const discount=Math.min(Math.max(input.discount,0),subtotal);const tax=round(Math.max(subtotal-discount,0)*Math.max(input.taxRate,0)/100);const total=round(Math.max(subtotal-discount+tax,0));const current=await getInvoiceById(id);return updateInvoice(id,{...input,line_items:input.line_items.map(x=>({...x,amount:round(Math.max(x.quantity,0)*Math.max(x.rate,0))})),subtotal,discount,tax,total,balance_due:Math.max(round(total-current.amount_paid),0),status:paymentStatus(current.status,current.amount_paid,total),paid_at:current.amount_paid>=total&&total>0?current.paid_at??new Date().toISOString():null})}
export async function sendInvoice(id:string,via:"Text"|"Email"){const invoice=await getInvoiceById(id);if(via==="Text"&&!invoice.customer_phone)throw new Error("This invoice does not have a customer phone number.");if(via==="Email"&&!invoice.customer_email)throw new Error("This invoice does not have a customer email address.");return updateInvoice(id,{status:"Sent",sent_at:new Date().toISOString()})}
export const cancelInvoice=(id:string)=>updateInvoice(id,{status:"Cancelled"});
export const archiveInvoice=(id:string)=>updateInvoice(id,{status:"Archived",archived_at:new Date().toISOString()});
export async function recalculateInvoicePaymentTotals(id:string){const db=getSupabaseClient();const invoice=await getInvoiceById(id);const{data,error}=await db.from("payments").select("amount").eq("invoice_id",id);if(error)throw error;const paid=round((data??[]).reduce((sum,row)=>sum+Number(row.amount),0));const balance=Math.max(round(invoice.total-paid),0);const status:InvoiceStatus=paid>=invoice.total&&invoice.total>0?"Paid":paid>0?"Partially Paid":invoice.status==="Draft"?"Draft":invoice.status==="Sent"?"Sent":"Open";return updateInvoice(id,{amount_paid:paid,balance_due:balance,status,paid_at:status==="Paid"?invoice.paid_at??new Date().toISOString():null})}
export async function markPastDueInvoices(rows:InvoiceWithRelations[]){const due=rows.filter(x=>x.due_date&&x.due_date<localDate()&&x.balance_due>0&&!(["Paid","Cancelled","Archived","Past Due"] as InvoiceStatus[]).includes(x.status));if(!due.length)return false;const{error}=await getSupabaseClient().from("invoices").update({status:"Past Due"}).in("id",due.map(x=>x.id));if(error)throw error;return true}
function paymentStatus(current:InvoiceStatus,paid:number,total:number):InvoiceStatus{if(paid>=total&&total>0)return"Paid";if(paid>0)return"Partially Paid";return current==="Draft"?"Draft":current==="Sent"?"Sent":"Open"}
function invoiceNumber(){const d=new Date();return`INV-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}-${String(Math.floor(Math.random()*10000)).padStart(4,"0")}`}
function localDate(d=new Date()){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function addDays(date:string,n:number){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);return localDate(d)}
const round=(n:number)=>Math.round(n*100)/100;
