import {getSupabaseClient} from "@/lib/supabase/client";
import type {MileageCalculationInput,MileageEntry,MileageInput,MileageSummary,MileageUpdate,MileageWithRelations} from "@/types/mileage";
const select="*, vehicle:vehicles!mileage_entries_vehicle_id_fkey(*), employee:employees!mileage_entries_employee_id_fkey(*), crew:crews!mileage_entries_crew_id_fkey(*), job:jobs!mileage_entries_job_id_fkey(*), client:clients!mileage_entries_client_id_fkey(*), property:properties!mileage_entries_property_id_fkey(*)";
export async function getMileageEntries():Promise<MileageWithRelations[]>{const{data,error}=await getSupabaseClient().from("mileage_entries").select(select).order("trip_date",{ascending:false});if(error)throw error;return data as MileageWithRelations[]}
export async function getMileageById(id:string):Promise<MileageWithRelations>{const{data,error}=await getSupabaseClient().from("mileage_entries").select(select).eq("id",id).single();if(error)throw error;return data as MileageWithRelations}
export async function getMileageForJob(jobId:string):Promise<MileageWithRelations[]>{const{data,error}=await getSupabaseClient().from("mileage_entries").select(select).eq("job_id",jobId).order("trip_date",{ascending:false});if(error)throw error;return data as MileageWithRelations[]}
export function calculateMileage(input:MileageCalculationInput){let miles:number;if(input.startOdometer!==null&&input.endOdometer!==null){if(input.endOdometer<input.startOdometer)throw new Error("End odometer cannot be less than start odometer.");miles=input.endOdometer-input.startOdometer}else{miles=Math.max(0,input.manualMiles)*(input.roundTrip?2:1)}const deductibleAmount=miles*Math.max(0,input.mileageRate??0);return{miles:round(miles),deductibleAmount:round(deductibleAmount)}}
export async function createMileageEntry(input:MileageInput):Promise<MileageEntry>{for(let i=0;i<5;i++){const calc=calculateMileage({startOdometer:input.start_odometer,endOdometer:input.end_odometer,manualMiles:input.miles,roundTrip:input.round_trip,mileageRate:input.mileage_rate});const{data,error}=await getSupabaseClient().from("mileage_entries").insert({...input,miles:calc.miles,deductible_amount:calc.deductibleAmount,mileage_number:number()}).select().single();if(!error)return data;if(error.code!=="23505")throw error}throw new Error("A unique mileage number could not be generated.")}
export async function updateMileageEntry(id:string,input:MileageInput):Promise<MileageEntry>{const calc=calculateMileage({startOdometer:input.start_odometer,endOdometer:input.end_odometer,manualMiles:input.miles,roundTrip:input.round_trip,mileageRate:input.mileage_rate});const{data,error}=await getSupabaseClient().from("mileage_entries").update({...input,miles:calc.miles,deductible_amount:calc.deductibleAmount} satisfies MileageUpdate).eq("id",id).select().single();if(error)throw error;return data}
export async function voidMileageEntry(id:string){const{data,error}=await getSupabaseClient().from("mileage_entries").update({status:"Voided"}).eq("id",id).select().single();if(error)throw error;return data}
export async function archiveMileageEntry(id:string){const{data,error}=await getSupabaseClient().from("mileage_entries").update({status:"Archived",archived_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;return data}
export function getMileageSummary(rows:MileageEntry[]):MileageSummary{const active=rows.filter(x=>x.status==="Active"&&!x.archived_at),now=new Date(),month=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`,year=String(now.getFullYear());return{thisMonth:sum(active.filter(x=>x.trip_date.startsWith(month))),thisYear:sum(active.filter(x=>x.trip_date.startsWith(year))),businessMiles:sum(active.filter(x=>x.business_use)),personalMiles:sum(active.filter(x=>!x.business_use)),deductibleAmount:active.filter(x=>x.business_use).reduce((n,x)=>n+x.deductible_amount,0),averageMiles:active.length?sum(active)/active.length:0}}
function sum(rows:MileageEntry[]){return rows.reduce((n,x)=>n+x.miles,0)}function round(n:number){return Math.round(n*100)/100}function number(){const d=new Date();return`MIL-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}-${String(Math.floor(Math.random()*10000)).padStart(4,"0")}`}
