import {getSupabaseClient} from "@/lib/supabase/client";
import {getJobsForMileageAssociation} from "@/lib/services/jobs";
import type {MileageCalculationInput,MileageEntry,MileageInput,MileageStopInput,MileageStopWithRelations,MileageSummary,MileageWithRelations} from "@/types/mileage";

const stopSelect="*, property:properties!mileage_stops_property_id_fkey(id,client_id,property_name,address,address_line_2,city,state,zip)";
const select=`*, vehicle:vehicles!mileage_entries_vehicle_id_fkey(*), employee:employees!mileage_entries_employee_id_fkey(*), crew:crews!mileage_entries_crew_id_fkey(*), job:jobs!mileage_entries_job_id_fkey(*), client:clients!mileage_entries_client_id_fkey(*), property:properties!mileage_entries_property_id_fkey(*), stops:mileage_stops(${stopSelect})`;

function ordered(row:MileageWithRelations,jobMap:Map<string,Awaited<ReturnType<typeof getJobsForMileageAssociation>>[number]>):MileageWithRelations{return{...row,stops:[...(row.stops??[])].sort((a,b)=>a.stop_order-b.stop_order).map(stop=>({...stop,job:stop.job_id?jobMap.get(stop.job_id)??null:null}))}}
export async function getMileageEntries():Promise<MileageWithRelations[]>{const[{data,error},jobs]=await Promise.all([getSupabaseClient().from("mileage_entries").select(select).order("trip_date",{ascending:false}),getJobsForMileageAssociation()]);if(error)throw error;const jobMap=new Map(jobs.map(job=>[job.id,job]));return(data as unknown as MileageWithRelations[]).map(row=>ordered(row,jobMap))}
export async function getMileageById(id:string):Promise<MileageWithRelations>{const[{data,error},jobs]=await Promise.all([getSupabaseClient().from("mileage_entries").select(select).eq("id",id).single(),getJobsForMileageAssociation()]);if(error)throw error;return ordered(data as unknown as MileageWithRelations,new Map(jobs.map(job=>[job.id,job])))}
export async function getMileageStops(mileageEntryId:string):Promise<MileageStopWithRelations[]>{const[{data,error},jobs]=await Promise.all([getSupabaseClient().from("mileage_stops").select(stopSelect).eq("mileage_entry_id",mileageEntryId).order("stop_order"),getJobsForMileageAssociation()]);if(error)throw error;const jobMap=new Map(jobs.map(job=>[job.id,job]));return(data as unknown as MileageStopWithRelations[]).map(stop=>({...stop,job:stop.job_id?jobMap.get(stop.job_id)??null:null}))}
export async function getMileageForJob(jobId:string):Promise<MileageWithRelations[]>{return(await getMileageEntries()).filter(row=>row.job_id===jobId||row.stops.some(stop=>stop.job_id===jobId))}
export function calculateMileage(input:MileageCalculationInput){let miles:number;if(input.startOdometer!==null&&input.endOdometer!==null){if(input.endOdometer<input.startOdometer)throw new Error("End odometer cannot be less than start odometer.");miles=input.endOdometer-input.startOdometer}else{miles=Math.max(0,input.manualMiles)*(input.roundTrip?2:1)}const deductibleAmount=miles*Math.max(0,input.mileageRate??0);return{miles:round(miles),deductibleAmount:round(deductibleAmount)}}
async function save(id:string|null,input:MileageInput,stops:MileageStopInput[],mileageNumber?:string):Promise<MileageEntry>{const calc=calculateMileage({startOdometer:input.start_odometer,endOdometer:input.end_odometer,manualMiles:input.miles,roundTrip:input.round_trip,mileageRate:input.mileage_rate});const p_entry={...input,mileage_number:mileageNumber,miles:calc.miles,deductible_amount:calc.deductibleAmount};const{data,error}=await getSupabaseClient().rpc("save_mileage_entry_with_stops",{p_entry_id:id,p_entry,p_stops:stops});if(error)throw error;return data}
export async function createMileageEntry(input:MileageInput,stops:MileageStopInput[]=[]):Promise<MileageEntry>{for(let i=0;i<5;i++){try{return await save(null,input,stops,number())}catch(error){if(!isUniqueError(error))throw error}}throw new Error("A unique mileage number could not be generated.")}
export async function updateMileageEntry(id:string,input:MileageInput,stops:MileageStopInput[]=[]):Promise<MileageEntry>{return save(id,input,stops)}
export async function voidMileageEntry(id:string){const{data,error}=await getSupabaseClient().from("mileage_entries").update({status:"Voided"}).eq("id",id).select().single();if(error)throw error;return data}
export async function archiveMileageEntry(id:string){const{data,error}=await getSupabaseClient().from("mileage_entries").update({status:"Archived",archived_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;return data}
export function getMileageSummary(rows:MileageEntry[]):MileageSummary{const active=rows.filter(x=>x.status==="Active"&&!x.archived_at),now=new Date(),month=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`,year=String(now.getFullYear());return{thisMonth:sum(active.filter(x=>x.trip_date.startsWith(month))),thisYear:sum(active.filter(x=>x.trip_date.startsWith(year))),businessMiles:sum(active.filter(x=>x.business_use)),personalMiles:sum(active.filter(x=>!x.business_use)),deductibleAmount:active.filter(x=>x.business_use).reduce((n,x)=>n+x.deductible_amount,0),averageMiles:active.length?sum(active)/active.length:0}}
function isUniqueError(error:unknown){return Boolean(error&&typeof error==="object"&&"code" in error&&(error as{code?:string}).code==="23505")}
function sum(rows:MileageEntry[]){return rows.reduce((n,x)=>n+x.miles,0)}function round(n:number){return Math.round(n*100)/100}function number(){const d=new Date();return`MIL-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}-${String(Math.floor(Math.random()*10000)).padStart(4,"0")}`}
