import { getSupabaseClient } from "@/lib/supabase/client";
import type { Proposal, ProposalAcceptanceMethod, ProposalHistory, ProposalInsert, ProposalStatus, ProposalUpdate, ProposalWithRelations } from "@/types/proposal";
import { buildAcceptedPricingAllocation } from "@/lib/pricing/acceptedPricingAllocation";

const select = "*, client:clients!proposals_client_id_fkey(*), property:properties!proposals_property_id_fkey(*), estimate:estimates!proposals_estimate_id_fkey(*), walkthrough:walkthroughs!proposals_walkthrough_id_fkey(*)";
export async function getProposals(): Promise<ProposalWithRelations[]> { const { data,error }=await getSupabaseClient().from("proposals").select(select).order("created_at",{ascending:false}); if(error) throw error; return data as ProposalWithRelations[]; }
export async function getProposalById(id:string):Promise<ProposalWithRelations>{const{data,error}=await getSupabaseClient().from("proposals").select(select).eq("id",id).single();if(error)throw error;return data as ProposalWithRelations;}
export async function createProposal(input:ProposalInsert):Promise<Proposal>{if(input.estimate_id&&await getProposalForEstimate(input.estimate_id))throw new Error("A proposal already exists for this record.");if(input.walkthrough_id&&await getProposalForWalkthrough(input.walkthrough_id))throw new Error("A proposal already exists for this record.");for(let i=0;i<5;i++){const{data,error}=await getSupabaseClient().from("proposals").insert({...input,proposal_number:number()}).select().single();if(!error){await addProposalHistory(data.id,"Proposal Created",null,"Draft");return data;}if(error.code!=="23505")throw error;}throw new Error("A unique proposal number could not be generated.");}
export async function updateProposal(id:string,input:ProposalUpdate,event="Proposal Edited"):Promise<Proposal>{const current=await getProposalById(id);const{data,error}=await getSupabaseClient().from("proposals").update(input).eq("id",id).select().single();if(error)throw error;await addProposalHistory(id,event,current.status,data.status);return data;}
export const updateProposalStatus=(id:string,status:ProposalStatus,event:string,extra:ProposalUpdate={})=>updateProposal(id,{...extra,status},event);
export function submitProposalForApproval(id:string):Promise<Proposal>{return transitionApproval(id,"Draft",null,{status:"Ready for Approval",approval_status:"Pending Approval"},"Submitted for Approval","Proposal submitted for approval.");}
export function approveProposal(id:string):Promise<Proposal>{return transitionApproval(id,"Ready for Approval","Pending Approval",{status:"Approved",approval_status:"Approved",approved_at:new Date().toISOString(),approved_by:"Master Admin"},"Approved","Proposal approved by Master Admin.");}
export function requestProposalChanges(id:string,notes:string):Promise<Proposal>{return transitionApproval(id,"Ready for Approval","Pending Approval",{status:"Draft",approval_status:"Changes Requested",approved_at:null,approved_by:null,approval_notes:notes||null},"Changes Requested",notes||"Proposal changes requested.");}
export function rejectProposal(id:string,notes:string):Promise<Proposal>{return transitionApproval(id,"Ready for Approval","Pending Approval",{approval_status:"Rejected",approval_notes:notes||null},"Rejected",notes||"Proposal rejected.");}
export async function markProposalSent(id:string,via:"Text"|"Email",delivery:{recipient:string;sender:string;token:string;expiresAt:string;snapshot:Record<string,unknown>}) { const proposal=await getProposalById(id); if(proposal.approval_status!=="Approved")throw new Error("Only approved proposals can be sent."); if(proposal.expiration_date<new Date().toISOString().slice(0,10))throw new Error("Expired proposals must be renewed before sending."); if(via==="Text"&&!proposal.customer_phone)throw new Error("A client phone number is required to send by text."); if(via==="Email"&&!proposal.customer_email)throw new Error("A client email address is required to send by email."); const{data,error}=await getSupabaseClient().rpc("mark_proposal_sent_for_delivery",{p_proposal_id:id,p_via:via,p_recipient:delivery.recipient,p_sender:delivery.sender,p_token:delivery.token,p_token_expires_at:delivery.expiresAt,p_snapshot:delivery.snapshot});if(error)throw error;return data; }
export const markProposalViewed=(id:string)=>updateProposalStatus(id,"Viewed","Marked Viewed",{viewed_at:new Date().toISOString()});
export async function markProposalAccepted(id:string,name:string,method:ProposalAcceptanceMethod){const proposal=await getProposalById(id);const acceptedPricingAllocation=buildAcceptedPricingAllocation(proposal.result);return updateProposalStatus(id,"Accepted","Accepted",{accepted:true,accepted_at:new Date().toISOString(),accepted_by_name:name,acceptance_method:method,result:{...proposal.result,acceptedPricingAllocation}})}
export const markProposalDeclined=(id:string,reason:string)=>updateProposalStatus(id,"Declined","Declined",{accepted:false,declined_at:new Date().toISOString(),decline_reason:reason});
export const renewProposal=(id:string,expiration:string)=>updateProposalStatus(id,"Draft","Proposal Renewed",{approval_status:"Not Submitted",expired_at:null,expiration_date:expiration});
export const archiveProposal=(id:string)=>updateProposalStatus(id,"Archived","Archived",{archived_at:new Date().toISOString()});
export async function getProposalHistory(id:string):Promise<ProposalHistory[]>{const{data,error}=await getSupabaseClient().from("proposal_history").select("*").eq("proposal_id",id).order("created_at",{ascending:false});if(error)throw error;return data;}
export async function addProposalHistory(proposalId:string,eventType:string,previousStatus:string|null,newStatus:string|null,description:string|null=null){const{error}=await getSupabaseClient().from("proposal_history").insert({proposal_id:proposalId,event_type:eventType,previous_status:previousStatus,new_status:newStatus,description,metadata:{},performed_by:"Master Admin"});if(error)throw new Error(`Proposal history could not record ${eventType}: ${error.message}`);}
export async function getProposalForEstimate(id:string){const{data,error}=await getSupabaseClient().from("proposals").select(select).eq("estimate_id",id).is("archived_at",null).maybeSingle();if(error)throw error;return data as ProposalWithRelations|null;}
export async function getProposalForWalkthrough(id:string){const{data,error}=await getSupabaseClient().from("proposals").select(select).eq("walkthrough_id",id).is("archived_at",null).maybeSingle();if(error)throw error;return data as ProposalWithRelations|null;}
export async function expireDueProposals(rows:ProposalWithRelations[]):Promise<boolean>{const today=new Date().toISOString().slice(0,10);const due=rows.filter(p=>p.expiration_date<today&&!p.expired_at&&!['Accepted','Declined','Archived','Expired'].includes(p.status));for(const p of due)await updateProposalStatus(p.id,"Expired","Proposal Expired",{expired_at:new Date().toISOString()});return due.length>0;}
async function transitionApproval(id:string,expectedStatus:ProposalStatus,expectedApproval:Proposal["approval_status"]|null,changes:ProposalUpdate,eventType:string,description:string):Promise<Proposal>{let query=getSupabaseClient().from("proposals").update(changes).eq("id",id).eq("status",expectedStatus);if(expectedApproval)query=query.eq("approval_status",expectedApproval);const{data,error}=await query.select().maybeSingle();if(error)throw new Error(`${eventType} failed: ${error.message}`);if(!data)throw new Error(`Proposal is no longer eligible for ${eventType.toLowerCase()}. Refresh and try again.`);await addProposalHistory(id,eventType,expectedStatus,data.status,description);return data;}
function number(){const d=new Date();return`PROP-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}-${String(Math.floor(Math.random()*10000)).padStart(4,"0")}`;}
