import { getSupabaseClient } from "@/lib/supabase/client";
import type { ProposalDepositRequirement } from "@/types/proposalDeposit";

export type ProposalDepositWithActor=ProposalDepositRequirement&{received_by_name?:string|null};
export async function getProposalDeposit(proposalId:string):Promise<ProposalDepositWithActor|null>{const db=getSupabaseClient(),{data,error}=await db.from("proposal_deposit_requirements").select("*").eq("proposal_id",proposalId).maybeSingle();if(error)throw error;if(!data)return null;let received_by_name:string|null=null;if(data.received_by){const{data:profile}=await db.from("user_profiles").select("display_name,email").eq("id",data.received_by).maybeSingle();received_by_name=profile?.display_name||profile?.email||null}return{...(data as ProposalDepositRequirement),received_by_name}}
export async function getProposalDeposits(){const{data,error}=await getSupabaseClient().from("proposal_deposit_requirements").select("*");if(error)throw error;return data as ProposalDepositRequirement[]}
export async function confirmProposalDeposit(proposalId:string,input:{receivedDate:string;referenceNumber?:string;notes?:string}){const{data,error}=await getSupabaseClient().rpc("confirm_post_construction_deposit",{p_proposal_id:proposalId,p_received_date:input.receivedDate,p_reference_number:input.referenceNumber||null,p_notes:input.notes||null});if(error)throw new Error(error.message);return data}
export async function refreshProposalDepositInstructions(proposalId:string){const{data,error}=await getSupabaseClient().rpc("refresh_post_construction_deposit_instructions",{p_proposal_id:proposalId});if(error)throw new Error(error.message);return data}
export async function reverseProposalDeposit(proposalId:string,reason:string){const{data,error}=await getSupabaseClient().rpc("reverse_post_construction_deposit",{p_proposal_id:proposalId,p_reason:reason});if(error)throw new Error(error.message);return data}
export async function reopenProposalDeposit(proposalId:string){const{data,error}=await getSupabaseClient().rpc("reopen_post_construction_deposit",{p_proposal_id:proposalId});if(error)throw new Error(error.message);return data}
export async function resendProposalDepositInstructions(proposalId:string){const response=await fetch(`/api/proposals/${proposalId}/deposit-instructions/send`,{method:"POST"}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"Deposit instructions could not be sent.");return result}
