import { getSupabaseClient } from "@/lib/supabase/client";
import type { Proposal, ProposalAcceptanceMethod, ProposalHistory, ProposalInsert, ProposalStatus, ProposalUpdate, ProposalWithRelations } from "@/types/proposal";

const select = "*, client:clients!proposals_client_id_fkey(*), property:properties!proposals_property_id_fkey(*), estimate:estimates!proposals_estimate_id_fkey(*), walkthrough:walkthroughs!proposals_walkthrough_id_fkey(*)";
export async function getProposals(): Promise<ProposalWithRelations[]> { const { data,error }=await getSupabaseClient().from("proposals").select(select).order("created_at",{ascending:false}); if(error) throw error; return data as ProposalWithRelations[]; }
export async function getProposalById(id:string):Promise<ProposalWithRelations>{const{data,error}=await getSupabaseClient().from("proposals").select(select).eq("id",id).single();if(error)throw error;return data as ProposalWithRelations;}
export async function createProposal(input:ProposalInsert):Promise<Proposal>{if(input.estimate_id&&await getProposalForEstimate(input.estimate_id))throw new Error("A proposal already exists for this record.");if(input.walkthrough_id&&await getProposalForWalkthrough(input.walkthrough_id))throw new Error("A proposal already exists for this record.");for(let i=0;i<5;i++){const{data,error}=await getSupabaseClient().from("proposals").insert({...input,proposal_number:number()}).select().single();if(!error){await addProposalHistory(data.id,"Proposal Created",null,"Draft");return data;}if(error.code!=="23505")throw error;}throw new Error("A unique proposal number could not be generated.");}
export async function updateProposal(id:string,input:ProposalUpdate,event="Proposal Edited"):Promise<Proposal>{const current=await getProposalById(id);const{data,error}=await getSupabaseClient().from("proposals").update(input).eq("id",id).select().single();if(error)throw error;await addProposalHistory(id,event,current.status,data.status);return data;}
export const updateProposalStatus=(id:string,status:ProposalStatus,event:string,extra:ProposalUpdate={})=>updateProposal(id,{...extra,status},event);
export const submitProposalForApproval=(id:string)=>updateProposalStatus(id,"Ready for Approval","Submitted for Approval",{approval_status:"Pending Approval"});
export const approveProposal=(id:string)=>updateProposalStatus(id,"Approved","Approved",{approval_status:"Approved",approved_at:new Date().toISOString(),approved_by:"Master Admin"});
export const requestProposalChanges=(id:string,notes:string)=>updateProposalStatus(id,"Draft","Changes Requested",{approval_status:"Changes Requested",approval_notes:notes});
export const rejectProposal=(id:string,notes:string)=>updateProposal(id,{approval_status:"Rejected",approval_notes:notes},"Rejected");
export async function markProposalSent(id:string,via:"Text"|"Email") { const proposal=await getProposalById(id); if(proposal.approval_status!=="Approved")throw new Error("Only approved proposals can be sent."); if(proposal.expiration_date<new Date().toISOString().slice(0,10))throw new Error("Expired proposals must be renewed before sending."); if(via==="Text"&&!proposal.customer_phone)throw new Error("A client phone number is required to send by text."); if(via==="Email"&&!proposal.customer_email)throw new Error("A client email address is required to send by email."); return updateProposalStatus(id,"Sent",`Sent by ${via}`,{sent_at:new Date().toISOString(),sent_via:via}); }
export const markProposalViewed=(id:string)=>updateProposalStatus(id,"Viewed","Marked Viewed",{viewed_at:new Date().toISOString()});
export const markProposalAccepted=(id:string,name:string,method:ProposalAcceptanceMethod)=>updateProposalStatus(id,"Accepted","Accepted",{accepted:true,accepted_at:new Date().toISOString(),accepted_by_name:name,acceptance_method:method});
export const markProposalDeclined=(id:string,reason:string)=>updateProposalStatus(id,"Declined","Declined",{accepted:false,declined_at:new Date().toISOString(),decline_reason:reason});
export const renewProposal=(id:string,expiration:string)=>updateProposalStatus(id,"Draft","Proposal Renewed",{approval_status:"Not Submitted",expired_at:null,expiration_date:expiration});
export const archiveProposal=(id:string)=>updateProposalStatus(id,"Archived","Archived",{archived_at:new Date().toISOString()});
export async function getProposalHistory(id:string):Promise<ProposalHistory[]>{const{data,error}=await getSupabaseClient().from("proposal_history").select("*").eq("proposal_id",id).order("created_at",{ascending:false});if(error)throw error;return data;}
export async function addProposalHistory(proposalId:string,eventType:string,previousStatus:string|null,newStatus:string|null,description:string|null=null){const{error}=await getSupabaseClient().from("proposal_history").insert({proposal_id:proposalId,event_type:eventType,previous_status:previousStatus,new_status:newStatus,description,metadata:{},performed_by:"Master Admin"});if(error)throw error;}
export async function getProposalForEstimate(id:string){const{data,error}=await getSupabaseClient().from("proposals").select(select).eq("estimate_id",id).is("archived_at",null).maybeSingle();if(error)throw error;return data as ProposalWithRelations|null;}
export async function getProposalForWalkthrough(id:string){const{data,error}=await getSupabaseClient().from("proposals").select(select).eq("walkthrough_id",id).is("archived_at",null).maybeSingle();if(error)throw error;return data as ProposalWithRelations|null;}
export async function expireDueProposals(rows:ProposalWithRelations[]):Promise<boolean>{const today=new Date().toISOString().slice(0,10);const due=rows.filter(p=>p.expiration_date<today&&!p.expired_at&&!['Accepted','Declined','Archived','Expired'].includes(p.status));for(const p of due)await updateProposalStatus(p.id,"Expired","Proposal Expired",{expired_at:new Date().toISOString()});return due.length>0;}
function number(){const d=new Date();return`PROP-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}-${String(Math.floor(Math.random()*10000)).padStart(4,"0")}`;}
