import { getSupabaseClient } from "@/lib/supabase/client";
import type { CatalogService, RecurringPricingRule, RecurringPricingRuleInput, ServiceAddon, ServiceAddonInput, ServiceCatalogBundle, ServiceInput, ServicePriceTier, ServicePriceTierInput } from "@/types/serviceCatalog";
export async function getServices(){const{data,error}=await getSupabaseClient().from("services").select("*").order("display_order");if(error)throw new Error(`Service catalog could not be loaded: ${error.message}`);return data as CatalogService[]}
export async function getActiveServices(){return(await getServices()).filter(x=>x.is_active&&!x.archived_at)}
export async function getServiceById(id:string){const{data,error}=await getSupabaseClient().from("services").select("*").eq("id",id).single();if(error)throw error;return data as CatalogService}
export async function createService(input:ServiceInput){const duplicate=(await getServices()).some(x=>x.service_code.toLowerCase()===input.service_code.trim().toLowerCase());if(duplicate)throw new Error("A service with this code already exists.");const{data,error}=await getSupabaseClient().from("services").insert({...input,service_code:input.service_code.trim().toUpperCase()}).select().single();if(error)throw error;return data as CatalogService}
export async function updateService(id:string,input:Partial<ServiceInput>){const{data,error}=await getSupabaseClient().from("services").update(input).eq("id",id).select().single();if(error)throw error;return data as CatalogService}
export async function archiveService(id:string):Promise<CatalogService>{const{data,error}=await getSupabaseClient().from("services").update({is_active:false,archived_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;return data as CatalogService}
export async function getServicePriceTiers(serviceId?:string){let q=getSupabaseClient().from("service_price_tiers").select("*").order("display_order");if(serviceId)q=q.eq("service_id",serviceId);const{data,error}=await q;if(error)throw error;return data as ServicePriceTier[]}
export async function createServicePriceTier(input:ServicePriceTierInput){const{data,error}=await getSupabaseClient().from("service_price_tiers").insert(input).select().single();if(error)throw error;return data as ServicePriceTier}
export async function updateServicePriceTier(id:string,input:Partial<ServicePriceTierInput>){const{data,error}=await getSupabaseClient().from("service_price_tiers").update(input).eq("id",id).select().single();if(error)throw error;return data as ServicePriceTier}
export async function getAddons(){const{data,error}=await getSupabaseClient().from("service_addons").select("*").order("display_order");if(error)throw error;return data as ServiceAddon[]}
export async function getActiveAddons(){return(await getAddons()).filter(x=>x.is_active&&!x.archived_at)}
export async function createAddon(input:ServiceAddonInput){const duplicate=(await getAddons()).some(x=>x.addon_code.toLowerCase()===input.addon_code.trim().toLowerCase());if(duplicate)throw new Error("An add-on with this code already exists.");const{data,error}=await getSupabaseClient().from("service_addons").insert({...input,addon_code:input.addon_code.trim().toUpperCase()}).select().single();if(error)throw error;return data as ServiceAddon}
export async function updateAddon(id:string,input:Partial<ServiceAddonInput>){const{data,error}=await getSupabaseClient().from("service_addons").update(input).eq("id",id).select().single();if(error)throw error;return data as ServiceAddon}
export async function archiveAddon(id:string):Promise<ServiceAddon>{const{data,error}=await getSupabaseClient().from("service_addons").update({is_active:false,archived_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;return data as ServiceAddon}
export async function getRecurringPricingRules(){const{data,error}=await getSupabaseClient().from("recurring_pricing_rules").select("*").order("frequency");if(error)throw error;return data as RecurringPricingRule[]}
export async function createRecurringPricingRule(input:RecurringPricingRuleInput){const{data,error}=await getSupabaseClient().from("recurring_pricing_rules").insert(input).select().single();if(error)throw error;return data as RecurringPricingRule}
export async function updateRecurringPricingRule(id:string,input:Partial<RecurringPricingRuleInput>){const{data,error}=await getSupabaseClient().from("recurring_pricing_rules").update(input).eq("id",id).select().single();if(error)throw error;return data as RecurringPricingRule}
export async function getServiceCatalog():Promise<ServiceCatalogBundle>{const[services,tiers,addons,recurringRules]=await Promise.all([getActiveServices(),getServicePriceTiers(),getActiveAddons(),getRecurringPricingRules()]);return{services,tiers,addons,recurringRules:recurringRules.filter(x=>x.is_active)}}
