import { getSupabaseClient } from "@/lib/supabase/client";
import { retryJwtIssuedAtFuture } from "@/lib/supabase/retry";
import type { EstimateDivision } from "@/types/estimate";
import type { CatalogService, RecurringPricingRule, RecurringPricingRuleInput, ServiceAddon, ServiceAddonInput, ServiceAddonLink, ServiceCatalogBundle, ServiceInput, ServiceLabel, ServiceLabelAssignment, ServicePriceTier, ServicePriceTierInput } from "@/types/serviceCatalog";
export async function getServices(){const{data,error}=await getSupabaseClient().from("services").select("*").order("display_order").order("service_name");if(error)throw new Error(`Service catalog could not be loaded: ${error.message}`);return data as CatalogService[]}
export async function getActiveServices(){const{data,error}=await retryJwtIssuedAtFuture(()=>getSupabaseClient().from("services").select("*").eq("is_active",true).is("archived_at",null).order("display_order").order("service_name"));if(error)throw new Error(`Active services could not be loaded: ${error.message}`);return data as CatalogService[]}
export function findCatalogService(services:CatalogService[],division:EstimateDivision,serviceName:string){const normalizedName=normalizeServiceName(serviceName);return services.find(service=>(service.division===division||service.division==="Both")&&normalizeServiceName(service.service_name)===normalizedName)}
function normalizeServiceName(value:string){return value.replace(/ Cleaning$/i,"").trim().toLowerCase()}
export async function getServiceById(id:string){const{data,error}=await getSupabaseClient().from("services").select("*").eq("id",id).single();if(error)throw error;return data as CatalogService}
export async function createService(input:ServiceInput){const duplicate=(await getServices()).some(x=>x.service_code.toLowerCase()===input.service_code.trim().toLowerCase());if(duplicate)throw new Error("A service with this code already exists.");const{data,error}=await getSupabaseClient().from("services").insert({...input,service_code:input.service_code.trim().toUpperCase()}).select().single();if(error)throw error;return data as CatalogService}
export async function updateService(id:string,input:Partial<ServiceInput>){const{data,error}=await getSupabaseClient().from("services").update(input).eq("id",id).select().single();if(error)throw error;return data as CatalogService}
export async function archiveService(id:string):Promise<CatalogService>{const{data,error}=await getSupabaseClient().from("services").update({is_active:false,archived_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;return data as CatalogService}
export async function getServicePriceTiers(serviceId?:string){const{data,error}=await retryJwtIssuedAtFuture(()=>{let q=getSupabaseClient().from("service_price_tiers").select("*").order("display_order");if(serviceId)q=q.eq("service_id",serviceId);return q});if(error)throw error;return data as ServicePriceTier[]}
export async function createServicePriceTier(input:ServicePriceTierInput){const{data,error}=await getSupabaseClient().from("service_price_tiers").insert(input).select().single();if(error)throw error;return data as ServicePriceTier}
export async function updateServicePriceTier(id:string,input:Partial<ServicePriceTierInput>){const{data,error}=await getSupabaseClient().from("service_price_tiers").update(input).eq("id",id).select().single();if(error)throw error;return data as ServicePriceTier}
export async function getAddons(){const{data,error}=await retryJwtIssuedAtFuture(()=>getSupabaseClient().from("service_addons").select("*").order("display_order"));if(error)throw error;return data as ServiceAddon[]}
export async function getActiveAddons(){return(await getAddons()).filter(x=>x.is_active&&!x.archived_at)}
export async function getServiceAddonLinks(){const{data,error}=await retryJwtIssuedAtFuture(()=>getSupabaseClient().from("service_addon_links").select("service_id,addon_id"));if(error)throw error;return data as ServiceAddonLink[]}
export function getAvailableServiceAddons(catalog:Pick<ServiceCatalogBundle,"services"|"addons"|"addonLinks">,serviceId:string,division?:EstimateDivision){const service=catalog.services.find(item=>item.id===serviceId);if(!service)return[];const effectiveDivision=division??service.division;const linkedToService=new Set(catalog.addonLinks.filter(link=>link.service_id===serviceId).map(link=>link.addon_id));const linkedAnywhere=new Set(catalog.addonLinks.map(link=>link.addon_id));return catalog.addons.filter(addon=>{const divisionMatches=addon.division==="Both"||effectiveDivision==="Both"||addon.division===effectiveDivision;return divisionMatches&&(linkedToService.has(addon.id)||!linkedAnywhere.has(addon.id))})}
export async function createAddon(input:ServiceAddonInput){const duplicate=(await getAddons()).some(x=>x.addon_code.toLowerCase()===input.addon_code.trim().toLowerCase());if(duplicate)throw new Error("An add-on with this code already exists.");const{data,error}=await getSupabaseClient().from("service_addons").insert({...input,addon_code:input.addon_code.trim().toUpperCase()}).select().single();if(error)throw error;return data as ServiceAddon}
export async function updateAddon(id:string,input:Partial<ServiceAddonInput>){const{data,error}=await getSupabaseClient().from("service_addons").update(input).eq("id",id).select().single();if(error)throw error;return data as ServiceAddon}
export async function archiveAddon(id:string):Promise<ServiceAddon>{const{data,error}=await getSupabaseClient().from("service_addons").update({is_active:false,archived_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;return data as ServiceAddon}
export async function getRecurringPricingRules(){const{data,error}=await retryJwtIssuedAtFuture(()=>getSupabaseClient().from("recurring_pricing_rules").select("*").order("frequency"));if(error)throw error;return data as RecurringPricingRule[]}
export async function createRecurringPricingRule(input:RecurringPricingRuleInput){const{data,error}=await getSupabaseClient().from("recurring_pricing_rules").insert(input).select().single();if(error?.code==="23505")throw new Error("A recurring pricing rule with this name already exists for the selected service. Use a different rule name or edit the existing rule.");if(error)throw error;return data as RecurringPricingRule}
export async function updateRecurringPricingRule(id:string,input:Partial<RecurringPricingRuleInput>){const{data,error}=await getSupabaseClient().from("recurring_pricing_rules").update(input).eq("id",id).select().single();if(error?.code==="23505")throw new Error("A recurring pricing rule with this name already exists for the selected service. Use a different rule name.");if(error)throw error;return data as RecurringPricingRule}
export async function getServiceLabels(){const{data,error}=await getSupabaseClient().from("service_labels").select("*").order("name");if(error)throw error;return data as ServiceLabel[]}
export async function getServiceLabelAssignments(){const{data,error}=await getSupabaseClient().from("service_label_assignments").select("*");if(error)throw error;return data as ServiceLabelAssignment[]}
export async function getOrCreateServiceLabel(name:string){const{data,error}=await getSupabaseClient().rpc("get_or_create_service_label",{p_name:name});if(error)throw error;return data as ServiceLabel}
export async function setServiceLabels(serviceId:string,labelIds:string[]){const client=getSupabaseClient();const{data:current,error:loadError}=await client.from("service_label_assignments").select("label_id").eq("service_id",serviceId);if(loadError)throw loadError;const currentIds=new Set((current??[]).map(item=>item.label_id as string));const desiredIds=new Set(labelIds);const additions=[...desiredIds].filter(id=>!currentIds.has(id)).map(label_id=>({service_id:serviceId,label_id}));const removals=[...currentIds].filter(id=>!desiredIds.has(id));if(additions.length){const{error}=await client.from("service_label_assignments").insert(additions);if(error)throw error}if(removals.length){const{error}=await client.from("service_label_assignments").delete().eq("service_id",serviceId).in("label_id",removals);if(error)throw error}}
export async function getServiceCatalog():Promise<ServiceCatalogBundle>{const[services,tiers,addons,addonLinks,recurringRules]=await Promise.all([getActiveServices(),getServicePriceTiers(),getActiveAddons(),getServiceAddonLinks(),getRecurringPricingRules()]);return{services,tiers,addons,addonLinks,recurringRules:recurringRules.filter(x=>x.is_active)}}
