import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const sql = readFileSync(resolve("supabase/migrations/20260901005100_addon_quantity_financial_handoff.sql"), "utf8");
const directUi = readFileSync(resolve("components/jobs/DirectJobModal.tsx"), "utf8");
const jobsService = readFileSync(resolve("lib/services/jobs.ts"), "utf8");

assert.match(sql, /alter table public\.jobs add column pricing_snapshot jsonb/);
assert.match(sql, /create or replace function public\.is_valid_job_pricing_snapshot/);
assert.match(sql, /round\(v_base \+ v_addon_total, 2\) = round\(v_total, 2\)/);
assert.match(sql, /round\(v_total, 2\) = round\(p_authoritative_total, 2\)/);
assert.match(sql, /agreement_row\.pricing_snapshot->'accepted_pricing_allocation'/);
assert.match(sql, /job_amount := round\(\(job_pricing_snapshot->>'totalAmount'\)::numeric, 2\)/);
assert.match(sql, /agreement_row\.billing_type = 'Per Visit'/);
assert.match(sql, /else null end/);
assert.match(sql, /p_addon_quantities jsonb default '\[\]'::jsonb/);
assert.match(sql, /v_addon_quantity < 1 or v_addon_quantity <> trunc\(v_addon_quantity\)/);
assert.match(sql, /v_addon_line_total := round\(v_addon_quantity \* v_addon_unit_price, 2\)/);
assert.match(sql, /v_effective_base := round\(v_price - v_addons, 2\)/);
assert.match(sql, /v_effective_base < 0/);
assert.match(sql, /'baseServiceAmount', v_effective_base/);
assert.match(sql, /'totalAmount', v_price/);
assert.match(sql, /if job_row\.pricing_snapshot is null then/);
assert.match(sql, /line_items := jsonb_build_array/);
assert.match(sql, /for snapshot_addon in select value from jsonb_array_elements/);
assert.match(sql, /'quantity'.*snapshot_addon->>'quantity'/s);
assert.match(sql, /'rate'.*snapshot_addon->>'unitPrice'/s);
assert.match(sql, /amount, 0, 0, amount, 0, amount/);
assert.match(sql, /agreement\.billing_type in \('Weekly','Biweekly','Monthly','Flat Contract'\)/);
assert.match(sql, /caller_role not in \('Master Admin','Administrator','Manager','Crew Lead'\)/);
assert.match(sql, /caller_role = 'Crew Lead'/);
assert.match(sql, /for update/);
assert.match(sql, /invoices_one_active_per_job_idx/);
assert.match(sql, /revoke all on function public\.create_direct_operational_job/);
assert.match(sql, /grant execute on function public\.create_completed_job_invoice\(uuid\) to postgres, service_role, authenticated/);
const invoiceFunction = sql.slice(sql.indexOf("create or replace function public.create_completed_job_invoice"));
assert.doesNotMatch(invoiceFunction, /public\\.service_addons/);
assert.match(directUi, /snapshots=\{addonSelections\}/);
assert.match(directUi, /pricingType === "Per Unit"/);
assert.match(directUi, /quantity: item\.quantity \?\? 0/);
assert.match(jobsService, /p_addon_quantities: input\.addon_quantities/);

const calculated = { baseServiceAmount: 200, addonTotal: 12 * 8 };
assert.equal(calculated.baseServiceAmount + calculated.addonTotal, 296);
assert.notEqual(296 + calculated.addonTotal, 296);
assert.equal(275 - calculated.addonTotal, 179);
assert.ok(80 - calculated.addonTotal < 0);
console.log("Add-on quantity financial handoff tests passed.");