import assert from "node:assert/strict";import{readFileSync}from"node:fs";import{test}from"node:test";
const read=p=>readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
const migration=read("supabase/migrations/20260924142944_lead_generator_applications.sql"),careers=read("app/site/careers/page.tsx"),form=read("components/site/LeadGeneratorApplicationForm.tsx"),route=read("app/api/public/careers/lead-generator/route.ts"),server=read("lib/recruiting/leadGeneratorApplications.ts"),management=read("components/recruiting/JobApplicationsPage.tsx"),applicationTypes=read("types/jobApplication.ts"),permissions=read("lib/auth/permissions.ts"),proxy=read("proxy.ts"),footer=read("components/site/SiteChrome.tsx"),sidebar=read("components/layout/Sidebar.tsx");
test("public Careers route uses the marketing shell and footer only",()=>{assert.match(proxy,/"\/careers"/);assert.match(footer,/href="\/careers"[\s\S]*Join Our Team/);assert.match(careers,/metadata:Metadata/);assert.doesNotMatch(sidebar,/href: "\/careers"/);assert.match(careers,/Lead Generator/)});
test("opening wording and responsive accessible application contract are exact",()=>{for(const text of["Commission-Based Opportunity","$25–$75 per qualified booking","3–5% residual commission on recurring commercial bookings","Flexible schedule","This is a commission-based opportunity. Compensation is earned only on qualifying bookings under the StudioScrubz Lead Generator program. Additional terms are provided during onboarding.","Identify homeowners, businesses, contractors, and property managers who may need professional cleaning services.","Ensure each referral identifies the Lead Generator by name."])assert.ok(careers.includes(text));for(const name of["fullName","email","phone","city","preferredContactMethod","relevantExperience","reachableNetworks","weeklyAvailability","fitReason","commissionAcknowledged","contactConsent","website"])assert.match(form,new RegExp(`name=[{]?"${name}"`));assert.match(form,/role="alert"/);assert.match(form,/role="status"/);assert.match(careers,/sm:|lg:/)});
test("public submission is server validated, spam limited, and anonymous data access is absent",()=>{assert.match(route,/attempts=new Map/);assert.match(route,/status:429/);assert.match(server,/raw\.website/);assert.match(server,/submitted_ip_hash/);assert.match(server,/contact_fingerprint/);assert.match(server,/commissionAcknowledged!==true/);assert.match(server,/contactConsent!==true/);assert.match(migration,/enable row level security/g);assert.match(migration,/revoke all on table public\.job_applications, public\.job_application_events from public, anon, authenticated/);assert.match(migration,/grant select, insert, update on table public\.job_applications to service_role/);assert.match(migration,/grant select, insert on table public\.job_application_events to service_role/);assert.doesNotMatch(migration,/grant (select|update|delete|insert).* anon/i);assert.doesNotMatch(migration,/grant[^;]*delete[^;]*service_role/i)});
test("management-only RPCs maintain status history without operational record creation",()=>{assert.match(migration,/has_any_role\(array\['Master Admin','Administrator','Manager'\]\)/g);assert.match(migration,/Status Changed/);assert.match(migration,/actor_user_id/);assert.match(applicationTypes,/New[\s\S]*Contacted[\s\S]*Interviewing[\s\S]*Selected[\s\S]*Declined/);assert.match(management,/mailto:/);assert.match(management,/tel:/);assert.match(permissions,/jobApplications\.manage/);assert.doesNotMatch(migration,/insert into public\.(employees|user_profiles|time_entries|payments|commissions)/i)});
test("email is best effort after durable insert and no SMS or protected fields are collected",()=>{assert.ok(server.indexOf('const created=await db.from("job_applications").insert')<server.indexOf("try{const sent=await sendResendEmail"));assert.match(server,/catch\(cause\).*status:"Failed"/s);assert.doesNotMatch(server,/send.*sms|twilio/i);for(const forbidden of["dateOfBirth","socialSecurity","ssn","banking","race","disability","medical","marital","resume"])assert.doesNotMatch(form,new RegExp(`name=[{]?"${forbidden}"`,"i"))});
test("existing estimate and marketing routes remain present",()=>{assert.match(proxy,/"\/request-estimate"/);for(const path of["/residential","/commercial","/post-construction","/contact"])assert.ok(proxy.includes(`"${path}"`))});
