import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import ts from "typescript";
const lib=fs.readFileSync("lib/prospectDiscovery.ts","utf8");
const route=fs.readFileSync("app/api/prospects/discover/route.ts","utf8");
const ui=fs.readFileSync("components/prospects/ProspectDiscovery.tsx","utf8");
const discovery=await import(`data:text/javascript;base64,${Buffer.from(ts.transpileModule(lib,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString("base64")}`);
test("discovery supports 250 miles",()=>{assert.match(lib,/DISCOVERY_MAX_RADIUS_MILES=250/);assert.match(lib,/100,150,250/);});
test("large searches keep individual Overpass queries bounded",()=>{assert.match(lib,/DISCOVERY_PROVIDER_TILE_RADIUS_METERS=25_000/);const query=discovery.buildOverpassQuery("Commercial Offices",34,-118,402_336);for(const radius of [...query.matchAll(/around:(\d+)/g)].map(match=>Number(match[1])))assert.ok(radius<=25_000);});
test("25-mile searches cover beyond the central provider tile deterministically",()=>{const points=discovery.buildDiscoverySearchPoints(34.2068925,-118.5734436,40_234);assert.ok(points.length>1);assert.deepEqual(points,discovery.buildDiscoverySearchPoints(34.2068925,-118.5734436,40_234));assert.ok(points.some(point=>discovery.haversineMeters(34.2068925,-118.5734436,point.latitude,point.longitude)>25_000));assert.match(lib,/intersectionRadius=radiusMeters\+DISCOVERY_PROVIDER_TILE_RADIUS_METERS/);});
test("server filters tiled results to requested radius",()=>{assert.match(route,/if\(distanceMeters>radiusMeters\)\{diagnostics\.rejectedOutsideRadius\+=1;continue;\}/);});
test("provider work and final results remain bounded",()=>{assert.match(route,/MAX_PROVIDER_REQUESTS=48/);assert.match(route,/points\.slice\(0,MAX_PROVIDER_REQUESTS\)/);assert.match(route,/results\.length>=DISCOVERY_MAX_RESULTS/);assert.doesNotMatch(route,/elements\.length>=DISCOVERY_MAX_RESULTS/);});
test("raw rejected rows do not stop later tiles",()=>{assert.match(route,/diagnostics\.rawElements\+=elements\.length/);assert.match(route,/if\(!name\)\{diagnostics\.rejectedMissingName\+=1;continue;\}/);assert.ok(route.indexOf("diagnostics.rawElements+=elements.length")<route.indexOf("if(!name)"));assert.ok(route.indexOf("if(results.length>=DISCOVERY_MAX_RESULTS)break")<route.indexOf("diagnostics.rawElements+=elements.length"));});
test("normalization keeps coordinate rejection, OSM deduplication, and distance ordering",()=>{assert.match(route,/if\(lat===undefined\|\|lon===undefined\)\{diagnostics\.rejectedMissingCoordinate\+=1;continue;\}/);assert.match(route,/if\(seen\.has\(providerIdentifier\)\)\{diagnostics\.duplicates\+=1;continue;\}/);assert.match(route,/results\.sort\(\(a,b\)=>\(a\.distanceMeters as number\)-\(b\.distanceMeters as number\)\)/);});
test("UI exposes shared radius options",()=>{assert.match(ui,/DISCOVERY_RADIUS_OPTIONS_MILES\.map/);});
