import { StudioScrubzLogo } from "@/components/branding/StudioScrubzLogo";
import type { EstimateWithRelations } from "@/types/estimate";
import type { PublicEstimate } from "@/types/publicEstimate";

export function EstimateDocument({ document }: { document: PublicEstimate }) {
  const recurring=document.recurring_discount_amount??0,manual=document.manual_discount??Math.max(0,document.total_discount-recurring);const pricing: string[][] = [["Base Service Price", money(document.base_price)], ...document.adjustments.map((item) => [item.label, money(item.amount)]), ["Standard / One-Time Price", money(document.one_time_price)], [`${document.frequency} Service Discount`, `${document.recurring_discount_percent??0}%`], ["Recurring Discount", `-${money(recurring)}`], ["Price After Recurring Discount", money(document.price_after_recurring_discount??Math.max(0,document.one_time_price-recurring))], ["Manual / Custom Discount", `-${money(manual)}`], ["Taxes", money(document.taxes)], ["Final Per-Visit Price", money(document.estimated_total)]];
  if (document.monthly_price !== null) pricing.push(["Estimated Monthly", money(document.monthly_price)]);
  return <article id="estimate-document" className="document-print-root mx-auto max-w-3xl bg-white p-6 text-sm text-neutral-800 print:max-w-none print:p-0">
    <Brand document={document}/><h2 className="mt-6 text-2xl font-extrabold text-[#143d1a]">Estimate</h2><p className="font-semibold">{document.estimate_number}</p>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><Detail label="Client" value={document.client_name}/><Detail label="Property / Service Location" value={document.property_location}/><Detail label="Service Type" value={document.service_name}/><Detail label="Frequency" value={document.frequency}/></div>
    <section className="mt-6"><h3 className="font-bold text-[#143d1a]">Service Description</h3><p className="mt-2 whitespace-pre-line">{document.service_description||"No service description available."}</p></section>
    <section className="mt-6"><h3 className="font-bold text-[#143d1a]">Scope / Service Details</h3><ul className="mt-2 list-disc space-y-1 pl-5">{document.scope.map((item,index)=><li key={`${item}-${index}`}>{item}</li>)}</ul></section>
    <section className="mt-6"><h3 className="font-bold text-[#143d1a]">Pricing Breakdown</h3><dl className="mt-2 divide-y border-y">{pricing.map(([label,value])=><div key={label} className={`flex justify-between gap-4 py-2 ${label==="Estimated Total"?"text-base font-extrabold text-[#143d1a]":""}`}><dt>{label}</dt><dd className="font-bold">{value}</dd></div>)}</dl></section>
  </article>;
}
export function estimateDocumentFromRecord(estimate:EstimateWithRelations):PublicEstimate{return{estimate_number:estimate.estimate_number,status:estimate.status,client_name:[estimate.customer_first_name,estimate.customer_last_name].filter(Boolean).join(" ")||estimate.client?.company_name||"Client",client_email:estimate.customer_email||estimate.client?.email||null,client_phone:estimate.customer_phone||estimate.client?.phone||null,property_location:estimate.property?[estimate.property.address,estimate.property.address_line_2,estimate.property.city,estimate.property.state,estimate.property.zip].filter(Boolean).join(", "):"Deleted Property",service_name:estimate.service_name||estimate.result.serviceName,service_description:estimate.result.serviceDescription??null,frequency:estimate.frequency,scope:estimate.result.scope,base_price:estimate.result.basePrice,adjustments:estimate.result.adjustments,one_time_price:estimate.result.oneTimePrice,recurring_discount_percent:estimate.result.recurringDiscountPercent,recurring_discount_amount:estimate.result.recurringDiscount,price_after_recurring_discount:Math.max(0,estimate.result.oneTimePrice-estimate.result.recurringDiscount),manual_discount:estimate.result.manualDiscount,total_discount:estimate.result.totalDiscount,taxes:estimate.result.taxes,estimated_total:estimate.result.finalPrice,monthly_price:estimate.result.monthlyPrice,sent_at:estimate.sent_at,walkthrough_requested:false,walkthrough_requested_at:null,walkthrough_preferred_contact_method:null,business_name:"StudioScrubz",tagline:"No mess. No stress.",business_email:null,business_phone:null,website:null,address:null,city:null,state:null,zip:null}}
export function estimateDeliverySnapshot(estimate:EstimateWithRelations){const d=estimateDocumentFromRecord(estimate);return{estimate_number:d.estimate_number,client_name:d.client_name,client_email:d.client_email,client_phone:d.client_phone,property_location:d.property_location,service_name:d.service_name,service_description:d.service_description,frequency:d.frequency,scope:d.scope,base_price:d.base_price,adjustments:d.adjustments,one_time_price:d.one_time_price,recurring_discount_percent:d.recurring_discount_percent,recurring_discount_amount:d.recurring_discount_amount,price_after_recurring_discount:d.price_after_recurring_discount,manual_discount:d.manual_discount,total_discount:d.total_discount,taxes:d.taxes,estimated_total:d.estimated_total,monthly_price:d.monthly_price}}
function Brand({document}:{document:PublicEstimate}){return <header className="flex flex-col items-center gap-4 border-b-2 border-[#143d1a] pb-4 text-center sm:flex-row sm:text-left"><StudioScrubzLogo size={108}/><div><h1 className="text-3xl font-extrabold text-[#143d1a]">{document.business_name}</h1>{document.tagline&&<p>{document.tagline}</p>}<p>{[document.business_email,document.business_phone,document.website].filter(Boolean).join(" · ")}</p><p>{[document.address,document.city,document.state,document.zip].filter(Boolean).join(", ")}</p></div></header>}
function Detail({label,value}:{label:string;value:string}){return <div><b className="block text-[#143d1a]">{label}</b><span>{value||"—"}</span></div>}function money(value:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value)}
