"use client";
import { useEffect, useMemo, useState } from "react";

type Division="Residential"|"Commercial"; type Service={name:string;description:string|null;division:Division;recurring:boolean;fields:string[];addons:Array<{name:string;description:string|null}>};
type Confirmation={estimateNumber:string;service:string;price:number;customerName:string;address:string};
const blank={firstName:"",lastName:"",companyName:"",phone:"",email:"",address:"",addressLine2:"",city:"",state:"",zip:""};
const input="w-full rounded-xl border border-[#d7ddd5] bg-white px-4 py-3 text-base text-[#18201a] outline-none transition focus:border-[#d4af37] focus:ring-4 focus:ring-[#d4af37]/15";
export function PublicEstimateRequest(){
  const[services,setServices]=useState<Service[]>([]),[division,setDivision]=useState<Division>("Residential"),[service,setService]=useState(""),[customer,setCustomer]=useState(blank),[frequency,setFrequency]=useState("One-Time"),[condition,setCondition]=useState("Average"),[squareFeet,setSquareFeet]=useState(1000),[values,setValues]=useState({bedrooms:2,bathrooms:1,floors:1,restrooms:2,kitchens:1,stations:0,units:0}),[occupied,setOccupied]=useState(true),[pets,setPets]=useState(false),[addons,setAddons]=useState<string[]>([]),[preferredDate,setPreferredDate]=useState(""),[notes,setNotes]=useState(""),[price,setPrice]=useState<number|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState<Confirmation|null>(null),[website,setWebsite]=useState("");
  const available=useMemo(()=>services.filter(x=>x.division===division),[services,division]),selected=available.find(x=>x.name===service)??available[0];
  useEffect(()=>{fetch("/api/public/request-estimate/catalog").then(r=>r.json()).then(data=>{if(data.error)throw new Error(data.error);setServices(data.services)}).catch(e=>setError(e.message))},[]);
  const payload=useMemo(()=>({division,customer,service:selected?.name??service,frequency,condition,squareFeet,...values,occupied,pets,addons,preferredDate,notes,website}),[addons,condition,customer,division,frequency,notes,occupied,pets,preferredDate,selected,service,squareFeet,values,website]);
  useEffect(()=>{if(!selected)return;const controller=new AbortController(),timer=setTimeout(()=>fetch("/api/public/request-estimate/quote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),signal:controller.signal}).then(async r=>{const data=await r.json();if(r.ok)setPrice(data.price);else setPrice(null)}).catch(()=>{}),350);return()=>{clearTimeout(timer);controller.abort()}},[payload,selected]);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/public/request-estimate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw new Error(data.error);setConfirmation(data)}catch(cause){setError(cause instanceof Error?cause.message:"Submission failed.")}finally{setBusy(false)}}
  if(confirmation)return <Confirmation result={confirmation} restart={()=>{setConfirmation(null);setCustomer(blank);setNotes("");setPreferredDate("");setAddons([])}}/>;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#fff9df_0,#f5f6f4_36rem)] px-4 py-8 sm:px-6"><div className="mx-auto max-w-4xl"><header className="mb-7 text-center"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-[#143d1a] text-2xl font-black text-[#d4af37] shadow-lg">SS</div><p className="text-sm font-black uppercase tracking-[.28em] text-[#143d1a]">StudioScrubz</p><h1 className="mt-2 text-3xl font-black text-[#143d1a] sm:text-5xl">Request an Estimate</h1><p className="mt-2 text-lg font-semibold text-neutral-600">No mess. No stress.</p></header>
  <form onSubmit={submit} className="space-y-6"><Card title="What can we clean for you?"><div className="grid grid-cols-2 gap-3">{(["Residential","Commercial"] as Division[]).map(x=><button key={x} type="button" onClick={()=>{setDivision(x);setService("");setAddons([]);setFrequency("One-Time")}} className={`rounded-xl border-2 px-4 py-4 font-extrabold ${division===x?"border-[#d4af37] bg-[#143d1a] text-white":"border-neutral-200 bg-white text-[#143d1a]"}`}>{x}</button>)}</div></Card>
  <Card title="Your information"><div className="grid gap-4 sm:grid-cols-2"><Field label="First Name *" value={customer.firstName} set={v=>setCustomer({...customer,firstName:v})}/><Field label="Last Name *" value={customer.lastName} set={v=>setCustomer({...customer,lastName:v})}/>{division==="Commercial"&&<Field label="Company Name *" value={customer.companyName} set={v=>setCustomer({...customer,companyName:v})}/>}<Field label="Phone *" type="tel" value={customer.phone} set={v=>setCustomer({...customer,phone:v})}/><Field label="Email *" type="email" value={customer.email} set={v=>setCustomer({...customer,email:v})}/></div></Card>
  <Card title="Service location"><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Address *" value={customer.address} set={v=>setCustomer({...customer,address:v})}/></div><div className="sm:col-span-2"><Field label="Address Line 2" value={customer.addressLine2} set={v=>setCustomer({...customer,addressLine2:v})}/></div><Field label="City *" value={customer.city} set={v=>setCustomer({...customer,city:v})}/><Field label="State *" maxLength={2} value={customer.state} set={v=>setCustomer({...customer,state:v.toUpperCase()})}/><Field label="ZIP *" value={customer.zip} set={v=>setCustomer({...customer,zip:v})}/></div></Card>
  <Card title="Cleaning details"><div className="grid gap-4 sm:grid-cols-2"><Select label={division==="Commercial"?"Property / Service Type":"Service Type"} value={selected?.name??""} options={available.map(x=>x.name)} set={v=>{setService(v);setAddons([])}}/><Select label="Frequency" value={frequency} options={selected?.recurring?["One-Time","Daily","Weekly","Biweekly","Monthly"]:["One-Time"]} set={setFrequency}/><NumberField label="Square Feet" value={squareFeet} set={setSquareFeet}/><Select label="Property Condition" value={condition} options={["Light","Average","Heavy","Extreme"]} set={setCondition}/>{division==="Residential"?<><NumberField label="Bedrooms" value={values.bedrooms} set={v=>setValues({...values,bedrooms:v})}/><NumberField label="Bathrooms" value={values.bathrooms} set={v=>setValues({...values,bathrooms:v})}/><Check label="Property is occupied" checked={occupied} set={setOccupied}/><Check label="Pets / heavy pet hair" checked={pets} set={setPets}/></>:selected?.fields.map(field=><NumberField key={field} label={labels[field]} value={values[field as keyof typeof values]} set={v=>setValues({...values,[field]:v})}/>)}</div>{selected?.description&&<p className="mt-4 text-sm text-neutral-600">{selected.description}</p>}{selected?.addons.length?<div className="mt-6"><p className="mb-3 font-extrabold text-[#143d1a]">Available add-ons</p><div className="grid gap-3 sm:grid-cols-2">{selected.addons.map(a=><Check key={a.name} label={a.name} detail={a.description} checked={addons.includes(a.name)} set={on=>setAddons(on?[...addons,a.name]:addons.filter(x=>x!==a.name))}/>)}</div></div>:null}</Card>
  <Card title="Anything else?"><div className="grid gap-4"><Field label="Preferred Service Date" type="date" value={preferredDate} set={setPreferredDate}/><label className="text-sm font-bold text-[#143d1a]">Special Requests / Notes<textarea value={notes} maxLength={2000} onChange={e=>setNotes(e.target.value)} rows={4} className={`${input} mt-1.5 resize-y`}/></label><label className="absolute left-[-10000px]" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label></div></Card>
  <section className="document-print-root rounded-3xl bg-[#143d1a] p-6 text-white shadow-xl sm:p-8"><p className="text-sm font-bold uppercase tracking-widest text-[#d4af37]">Estimated Service Price</p><p className="mt-2 text-4xl font-black">{price===null?"—":money(price)}</p><p className="mt-4 max-w-2xl text-sm leading-6 text-white/75">This estimate is based on the information provided and is subject to review. Final pricing may change if the actual property condition or requested scope differs.</p><button disabled={busy||price===null} className="mt-6 w-full rounded-xl bg-[#d4af37] px-6 py-4 text-lg font-black text-[#143d1a] disabled:cursor-not-allowed disabled:opacity-50">{busy?"Submitting…":"Submit Estimate Request"}</button>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-950/40 p-3 font-semibold text-red-100">{error}</p>}</section></form><p className="py-8 text-center text-xs text-neutral-500">Your information is used only to prepare and review your estimate request.</p></div></main>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-3xl border border-white bg-white/90 p-5 shadow-[0_12px_40px_rgba(20,61,26,.08)] sm:p-7"><h2 className="mb-5 text-xl font-black text-[#143d1a]">{title}</h2>{children}</section>}
function Field({label,value,set,type="text",maxLength}:{label:string;value:string;set:(v:string)=>void;type?:string;maxLength?:number}){return <label className="text-sm font-bold text-[#143d1a]">{label}<input required={label.endsWith("*")} type={type} maxLength={maxLength} value={value} onChange={e=>set(e.target.value)} className={`${input} mt-1.5`}/></label>}
function Select({label,value,options,set}:{label:string;value:string;options:string[];set:(v:string)=>void}){return <label className="text-sm font-bold text-[#143d1a]">{label}<select value={value} onChange={e=>set(e.target.value)} className={`${input} mt-1.5`}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function NumberField({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="text-sm font-bold text-[#143d1a]">{label}<input required type="number" min="0" value={value} onChange={e=>set(Number(e.target.value))} className={`${input} mt-1.5`}/></label>}
function Check({label,detail,checked,set}:{label:string;detail?:string|null;checked:boolean;set:(v:boolean)=>void}){return <label className="flex cursor-pointer gap-3 rounded-xl border border-neutral-200 bg-white p-4"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)} className="mt-1 h-5 w-5 accent-[#143d1a]"/><span><span className="block font-bold text-[#143d1a]">{label}</span>{detail&&<span className="mt-1 block text-xs text-neutral-500">{detail}</span>}</span></label>}
function Confirmation({result,restart}:{result:Confirmation;restart:()=>void}){return <main className="min-h-screen bg-[#f5f6f4] px-4 py-10"><article className="document-print-root mx-auto max-w-2xl rounded-3xl bg-white p-7 shadow-xl sm:p-12"><p className="text-sm font-black uppercase tracking-[.25em] text-[#d4af37]">StudioScrubz</p><h1 className="mt-3 text-3xl font-black text-[#143d1a]">Estimate Request Received</h1><p className="mt-3 text-neutral-600">Thank you for choosing StudioScrubz. Your estimate has been submitted for review.</p><dl className="mt-8 grid gap-5 border-y border-neutral-200 py-6 sm:grid-cols-2"><Item label="Estimate Number" value={result.estimateNumber}/><Item label="Service" value={result.service}/><Item label="Estimated Price" value={money(result.price)}/><Item label="Customer Name" value={result.customerName}/><div className="sm:col-span-2"><Item label="Service Address" value={result.address}/></div></dl><p className="mt-6 text-sm text-neutral-500">This estimate is based on the information provided and is subject to review. Final pricing may change if the actual property condition or requested scope differs.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row print:hidden"><button onClick={()=>window.print()} className="rounded-xl bg-[#143d1a] px-5 py-3 font-extrabold text-white">Print / Save Estimate</button><button onClick={restart} className="rounded-xl border border-[#143d1a] px-5 py-3 font-extrabold text-[#143d1a]">Start Another Estimate</button></div></article></main>}
function Item({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase tracking-wider text-neutral-500">{label}</dt><dd className="mt-1 font-extrabold text-[#143d1a]">{value}</dd></div>}
const labels:Record<string,string>={floors:"Floors",restrooms:"Restrooms",kitchens:"Kitchens / Breakrooms",stations:"Stations / Booths",units:"Units"};function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v)}
