import type { Client } from "@/types/client";
import type { Estimate, EstimateDivision, Frequency } from "@/types/estimate";
import type { Property } from "@/types/property";
import type { Walkthrough } from "@/types/walkthrough";

export const PROPOSAL_STATUSES = ["Draft", "Ready for Approval", "Approved", "Sent", "Viewed", "Accepted", "Declined", "Expired", "Archived"] as const;
export const APPROVAL_STATUSES = ["Not Submitted", "Pending Approval", "Approved", "Changes Requested", "Rejected"] as const;
export const ACCEPTANCE_METHODS = ["Text Message", "Email", "Phone Call", "Signed Proposal", "In Person", "Other"] as const;
export type ProposalStatus = (typeof PROPOSAL_STATUSES)[number];
export type ProposalApprovalStatus = (typeof APPROVAL_STATUSES)[number];
export type ProposalAcceptanceMethod = Exclude<(typeof ACCEPTANCE_METHODS)[number], "Other"> | `Other: ${string}`;
export type ProposalScopeItem = { id: string; text: string };
export type ProposalAdjustment = { id: string; label: string; amount: number };
export type ProposalTerms = { paymentTerms: string; cancellationPolicy: string; accessRequirements: string; specialConditions: string };
export type ProposalResult = { serviceName: string; baseEstimateAmount: number; adjustments: ProposalAdjustment[]; additionalLabor: number; additionalMaterials: number; manualDiscount: number; taxRate: number; taxes: number; perVisitTotal: number; monthlyTotal: number | null; laborHours: number; crewRecommendation: number; estimatedDuration: number; estimatedProfit: number; scope: ProposalScopeItem[]; terms: ProposalTerms };
export type Proposal = { id: string; proposal_number: string; client_id: string; property_id: string; estimate_id: string | null; walkthrough_id: string | null; division: EstimateDivision; client_name: string | null; property_name: string | null; customer_phone: string | null; customer_email: string | null; frequency: Frequency; requested_date: string | null; representative_name: string | null; notes: string | null; result: ProposalResult; photos: { id: string; fileName: string; storagePath: string | null }[]; signature: string | null; status: ProposalStatus; approval_status: ProposalApprovalStatus; approved_at: string | null; approved_by: string | null; approval_notes: string | null; sent_at: string | null; sent_via: string | null; viewed_at: string | null; accepted: boolean; accepted_at: string | null; accepted_by_name: string | null; acceptance_method: ProposalAcceptanceMethod | null; declined_at: string | null; decline_reason: string | null; expiration_date: string; expired_at: string | null; created_at: string; updated_at: string; archived_at: string | null };
export type ProposalInsert = Omit<Proposal, "id" | "created_at" | "updated_at" | "archived_at" | "proposal_number"> & { proposal_number?: string; archived_at?: string | null };
export type ProposalUpdate = Partial<Omit<Proposal, "id" | "created_at" | "updated_at">>;
export type ProposalWithRelations = Proposal & { client: Client; property: Property; estimate: Estimate | null; walkthrough: Walkthrough | null };
export type ProposalHistory = { id: string; proposal_id: string; event_type: string; previous_status: string | null; new_status: string | null; description: string | null; metadata: Record<string, string | number | boolean | null>; performed_by: string; created_at: string };
