import type {Crew} from "@/types/crew";import type {Employee} from "@/types/employee";import type {Job} from "@/types/job";
export const TIME_ENTRY_TYPES=["Job","Training","Office","Travel","Administrative","Other"] as const;export const TIME_ENTRY_STATUSES=["Open","Completed","Approved","Rejected","Archived"] as const;
export type TimeEntryType=(typeof TIME_ENTRY_TYPES)[number];export type TimeEntryStatus=(typeof TIME_ENTRY_STATUSES)[number];
export type TimeEntry={id:string;time_entry_number:string;employee_id:string;job_id:string|null;crew_id:string|null;work_date:string;clock_in:string;clock_out:string|null;break_minutes:number;regular_hours:number;overtime_hours:number;total_hours:number;hourly_rate_snapshot:number;overtime_rate_snapshot:number;regular_pay:number;overtime_pay:number;gross_pay:number;entry_type:TimeEntryType;notes:string|null;status:TimeEntryStatus;approved_at:string|null;approved_by:string|null;created_at:string;updated_at:string;archived_at:string|null};
export type TimeEntryInput={employee_id:string;job_id:string|null;crew_id:string|null;work_date:string;clock_in:string;clock_out?:string|null;break_minutes?:number;entry_type:TimeEntryType;notes:string|null};
export type TimeEntryUpdate=Partial<TimeEntryInput&Pick<TimeEntry,"status"|"approved_at"|"approved_by"|"archived_at"|"regular_hours"|"overtime_hours"|"total_hours"|"hourly_rate_snapshot"|"overtime_rate_snapshot"|"regular_pay"|"overtime_pay"|"gross_pay">>;
export type TimeEntryWithRelations=TimeEntry&{employee:Employee;job:Job|null;crew:Crew|null};
export type EmployeeTimeSummary={currentWeekHours:number;currentMonthHours:number;regularHours:number;overtimeHours:number;estimatedGrossPay:number;recent:TimeEntryWithRelations[]};
export type JobLaborSummary={employeesWorked:number;regularHours:number;overtimeHours:number;totalHours:number;actualLaborCost:number};
export type JobProfitabilitySummary=JobLaborSummary&{collectedRevenue:number;expenses:number;grossProfit:number;grossMargin:number|null};
export type CrewLaborSummary={currentWeekHours:number;currentMonthHours:number;jobsWorked:number;estimatedGrossLaborCost:number};
