import type { Metadata } from "next";
import { ContactBand, EstimateCta, FeatureList, PageHero, RelatedServices, SectionHeading } from "@/components/site/SiteSections";
export const metadata: Metadata = { title: { absolute: "Post-Construction Cleaning Los Angeles | StudioScrubz" }, description: "Construction cleanup, post-renovation cleaning, dust removal, floor care, and final-readiness service across Los Angeles County and the San Fernando Valley.", alternates: { canonical: "https://studioscrubz.com/post-construction" }, openGraph: { title: "Post-Construction Cleaning Los Angeles | StudioScrubz", description: "Detailed construction and renovation cleanup for ready spaces across Los Angeles County and the San Fernando Valley.", url: "https://studioscrubz.com/post-construction" } };
export default function PostConstructionPage(){return <>
  <PageHero eyebrow="Post-construction cleaning" title="The Final Clean Before the Space Is Ready." copy="Detailed cleaning after construction or renovation for residential and commercial spaces across Los Angeles County and the San Fernando Valley. StudioScrubz helps contractors, builders, remodelers, property managers, homeowners, and commercial project teams plan the final clean." cta="Request a Post-Construction Estimate"/>
  <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2"><div><SectionHeading eyebrow="Final-detail care" title="Clean the details construction leaves behind." copy="Fine dust and renovation residue settle beyond the obvious surfaces. We define the cleaning areas and methods around the materials, condition, and finish of your space, from detailed surface care to final presentation."/><p className="mt-6 text-sm leading-6 text-neutral-500">Sticker and label residue removal depends on the surface and finish. Interior glass and light construction debris are included only within the confirmed cleaning scope. Hazardous-material cleanup, mold remediation, asbestos handling, heavy debris hauling, repairs, and trade work are excluded.</p></div><FeatureList items={["Fine construction dust removal","Surface wiping and detailing","Floor cleaning","Baseboards and trim","Fixture detailing","Cabinets and suitable built-ins","Kitchens and bathrooms","Surface-safe sticker and label residue removal","Interior glass within scope","Light construction debris within scope","Final presentation and readiness cleaning"]}/></div></section>
  <section className="bg-[#eef3ea] px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2"><SectionHeading eyebrow="Projects we assess" title="From renovated homes to commercial build-outs." copy="Share the project details so we can assess the cleaning needs and confirm whether the work fits our services. Each project is reviewed for its condition, access, materials, and requested scope."/><FeatureList items={["Residential renovations","Home remodels","New-build final cleaning","Apartment and unit renovation cleanup","Commercial build-outs","Property improvement projects"]}/></div></section>
  <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Project planning" title="A clear scope before the final clean." copy="Pricing and planning reflect square footage, construction or renovation condition, dust level, surfaces and materials, number of rooms or areas, project phase, timeline, and readiness expectations. A walkthrough or project assessment helps establish the scope when needed."/><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{[
    ["01", "Share the project details", "Tell us about the space, work completed, current condition, timeline, and how the space needs to look when cleaning is complete."],
    ["02", "Assess the space", "We review your information and use a walkthrough or project assessment when needed to understand the surfaces, dust, access, and cleaning areas."],
    ["03", "Confirm the scope", "Agree on the areas and cleaning tasks, including surface-specific details and exclusions, so expectations are clear."],
    ["04", "Review the estimate or proposal", "Review the cleaning scope and pricing before confirming the service."],
    ["05", "Schedule the cleaning", "Coordinate the cleaning date around the confirmed project timeline and access arrangements."],
    ["06", "Complete the final review", "StudioScrubz completes the agreed cleaning scope and performs a final service review."]
  ].map(([number,title,copy])=><article key={number} className="rounded-[1.6rem] border border-[#143d1a]/10 bg-[#f4f7f1] p-6"><p className="text-sm font-black text-[#9a7a17]">{number}</p><h3 className="mt-4 text-xl font-extrabold text-[#143d1a]">{title}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">{copy}</p></article>)}</div><div className="mt-8"><EstimateCta label="Request a Post-Construction Estimate"/></div></div></section>
  <RelatedServices links={[["Commercial Cleaning", "/commercial"], ["Property Management Cleaning", "/property-management"], ["Residential Cleaning", "/residential"]]}/><ContactBand title="Make the final walkthrough feel finished." copy="Tell us about your project, current condition, and timeline so we can plan the cleaning scope with you."/>
</>}
