import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { attentionPushPayload, deliverAttentionPushes, safeAttentionUrl } from "./delivery.ts";

const item = (overrides = {}) => ({ id: "invoice:1:overdue", severity: "Urgent", category: "Money", type: "Overdue Invoice", title: "Invoice overdue", description: "Review invoice", entity_label: "1234", action_label: "View", action_url: "/invoices?id=1", due_at: null, amount: null, priority: 1, created_at: "2026-08-31T00:00:00Z", source_created_at: "2026-08-31T00:00:00Z", client_id: null, property_id: null, employee_id: null, crew_id: null, invoice_id: "1", job_id: null, proposal_id: null, agreement_id: null, estimate_id: null, walkthrough_id: null, communication_id: null, communication_context: null, sms_action: null, resolution_label: null, attention_state: null, ...overrides });
const subscription = (id, overrides = {}) => ({ id, user_id: "user-1", endpoint: `https://push.example/${id}`, p256dh: "key", auth: "auth", user_agent: null, created_at: "", updated_at: "", revoked_at: null, ...overrides });
function repository(claim = async (_u, _k, id) => ({ id: `delivery-${id}` })) { const calls = { sent: [], failed: [], revoked: [] }; return { calls, value: { claim, async sent(id) { calls.sent.push(id); }, async failed(...args) { calls.failed.push(args); }, async revoke(id) { calls.revoked.push(id); } } }; }

test("duplicate attention delivery is not resent", async () => { const repo = repository(async () => null); let sends = 0; const result = await deliverAttentionPushes({ userId: "user-1", items: [item()], subscriptions: [subscription("a")], repository: repo.value, send: async () => { sends += 1; } }); assert.equal(sends, 0); assert.equal(result.duplicates, 1); });
test("revoked subscriptions and dismissed items are skipped", async () => { const repo = repository(); let sends = 0; await deliverAttentionPushes({ userId: "user-1", items: [item({ attention_state: { state: "Dismissed" } })], subscriptions: [subscription("a"), subscription("b", { revoked_at: "2026-08-31T00:00:00Z" })], repository: repo.value, send: async () => { sends += 1; } }); assert.equal(sends, 0); });
test("expired subscription is revoked", async () => { const repo = repository(); const error = Object.assign(new Error("gone"), { statusCode: 410 }); await deliverAttentionPushes({ userId: "user-1", items: [item()], subscriptions: [subscription("a")], repository: repo.value, send: async () => { throw error; } }); assert.deepEqual(repo.calls.revoked, ["a"]); });
test("one failed device does not prevent another delivery", async () => { const repo = repository(); const sent = []; const result = await deliverAttentionPushes({ userId: "user-1", items: [item()], subscriptions: [subscription("bad"), subscription("good")], repository: repo.value, send: async (value) => { if (value.id === "bad") throw new Error("failed"); sent.push(value.id); } }); assert.deepEqual(sent, ["good"]); assert.equal(result.sent, 1); assert.equal(result.failed, 1); });
test("notification URLs remain same-origin paths", () => { for (const value of ["https://evil.example/a", "//evil.example/a", "javascript:alert(1)", undefined]) assert.equal(safeAttentionUrl(value), "/attention"); assert.equal(safeAttentionUrl("/jobs?jobId=1"), "/jobs?jobId=1"); assert.equal(attentionPushPayload(item()).tag, attentionPushPayload(item()).tag); });
test("server recipient generation reuses Attention permissions and rules", () => { const source = readFileSync(new URL("../attention/server.ts", import.meta.url), "utf8"); assert.match(source, /hasPermission\(profile, "attention\.view"\)/); assert.match(source, /buildAttentionItems\(input, "Active"\)/); assert.match(source, /snapshot\.states\.filter\(\(state\) => state\.user_id === profile\.id\)/); });
test("private VAPID key is confined to server source", () => { const server = readFileSync(new URL("./server.ts", import.meta.url), "utf8"); const client = readFileSync(new URL("../services/pushNotifications.ts", import.meta.url), "utf8"); assert.match(server, /WEB_PUSH_VAPID_PRIVATE_KEY/); assert.doesNotMatch(client, /WEB_PUSH_VAPID_PRIVATE_KEY/); });
test("existing items are baselined instead of pushed to a newly initialized device", () => { const source = readFileSync(new URL("./server.ts", import.meta.url), "utf8"); assert.match(source, /delivery_status: "Suppressed"/); assert.match(source, /attention_push_checkpoints/); assert.match(source, /allDevices\.filter\(\(subscription\) => initialized\.has\(subscription\.id\)\)/); });
