import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { sendVerifiedTestNotification, TEST_PUSH_PAYLOAD, TestPushError } from "./testNotification.ts";

const subscription = (overrides = {}) => ({ id: "sub-1", user_id: "user-1", endpoint: "https://push.example/one", p256dh: "key", auth: "auth", user_agent: null, created_at: "", updated_at: "", revoked_at: null, ...overrides });
const dependencies = (overrides = {}) => ({ loadSubscription: async () => subscription(), send: async () => undefined, revoke: async () => undefined, failureStatus: () => null, ...overrides });

test("unauthenticated test request is rejected", async () => { await assert.rejects(() => sendVerifiedTestNotification({ userId: null, endpoint: "https://push.example/one", ...dependencies() }), (error) => error instanceof TestPushError && error.status === 401); });
test("another user's subscription cannot be used", async () => { await assert.rejects(() => sendVerifiedTestNotification({ userId: "user-1", endpoint: "https://push.example/two", ...dependencies({ loadSubscription: async () => subscription({ user_id: "user-2" }) }) }), (error) => error instanceof TestPushError && error.status === 404); });
test("revoked subscription is rejected", async () => { let sent = false; await assert.rejects(() => sendVerifiedTestNotification({ userId: "user-1", endpoint: "https://push.example/one", ...dependencies({ loadSubscription: async () => subscription({ revoked_at: "2026-08-31T00:00:00Z" }), send: async () => { sent = true; } }) }), (error) => error instanceof TestPushError && error.status === 409); assert.equal(sent, false); });
test("test notification uses the fixed payload", async () => { let payload; await sendVerifiedTestNotification({ userId: "user-1", endpoint: "https://push.example/one", ...dependencies({ send: async (_subscription, value) => { payload = value; } }) }); assert.deepEqual(payload, { title: "StudioScrubz Test", body: "Push notifications are working on this device.", url: "/settings/notifications", tag: "studioscrubz-push-test" }); assert.deepEqual(payload, TEST_PUSH_PAYLOAD); });
for (const statusCode of [404, 410]) test(`expired ${statusCode} subscription is revoked`, async () => { const revoked = []; const error = Object.assign(new Error("expired"), { statusCode }); await assert.rejects(() => sendVerifiedTestNotification({ userId: "user-1", endpoint: "https://push.example/one", ...dependencies({ send: async () => { throw error; }, revoke: async (id) => { revoked.push(id); }, failureStatus: () => statusCode }) }), (cause) => cause instanceof TestPushError && cause.status === 502); assert.deepEqual(revoked, ["sub-1"]); });
test("private VAPID key remains server-only", () => { const server = readFileSync(new URL("./server.ts", import.meta.url), "utf8"); const client = readFileSync(new URL("../services/pushNotifications.ts", import.meta.url), "utf8"); assert.match(server, /WEB_PUSH_VAPID_PRIVATE_KEY/); assert.doesNotMatch(client, /WEB_PUSH_VAPID_PRIVATE_KEY/); });
