import { StudioScrubzLogo } from "@/components/branding/StudioScrubzLogo";
import type { ProposalWithRelations } from "@/types/proposal";
import type { PublicProposal } from "@/types/publicProposal";

export function ProposalDocument({ document }: { document: PublicProposal }) { return <article id="proposal-document" className="document-print-root mx-auto max-w-3xl bg-white p-6 text-sm text-neutral-800 print:max-w-none print:p-0">
  <header className="flex flex-col items-center gap-4 border-b-2 border-[#143d1a] pb-4 text-center sm:flex-row sm:text-left"><StudioScrubzLogo size={108}/><div><h1 className="text-3xl font-extrabold text-[#143d1a]">{document.business_name}</h1>{document.tagline&&<p>{document.tagline}</p>}<p>{[document.business_email,document.business_phone,document.website].filter(Boolean).join(" · ")}</p><p>{[document.address,document.city,document.state,document.zip].filter(Boolean).join(", ")}</p></div></header>
  <h2 className="mt-6 text-2xl font-extrabold text-[#143d1a]">Proposal</h2><p className="font-semibold">{document.proposal_number}</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Detail label="Client" value={document.client_name}/><Detail label="Property / Service Location" value={document.property_location}/><Detail label="Service Type" value={document.service_name}/><Detail label="Frequency" value={document.frequency}/><Detail label="Requested Date" value={document.requested_date||"—"}/><Detail label="Expiration Date" value={document.expiration_date}/></div>
  <section className="mt-6"><h3 className="font-bold text-[#143d1a]">Service Description</h3><p className="mt-2 whitespace-pre-line">{document.service_description||"No service description available."}</p></section>
  <section className="mt-6"><h3 className="font-bold text-[#143d1a]">Scope / Service Details</h3><ul className="mt-2 list-disc space-y-1 pl-5">{document.scope.map(item=><li key={item.id}>{item.text}</li>)}</ul></section>
  {document.adjustments.length>0&&<section className="mt-6"><h3 className="font-bold text-[#143d1a]">Adjustments</h3><dl className="mt-2 divide-y border-y">{document.adjustments.map((item,index)=><div className="flex justify-between py-2" key={`${item.label}-${index}`}><dt>{item.label}</dt><dd className="font-bold">{money(item.amount)}</dd></div>)}</dl></section>}
  <section className="mt-6"><h3 className="font-bold text-[#143d1a]">Pricing</h3><dl className="mt-2 divide-y border-y"><Price label="Base Service Price" value={document.base_price??document.per_visit_total}/><div className="flex justify-between py-2"><dt>{document.frequency} Service Discount</dt><dd className="font-bold">{document.recurring_discount_percent??0}%</dd></div><Price label="Recurring Discount" value={-(document.recurring_discount_amount??0)}/><Price label="Manual / Custom Discount" value={-(document.manual_discount??document.discount)}/><Price label="Taxes" value={document.taxes}/><Price label="Final Per Visit" value={document.per_visit_total}/>{document.monthly_total!==null&&<Price label="Estimated Monthly Total" value={document.monthly_total}/>}</dl></section>
  <section className="mt-6"><h3 className="font-bold text-[#143d1a]">Terms</h3>{Object.entries(document.terms).map(([key,value])=><p className="mt-2 whitespace-pre-line" key={key}><b>{human(key)}:</b> {value||"—"}</p>)}</section>
  </article> }
export function proposalDocumentFromRecord(p:ProposalWithRelations):PublicProposal{return{proposal_number:p.proposal_number,status:p.status,client_name:p.client_name||"Client",property_location:p.property_name||"Service location",service_name:p.result.serviceName,service_description:p.result.serviceDescription??null,frequency:p.frequency,requested_date:p.requested_date,scope:p.result.scope,adjustments:p.result.adjustments,base_price:p.estimate?.result.oneTimePrice??p.result.baseEstimateAmount,recurring_discount_percent:p.result.frequencyDiscountPercent??0,recurring_discount_amount:p.result.frequencyDiscount??0,manual_discount:(p.result.inheritedManualDiscount??0)+p.result.manualDiscount,discount:p.result.manualDiscount,taxes:(p.estimate?.result.taxes??0)+p.result.taxes,per_visit_total:p.result.perVisitTotal,monthly_total:p.result.monthlyTotal,terms:p.result.terms,expiration_date:p.expiration_date,accepted_at:p.accepted_at,accepted_by_name:p.accepted_by_name,client_acceptance_consent:p.client_acceptance_consent,business_name:"StudioScrubz",tagline:"No mess. No stress.",business_email:null,business_phone:null,website:null,address:null,city:null,state:null,zip:null}}
export function proposalDeliverySnapshot(p:ProposalWithRelations){const d=proposalDocumentFromRecord(p);return{proposal_number:d.proposal_number,client_name:d.client_name,property_location:d.property_location,service_name:d.service_name,service_description:d.service_description,frequency:d.frequency,requested_date:d.requested_date,scope:d.scope,adjustments:d.adjustments,base_price:d.base_price,recurring_discount_percent:d.recurring_discount_percent,recurring_discount_amount:d.recurring_discount_amount,manual_discount:d.manual_discount,discount:d.discount,taxes:d.taxes,per_visit_total:d.per_visit_total,monthly_total:d.monthly_total,terms:d.terms,expiration_date:d.expiration_date}}
function Detail({label,value}:{label:string;value:string}){return <div><b className="block text-[#143d1a]">{label}</b><span>{value||"—"}</span></div>}function Price({label,value}:{label:string;value:number}){return <div className="flex justify-between py-2"><dt>{label}</dt><dd className="font-bold">{money(value)}</dd></div>}function money(value:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value)}function human(value:string){return value.replace(/([A-Z])/g," $1").replace(/^./,letter=>letter.toUpperCase())}
