import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: [
        "/",
        "/residential",
        "/commercial",
        "/property-management",
        "/property-porter-services",
        "/luxury-property-care",
        "/airbnb-cleaning",
        "/post-construction",
        "/pressure-washing",
        "/about",
        "/contact",
        "/careers",
      ],
      disallow: [
        "/site",
        "/api/",
        "/login",
        "/access-denied",
        "/request-estimate",
        "/agreement/",
        "/assessment/",
        "/change-request/",
        "/estimate/",
        "/invoice/",
        "/proposal/",
        "/agreements",
        "/applications",
        "/archives",
        "/attention",
        "/clients",
        "/employees",
        "/estimates",
        "/expenses",
        "/field-walkthroughs",
        "/invoices",
        "/job-performance",
        "/jobs",
        "/lead-generator-applications",
        "/marketing-materials",
        "/messages",
        "/open-estimates",
        "/open-proposals",
        "/payroll-prep",
        "/properties",
        "/proposals",
        "/revenue",
        "/schedule",
        "/settings",
        "/time-clock",
        "/users",
        "/vehicles",
        "/vendor-packets",
        "/walkthroughs",
      ],
    },
    sitemap: "https://studioscrubz.com/sitemap.xml",
    host: "https://studioscrubz.com",
  };
}
