import type { Metadata } from "next";
import { ContactBand, EstimateCta, FeatureList, PageHero, RelatedServices, SectionHeading } from "@/components/site/SiteSections";
export const metadata: Metadata = { title: { absolute: "Commercial Cleaning Services in Los Angeles | StudioScrubz" }, description: "Office, janitorial, property-management, apartment-community, and common-area cleaning across Los Angeles County and the San Fernando Valley.", alternates: { canonical: "https://studioscrubz.com/commercial" }, openGraph: { title: "Commercial Cleaning Services in Los Angeles | StudioScrubz", description: "Commercial cleaning plans built around your facility, traffic, frequency, and operating needs across Los Angeles County.", url: "https://studioscrubz.com/commercial" } };

const commercialSpaces = [
  ["Offices", "Professional cleaning designed for offices, reception areas, workspaces, breakrooms, restrooms, and common areas. Service may focus on accessible surfaces, floors, trash, high-touch areas, and the overall presentation of the workplace."],
  ["Property management", "Flexible cleaning support for managed properties, including leasing offices, common areas, and unit turns where applicable. Plans are shaped around the property, turnover schedule, and day-to-day management needs."],
  ["Apartment communities", "Cleaning may cover hallways, stairwells, laundry rooms, gyms, amenity spaces, leasing areas, and other shared spaces. Unit-turn service can also be coordinated when included in the confirmed property scope."],
  ["Barbershops and salons", "Cleaning designed around busy personal-care spaces, with attention to floors, stations, mirrors, waiting areas, restrooms, and common surfaces. Routine service may also include everyday hair and debris removal."],
  ["Gyms and spas", "Cleaning focused on floors, mirrors, equipment-area surfaces, restrooms, locker or common areas, and frequently touched surfaces. The plan is adjusted to the facility layout, traffic, and operating schedule."],
  ["Restaurants", "Cleaning support for customer-facing and back-of-house areas, with attention to floors, surfaces, grease-prone areas, fixtures, restrooms, and high-touch points. Scope is tailored to the space and does not include specialized hood, exhaust, or regulatory sanitation services unless specifically confirmed."],
  ["Recording studios", "Cleaning designed around professional creative spaces, including control rooms, recording areas, lounges, restrooms, floors, and general surfaces. We focus on general dust and debris removal without handling sensitive audio equipment unless that work is specifically approved."],
  ["Tattoo studios", "Cleaning support for reception areas, floors, restrooms, common surfaces, and general presentation. The confirmed scope complements the studio’s own specialized equipment and regulated sanitation procedures rather than replacing them."],
  ["Warehouses and appropriate light industrial spaces", "Practical cleaning for suitable warehouse and light industrial areas, which may include accessible floors, common areas, offices, restrooms, and general surface dust or debris. Service is confirmed after reviewing site conditions, operations, and safety requirements."],
] as const;

export default function CommercialPage(){return <><PageHero eyebrow="Commercial cleaning" title="Commercial cleaning built around your facility." copy="StudioScrubz provides office, janitorial, property-management, apartment-community, and common-area cleaning across Los Angeles County, the San Fernando Valley, and surrounding service areas."/><section className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Spaces we support" title="Commercial care without the one-size-fits-all plan."/><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{commercialSpaces.map(([space,copy])=><article id={space === "Property management" ? "property-management" : undefined} key={space} className="rounded-[1.6rem] border border-[#143d1a]/10 bg-[#f4f7f1] p-6"><h2 className="text-xl font-extrabold text-[#143d1a]">{space}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{copy}</p></article>)}</div><FeatureList items={["Recurring janitorial service","One-time deep cleans","Property and unit turns","Common-area cleaning","Flexible scheduling","Walkthrough-based proposals"]}/></div></section><section className="bg-[#143d1a] px-5 py-20 text-white sm:px-8 sm:py-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#e5cd7d]">Commercial walkthroughs</p><h2 className="mt-4 max-w-4xl text-4xl font-extrabold tracking-[-.045em] sm:text-5xl">Let’s walk the property before we price the clean.</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">Every commercial space operates differently. We review your facility, cleanable areas, traffic, service frequency, priorities, and operating needs before building a cleaning proposal around the property.</p><div className="mt-8"><EstimateCta label="Request a Property Walkthrough" className="bg-[#d4af37] text-[#143d1a] hover:bg-[#e5cd7d]"/></div><p className="mt-5 max-w-4xl text-sm leading-6 text-white/60">Ideal for offices, apartment communities, property managers, gyms, restaurants, barbershops and salons, recording studios, and other appropriate commercial spaces.</p></div></section><RelatedServices links={[["Property Management Cleaning", "#property-management"], ["Post-Construction Cleaning", "/post-construction"], ["Pressure Washing", "/pressure-washing"]]}/><ContactBand title="Bring clarity to your cleaning plan."/></>}
