import dns from "node:dns/promises";
import net from "node:net";
import type { EnrichmentFieldName } from "@/types/prospectEnrichment";

export const ENRICHMENT_MAX_ITEMS=10, ENRICHMENT_MAX_PAGES=4, ENRICHMENT_MAX_BYTES=1_000_000;
export const ENRICHMENT_USER_AGENT="StudioScrubz Prospect Enrichment/1.0 (contact: support@studioscrubz.com)";
export interface Candidate{fieldName:EnrichmentFieldName;value:string;normalizedValue:string;sourceUrl:string;sourcePageType:string;confidence:number;retrievedAt:string}
const blockedV4=(ip:string)=>{const p=ip.split('.').map(Number);return p[0]===0||p[0]===10||p[0]===127||p[0]>=224||p[0]===169&&p[1]===254||p[0]===172&&p[1]>=16&&p[1]<=31||p[0]===192&&p[1]===168||p[0]===192&&p[1]===0&&p[2]===0||p[0]===198&&[18,19,51].includes(p[1])||p[0]===203&&p[1]===0&&p[2]===113};
const blockedIp=(ip:string)=>net.isIPv4(ip)?blockedV4(ip):net.isIPv6(ip)?(/^(::|::1|fc|fd|fe8|fe9|fea|feb|ff)/i.test(ip)||ip.toLowerCase().startsWith("2001:db8:")):true;
export async function validatePublicHttps(input:string, expectedHost?:string){let url:URL;try{url=new URL(input)}catch{throw new Error("Invalid website URL.")}if(url.protocol!=="https:"||url.username||url.password||url.port)throw new Error("Website must use public HTTPS.");const host=url.hostname.toLowerCase().replace(/\.$/,"");if(host==="localhost"||host.endsWith(".localhost")||host==="169.254.169.254")throw new Error("Website destination is blocked.");if(expectedHost&&!sameSite(host,expectedHost))throw new Error("Secondary enrichment page left the official site.");const addresses=await dns.lookup(host,{all:true,verbatim:true});if(!addresses.length||addresses.some(a=>blockedIp(a.address)))throw new Error("Website destination is not public.");url.hostname=host;return url;}
export function sameSite(a:string,b:string){const clean=(v:string)=>v.toLowerCase().replace(/^www\./,"").replace(/\.$/,"");return clean(a)===clean(b)}
async function fetchBounded(url:URL, expectedHost?:string){let current=await validatePublicHttps(url.toString(),expectedHost);for(let redirects=0;redirects<=2;redirects++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);try{const response=await fetch(current,{headers:{"User-Agent":ENRICHMENT_USER_AGENT,"Accept":"text/html,application/xhtml+xml"},redirect:"manual",signal:controller.signal,cache:"no-store"});if(response.status>=300&&response.status<400){const location=response.headers.get("location");if(!location||redirects===2)throw new Error("Website redirect limit reached.");current=await validatePublicHttps(new URL(location,current).toString(),expectedHost??current.hostname);continue}if(!response.ok)throw new Error(`Website returned ${response.status}.`);const type=(response.headers.get("content-type")||"").toLowerCase();if(!type.includes("text/html")&&!type.includes("application/xhtml+xml"))throw new Error("Website content type is unsupported.");const reader=response.body?.getReader();if(!reader)return"";let size=0,out="";const decoder=new TextDecoder();while(true){const{done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>ENRICHMENT_MAX_BYTES){await reader.cancel();throw new Error("Website response is too large.")}out+=decoder.decode(value,{stream:true})}return out+decoder.decode()}finally{clearTimeout(timer)}}throw new Error("Website redirect failed.")}
function strip(value:string){return value.replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim()}
function add(list:Candidate[],fieldName:EnrichmentFieldName,value:string|undefined,sourceUrl:string,page:string,confidence:number){const v=strip(value||"");if(!v)return;const normalized=fieldName==="business_email"?v.toLowerCase():fieldName==="business_phone"?v.replace(/\D/g,""):fieldName==="website"?v.toLowerCase():v.toLowerCase();if(!normalized)return;if(!list.some(x=>x.fieldName===fieldName&&x.normalizedValue===normalized))list.push({fieldName,value:v,normalizedValue:normalized,sourceUrl,sourcePageType:page,confidence,retrievedAt:new Date().toISOString()})}
function extractJsonLd(html:string,url:string,page:string,list:Candidate[]){for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const raw=JSON.parse(m[1]);const walk=(x:any)=>{if(Array.isArray(x))return x.forEach(walk);if(!x||typeof x!=="object")return;const type=Array.isArray(x["@type"])?x["@type"].join(" "):String(x["@type"]||"");if(/Organization|LocalBusiness|Restaurant|Person|ContactPoint/i.test(type)){add(list,"business_phone",x.telephone,url,"Structured Data",90);add(list,"business_email",x.email,url,"Structured Data",90);if(typeof x.url==="string")add(list,"website",x.url,url,"Structured Data",90);if(x.address&&typeof x.address==="object"){add(list,"address",[x.address.streetAddress].filter(Boolean).join(" "),url,"Structured Data",92);add(list,"city",x.address.addressLocality,url,"Structured Data",92);add(list,"state",x.address.addressRegion,url,"Structured Data",92);add(list,"zip",x.address.postalCode,url,"Structured Data",92)}if(/Person/i.test(type)){add(list,"contact_name",x.name,url,"Structured Data",75);add(list,"contact_title",x.jobTitle,url,"Structured Data",75)}}Object.values(x).forEach(walk)};walk(raw)}catch{}}
}
function extractPage(html:string,url:string,page:string,list:Candidate[]){extractJsonLd(html,url,page,list);for(const m of html.matchAll(/href=["']mailto:([^"'?]+)[^"']*["']/gi))add(list,"business_email",decodeURIComponent(m[1]),url,page,85);for(const m of html.matchAll(/href=["']tel:([^"']+)["']/gi))add(list,"business_phone",decodeURIComponent(m[1]),url,page,85)}
function pageLinks(html:string,base:URL){const links:{url:string;page:string}[]=[];for(const m of html.matchAll(/<a[^>]+href=["']([^"'#]+)["'][^>]*>([\s\S]*?)<\/a>/gi)){try{const label=strip(m[2]).toLowerCase(),u=new URL(m[1],base);const patterns: Array<[RegExp,string]>=[[/contact/i,"Contact"],[/about/i,"About"],[/team/i,"Team"],[/staff/i,"Staff"],[/management/i,"Management"],[/locations?/i,"Locations"]];const hit=patterns.find(([r])=>r.test(label)||r.test(u.pathname));if(hit&&sameSite(u.hostname,base.hostname)&&u.protocol==="https:")links.push({url:u.toString(),page:hit[1]})}catch{}}return links.filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i).slice(0,3)}
export async function robotsAllows(base:URL){try{const robots=await fetchBounded(new URL('/robots.txt',base),base.hostname);const section=robots.split(/user-agent:/i).find(x=>/^\s*\*/.test(x));if(!section)return true;return !section.split(/\r?\n/).some(line=>/^\s*disallow\s*:\s*\/\s*$/i.test(line))}catch{return true}}
export async function enrichOfficialWebsite(input:string){const base=await validatePublicHttps(input);if(!(await robotsAllows(base)))throw new Error("Website robots policy blocks automated access.");const candidates:Candidate[]=[];const home=await fetchBounded(base);add(candidates,"website",base.origin,base.toString(),"Homepage",95);extractPage(home,base.toString(),"Homepage",candidates);for(const link of pageLinks(home,base)){try{const url=await validatePublicHttps(link.url,base.hostname),html=await fetchBounded(url,base.hostname);extractPage(html,url.toString(),link.page,candidates);if(link.page==="Contact")add(candidates,"contact_page_url",url.toString(),url.toString(),"Contact",95)}catch{}}return{canonicalUrl:base.origin,canonicalDomain:base.hostname.replace(/^www\./,""),candidates}}

