import type { Prospect, ProspectCsvField, ProspectCsvValues, ProspectDuplicateClass, ProspectImportPreviewRow } from "@/types/prospect";

export const CSV_MAX_BYTES = 5 * 1024 * 1024;
export const CSV_MAX_ROWS = 2000;
export const csvFields: Array<{key:ProspectCsvField;label:string}> = [
  {key:"company_name",label:"Business name"},{key:"contact_name",label:"Contact name"},{key:"business_email",label:"Email"},{key:"business_phone",label:"Phone"},{key:"website",label:"Website"},{key:"address",label:"Street address"},{key:"city",label:"City"},{key:"state",label:"State"},{key:"zip",label:"ZIP"},{key:"industry",label:"Industry/category"},{key:"notes",label:"Notes"},{key:"source",label:"Source"},
];

export function parseCsv(text:string):string[][] {
  const rows:string[][]=[]; let row:string[]=[]; let cell=""; let quoted=false;
  for(let i=0;i<text.length;i++){const char=text[i];if(quoted){if(char==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(char==='"')quoted=false;else cell+=char;}else if(char==='"'){if(cell)throw new Error(`Malformed quote near row ${rows.length+1}.`);quoted=true;}else if(char===","){row.push(cell);cell="";}else if(char==="\n"){row.push(cell.replace(/\r$/, ""));rows.push(row);row=[];cell="";}else cell+=char;}
  if(quoted)throw new Error("CSV contains an unterminated quoted value."); if(cell||row.length){row.push(cell.replace(/\r$/, ""));rows.push(row);} return rows.filter(values=>values.some(value=>value.trim()));
}

export function suggestMapping(headers:string[]):Partial<Record<ProspectCsvField,number>> {const result:Partial<Record<ProspectCsvField,number>>={};const aliases:Record<ProspectCsvField,string[]>={company_name:["business name","company name","company","business"],contact_name:["contact name","contact"],business_email:["email","business email"],business_phone:["phone","business phone","telephone"],website:["website","url","domain"],address:["street address","address","address 1"],city:["city"],state:["state","province"],zip:["zip","zipcode","postal code"],industry:["industry","category"],notes:["notes","comments"],source:["source","lead source"]};headers.forEach((header,index)=>{const normalized=normalizeText(header).toLocaleLowerCase();for(const field of csvFields)if(result[field.key]===undefined&&aliases[field.key].includes(normalized))result[field.key]=index;});return result;}

export function buildPreview(dataRows:string[][],mapping:Partial<Record<ProspectCsvField,number>>,prospects:Prospect[]):ProspectImportPreviewRow[]{return dataRows.map((cells,index)=>{const values={} as ProspectCsvValues;for(const field of csvFields){const column=mapping[field.key];if(column!==undefined)values[field.key]=normalizeField(field.key,cells[column]??"");}const error=!values.company_name?"Business name is required.":validateEmail(values.business_email);const match=findDuplicate(values,prospects);const classification:ProspectDuplicateClass=error?"Invalid":match?.exact?"Exact duplicate":match?"Possible duplicate":"New";return{rowNumber:index+2,fingerprint:fingerprint(values),values,classification,decision:classification==="Exact duplicate"||classification==="Invalid"?"Skip":classification==="Possible duplicate"?"":"Import Separately",matchedProspectId:match?.prospect.id??null,error};});}

export function normalizeField(field:ProspectCsvField,value:string){const clean=normalizeText(value);if(!clean)return "";if(field==="business_email")return clean.toLocaleLowerCase();if(field==="business_phone")return clean.replace(/[^0-9+]/g,"");if(field==="website")return clean.replace(/^https?:\/\/(www\.)?/i,"").replace(/\/$/,"").toLocaleLowerCase();if(field==="state")return clean.toLocaleUpperCase();return clean;}
export function normalizeText(value:string){return value.replace(/^\uFEFF/,"").trim().replace(/\s+/g," ");}
function validateEmail(value?:string){return value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)?"Email is malformed.":null;}
function findDuplicate(values:ProspectCsvValues,prospects:Prospect[]){const email=values.business_email?.toLocaleLowerCase();const phone=values.business_phone?.replace(/\D/g,"");const domain=values.website?.replace(/^https?:\/\/(www\.)?/i,"").split("/")[0].toLocaleLowerCase();const name=normalizeText(values.company_name??"").toLocaleLowerCase();const address=normalizeText(values.address??"").toLocaleLowerCase();const zip=normalizeText(values.zip??"");let possible:Prospect|null=null;for(const prospect of prospects.filter(item=>!item.merged_into_prospect_id)){const strong=Boolean((email&&email===prospect.email_normalized)||(phone&&phone===prospect.phone_normalized)||(domain&&domain===prospect.domain_normalized)||(name===normalizeText(prospect.company_name).toLocaleLowerCase()&&((address&&address===normalizeText(prospect.address??"").toLocaleLowerCase())||(zip&&zip===normalizeText(prospect.zip??"")))));if(strong)return{prospect,exact:true};if(!possible&&(name===normalizeText(prospect.company_name).toLocaleLowerCase()||(address&&address===normalizeText(prospect.address??"").toLocaleLowerCase())))possible=prospect;}return possible?{prospect:possible,exact:false}:null;}
function fingerprint(values:ProspectCsvValues){const text=JSON.stringify(csvFields.map(field=>values[field.key]??""));let hash=2166136261;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16).padStart(8,"0");}
