import type { CommercialCalculatorInput, ResidentialCalculatorInput } from "@/types/estimate";
import type { CatalogService, RecurringPricingRule, ServiceAddon, ServicePriceTier } from "@/types/serviceCatalog";
import { estimatedMonthlyTotal } from "@/lib/scheduling/frequency";

export function findMatchingTier(tiers:ServicePriceTier[],value:number){return tiers.filter(x=>x.is_active&&(x.min_value==null||value>=x.min_value)&&(x.max_value==null||value<=x.max_value)).sort((a,b)=>a.display_order-b.display_order)[0]??null}
export function calculateAddons(names:string[],addons:ServiceAddon[],hourlyRate=0){return names.map(name=>{const addon=addons.find(x=>x.addon_name===name);if(!addon)throw new Error(`Pricing is unavailable for add-on: ${name}`);const labor=Number(addon.pricing_config.labor_hours??0);const supplies=Number(addon.pricing_config.supply_cost??addon.price);return{label:name,amount:round(addon.pricing_model==="Custom"?labor*hourlyRate+supplies:addon.price),catalogAddonId:addon.id,description:addon.description,pricingModel:addon.pricing_model,unitLabel:addon.unit_label}})}
export function matchingRecurringRules(frequency:string,rules:RecurringPricingRule[],serviceId:string){const specific=rules.filter(x=>x.is_active&&x.frequency===frequency&&x.service_id===serviceId);return specific.length?specific:rules.filter(x=>x.is_active&&x.frequency===frequency&&x.service_id===null)}
export function applyRecurringRule(amount:number,frequency:string,rules:RecurringPricingRule[],serviceId:string,ruleId?:string|null){const matches=matchingRecurringRules(frequency,rules,serviceId);const rule=ruleId?matches.find(x=>x.id===ruleId):matches.length===1?matches[0]:undefined;if(ruleId&&!rule)throw new Error("The selected recurring pricing rule is unavailable for this service and frequency.");if(!rule&&matches.length>1)throw new Error("Select a recurring pricing rule before calculating this frequency.");if(!rule)return{amount,discount:0,percent:0,rule:null};if(rule.adjustment_type==="Percentage"){const discount=amount*rule.adjustment_value/100;return{amount:amount-discount,discount,percent:rule.adjustment_value,rule}}if(rule.adjustment_type==="Flat Amount")return{amount:Math.max(0,amount-rule.adjustment_value),discount:Math.min(amount,rule.adjustment_value),percent:amount?rule.adjustment_value/amount*100:0,rule};return{amount:rule.adjustment_value,discount:Math.max(0,amount-rule.adjustment_value),percent:amount?Math.max(0,amount-rule.adjustment_value)/amount*100:0,rule}}
export function calculateRecurringTotals(input:{subtotal:number;frequency:string;customIntervalDays?:number|null;rules:RecurringPricingRule[];serviceId:string;recurringPricingRuleId?:string|null;manualDiscountAmount?:number;manualDiscountPercent?:number;taxRatePercent?:number;fixedTaxes?:number}){const subtotal=Math.max(0,input.subtotal),recurring=applyRecurringRule(subtotal,input.frequency,input.rules,input.serviceId,input.recurringPricingRuleId),manualDiscount=input.manualDiscountAmount??subtotal*clampPercent(input.manualDiscountPercent??0)/100,taxable=Math.max(0,recurring.amount-manualDiscount),taxes=input.fixedTaxes??taxable*clampPercent(input.taxRatePercent??0)/100,finalPrice=taxable+Math.max(0,taxes);return{subtotal:round(subtotal),recurringPricingRuleId:recurring.rule?.id??null,recurringPricingRuleName:recurring.rule?.rule_name??null,recurringDiscountPercent:round(recurring.percent),recurringDiscountAmount:round(recurring.discount),priceAfterRecurringDiscount:round(recurring.amount),manualDiscount:round(manualDiscount),taxes:round(taxes),finalPrice:round(finalPrice),monthlyPrice:estimatedMonthlyTotal(finalPrice,input.frequency,input.customIntervalDays)}}
export function residentialCatalogPrice(input:ResidentialCalculatorInput,service:CatalogService,tiers:ServicePriceTier[],addons:ServiceAddon[]){const serviceTiers=tiers.filter(x=>x.service_id===service.id&&x.is_active);const exact=serviceTiers.find(x=>x.pricing_config.bedrooms===input.bedrooms&&x.pricing_config.bathrooms===input.bathrooms);const tier=exact??findMatchingTier(serviceTiers,Math.min(Math.max(Math.round(input.bedrooms),0),4));if(!tier)throw new Error(`No active price tier matches ${input.bedrooms} bedrooms for ${service.service_name}.`);return{basePrice:Math.max(tier.price,service.minimum_price),isExactConfiguration:Boolean(exact),addonAdjustments:calculateAddons(input.addOns,addons)}}
export function catalogConfigNumber(service:CatalogService,key:string){const value=Number(service.pricing_config[key]);if(!Number.isFinite(value))throw new Error(`Pricing configuration is missing ${key} for ${service.service_name}.`);return value}
export function commercialCatalogContext(input:CommercialCalculatorInput,service:CatalogService,addons:ServiceAddon[]){const context={productionRate:catalogConfigNumber(service,"production_rate"),restroomHours:catalogConfigNumber(service,"restroom_hours"),kitchenHours:catalogConfigNumber(service,"kitchen_hours"),stationHours:catalogConfigNumber(service,"station_hours"),unitHours:catalogConfigNumber(service,"unit_hours"),additionalFloorHours:catalogConfigNumber(service,"additional_floor_hours"),minimumSupplyCost:catalogConfigNumber(service,"minimum_supply_cost"),supplyCostPerSquareFoot:catalogConfigNumber(service,"supply_cost_per_square_foot"),maximumMarginPercent:catalogConfigNumber(service,"maximum_margin_percent"),minimumMarginDenominator:catalogConfigNumber(service,"minimum_margin_denominator"),addonAdjustments:calculateAddons(input.additionalServices,addons,input.workerHourlyPay)};assertProductionPricing(service,context);return context}
export function assertProductionPricing(service:CatalogService,context:{productionRate:number;minimumSupplyCost:number;supplyCostPerSquareFoot:number;maximumMarginPercent:number;minimumMarginDenominator:number}){if(context.productionRate<=0)throw new Error(`Custom Pricing Required for ${service.service_name}: configure a production rate.`);if(service.pricing_config.requires_complete_pricing_config&&(context.minimumSupplyCost<=0&&context.supplyCostPerSquareFoot<=0))throw new Error(`Custom Pricing Required for ${service.service_name}: configure supply or material costs.`);if(context.maximumMarginPercent<=0||context.minimumMarginDenominator<=0)throw new Error(`Custom Pricing Required for ${service.service_name}: configure valid margin guardrails.`)}
export function calculateServicePrice(service:CatalogService,quantity:number,tiers:ServicePriceTier[]){if(service.pricing_model==="Custom")return null;if(service.pricing_model==="Size Tier")return findMatchingTier(tiers.filter(x=>x.service_id===service.id),quantity)?.price??null;if(service.pricing_model==="Flat Rate"||service.pricing_model==="Per Visit")return Math.max(service.base_price,service.minimum_price);return Math.max(service.base_price*quantity,service.minimum_price)}
const round=(n:number)=>Math.round(n*100)/100;
const clampPercent=(value:number)=>Math.min(100,Math.max(0,Number(value)||0));
