import type { Frequency, CommercialCalculatorInput, ResidentialCalculatorInput } from "@/types/estimate";
import type { CatalogService, RecurringPricingRule, ServiceAddon, ServicePriceTier } from "@/types/serviceCatalog";

export function findMatchingTier(tiers:ServicePriceTier[],value:number){return tiers.filter(x=>x.is_active&&(x.min_value==null||value>=x.min_value)&&(x.max_value==null||value<=x.max_value)).sort((a,b)=>a.display_order-b.display_order)[0]??null}
export function calculateAddons(names:string[],addons:ServiceAddon[],hourlyRate=0){return names.map(name=>{const addon=addons.find(x=>x.addon_name===name);if(!addon)throw new Error(`Pricing is unavailable for add-on: ${name}`);const labor=Number(addon.pricing_config.labor_hours??0);const supplies=Number(addon.pricing_config.supply_cost??addon.price);return{label:name,amount:round(addon.pricing_model==="Custom"?labor*hourlyRate+supplies:addon.price)}})}
export function applyRecurringRule(amount:number,frequency:string,rules:RecurringPricingRule[],serviceId:string){const matches=rules.filter(x=>x.is_active&&x.frequency===frequency&&(x.service_id===serviceId||x.service_id===null));const rule=matches.find(x=>x.service_id===serviceId)??matches.find(x=>x.service_id===null);if(!rule)return{amount,discount:0,percent:0};if(rule.adjustment_type==="Percentage"){const discount=amount*rule.adjustment_value/100;return{amount:amount-discount,discount,percent:rule.adjustment_value}}if(rule.adjustment_type==="Flat Amount")return{amount:Math.max(0,amount-rule.adjustment_value),discount:Math.min(amount,rule.adjustment_value),percent:amount?rule.adjustment_value/amount*100:0};return{amount:rule.adjustment_value,discount:Math.max(0,amount-rule.adjustment_value),percent:amount?Math.max(0,amount-rule.adjustment_value)/amount*100:0}}
export function residentialCatalogPrice(input:ResidentialCalculatorInput,service:CatalogService,tiers:ServicePriceTier[],addons:ServiceAddon[]){const serviceTiers=tiers.filter(x=>x.service_id===service.id&&x.is_active);const exact=serviceTiers.find(x=>x.pricing_config.bedrooms===input.bedrooms&&x.pricing_config.bathrooms===input.bathrooms);const tier=exact??findMatchingTier(serviceTiers,Math.min(Math.max(Math.round(input.bedrooms),0),4));if(!tier)throw new Error(`No active price tier matches ${input.bedrooms} bedrooms for ${service.service_name}.`);return{basePrice:Math.max(tier.price,service.minimum_price),isExactConfiguration:Boolean(exact),addonAdjustments:calculateAddons(input.addOns,addons)}}
export function commercialCatalogContext(input:CommercialCalculatorInput,service:CatalogService,addons:ServiceAddon[]){const number=(key:string)=>{const value=Number(service.pricing_config[key]);if(!Number.isFinite(value))throw new Error(`Commercial pricing configuration is missing ${key} for ${service.service_name}.`);return value};return{productionRate:number("production_rate"),restroomHours:number("restroom_hours"),kitchenHours:number("kitchen_hours"),stationHours:number("station_hours"),unitHours:number("unit_hours"),additionalFloorHours:number("additional_floor_hours"),minimumSupplyCost:number("minimum_supply_cost"),supplyCostPerSquareFoot:number("supply_cost_per_square_foot"),maximumMarginPercent:number("maximum_margin_percent"),minimumMarginDenominator:number("minimum_margin_denominator"),addonAdjustments:calculateAddons(input.additionalServices,addons,input.workerHourlyPay)}}
export function calculateServicePrice(service:CatalogService,quantity:number,tiers:ServicePriceTier[]){if(service.pricing_model==="Custom")return null;if(service.pricing_model==="Size Tier")return findMatchingTier(tiers.filter(x=>x.service_id===service.id),quantity)?.price??null;if(service.pricing_model==="Flat Rate"||service.pricing_model==="Per Visit")return Math.max(service.base_price,service.minimum_price);return Math.max(service.base_price*quantity,service.minimum_price)}
const round=(n:number)=>Math.round(n*100)/100;
