import type { EstimateResult, Frequency } from "@/types/estimate";
import type { ProposalAdjustment, ProposalResult, ProposalScopeItem, ProposalTerms } from "@/types/proposal";
import { estimatedMonthlyTotal } from "@/lib/scheduling/frequency";
import { applyRecurringRule } from "@/lib/pricing/pricingEngine";
import type { RecurringPricingRule } from "@/types/serviceCatalog";

export function repriceEstimateFrequency(estimate:EstimateResult,frequency:Frequency,rules:RecurringPricingRule[],serviceId:string):EstimateResult{const recurring=applyRecurringRule(estimate.oneTimePrice,frequency,rules,serviceId),manualDiscount=estimate.manualDiscount,subtotal=Math.max(0,estimate.oneTimePrice-recurring.discount-manualDiscount),taxRate=estimate.calculatorInput.taxRatePercent,taxes=money(subtotal*Math.min(100,Math.max(0,taxRate))/100),finalPrice=money(subtotal+taxes);return{...estimate,recurringDiscount:money(recurring.discount),recurringDiscountPercent:money(recurring.percent),totalDiscount:money(recurring.discount+manualDiscount),taxes,finalPrice,monthlyPrice:estimatedMonthlyTotal(finalPrice,frequency),calculatorInput:{...estimate.calculatorInput,frequency}}}

export function calculateProposal(input: { estimate: EstimateResult | null; catalogBasePrice?:number; catalogRecurringDiscount?:number; catalogRecurringDiscountPercent?:number; serviceName: string; serviceDescription: string | null; frequency: Frequency; adjustments: ProposalAdjustment[]; additionalLabor: number; additionalMaterials: number; manualDiscountPercent: number; taxRate: number; scope: ProposalScopeItem[]; terms: ProposalTerms }): ProposalResult {
  const base = input.estimate?.finalPrice ?? Math.max(0,(input.catalogBasePrice??0)-(input.catalogRecurringDiscount??0)); const adjustmentTotal = input.adjustments.reduce((sum, item) => sum + item.amount, 0); const beforeDiscount = base + adjustmentTotal + input.additionalLabor + input.additionalMaterials; const manualDiscount = beforeDiscount * clamp(input.manualDiscountPercent) / 100; const taxable = Math.max(0, beforeDiscount - manualDiscount); const taxes = taxable * clamp(input.taxRate) / 100; const perVisitTotal = taxable + taxes; const laborHours = (input.estimate?.laborHours ?? 0) + input.additionalLabor / 25; const crew = Math.max(1, input.estimate?.crewSize ?? Math.ceil(laborHours / 4)); const duration = Math.round((laborHours / crew) * 10) / 10; const costs = (input.estimate?.laborCost ?? 0) + (input.estimate?.supplyCost ?? 0) + input.additionalMaterials + input.additionalLabor;
  return { serviceName: input.serviceName, serviceDescription: input.serviceDescription, baseEstimateAmount: money(input.estimate?.oneTimePrice??input.catalogBasePrice??base), adjustments: input.adjustments, additionalLabor: money(input.additionalLabor), additionalMaterials: money(input.additionalMaterials), frequencyDiscount: input.estimate?.recurringDiscount ?? input.catalogRecurringDiscount ?? 0, frequencyDiscountPercent: input.estimate?.recurringDiscountPercent ?? input.catalogRecurringDiscountPercent ?? 0, inheritedManualDiscount: input.estimate?.manualDiscount ?? 0, manualDiscount: money(manualDiscount), taxRate: input.taxRate, taxes: money(taxes), perVisitTotal: money(perVisitTotal), monthlyTotal: estimatedMonthlyTotal(perVisitTotal,input.frequency), laborHours: Math.round(laborHours * 10) / 10, crewRecommendation: crew, estimatedDuration: duration, estimatedProfit: money(perVisitTotal - costs), scope: input.scope, terms: input.terms };
}
function clamp(value: number): number { return Math.min(100, Math.max(0, value || 0)); }
function money(value: number): number { return Math.round(value * 100) / 100; }
