import type { EstimateResult, Frequency } from "@/types/estimate";
import type { ProposalAdjustment, ProposalResult, ProposalScopeItem, ProposalTerms } from "@/types/proposal";

const visits: Record<Frequency, number> = { "One-Time": 1, Weekly: 4.33, Biweekly: 2.17, Monthly: 1 };
export function calculateProposal(input: { estimate: EstimateResult | null; serviceName: string; serviceDescription: string | null; frequency: Frequency; adjustments: ProposalAdjustment[]; additionalLabor: number; additionalMaterials: number; manualDiscountPercent: number; taxRate: number; scope: ProposalScopeItem[]; terms: ProposalTerms }): ProposalResult {
  const base = input.estimate?.finalPrice ?? 0; const adjustmentTotal = input.adjustments.reduce((sum, item) => sum + item.amount, 0); const beforeDiscount = base + adjustmentTotal + input.additionalLabor + input.additionalMaterials; const manualDiscount = beforeDiscount * clamp(input.manualDiscountPercent) / 100; const taxable = Math.max(0, beforeDiscount - manualDiscount); const taxes = taxable * clamp(input.taxRate) / 100; const perVisitTotal = taxable + taxes; const laborHours = (input.estimate?.laborHours ?? 0) + input.additionalLabor / 25; const crew = Math.max(1, input.estimate?.crewSize ?? Math.ceil(laborHours / 4)); const duration = Math.round((laborHours / crew) * 10) / 10; const costs = (input.estimate?.laborCost ?? 0) + (input.estimate?.supplyCost ?? 0) + input.additionalMaterials + input.additionalLabor;
  return { serviceName: input.serviceName, serviceDescription: input.serviceDescription, baseEstimateAmount: money(base), adjustments: input.adjustments, additionalLabor: money(input.additionalLabor), additionalMaterials: money(input.additionalMaterials), manualDiscount: money(manualDiscount), taxRate: input.taxRate, taxes: money(taxes), perVisitTotal: money(perVisitTotal), monthlyTotal: input.frequency === "One-Time" ? null : money(perVisitTotal * visits[input.frequency]), laborHours: Math.round(laborHours * 10) / 10, crewRecommendation: crew, estimatedDuration: duration, estimatedProfit: money(perVisitTotal - costs), scope: input.scope, terms: input.terms };
}
function clamp(value: number): number { return Math.min(100, Math.max(0, value || 0)); }
function money(value: number): number { return Math.round(value * 100) / 100; }
