"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { dismissAttentionItem, getAttentionItems, restoreAttentionItem, snoozeAttentionItem, summarizeAttention } from "@/lib/services/attention";
import { ATTENTION_CATEGORIES, ATTENTION_SEVERITIES, type AttentionCategory, type AttentionItem, type AttentionSeverity, type AttentionView } from "@/types/attention";
import { LogCommunicationModal } from "@/components/communications/LogCommunicationModal";

export function AttentionCenterPage() {
  const [items, setItems] = useState<AttentionItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [severity, setSeverity] = useState<"All" | AttentionSeverity>("All"); const [category, setCategory] = useState<"All" | AttentionCategory>("All");
  const [view, setView] = useState<AttentionView>("Active"); const [changing, setChanging] = useState<string | null>(null);
  const [composerItem, setComposerItem] = useState<AttentionItem | null>(null);
  async function load() { setLoading(true); setError(null); try { setItems(await getAttentionItems("All")); } catch (caught) { console.error("Attention Center load failed", caught); setError("Attention Center could not be loaded."); } finally { setLoading(false); } }
  useEffect(() => {
    // Initial client-side hydration from role-scoped services.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, []);
  const activeItems = items.filter((item) => !item.attention_state); const summary = summarizeAttention(activeItems);
  const shown = useMemo(() => items.filter((item) => (view === "All" || (view === "Active" ? !item.attention_state : item.attention_state?.state === view)) && (severity === "All" || item.severity === severity) && (category === "All" || item.category === category)), [category, items, severity, view]);
  async function change(key: string, action: () => Promise<void>) { setChanging(key); setError(null); try { await action(); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Attention state could not be updated."); } finally { setChanging(null); } }
  function snooze(entry: AttentionItem) { const choice = window.prompt("Snooze for: 1 hour, Tomorrow, 3 days, 1 week, or enter a date/time", "Tomorrow"); if (!choice) return; const until = snoozeDate(choice); if (!until) { setError("Enter 1 hour, Tomorrow, 3 days, 1 week, or a valid date/time."); return; } void change(entry.id, () => snoozeAttentionItem(entry.id, until)); }
  return <>
    <header className="border-b border-[#143d1a]/10 pb-7"><p className="mb-3 text-[11px] font-extrabold uppercase tracking-[.2em] text-[#9a7a17]">Operations workspace</p><h1 className="text-3xl font-extrabold tracking-[-.04em] text-[#143d1a] sm:text-4xl">Attention Center</h1><p className="mt-3 max-w-2xl text-neutral-600">Review operational items that need follow-up across StudioScrubz OS.</p></header>
    <section className="mt-7 grid grid-cols-2 gap-4 xl:grid-cols-4"><Metric label="Urgent" value={summary.urgent} tone="red"/><Metric label="Needs Attention" value={summary.attention} tone="amber"/><Metric label="Upcoming" value={summary.info} tone="green"/><Metric label="Total Open" value={summary.total} tone="neutral"/></section>
    <section className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3"><select className={selectClass} value={view} onChange={(e) => setView(e.target.value as AttentionView)}>{(["Active", "Snoozed", "Dismissed", "All"] as AttentionView[]).map((value) => <option key={value}>{value}</option>)}</select><select className={selectClass} value={severity} onChange={(e) => setSeverity(e.target.value as typeof severity)}><option>All</option>{ATTENTION_SEVERITIES.map((value) => <option key={value}>{value}</option>)}</select><select className={selectClass} value={category} onChange={(e) => setCategory(e.target.value as typeof category)}><option>All</option>{ATTENTION_CATEGORIES.map((value) => <option key={value}>{value}</option>)}</select></section>
    {error && <div role="alert" className="mt-6 flex items-center justify-between rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700"><span>{error}</span><button className="rounded-lg border border-red-200 px-3 py-2" onClick={() => void load()}>Retry</button></div>}
    {loading ? <div className="mt-6 space-y-3" aria-label="Loading attention items"><p className="text-sm font-semibold text-neutral-500">Loading attention items…</p><div className="h-28 animate-pulse rounded-2xl bg-neutral-100"/><div className="h-28 animate-pulse rounded-2xl bg-neutral-100"/></div>
      : shown.length === 0 ? <div className="mt-6 grid min-h-64 place-items-center rounded-2xl border bg-white p-8 text-center"><div><h2 className="font-extrabold text-[#143d1a]">No items need attention.</h2><p className="mt-2 text-sm text-neutral-500">Resolved items disappear automatically as operational records are updated.</p></div></div>
      : <div className="mt-6 grid gap-4 xl:grid-cols-2">{shown.map((entry) => <article key={entry.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${border(entry.severity)}`}><div className="flex items-start justify-between gap-4"><div><div className="flex gap-2"><span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wide ${badge(entry.severity)}`}>{entry.severity}</span>{entry.attention_state && <span className="rounded-full bg-neutral-100 px-2.5 py-1 text-[10px] font-extrabold uppercase text-neutral-600">{entry.attention_state.state}</span>}</div><h2 className="mt-3 text-lg font-extrabold text-[#143d1a]">{entry.title}</h2><p className="mt-1 text-sm leading-6 text-neutral-600">{entry.description}</p></div><span className="text-xs font-bold text-neutral-400">{entry.category}</span></div><div className="mt-4 flex flex-wrap items-end justify-between gap-3 border-t border-neutral-100 pt-4"><div><p className="text-sm font-bold text-neutral-700">{entry.entity_label || entry.record_type}</p>{(entry.due_date || entry.scheduled_date) && <p className="mt-1 text-xs text-neutral-500">{entry.due_date ? "Due" : "Scheduled"} {friendlyDate(entry.due_date || entry.scheduled_date!)}</p>}</div><div className="flex flex-wrap justify-end gap-2">{entry.attention_state ? <button disabled={changing === entry.id} onClick={() => void change(entry.id, () => restoreAttentionItem(entry.id))} className={secondary}>Restore</button> : <>{entry.snoozable && <button disabled={changing === entry.id} onClick={() => snooze(entry)} className={secondary}>Snooze</button>}{entry.dismissible && <button disabled={changing === entry.id} onClick={() => void change(entry.id, () => dismissAttentionItem(entry.id))} className={secondary}>Dismiss</button>}</>}{entry.communication_context && <button onClick={() => setComposerItem(entry)} className="rounded-lg bg-[#143d1a] px-4 py-2.5 text-sm font-bold text-white">{followupLabel(entry.type)}</button>}<Link href={entry.action_url} className={entry.communication_context ? secondary : "rounded-lg bg-[#143d1a] px-4 py-2.5 text-sm font-bold text-white"}>{entry.action_label}</Link></div></div></article>)}</div>}
    {composerItem?.communication_context && <LogCommunicationModal links={{ clientId: composerItem.communication_context.clientId ?? undefined, propertyId: composerItem.communication_context.propertyId ?? undefined, proposalId: composerItem.communication_context.proposalId ?? undefined, agreementId: composerItem.communication_context.agreementId ?? undefined, invoiceId: composerItem.communication_context.invoiceId ?? undefined }} context={composerItem.communication_context} onClose={() => setComposerItem(null)} onCreated={() => { void load(); }} />}
  </>;
}

function Metric({ label, value, tone }: { label: string; value: number; tone: "red" | "amber" | "green" | "neutral" }) { const style = { red: "border-red-200 bg-red-50", amber: "border-amber-200 bg-amber-50", green: "border-emerald-200 bg-emerald-50", neutral: "border-neutral-200 bg-white" }[tone]; return <article className={`rounded-2xl border p-5 ${style}`}><p className="text-xs font-extrabold uppercase tracking-wide text-neutral-500">{label}</p><p className="mt-4 text-3xl font-extrabold text-[#143d1a]">{value}</p></article>; }
function friendlyDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(`${value.slice(0, 10)}T12:00:00`)); }
function badge(value: AttentionSeverity) { return value === "Urgent" ? "bg-red-100 text-red-800" : value === "Attention" ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"; }
function border(value: AttentionSeverity) { return value === "Urgent" ? "border-red-200" : value === "Attention" ? "border-amber-200" : "border-emerald-200"; }
const selectClass = "h-11 rounded-lg border border-neutral-200 bg-white px-3.5 text-sm text-neutral-700 outline-none focus:border-[#d4af37]";
const secondary = "rounded-lg border border-neutral-200 px-3 py-2.5 text-sm font-bold text-[#143d1a] disabled:opacity-50";
function snoozeDate(value: string) { const now = new Date(); const normalized = value.trim().toLowerCase(); if (normalized === "1 hour") now.setHours(now.getHours() + 1); else if (normalized === "tomorrow") { now.setDate(now.getDate() + 1); now.setHours(9, 0, 0, 0); } else if (normalized === "3 days") now.setDate(now.getDate() + 3); else if (normalized === "1 week") now.setDate(now.getDate() + 7); else { const parsed = new Date(value); if (Number.isNaN(parsed.getTime())) return null; return parsed.toISOString(); } return now.toISOString(); }
function followupLabel(type: AttentionItem["type"]) { if (type === "Service Reminder Due") return "Send Reminder"; if (type === "Invoice Due Soon" || type === "Overdue Invoice") return "Send Payment Reminder"; if (type === "Failed Client Communication") return "Prepare Again"; return "Follow Up"; }
