// Packet sections are presentation copy, not catalog services or pricing records.
export const modules = [
  { id: "commercial", title: "Commercial Cleaning", bullets: ["Offices and professional spaces","Floor cleaning","Restrooms","Breakrooms and shared areas","High-touch surfaces","Interior glass","Trash removal when included","Detail cleaning","Recurring and custom facility scopes"], note: "StudioScrubz structures commercial cleaning around traffic, operating hours, customer-facing areas, shared spaces, and recurring facility needs. The plan supports how your facility operates, rather than forcing every business into the same generic checklist." },
  { id: "property-management", title: "Property Management & Common Areas", bullets: ["Common-area cleaning","Lobbies, corridors, and stairwells","Laundry rooms","Shared amenities","Interior glass and touchpoints","Unit-turn coordination","Pressure washing and exterior cleaning for suitable surfaces","Recurring property-specific scopes"], note: "StudioScrubz supports management and ownership teams with recurring common-area service, unit turns, exterior cleaning, and specialty projects under a property-specific scope. Our goal is to help maintain presentation standards with clear service expectations, scheduling, and included work. Exterior work and unit turns are confirmed within that scope." },
  { id: "unit-turns", title: "Unit Turns", bullets: ["Move-out cleaning and move-in preparation","Kitchens and bathrooms","Cabinets and drawers when included","Appliances when included","Interior glass when included","Dust and light debris within the cleaning scope","Floors","Final presentation cleaning"], note: "StudioScrubz helps prepare vacancies for leasing, inspection, and move-in, coordinating cleaning around maintenance, renovation, and turnover schedules. Each turn is assessed against unit condition and management requirements to define the work needed for the expected presentation standard. Repairs, painting, and maintenance are excluded." },
  { id: "post-construction", title: "Post-Construction Cleaning", bullets: ["Construction dust removal","Detailed surface cleaning","Cabinets and built-ins","Baseboards, trim, and doors","Fixtures","Interior glass when included","Floors","Kitchens and bathrooms","Final-detail cleaning","Phased cleaning based on project readiness"], note: "StudioScrubz treats cleaning as project closeout, organized around construction residue, finished surfaces, access, and turnover expectations. Area-by-area or phased service can help completed spaces move toward presentation, inspection, or occupancy. Hazardous-material cleanup, asbestos handling, mold remediation, heavy debris hauling, and trade work are excluded." },
  { id: "pressure-washing", title: "Pressure Washing", bullets: ["Walkways and entries","Courtyards and patios","Exterior common areas","Suitable hardscape surfaces","Trash-area exterior cleaning","Property-specific exterior projects"], note: "StudioScrubz plans exterior cleaning around surface material, condition, surrounding areas, and access to support property presentation. Not every surface is suitable for pressure washing. Projects can be included in broader property-service scopes or scheduled individually for maintenance and presentation." },
  { id: "production-facilities", title: "Recording & Production Facilities", bullets: ["Recording rooms","Control rooms and production rooms","Lounges and common areas","Kitchens and restrooms","Floors and accessible surfaces","Interior glass","Equipment-conscious, facility-specific cleaning"], note: "Recording and production environments are where StudioScrubz began. Working in creative facilities helped shape our attention to detail, respect for active professional spaces, and awareness that these environments require a different approach than a traditional office. Service can accommodate room availability, production schedules, access, and equipment-sensitive areas within the approved scope. Sensitive electronic and audio equipment servicing, internal cleaning, and repairs are excluded." },
  { id: "residential", title: "Residential Cleaning", bullets: ["Standard and deep cleaning","Move-in and move-out cleaning","Kitchens and bathrooms","Bedrooms and living areas","Floors","Interior detail work","Add-ons within the confirmed scope","Recurring service"], note: "StudioScrubz brings the same defined expectations and professional execution to homes as to commercial and specialty work. Recommendations reflect the home's condition, requested areas, service level, and additional work identified during assessment, so clients understand what is included before service begins." },
  { id: "airbnb-turnover", title: "Airbnb / Turnover Cleaning", bullets: ["Turnover cleaning","Kitchen and bathroom reset","Bedrooms and living areas","Floors","Trash removal when included","Laundry and bed reset when included","Restocking coordination when included","Property-condition observations"], note: "StudioScrubz structures turnovers around the property's schedule and the host or management team's reset requirements to support timing, consistency, and presentation between guests. Timing and access are confirmed before service. When included, laundry coordination, restocking coordination, bed resets, and condition observations support preparation for the next guest." },
] as const;
export const strengths = [{"title":"Clearly Defined Scope","copy":"We confirm the areas, tasks, and service expectations before work begins so you know what is included."},{"title":"Professional Communication","copy":"Clear communication keeps property priorities, access details, and scheduling needs part of the service plan."},{"title":"Flexible Service Capabilities","copy":"Selected services can support one-time projects or recurring needs across residential and commercial environments."},{"title":"Documented Workflow","copy":"Our operating process is designed to maintain visibility from assessment through completion. When work outside the approved scope is discovered, it can be documented and addressed before additional work is treated as authorized."},{"title":"Property-Aware Service","copy":"We plan around the space, its surfaces, and how it is used, with respect for customer property and operating needs."}];
export const process = [{"title":"Assessment","copy":"We review your property, priorities, and cleaning needs, with a walkthrough or project assessment when needed."},{"title":"Defined Scope","copy":"We confirm the areas, tasks, inclusions, and service expectations."},{"title":"Proposal & Scheduling","copy":"We prepare a proposal and coordinate scheduling and access once service details are confirmed."},{"title":"Professional Service","copy":"We perform the confirmed cleaning scope with attention to the property and its operating needs."},{"title":"Review & Documentation","copy":"We review the completed service and document completion details and relevant observations."}];

export const intro = ["StudioScrubz provides professional cleaning and property-service solutions for residential, commercial, property-management, construction, hospitality, and production environments.","Our approach is built around clearly defined scope, dependable communication, professional service, and documented completion so clients know what is being handled before, during, and after service."];

export const about = ["StudioScrubz began by cleaning recording studios and production environments, where attention to detail, equipment-conscious work, and respect for active professional spaces were essential.","The company expanded that service approach into residential, commercial, property-management, post-construction, turnover, and exterior cleaning services.","Today, StudioScrubz works with clients who need more than a basic cleaning appointment. Our goal is to provide clearly defined service, dependable communication, professional execution, and a documented process from assessment through completion."];

export const cta = "Every property and project has different needs. StudioScrubz can assess your facility, define the appropriate scope, and prepare a service proposal based on your priorities.";

export const disclaimer = "This capability overview is not an estimate, proposal, or service agreement. Specific work and pricing are confirmed separately.";
