// Packet sections are presentation copy, not catalog services or pricing records.
export const modules = [
  { id: "commercial", title: "Commercial Cleaning", bullets: ["Offices and professional spaces","Floor cleaning","Restrooms","Breakrooms and shared areas","High-touch surfaces","Interior glass","Trash removal when included","Detail cleaning","Recurring and custom facility scopes"], note: "" },
  { id: "property-management", title: "Property Management & Common Areas", bullets: ["Common-area cleaning","Lobbies, corridors, and stairwells","Laundry rooms","Shared amenities","Interior glass and touchpoints","Unit-turn coordination","Pressure washing and exterior cleaning for suitable surfaces","Recurring property-specific scopes"], note: "Exterior work and unit turns are confirmed as part of the property service scope." },
  { id: "unit-turns", title: "Unit Turns", bullets: ["Move-out cleaning and move-in preparation","Kitchens and bathrooms","Cabinets and drawers when included","Appliances when included","Interior glass when included","Dust and light debris within the cleaning scope","Floors","Final presentation cleaning"], note: "Cleaning does not include repairs, painting, or maintenance." },
  { id: "post-construction", title: "Post-Construction Cleaning", bullets: ["Construction dust removal","Detailed surface cleaning","Cabinets and built-ins","Baseboards, trim, and doors","Fixtures","Interior glass when included","Floors","Kitchens and bathrooms","Final-detail cleaning","Phased cleaning based on project readiness"], note: "Hazardous-material cleanup, asbestos handling, mold remediation, heavy debris hauling, and trade work are excluded." },
  { id: "pressure-washing", title: "Pressure Washing", bullets: ["Walkways and entries","Courtyards and patios","Exterior common areas","Suitable hardscape surfaces","Trash-area exterior cleaning","Property-specific exterior projects"], note: "Surface material, condition, access, and cleaning needs are reviewed before scope is confirmed. Not every surface is suitable for pressure washing." },
  { id: "production-facilities", title: "Recording & Production Facilities", bullets: ["Recording rooms","Control rooms and production rooms","Lounges and common areas","Kitchens and restrooms","Floors and accessible surfaces","Interior glass","Equipment-conscious, facility-specific cleaning"], note: "Sensitive electronic and audio equipment servicing, internal cleaning, and repairs are excluded." },
  { id: "residential", title: "Residential Cleaning", bullets: ["Standard and deep cleaning","Move-in and move-out cleaning","Kitchens and bathrooms","Bedrooms and living areas","Floors","Interior detail work","Add-ons within the confirmed scope","Recurring service"], note: "" },
  { id: "airbnb-turnover", title: "Airbnb / Turnover Cleaning", bullets: ["Turnover cleaning","Kitchen and bathroom reset","Bedrooms and living areas","Floors","Trash removal when included","Laundry and bed reset when included","Restocking coordination when included","Property-condition observations"], note: "Timing, access, laundry, and special turnover requirements are confirmed before service." },
] as const;
export const strengths = [{"title":"Clearly Defined Scope","copy":"We confirm the areas, tasks, and service expectations before work begins so you know what is included."},{"title":"Professional Communication","copy":"Clear communication keeps property priorities, access details, and scheduling needs part of the service plan."},{"title":"Flexible Service Capabilities","copy":"Selected services can support one-time projects or recurring needs across residential and commercial environments."},{"title":"Documented Workflow","copy":"Assessment, scope, and completion details provide a clear record of the service process."},{"title":"Property-Aware Service","copy":"We plan around the space, its surfaces, and how it is used, with respect for customer property and operating needs."}];
export const process = [{"title":"Assessment","copy":"We review your property, priorities, and cleaning needs, with a walkthrough or project assessment when needed."},{"title":"Defined Scope","copy":"We confirm the areas, tasks, inclusions, and service expectations."},{"title":"Proposal & Scheduling","copy":"We prepare a proposal and coordinate scheduling and access once service details are confirmed."},{"title":"Professional Service","copy":"We perform the confirmed cleaning scope with attention to the property and its operating needs."},{"title":"Review & Documentation","copy":"We review the completed service and document completion details and relevant observations."}];

export const intro = ["StudioScrubz provides professional cleaning and property-service solutions for residential, commercial, property-management, construction, hospitality, and production environments.","Our approach is built around clearly defined scope, dependable communication, professional service, and documented completion so clients know what is being handled before, during, and after service."];

export const about = ["StudioScrubz began by cleaning recording studios and production environments, where attention to detail, equipment-conscious work, and respect for active professional spaces were essential.","The company expanded that service approach into residential, commercial, property-management, post-construction, turnover, and exterior cleaning services.","Today, StudioScrubz works with clients who need more than a basic cleaning appointment. Our goal is to provide clearly defined service, dependable communication, professional execution, and a documented process from assessment through completion."];

export const cta = "Every property and project has different needs. StudioScrubz can assess your facility, define the appropriate scope, and prepare a service proposal based on your priorities.";

export const disclaimer = "This capability overview is not an estimate, proposal, or service agreement. Specific work and pricing are confirmed separately.";
