import Link from "next/link";
import { ESTIMATE_URL, services } from "./siteData";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="text-xs font-extrabold uppercase tracking-[.22em] text-[#9a7a17]">{children}</p>; }
export function SectionHeading({ eyebrow, title, copy, centered=false }: { eyebrow: string; title: string; copy?: string; centered?: boolean }) { return <div className={centered?"mx-auto max-w-3xl text-center":"max-w-3xl"}><Eyebrow>{eyebrow}</Eyebrow><h2 className="mt-4 text-3xl font-extrabold tracking-[-.045em] text-[#143d1a] sm:text-5xl">{title}</h2>{copy&&<p className="mt-5 text-base leading-7 text-neutral-600 sm:text-lg">{copy}</p>}</div>; }
export function EstimateCta({ label="Get an Estimate", className="" }: { label?: string; className?: string }) { return <a href={ESTIMATE_URL} className={`inline-flex min-h-12 items-center justify-center rounded-full bg-[#143d1a] px-6 py-3 text-sm font-extrabold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-[#0d2b12] ${className}`}>{label}</a>; }
export function ServiceGrid() { return <div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{services.map((service,index)=><article key={service.title} className="group flex min-h-64 flex-col rounded-[1.6rem] border border-[#143d1a]/10 bg-white p-7 shadow-[0_18px_50px_rgba(20,61,26,.06)]"><span className="grid size-11 place-items-center rounded-full bg-[#edf4e9] text-sm font-black text-[#9a7a17]">{String(index+1).padStart(2,"0")}</span><h3 className="mt-6 text-xl font-extrabold text-[#143d1a]">{service.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-neutral-600">{service.description}</p><div className="mt-6 flex items-center gap-4"><Link href={service.href} className="text-sm font-extrabold text-[#143d1a] hover:text-[#9a7a17]">Learn More →</Link><a href={ESTIMATE_URL} className="text-sm font-bold text-[#9a7a17]">Get Estimate</a></div></article>)}</div>; }
export function ContactBand({ title="Ready for a cleaner, calmer space?", copy="Tell us what you need and StudioScrubz will help you find the right next step." }: { title?: string; copy?: string }) { return <section className="px-5 py-16 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 overflow-hidden rounded-[2rem] bg-[#143d1a] p-8 text-white shadow-[0_24px_70px_rgba(13,43,18,.22)] sm:p-12 lg:flex-row lg:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#e5cd7d]">No mess. No stress.</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.04em] sm:text-4xl">{title}</h2><p className="mt-3 max-w-2xl text-white/70">{copy}</p></div><div className="flex flex-wrap gap-3"><EstimateCta className="bg-[#d4af37] text-[#143d1a] hover:bg-[#e5cd7d]"/><Link href="/contact" className="inline-flex min-h-12 items-center rounded-full border border-white/25 px-6 py-3 text-sm font-extrabold text-white hover:bg-white/10">Contact StudioScrubz</Link></div></div></section>; }
export function PageHero({ eyebrow, title, copy, cta="Get an Estimate" }: { eyebrow: string; title: string; copy: string; cta?: string }) { return <section className="relative overflow-hidden bg-[#eef3ea] px-5 py-20 sm:px-8 sm:py-28"><div className="absolute -right-28 -top-28 size-96 rounded-full bg-[#d4af37]/15 blur-3xl"/><div className="absolute -bottom-40 left-0 size-96 rounded-full bg-[#143d1a]/10 blur-3xl"/><div className="relative mx-auto max-w-7xl"><div className="max-w-4xl"><Eyebrow>{eyebrow}</Eyebrow><h1 className="mt-5 text-5xl font-extrabold tracking-[-.055em] text-[#143d1a] sm:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-neutral-600">{copy}</p><div className="mt-8 flex flex-wrap gap-3"><EstimateCta label={cta}/><Link href="/contact" className="inline-flex min-h-12 items-center rounded-full border border-[#143d1a]/20 bg-white px-6 py-3 text-sm font-extrabold text-[#143d1a]">Talk to StudioScrubz</Link></div></div></div></section>; }
export function FeatureList({ items }: { items: readonly string[] }) { return <div className="mt-8 grid gap-3 sm:grid-cols-2">{items.map(item=><div key={item} className="flex gap-3 rounded-2xl border border-[#143d1a]/10 bg-white p-4 text-sm font-bold text-[#29472d]"><span className="text-[#d4af37]">✦</span>{item}</div>)}</div>; }
