"use client";

import { useState } from "react";
import { GuidedWalkthroughChoice } from "@/components/walkthroughs/GuidedWalkthroughChoice";
import { StandardResidentialCarryForward } from "@/components/walkthroughs/StandardResidentialFieldWalkthrough";
import type { BarbershopSalonFieldAssessment, FieldMeasurements, StandardResidentialContext } from "@/types/fieldWalkthrough";

type Props={measurements:FieldMeasurements;context:StandardResidentialContext;includedAddons:string[];onChange:(v:FieldMeasurements)=>void};
type Value=string|string[]|number|boolean|null;type Answers=Record<string,Value>;
const levels=["Light","Moderate","Heavy","Severe"];
const sections=["Facility Type","Operating Status During Service","Overall Condition","Service Stations","Floors / Hair Accumulation","Mirrors / Glass","Shampoo / Wash Areas","Product / Retail Areas","Reception / Waiting Area","Restrooms","Breakroom / Staff Area","Laundry / Towel Area","Trash / Waste","High-Touch Areas","Special Precautions","Areas Requiring Extra Attention","Service Frequency Observation","Service Suitability","Expected Labor","Exceptions","Final Confirmation"] as const;
export function isBarbershopSalonService(service:string|null|undefined){return service?.trim()==="Barbershop / Salon Cleaning"}
export function barbershopSalonCompletionIssues(m:FieldMeasurements,_c:StandardResidentialContext){const a=assessment(m).answers??{};return sections.filter((_,i)=>issues(i,a).length)}

export function BarbershopSalonFieldWalkthrough({measurements,context,includedAddons,onChange}:Props){
 const [current,setCurrent]=useState(0),a=assessment(measurements).answers??{},missing=issues(current,a);
 const set=(k:string,v:Value)=>onChange({...measurements,barbershopSalonAssessment:{...measurements.barbershopSalonAssessment,fieldWalkthrough:{answers:{...a,[k]:v}}}});
 const toggle=(k:string,v:string,exclusive="None")=>{const old=list(a[k]);set(k,old.includes(v)?old.filter(x=>x!==v):v===exclusive?[v]:[...old.filter(x=>x!==exclusive),v])};
 return <div><StandardResidentialCarryForward context={context}/><aside className="mt-3 rounded-xl bg-blue-50 p-4"><b>Included Add-ons / Scope</b><p className="mt-1 text-sm">{includedAddons.length?includedAddons.join(", "):"No included add-ons were provided."}</p></aside><div className="mt-6 flex justify-between text-sm"><b>{current+1} of {sections.length}</b><span>{Math.round((current+1)/sections.length*100)}% complete</span></div><div className="mt-2 h-2 rounded-full bg-neutral-200"><div className="h-full rounded-full bg-[#143d1a]" style={{width:`${(current+1)/sections.length*100}%`}}/></div><section className="mt-5 rounded-xl border p-4"><h3 className="text-lg font-extrabold text-[#143d1a]">{sections[current]}</h3><div className="mt-4 space-y-5">{render(current,a,set,toggle)}</div></section>{!!missing.length&&<div role="alert" className="mt-4 rounded-lg bg-amber-50 p-3 text-sm"><b>Before continuing:</b><ul className="list-disc pl-5">{missing.map(x=><li key={x}>{x}</li>)}</ul></div>}<div className="mt-5 flex justify-between"><button type="button" className={secondary} disabled={!current} onClick={()=>setCurrent(x=>x-1)}>Previous</button><button type="button" className={primary} disabled={!!missing.length||current===20} onClick={()=>setCurrent(x=>x+1)}>Continue</button></div></div>;
}

function render(i:number,a:Answers,set:(k:string,v:Value)=>void,toggle:(k:string,v:string,e?:string)=>void){switch(i){
case 0:return <><Radio q="What type of facility is this?" k="facilityType" values={["Barbershop","Hair salon","Combined barber/salon","Beauty salon","Other"]} a={a} set={set}/>{a.facilityType==="Other"&&<Notes q="Describe the facility type." k="facilityTypeOther" a={a} set={set}/>}</>;
case 1:return <><Radio q="What is the operating status during service?" k="operatingStatus" values={["Closed/vacant","Staff present","Customers may be present","Varies"]} a={a} set={set}/>{a.operatingStatus!=="Closed/vacant"&&<Radio q="Does occupancy limit cleaning?" k="occupancyLimits" values={["Yes","No"]} a={a} set={set}/>} {a.occupancyLimits==="Yes"&&<Notes q="Describe cleaning limitations." k="occupancyNotes" a={a} set={set}/>}</>;
case 2:return <Radio q="What is the overall condition?" k="overallCondition" values={levels} a={a} set={set}/>;
case 3:return <><label className="block text-sm font-bold">Station/chair count<input type="number" min="0" step="1" className={input} value={typeof a.stationCount==="number"?a.stationCount:""} onChange={e=>set("stationCount",e.target.value===""?null:Number(e.target.value))}/></label><Radio q="What is the service-station condition?" k="stationCondition" values={levels} a={a} set={set}/>{yn(["Hair or debris buildup?","Product residue?","Counter or surface buildup?","Chair or base buildup?","Clutter limits cleaning?","Professional tools require precautions?"],["stationHair","stationProduct","stationSurface","stationChair","stationClutter","stationTools"],a,set)}<p className="text-xs">Professional-tool cleaning or sanitizing is not implied unless explicitly in scope.</p></>;
case 4:return <><Checks q="Which floor types are present?" k="floorTypes" values={["Tile","Vinyl","Laminate","Hardwood","Concrete","Other"]} a={a} toggle={(k,v)=>toggle(k,v,"")}/><Radio q="What is the floor condition?" k="floorCondition" values={levels} a={a} set={set}/>{yn(["Heavy hair accumulation?","Hair concentrated around stations?","Sticky or product residue?","Staining or soiling?","Special precautions?"],["floorHair","floorStationHair","floorResidue","floorStaining","floorPrecautions"],a,set)}{(list(a.floorTypes).includes("Other")||["floorHair","floorStationHair","floorResidue","floorStaining","floorPrecautions"].some(k=>a[k]==="Yes"))&&<Notes q="Describe flooring conditions or precautions." k="floorNotes" a={a} set={set}/>}</>;
case 5:return <>{yn(["Station mirrors?","Entry glass?","Interior glass?","Product or residue buildup?","Heavy fingerprints or smudging?","Access limitations?"],["stationMirrors","entryGlass","interiorGlass","glassResidue","glassSmudging","glassAccess"],a,set)}{a.glassAccess==="Yes"&&<Notes q="Describe access limitations." k="glassNotes" a={a} set={set}/>}</>;
case 6:return <><Area q="What is the shampoo or wash-area condition?" prefix="shampoo" observations={["Sink or basin buildup","Product residue","Fixture buildup","Floor buildup","Hair accumulation","Visible mildew-like buildup"]} a={a} set={set}/><p className="text-xs">Observational only; this is not a professional mold diagnosis.</p></>;
case 7:return <><Area q="What is the product or retail-area condition?" prefix="retail" observations={["Dust on shelving","Product residue","Display surfaces need detailing","Merchandise limits cleaning access"]} a={a} set={set}/><p className="text-xs">Do not move or open products unless existing scope permits it.</p></>;
case 8:return <Area q="What is the reception or waiting-area condition?" prefix="reception" observations={["Reception surfaces","Seating or furniture","Floors","Glass","High-touch surfaces","Trash"]} a={a} set={set}/>;
case 9:return <Area q="What is the restroom condition?" prefix="restroom" observations={["Soap or mineral buildup","Toilet heavy detailing","Fixture buildup","Floor buildup","Odor concern","Visible mildew-like buildup"]} a={a} set={set}/>;
case 10:return <Area q="What is the breakroom or staff-area condition?" prefix="breakroom" observations={["Counters","Sink","Appliance exteriors","Food residue","Trash","Floors"]} a={a} set={set}/>;
case 11:return <><Area q="What is the laundry or towel-area condition?" prefix="laundry" observations={["Lint buildup","Hair or debris","Product residue","Machine exterior buildup","Floor buildup"]} a={a} set={set}/><p className="text-xs">Laundry service is not implied unless included upstream.</p></>;
case 12:return <><Radio q="What is the trash and waste condition?" k="wasteCondition" values={["Light","Moderate","Heavy","Excessive"]} a={a} set={set}/>{yn(["Hair-heavy waste?","Multiple receptacles?","Product containers?","Sharp or professional-tool waste present?","Restricted or special waste present?"],["hairWaste","multipleReceptacles","productContainers","sharpWaste","restrictedWaste"],a,set)}{(a.sharpWaste==="Yes"||a.restrictedWaste==="Yes")&&<Notes q="Document unusual or restricted waste." k="wasteNotes" a={a} set={set}/>}<p className="text-xs">StudioScrubz handling of sharps, biohazard, chemical, or regulated waste is not implied.</p></>;
case 13:return <Checks q="Which high-touch areas apply?" k="highTouchAreas" values={["Door handles","Chair surfaces","Reception surfaces","Waiting-area surfaces","Shampoo-area touchpoints","Restroom touchpoints","Other","None"]} a={a} toggle={toggle}/>;
case 14:return <><Radio q="Are special precautions required?" k="specialPrecautions" values={["Yes","No"]} a={a} set={set}/>{a.specialPrecautions==="Yes"&&<><Checks q="Which precautions apply?" k="precautionTypes" values={["Professional equipment/tools","Electrical equipment","Specialty chairs","Product displays","Delicate surfaces","Chemical/product storage areas","Other"]} a={a} toggle={(k,v)=>toggle(k,v,"")}/><Notes q="Describe required precautions." k="precautionNotes" a={a} set={set}/></>}</>;
case 15:return <Checks q="Which areas require extra attention?" k="extraAttention" values={["Stations","Floors","Mirrors/glass","Shampoo areas","Reception/waiting","Retail/product areas","Restrooms","Laundry/towel area","Breakroom","Trash","Other","None"]} a={a} toggle={toggle}/>;
case 16:return <><Radio q="Does the scheduled frequency appear appropriate?" k="frequencyObservation" values={["Scheduled frequency appears appropriate","More frequent service may be needed","Less frequent service may be sufficient","Management review needed"]} a={a} set={set}/>{a.frequencyObservation&&a.frequencyObservation!=="Scheduled frequency appears appropriate"&&<Notes q="Explain the frequency observation." k="frequencyNotes" a={a} set={set}/>}<p className="text-xs">Technicians cannot alter contract frequency.</p></>;
case 17:return <><Radio q="Does Barbershop/Salon Cleaning appear appropriate?" k="serviceSuitable" values={["Yes — Barbershop/Salon Cleaning appears appropriate","Additional service may be required","Management review needed"]} a={a} set={set}/>{a.serviceSuitable==="Additional service may be required"&&<Checks q="Which additional service may be required?" k="recommendedServices" values={["Deep cleaning","Floor treatment","Window/glass cleaning","Other"]} a={a} toggle={(k,v)=>toggle(k,v,"")}/>} {a.serviceSuitable&&a.serviceSuitable!=="Yes — Barbershop/Salon Cleaning appears appropriate"&&<Notes q="Explain the recommendation." k="serviceNotes" a={a} set={set}/>}<p className="text-xs">Recommendation only; technicians cannot add services or change pricing.</p></>;
case 18:return <><Radio q="What is the expected labor level?" k="laborLevel" values={["Normal","Above normal","Significantly above normal"]} a={a} set={set}/><Radio q="What crew size is recommended?" k="recommendedCrew" values={["1","2","3","4+"]} a={a} set={set}/><Radio q="What is the estimated duration?" k="serviceDuration" values={["Under 2 hours","2–4 hours","4–6 hours","6–8 hours","8+ hours"]} a={a} set={set}/></>;
case 19:return <><Radio q="Did you observe anything else that could materially affect service?" k="materialException" values={["No","Yes"]} a={a} set={set}/>{a.materialException==="Yes"&&<Notes q="Explain the exception." k="exceptionNotes" a={a} set={set}/>}</>;
default:return <label className="flex gap-3 rounded-lg border p-3 text-sm font-semibold"><input type="checkbox" checked={a.technicianConfirmation===true} onChange={e=>set("technicianConfirmation",e.target.checked)}/>I have physically reviewed the accessible service areas and completed this walkthrough based on the property&apos;s observed condition.</label>}}

function issues(i:number,a:Answers){const out:string[]=[];const need=(k:string,l:string)=>{if(a[k]==null||a[k]===""||(Array.isArray(a[k])&&!a[k].length))out.push(l)};const area=(p:string,n:number)=>{need(`${p}Condition`,"Select condition.");if(a[`${p}Condition`]!=="Not applicable")for(let x=1;x<=n;x++)need(`${p}Observation${x}`,"Complete every observation.")};switch(i){
case 0:need("facilityType","Select facility type.");if(a.facilityType==="Other")need("facilityTypeOther","Describe facility.");break;
case 1:need("operatingStatus","Select operating status.");if(a.operatingStatus!=="Closed/vacant")need("occupancyLimits","Answer occupancy limitations.");if(a.occupancyLimits==="Yes")need("occupancyNotes","Describe limitations.");break;
case 2:need("overallCondition","Select overall condition.");break;
case 3:["stationCount","stationCondition","stationHair","stationProduct","stationSurface","stationChair","stationClutter","stationTools"].forEach(k=>need(k,"Complete service stations."));break;
case 4:["floorTypes","floorCondition","floorHair","floorStationHair","floorResidue","floorStaining","floorPrecautions"].forEach(k=>need(k,"Complete floors."));if(list(a.floorTypes).includes("Other")||["floorHair","floorStationHair","floorResidue","floorStaining","floorPrecautions"].some(k=>a[k]==="Yes"))need("floorNotes","Describe floors.");break;
case 5:["stationMirrors","entryGlass","interiorGlass","glassResidue","glassSmudging","glassAccess"].forEach(k=>need(k,"Complete mirrors and glass."));if(a.glassAccess==="Yes")need("glassNotes","Describe access.");break;
case 6:area("shampoo",6);break;case 7:area("retail",4);break;case 8:area("reception",6);break;case 9:area("restroom",6);break;case 10:area("breakroom",6);break;case 11:area("laundry",5);break;
case 12:["wasteCondition","hairWaste","multipleReceptacles","productContainers","sharpWaste","restrictedWaste"].forEach(k=>need(k,"Complete waste."));if(a.sharpWaste==="Yes"||a.restrictedWaste==="Yes")need("wasteNotes","Document restricted waste.");break;
case 13:need("highTouchAreas","Select high-touch areas or None.");break;
case 14:need("specialPrecautions","Answer precautions.");if(a.specialPrecautions==="Yes"){need("precautionTypes","Select precautions.");need("precautionNotes","Describe precautions.")}break;
case 15:need("extraAttention","Select areas or None.");break;
case 16:need("frequencyObservation","Select frequency.");if(a.frequencyObservation&&a.frequencyObservation!=="Scheduled frequency appears appropriate")need("frequencyNotes","Explain frequency.");break;
case 17:need("serviceSuitable","Select suitability.");if(a.serviceSuitable==="Additional service may be required")need("recommendedServices","Select services.");if(a.serviceSuitable&&a.serviceSuitable!=="Yes — Barbershop/Salon Cleaning appears appropriate")need("serviceNotes","Explain recommendation.");break;
case 18:["laborLevel","recommendedCrew","serviceDuration"].forEach(k=>need(k,"Complete labor."));break;
case 19:need("materialException","Answer exceptions.");if(a.materialException==="Yes")need("exceptionNotes","Explain exception.");break;
case 20:if(a.technicianConfirmation!==true)out.push("Confirm the technician statement.")}return [...new Set(out)]}
function Area({q,prefix,observations,a,set}:{q:string;prefix:string;observations:string[];a:Answers;set:(k:string,v:Value)=>void}){return <><Radio q={q} k={`${prefix}Condition`} values={["Not applicable",...levels]} a={a} set={set}/>{a[`${prefix}Condition`]!=="Not applicable"&&yn(observations,observations.map((_,i)=>`${prefix}Observation${i+1}`),a,set)}</>}
function Radio({q,k,values,a,set}:{q:string;k:string;values:string[];a:Answers;set:(k:string,v:Value)=>void}){return <GuidedWalkthroughChoice label={q} options={values} selected={typeof a[k]==="string"?[a[k]]:[]} onSelect={value=>set(k,value)}/>}
function Checks({q,k,values,a,toggle}:{q:string;k:string;values:string[];a:Answers;toggle:(k:string,v:string)=>void}){return <GuidedWalkthroughChoice label={q} options={values} selected={list(a[k])} multiple onSelect={value=>toggle(k,value)}/>}
function Notes({q,k,a,set}:{q:string;k:string;a:Answers;set:(k:string,v:Value)=>void}){return <label className="block text-sm font-bold">{q}<textarea maxLength={5000} className="mt-2 block min-h-24 w-full rounded-lg border p-2 font-normal" value={typeof a[k]==="string"?a[k]:""} onChange={e=>set(k,e.target.value)}/></label>}
function yn(q:string[],k:string[],a:Answers,set:(k:string,v:Value)=>void){return q.map((x,i)=><Radio key={x} q={x} k={k[i]} values={["Yes","No"]} a={a} set={set}/>)}
function assessment(m:FieldMeasurements):BarbershopSalonFieldAssessment{return m.barbershopSalonAssessment?.fieldWalkthrough??{answers:{}}}function list(v:unknown):string[]{return Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"):[]}
const input="mt-2 block w-full rounded-lg border p-2",primary="rounded-lg bg-[#143d1a] px-4 py-2 font-bold text-white disabled:opacity-40",secondary="rounded-lg border px-4 py-2 font-bold disabled:opacity-40";
