"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CONDITION_CONCERNS, CUSTOMER_SCOPE_OPTIONS, guidedPhotoPrompts, serviceQuestionKind, type CustomerPhotoAssessmentInput } from "@/lib/customerPhotoAssessment";

type Photo={id:string;caption:string|null;originalFilename:string;url:string|null};
type PublicSubmission=Partial<CustomerPhotoAssessmentInput>&{reviewStatus:string;reviewNote:string|null};
type Assessment={serviceName:string;propertyAddress:string|null;submittedAt:string|null;propertyType:string;squareFeet:number|null;occupied:boolean|null;bedrooms:number|null;bathrooms:number|null;scope:string[];condition:CustomerPhotoAssessmentInput["condition"];selectedSpecialItems:string[];customerSubmission?:PublicSubmission|null};
const sections=["Property","Scope","Condition","Access & Items","Photos","Review & Confirm"];
const empty:CustomerPhotoAssessmentInput={propertyType:"",squareFeet:null,occupied:null,bedrooms:null,bathrooms:null,areasInScope:[],bedroomQuantity:null,bathroomQuantity:null,otherScope:"",areasExcluded:"",condition:"",lastProfessionallyCleaned:"",conditionConcerns:[],problemAreas:"",stairs:"",elevator:"",parkingAccess:"",gateAccessInstructions:"",pets:"",waterAvailable:"",powerAvailable:"",specialItems:[],serviceAnswers:{},certificationAccepted:false};

export function CustomerAssessmentPhotos({token}:{token:string}){
  const [assessment,setAssessment]=useState<Assessment|null>(null),[photos,setPhotos]=useState<Photo[]>([]),[form,setForm]=useState<CustomerPhotoAssessmentInput>(empty),[step,setStep]=useState(0),[files,setFiles]=useState<File[]>([]),[caption,setCaption]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[done,setDone]=useState(false);
  const endpoint=`/api/public/assessments/${encodeURIComponent(token)}/photos`;
  const load=useCallback(async()=>{const response=await fetch(endpoint,{cache:"no-store"}),body=await response.json() as {assessment?:Assessment;photos?:Photo[];error?:string};if(!response.ok)throw new Error(body.error||"Assessment unavailable.");const next=body.assessment??null;setAssessment(next);setPhotos(body.photos??[]);if(next)setForm(current=>({...current,...(next.customerSubmission??{}),propertyType:next.customerSubmission?.propertyType??next.propertyType,squareFeet:next.squareFeet,occupied:next.occupied,bedrooms:next.bedrooms,bathrooms:next.bathrooms,condition:next.condition,specialItems:next.customerSubmission?.specialItems??next.selectedSpecialItems,certificationAccepted:false}))},[endpoint]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load().catch(cause=>setError(msg(cause,"Assessment unavailable.")))},0);return()=>window.clearTimeout(timer)},[load]);
  const set=<K extends keyof CustomerPhotoAssessmentInput>(key:K,value:CustomerPhotoAssessmentInput[K])=>setForm(current=>({...current,[key]:value}));
  const toggle=(key:"areasInScope"|"conditionConcerns"|"specialItems",value:string)=>set(key,form[key].includes(value)?form[key].filter(item=>item!==value):[...form[key],value]);
  const prompts=useMemo(()=>guidedPhotoPrompts(assessment?.serviceName??"",form.areasInScope,form.conditionConcerns),[assessment?.serviceName,form.areasInScope,form.conditionConcerns]);
  async function upload(){if(!files.length)return;setBusy(true);setError(null);try{for(const file of files){const data=new FormData();data.set("file",file);data.set("caption",caption);const response=await fetch(endpoint,{method:"POST",body:data}),body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Photo upload failed.");}setFiles([]);setCaption("");await load()}catch(cause){setError(msg(cause,"Photo upload failed."))}finally{setBusy(false)}}
  async function submit(){setBusy(true);setError(null);try{const response=await fetch(endpoint,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Assessment submission failed.");setDone(true);await load()}catch(cause){setError(msg(cause,"Assessment submission failed."))}finally{setBusy(false)}}
  const review=assessment?.customerSubmission?.reviewStatus;
  if(done||review==="Pending Review"||review==="Approved for Pricing")return <Shell assessment={assessment}><div className="rounded-xl bg-green-50 p-5 text-green-900"><h2 className="text-lg font-extrabold">Assessment submitted</h2><p className="mt-2 text-sm leading-6">StudioScrubz will review your information and photos before pricing. A Proposal has not been created or approved by this submission.</p></div></Shell>;
  return <Shell assessment={assessment}><nav aria-label="Assessment progress" className="flex gap-2 overflow-x-auto pb-2">{sections.map((name,index)=><button key={name} type="button" onClick={()=>setStep(index)} className={`whitespace-nowrap rounded-full px-3 py-2 text-xs font-bold ${step===index?"bg-[#143d1a] text-white":"bg-[#edf1eb] text-[#143d1a]"}`}>{index+1}. {name}</button>)}</nav>{review==="More Information Requested"&&<Notice>{assessment?.customerSubmission?.reviewNote||"StudioScrubz needs additional information or photos. Update the submission and send it again."}</Notice>}{review==="On-Site Assessment Required"&&<Notice>StudioScrubz determined that an on-site Assessment is required. Your submitted information and photos remain attached.</Notice>}{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}
    {step===0&&<Section title="Property"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Property type" value={form.propertyType} setValue={value=>set("propertyType",value)} placeholder="Home, apartment, office, retail…"/><NumberField label="Approximate square footage" value={form.squareFeet} setValue={value=>set("squareFeet",value)}/><Choice label="Occupancy" value={form.occupied===null?"":form.occupied?"Occupied":"Vacant"} options={["Occupied","Vacant"]} setValue={value=>set("occupied",value==="Occupied")}/><NumberField label="Bedrooms (when applicable)" value={form.bedrooms} setValue={value=>set("bedrooms",value)}/><NumberField label="Bathrooms (when applicable)" value={form.bathrooms} setValue={value=>set("bathrooms",value)}/></div></Section>}
    {step===1&&<Section title="Rooms / Areas in Scope"><CheckboxGrid options={CUSTOMER_SCOPE_OPTIONS} selected={form.areasInScope} toggle={value=>toggle("areasInScope",value)}/><div className="grid gap-4 sm:grid-cols-2">{form.areasInScope.includes("Bedrooms")&&<NumberField label="Bedrooms in scope" value={form.bedroomQuantity} setValue={value=>set("bedroomQuantity",value)}/>} {form.areasInScope.includes("Bathrooms")&&<NumberField label="Bathrooms in scope" value={form.bathroomQuantity} setValue={value=>set("bathroomQuantity",value)}/>} {form.areasInScope.includes("Other")&&<TextField label="Other area" value={form.otherScope} setValue={value=>set("otherScope",value)}/>}</div><Area label="Areas excluded from scope" value={form.areasExcluded} setValue={value=>set("areasExcluded",value)}/></Section>}
    {step===2&&<Section title="Current Condition"><Choice label="Overall condition" value={form.condition} options={["Light","Average","Heavy","Extreme"]} setValue={value=>set("condition",value as CustomerPhotoAssessmentInput["condition"])}/><TextField label="When was the property last professionally cleaned?" value={form.lastProfessionallyCleaned} setValue={value=>set("lastProfessionallyCleaned",value)}/><p className="text-sm font-bold">Select any current concerns</p><CheckboxGrid options={CONDITION_CONCERNS} selected={form.conditionConcerns} toggle={value=>toggle("conditionConcerns",value)}/><Area label="Stains, problem areas, or unusually dirty areas" value={form.problemAreas} setValue={value=>set("problemAreas",value)}/><ServiceQuestions service={assessment?.serviceName??""} answers={form.serviceAnswers} setAnswers={value=>set("serviceAnswers",value)}/></Section>}
    {step===3&&<Section title="Access, Logistics & Special Items"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Stairs" value={form.stairs} setValue={value=>set("stairs",value)}/><TextField label="Elevator" value={form.elevator} setValue={value=>set("elevator",value)}/><TextField label="Parking / access limitations" value={form.parkingAccess} setValue={value=>set("parkingAccess",value)}/><TextField label="Gate / access instructions" value={form.gateAccessInstructions} setValue={value=>set("gateAccessInstructions",value)}/><TextField label="Pets" value={form.pets} setValue={value=>set("pets",value)}/><Choice label="Water available" value={form.waterAvailable} options={["Yes","No","Unsure"]} setValue={value=>set("waterAvailable",value)}/><Choice label="Power available" value={form.powerAvailable} options={["Yes","No","Unsure"]} setValue={value=>set("powerAvailable",value)}/></div>{(assessment?.selectedSpecialItems.length??0)>0&&<><p className="text-sm font-bold">Requested catalog add-ons</p><CheckboxGrid options={assessment!.selectedSpecialItems} selected={form.specialItems} toggle={value=>toggle("specialItems",value)}/></>}</Section>}
    {step===4&&<Section title="Guided Photos"><p className="text-sm text-neutral-600">Provide clear representative photos; a photo of every surface is not required.</p><ul className="list-disc space-y-1 pl-5 text-sm">{prompts.map(prompt=><li key={prompt}>{prompt}</li>)}</ul><Field label="Choose photos"><input type="file" multiple accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={event=>setFiles(Array.from(event.target.files??[]))} className={input}/></Field><TextField label="Area / note for this batch (optional)" value={caption} setValue={setCaption}/><button type="button" disabled={busy||!files.length} onClick={()=>void upload()} className={primary}>{busy?"Uploading…":`Upload ${files.length||""} Photo${files.length===1?"":"s"}`}</button><div className="grid gap-3 sm:grid-cols-2">{photos.map(photo=><article key={photo.id} className="overflow-hidden rounded-lg border">{photo.url&&<img src={photo.url} alt={photo.caption||photo.originalFilename} className="aspect-[4/3] w-full object-cover"/>}<p className="p-3 text-sm">{photo.caption||photo.originalFilename}</p></article>)}{!photos.length&&<p className="text-sm text-neutral-500">No photos uploaded yet.</p>}</div></Section>}
    {step===5&&<Section title="Review & Confirm"><Summary form={form} photoCount={photos.length}/><label className="flex gap-3 rounded-xl border border-[#143d1a]/15 bg-[#f5f8f4] p-4 text-sm leading-6"><input type="checkbox" checked={form.certificationAccepted} onChange={e=>set("certificationAccepted",e.target.checked)} className="mt-1 size-4"/><span><strong>I confirm that the information and photos I provided reasonably represent the property&apos;s current condition and requested scope.</strong><br/>Pricing is based on the information and photos provided. If the actual property condition, size, access, or scope differs materially from the submitted information, StudioScrubz may adjust the scope and pricing before additional work is performed.</span></label><button type="button" disabled={busy||!form.certificationAccepted||photos.length===0} onClick={()=>void submit()} className={`${primary} w-full`}>{busy?"Submitting…":"Submit Photo Assessment for Review"}</button></Section>}
    <div className="flex justify-between"><button type="button" disabled={step===0} onClick={()=>setStep(value=>Math.max(0,value-1))} className={secondary}>Back</button>{step<sections.length-1&&<button type="button" onClick={()=>setStep(value=>Math.min(sections.length-1,value+1))} className={primary}>Continue</button>}</div>
  </Shell>;
}

function Shell({assessment,children}:{assessment:Assessment|null;children:React.ReactNode}){return <main className="min-h-screen bg-[#f4f6f2] px-3 py-6 text-neutral-800 sm:px-4 sm:py-10"><section className="mx-auto max-w-3xl overflow-hidden rounded-2xl border border-[#143d1a]/10 bg-white shadow-xl"><header className="bg-[#143d1a] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d4af37]">Customer Photo Assessment</p><h1 className="mt-2 text-2xl font-extrabold">Tell us about the property</h1><p className="mt-2 text-sm text-white/75">{assessment?.serviceName??"Cleaning Service"}{assessment?.propertyAddress?` · ${assessment.propertyAddress}`:""}</p></header><div className="space-y-6 p-4 sm:p-6">{children}</div></section></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-4"><h2 className="text-xl font-extrabold text-[#143d1a]">{title}</h2>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-bold text-[#143d1a]">{label}<div className="mt-2">{children}</div></label>}
function TextField({label,value,setValue,placeholder}:{label:string;value:string;setValue:(value:string)=>void;placeholder?:string}){return <Field label={label}><input value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder} className={input}/></Field>}
function Area({label,value,setValue}:{label:string;value:string;setValue:(value:string)=>void}){return <Field label={label}><textarea value={value} onChange={e=>setValue(e.target.value)} className={input} rows={3}/></Field>}
function NumberField({label,value,setValue}:{label:string;value:number|null;setValue:(value:number|null)=>void}){return <Field label={label}><input type="number" min="0" value={value??""} onChange={e=>setValue(e.target.value?Number(e.target.value):null)} className={input}/></Field>}
function Choice({label,value,options,setValue}:{label:string;value:string;options:readonly string[];setValue:(value:string)=>void}){return <Field label={label}><select value={value} onChange={e=>setValue(e.target.value)} className={input}><option value="">Select…</option>{options.map(option=><option key={option}>{option}</option>)}</select></Field>}
function CheckboxGrid({options,selected,toggle}:{options:readonly string[];selected:string[];toggle:(value:string)=>void}){return <div className="grid gap-2 sm:grid-cols-2">{options.map(option=><label key={option} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={selected.includes(option)} onChange={()=>toggle(option)}/>{option}</label>)}</div>}
function ServiceQuestions({service,answers,setAnswers}:{service:string;answers:Record<string,string|boolean>;setAnswers:(value:Record<string,string|boolean>)=>void}){const kind=serviceQuestionKind(service);const fields=kind==="post-construction"?[["projectType","New construction or remodel?"],["workPerformed","What work was performed?"],["constructionFinished","Is construction completely finished?"],["remainingDebris","Is there remaining debris?"],["residue","Paint, adhesive, or sticker residue?"],["cabinetCleaning","Cabinet / interior storage cleaning needed?"],["newAppliances","Newly installed appliances?"],["constructionGlass","Windows / glass needing construction cleanup?"]]:kind==="move"?[["moveDirection","Move-in or move-out?"],["completelyVacant","Completely vacant?"],["cabinetsEmpty","Cabinets and drawers empty?"],["appliancesRemaining","Appliances remaining?"],["belongingsRemaining","Personal belongings remaining?"]]:kind==="pressure"?[["surfaceTypes","Which exterior surfaces need cleaning?"],["waterAccessDetail","Where is the nearest water access?"],["drainageConcerns","Any drainage or access concerns?"]]:[];if(!fields.length)return null;return <div className="rounded-xl bg-[#f5f8f4] p-4"><h3 className="font-extrabold text-[#143d1a]">Questions for {service}</h3><div className="mt-3 grid gap-4 sm:grid-cols-2">{fields.map(([key,label])=><TextField key={key} label={label} value={String(answers[key]??"")} setValue={value=>setAnswers({...answers,[key]:value})}/>)}</div></div>}
function Summary({form,photoCount}:{form:CustomerPhotoAssessmentInput;photoCount:number}){return <dl className="grid gap-3 rounded-xl bg-[#f5f8f4] p-4 text-sm sm:grid-cols-2"><div><dt className="font-bold">Property</dt><dd>{form.propertyType||"Not provided"} · {form.squareFeet??"—"} sq ft</dd></div><div><dt className="font-bold">Occupancy</dt><dd>{form.occupied===null?"Not provided":form.occupied?"Occupied":"Vacant"}</dd></div><div><dt className="font-bold">Scope</dt><dd>{form.areasInScope.join(", ")||"Not provided"}</dd></div><div><dt className="font-bold">Condition</dt><dd>{form.condition||"Not provided"}</dd></div><div><dt className="font-bold">Photos</dt><dd>{photoCount} uploaded</dd></div><div><dt className="font-bold">Special items</dt><dd>{form.specialItems.join(", ")||"None selected"}</dd></div></dl>}
function Notice({children}:{children:React.ReactNode}){return <p className="rounded-lg bg-amber-50 p-3 text-sm font-bold text-amber-800">{children}</p>}
function msg(cause:unknown,fallback:string){return cause instanceof Error?cause.message:fallback}
const input="w-full rounded-lg border border-neutral-300 bg-white px-3 py-2.5 text-sm font-normal text-neutral-800";
const primary="rounded-lg bg-[#d4af37] px-5 py-3 font-extrabold text-[#143d1a] disabled:opacity-50";
const secondary="rounded-lg border border-neutral-300 bg-white px-5 py-3 font-bold text-neutral-700 disabled:opacity-50";
