"use client";

import { useCallback, useEffect, useState } from "react";

type Photo={id:string;caption:string|null;originalFilename:string;url:string|null};
type Assessment={serviceName:string;propertyAddress:string|null;submittedAt:string|null};

export function CustomerAssessmentPhotos({token}:{token:string}){
  const [assessment,setAssessment]=useState<Assessment|null>(null),[photos,setPhotos]=useState<Photo[]>([]),[files,setFiles]=useState<File[]>([]),[caption,setCaption]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[done,setDone]=useState(false);
  const load=useCallback(async()=>{const response=await fetch(`/api/public/assessments/${encodeURIComponent(token)}/photos`,{cache:"no-store"}),body=await response.json() as {assessment?:Assessment;photos?:Photo[];error?:string};if(!response.ok)throw new Error(body.error||"Assessment unavailable.");setAssessment(body.assessment??null);setPhotos(body.photos??[])},[token]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load().catch(cause=>setError(cause instanceof Error?cause.message:"Assessment unavailable."))},0);return()=>window.clearTimeout(timer)},[load]);
  async function upload(){if(!files.length)return;setBusy(true);setError(null);try{for(const file of files){const form=new FormData();form.set("file",file);form.set("caption",caption);const response=await fetch(`/api/public/assessments/${encodeURIComponent(token)}/photos`,{method:"POST",body:form}),body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Photo upload failed.");}setFiles([]);setCaption("");setDone(true);await load()}catch(cause){setError(cause instanceof Error?cause.message:"Photo upload failed.")}finally{setBusy(false)}}
  return <main className="min-h-screen bg-[#f4f6f2] px-4 py-10 text-neutral-800"><section className="mx-auto max-w-3xl overflow-hidden rounded-2xl border border-[#143d1a]/10 bg-white shadow-xl"><header className="bg-[#143d1a] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d4af37]">Property Assessment</p><h1 className="mt-2 text-2xl font-extrabold">Upload Service-Area Photos</h1><p className="mt-2 text-sm text-white/75">{assessment?.serviceName??"Cleaning Service"}{assessment?.propertyAddress?` · ${assessment.propertyAddress}`:""}</p></header><div className="space-y-6 p-6"><p className="text-sm leading-6 text-neutral-600">Upload clear photos of the rooms and areas that need service. You may select several photos and add an optional area note.</p>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}{done&&<p role="status" className="rounded-lg bg-green-50 p-3 text-sm font-bold text-green-800">Photos submitted successfully. You can add more if needed.</p>}<label className="block text-sm font-bold text-[#143d1a]">Photos<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={event=>setFiles(Array.from(event.target.files??[]))} className="mt-2 block w-full rounded-lg border p-3 text-sm"/></label><label className="block text-sm font-bold text-[#143d1a]">Area / note (optional)<input value={caption} maxLength={1000} onChange={event=>setCaption(event.target.value)} placeholder="Example: Main bathroom shower" className="mt-2 w-full rounded-lg border px-3 py-2.5 text-sm"/></label><button type="button" disabled={busy||!files.length} onClick={()=>void upload()} className="w-full rounded-lg bg-[#d4af37] px-5 py-3 font-extrabold text-[#143d1a] disabled:opacity-50">{busy?"Uploading…":`Submit ${files.length||""} Photo${files.length===1?"":"s"}`}</button><section><h2 className="font-extrabold text-[#143d1a]">Submitted Photos</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{photos.map(photo=><article key={photo.id} className="overflow-hidden rounded-lg border">{photo.url&&<img src={photo.url} alt={photo.caption||photo.originalFilename} className="aspect-[4/3] w-full object-cover"/>}<p className="p-3 text-sm">{photo.caption||photo.originalFilename}</p></article>)}{photos.length===0&&<p className="text-sm text-neutral-500">No photos submitted yet.</p>}</div></section></div></section></main>;
}
