"use client";
import { useEffect, useRef, useState } from "react";
import { getAssignedFieldWalkthroughs, saveAssignedFieldWalkthrough } from "@/lib/services/fieldWalkthroughs";
import { createPhotoSignedUrls, getOperationalPhotos, uploadOperationalPhoto } from "@/lib/services/photoStorage";
import { fieldTextKeys, fieldNumberKeys, type FieldWalkthrough } from "@/types/fieldWalkthrough";
import type { OperationalPhotoWithUrl } from "@/types/photo";

export function FieldWalkthroughsPage() {
  const [rows,setRows]=useState<FieldWalkthrough[]>([]);
  const [active,setActive]=useState<FieldWalkthrough|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [notice,setNotice]=useState("");
  async function refresh() { setRows(await getAssignedFieldWalkthroughs()); }
  useEffect(()=>{let live=true; getAssignedFieldWalkthroughs().then(data=>{if(live)setRows(data);}).catch(()=>{if(live)setError("Assigned walkthroughs could not be loaded.");}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
  async function open(id:string) { try { const fresh=await getAssignedFieldWalkthroughs(); setRows(fresh); const row=fresh.find(item=>item.id===id); if(row)setActive(row); else setError("This walkthrough is no longer assigned and scheduled for you."); } catch { setError("Could not verify the current assignment. Please reload."); } }
  return <><h1 className="text-3xl font-extrabold text-[#143d1a]">Assigned Walkthroughs</h1><p className="mt-3 text-neutral-600">Scheduled field assessments assigned to you.</p>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}{notice&&<p role="status" className="mt-4 text-[#143d1a]">{notice}</p>}{loading?<p className="mt-6">Loading...</p>:<div className="mt-6 grid gap-4 lg:grid-cols-2">{rows.map(row=><article key={row.id} className="rounded-xl border bg-white p-5"><h2 className="font-bold text-[#143d1a]">{row.company_name||row.contact_name||"Scheduled visit"}</h2><p>{row.property}</p><p className="mt-2">{row.walkthrough_date} at {row.walkthrough_time.slice(0,5)}</p><p>{row.service}</p><button className={button} onClick={()=>void open(row.id)}>Open Field Assessment</button></article>)}{!rows.length&&<p>No scheduled walkthroughs are assigned to you.</p>}</div>}{active&&<FieldForm key={active.id} row={active} close={()=>setActive(null)} saved={async complete=>{setActive(null);setNotice(complete?"Walkthrough submitted and completed.":"Field observations saved.");try{await refresh();}catch{setError("Saved, but the list could not refresh. Reload the page.");}}}/>}</>;
}
function FieldForm({row,close,saved}:{row:FieldWalkthrough;close:()=>void;saved:(complete:boolean)=>Promise<void>}) {
  const [measurements,setMeasurements]=useState({...row.measurements,heavySoilBuildup:row.measurements.heavySoilBuildup??false});
  const [photos,setPhotos]=useState<OperationalPhotoWithUrl[]>([]);
  const operationInFlight=useRef(false);
  const pendingPhoto=useRef<File|null>(null);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  useEffect(()=>{let live=true; getOperationalPhotos("walkthroughs",row.id).then(createPhotoSignedUrls).then(items=>{if(live)setPhotos(items);}).catch(()=>{if(live)setError("Photos could not be loaded. Confirm your assignment is still scheduled.");});return()=>{live=false;};},[row.id]);
  async function submit(complete:boolean) { if(operationInFlight.current)return; if(pendingPhoto.current){setError("Retry the pending photo upload before saving or completing this walkthrough.");return;} if(complete&&!window.confirm("Submit this walkthrough as completed? It will leave your assigned list."))return;operationInFlight.current=true;setBusy(true);setError("");try{if(fieldNumberKeys.some(key=>measurements[key]!=null&&(!Number.isFinite(measurements[key])||Number(measurements[key])<0)))throw new Error("Invalid measurement");await saveAssignedFieldWalkthrough(row.id,measurements,complete);await saved(complete);}catch{setError("Could not save. Your assignment may have changed; reload before retrying.");}finally{operationInFlight.current=false;setBusy(false);} }
  async function upload(file:File) {if(operationInFlight.current)return;operationInFlight.current=true;pendingPhoto.current=file;setBusy(true);setError("");try{const items=await uploadOperationalPhoto({recordType:"walkthroughs",recordId:row.id,category:"General",caption:null,source:"camera",customerVisible:false,file});pendingPhoto.current=null;setPhotos(await createPhotoSignedUrls(items));}catch{setError("Photo upload failed. Confirm your assignment and try again.");}finally{operationInFlight.current=false;setBusy(false);}}
  return <div className="fixed inset-0 z-[75] overflow-y-auto bg-black/60 p-4"><section role="dialog" aria-modal="true" aria-label="Field walkthrough" className="mx-auto max-w-4xl rounded-2xl bg-white p-6"><h2 className="text-2xl font-bold text-[#143d1a]">Field Walkthrough</h2><p className="mt-3">{row.company_name} {row.contact_name}</p><p>{row.property}</p><p>{row.walkthrough_date} at {row.walkthrough_time.slice(0,5)}</p><p>{row.phone} {row.email}</p><p className="mt-3 font-bold">{row.service}</p><h3 className="mt-5 font-bold">Assessment Scope</h3><ul className="list-disc pl-5">{row.scope.map(item=><li key={item.id}>{item.label}</li>)}</ul><fieldset disabled={busy} className="mt-6"><legend className="font-bold">Measurements and Observations</legend><div className="mt-3 grid gap-4 sm:grid-cols-2">{fieldNumberKeys.map(key=><label key={key}>{label(key)}<input type="number" min="0" step="any" className={input} value={measurements[key]??""} onChange={e=>setMeasurements({...measurements,[key]:e.target.value===""?null:Number(e.target.value)})}/></label>)}{fieldTextKeys.map(key=><label key={key}>{label(key)}{key==="overallCondition"?<select className={input} value={measurements[key]??""} onChange={e=>setMeasurements({...measurements,[key]:e.target.value})}>{["","Light","Average","Heavy","Extreme"].map(value=><option key={value} value={value}>{value||"Select condition"}</option>)}</select>:<textarea maxLength={5000} className={input} value={measurements[key]??""} onChange={e=>setMeasurements({...measurements,[key]:e.target.value})}/>}</label>)}</div><label className="mt-4 flex gap-3"><input type="checkbox" checked={measurements.heavySoilBuildup??false} onChange={e=>setMeasurements({...measurements,heavySoilBuildup:e.target.checked})}/>Heavy soil buildup</label><h3 className="mt-6 font-bold">Photos</h3><label className="mt-3 block">Add walkthrough photo<input type="file" accept="image/*" className="mt-2 block" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value="";}}/></label><div className="mt-4 grid grid-cols-2 gap-3">{photos.map(photo=><figure key={photo.id}>{photo.signedUrl&&<img src={photo.signedUrl} alt={photo.caption||photo.category} className="max-h-64 w-full rounded-lg object-contain"/>}<figcaption className="text-sm">{photo.caption||photo.category}</figcaption></figure>)}</div></fieldset>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}{pendingPhoto.current&&!busy&&<button className={button} onClick={()=>{if(pendingPhoto.current)void upload(pendingPhoto.current);}}>Retry Photo Upload</button>}<div className="mt-6 flex flex-wrap gap-3"><button disabled={busy} className={button} onClick={()=>void submit(false)}>Save Observations</button><button disabled={busy} className={button} onClick={()=>void submit(true)}>Submit / Complete</button><button disabled={busy} className="rounded-lg border px-4 py-2" onClick={close}>Close</button></div></section></div>;
}
function label(key:string){return key.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase());}
const button="mt-3 rounded-lg bg-[#143d1a] px-4 py-2 font-bold text-white disabled:opacity-50";
const input="mt-1 block w-full rounded-lg border border-neutral-300 p-2";
