"use client";
import { useState } from "react";
import type { FieldMeasurements, PostConstructionFieldAssessment } from "@/types/fieldWalkthrough";
import type { OperationalPhotoWithUrl, WalkthroughPhotoCategory } from "@/types/photo";

type A=Record<string,unknown>; type S={title:string;question:string;key:string;missing:(a:A)=>string[]};
const has=(v:unknown)=>typeof v==="string"?!!v.trim():Array.isArray(v)?v.length>0:typeof v==="number"&&Number.isFinite(v)&&v>=0;
const req=(a:A,pairs:string[][])=>pairs.flatMap(([k,m])=>has(a[k])?[]:[m]);
export const POST_CONSTRUCTION_FIELD_SECTIONS:S[]=[
 {title:"Project Overview & Boundaries",key:"includedAreas",question:"What type of construction project is this, which areas are affected, and which areas are specifically excluded from cleaning?",missing:a=>[...req(a,[["constructionTypes","Select at least one construction type."],["affectedAreas","Select at least one affected area."],["excludedAreas","Enter excluded areas or “None”."]]),...(arr(a.constructionTypes).includes("Other")&&!has(a.constructionOther)?["Explain the other construction type."]:[])]},
 {title:"Construction Readiness",key:"siteReady",question:"What stage is construction in, and when will StudioScrubz have exclusive access to begin cleaning?",missing:a=>[...req(a,[["stage","Select the construction stage."],["exclusiveAccessAt","Enter the exclusive-access date and time."]]),...(a.stage==="Other"&&!has(a.stageOther)?["Explain the other construction stage."]:[])]},
 {title:"Property Measurements",key:"measurementsVerified",question:"What are the property measurements, quantities, and rooms or areas included in the cleaning scope?",missing:a=>req(a,[["squareFeet","Enter square feet."],["floors","Enter floors."],["bedrooms","Enter bedrooms."],["bathrooms","Enter bathrooms."],["kitchens","Enter kitchens."],["staircases","Enter staircases."],["garages","Enter garages."],["balconies","Enter balconies."],["roomsAreas","Select rooms or areas."]])},
 {title:"Cleaning Standard",key:"cleaningStandard",question:"Which cleaning level is required, and which horizontal and vertical surfaces must be cleaned?",missing:a=>req(a,[["cleaningLevel","Select the cleaning level."],["surfaces","Select required surfaces."]])},
 {title:"Windows & Glass",key:"windowsGlass",question:"Are windows or glass included, how many are included, what components or residue require cleaning, and is ladder or special access needed?",missing:a=>[...req(a,[["windowScope","Select the window scope."]]),...(a.windowScope!=="Not included"?req(a,[["windowQuantity","Enter the window quantity."],["windowDetails","Select components or residue."],["specialAccess","Answer the special-access question."]]):[]),...(a.specialAccess==="Yes"&&!has(a.specialAccessDetails)?["Explain the special-access requirement."]:[])]},
 {title:"Floors & Construction Residue",key:"floorsResidue",question:"Which floor materials are present, and is there paint, grout haze, adhesive, drywall compound, or no construction residue?",missing:a=>[...req(a,[["floorTypes","Select floor materials."],["residues","Select the residue condition."]]),...(arr(a.floorTypes).includes("Other")&&!has(a.floorOther)?["Explain the other floor material."]:[]),...(arr(a.residues).length>0&&!arr(a.residues).includes("None")&&a.residuePhotoConfirmed!==true?["Add and confirm a residue photo."]:[])]},
 {title:"Cabinets, Drawers & Closets",key:"cabinetScope",question:"Which cabinet, drawer, closet, shelving, or exterior-only storage surfaces are included?",missing:a=>req(a,[["storageScope","Select included storage surfaces."]])},
 {title:"Appliances",key:"applianceScope",question:"Are appliances excluded, exterior-only, or interior and exterior; which appliance types are included; and is protective film or sticker removal required?",missing:a=>[...req(a,[["applianceScope","Select the appliance scope."],["protectiveFilm","Answer the film and sticker question."]]),...(a.applianceScope!=="Not included"?req(a,[["applianceTypes","Select appliance types."]]):[])]},
 {title:"Debris & Exclusions",key:"debrisExclusions",question:"Is the site limited to cleaning waste, does it contain light debris, or does construction debris remain, and who is responsible for removing it?",missing:a=>req(a,[["debrisLevel","Select the debris condition."],["debrisResponsibleParty","Identify the responsible party."]])},
 {title:"Specialty Surfaces",key:"specialtySurfaces",question:"Which specialty or high-value surfaces and fixtures require special cleaning care?",missing:a=>[...req(a,[["specialtySurfaces","Select a specialty-surface answer."]]),...(arr(a.specialtySurfaces).includes("Other")&&!has(a.specialtyOther)?["Explain the other specialty surface."]:[])]},
 {title:"Access, Utilities & Equipment Staging",key:"accessUtilities",question:"For parking, stairs or elevator, gate or security, loading, equipment staging, water, electricity, and restroom access, is each available, unavailable, or restricted?",missing:a=>req(a,[["parking","Answer parking."],["stairsElevator","Answer stairs or elevator."],["gateSecurity","Answer gate or security."],["loading","Answer loading."],["staging","Answer staging."],["water","Answer water."],["electricity","Answer electricity."],["restroom","Answer restroom."]])},
 {title:"Schedule & Deadline",key:"scheduleDeadline",question:"When may cleaning start, when must it be completed, and who or what arrives immediately afterward?",missing:a=>req(a,[["cleaningStart","Enter the cleaning start."],["requiredCompletion","Enter required completion."],["arrivesAfterward","Identify who arrives afterward."]])},
 {title:"Active Trades & Re-cleaning Responsibility",key:"activeTrades",question:"Will other trades be absent, working during cleaning, or returning afterward, and who is responsible for any required re-cleaning?",missing:a=>req(a,[["tradeStatus","Select the trade status."],["recleanResponsibleParty","Identify re-clean responsibility."]])},
 {title:"Crew & Site Restrictions",key:"crewRestrictions",question:"Which HOA, building-hour, quiet-hour, security, crew-size, or other site restrictions apply?",missing:a=>[...req(a,[["restrictions","Select the restriction answer."]]),...(arr(a.restrictions).includes("Other")&&!has(a.restrictionOther)?["Explain the other restriction."]:[])]},
 {title:"Completion & Sign-Off",key:"finalSignOff",question:"Who will approve completion, what is their role, and will acceptance use a visual walkthrough, written punch list, photo approval, or another standard?",missing:a=>[...req(a,[["approverName","Enter the approver name."],["approverRole","Enter the approver role."],["acceptanceStandard","Select the acceptance standard."]]),...(a.acceptanceStandard==="Other"&&!has(a.acceptanceOther)?["Explain the other acceptance standard."]:[])]},
];
const arr=(v:unknown)=>Array.isArray(v)?v as string[]:[];
const parse=(v:unknown):A=>{if(typeof v!=="string")return{};try{const x=JSON.parse(v);return x&&typeof x==="object"&&!Array.isArray(x)?x:{}}catch{return{}}};
const fieldOf=(m:FieldMeasurements):PostConstructionFieldAssessment=>m.postConstructionAssessment?.fieldWalkthrough??{answers:{},sectionConfirmations:{}};
export function postConstructionCompletionIssues(m:FieldMeasurements){const f=fieldOf(m);return POST_CONSTRUCTION_FIELD_SECTIONS.flatMap(s=>s.missing(parse(f.answers?.[s.key])).length?[s.title]:[])}

export function PostConstructionFieldWalkthrough({measurements,onChange,photos,onPhoto}:{measurements:FieldMeasurements;onChange:(n:FieldMeasurements)=>void;photos:OperationalPhotoWithUrl[];onPhoto:(f:File,c:WalkthroughPhotoCategory,x:string)=>void}){
 const [current,setCurrent]=useState(0), section=POST_CONSTRUCTION_FIELD_SECTIONS[current], field=fieldOf(measurements), answer=parse(field.answers?.[section.key]), missing=section.missing(answer), issues=postConstructionCompletionIssues(measurements);
 const setAnswer=(patch:A)=>{const next={...answer,...patch}, assessment=measurements.postConstructionAssessment??{};onChange({...measurements,postConstructionAssessment:{...assessment,fieldWalkthrough:{...field,answers:{...field.answers,[section.key]:JSON.stringify(next)},sectionConfirmations:{...field.sectionConfirmations,[String(current+1)]:section.missing(next).length?"":"Yes"}}}})};
 return <div className="mt-6"><div className="sticky top-0 z-10 bg-white py-3"><p className="font-bold">Section {current+1} of 15 · {15-issues.length} complete</p><progress className="w-full" max={15} value={15-issues.length}/></div><section className="rounded-xl border p-4" data-walkthrough-section={current+1}><h3 className="text-lg font-bold text-[#143d1a]">{current+1}. {section.title}</h3><p className="mt-2 font-medium">{section.question}</p><Fields index={current} a={answer} setA={setAnswer} photos={photos} onPhoto={onPhoto}/>{missing.length>0&&<div role="alert" className="mt-4 rounded-lg bg-amber-50 p-3 text-amber-900"><b>Before continuing:</b><ul className="list-disc pl-5">{missing.map(x=><li key={x}>{x}</li>)}</ul></div>}</section><div className="mt-4 flex justify-between"><button type="button" className={secondary} disabled={!current} onClick={()=>setCurrent(x=>x-1)}>Previous</button><button type="button" className={primary} disabled={!!missing.length||current===14} onClick={()=>setCurrent(x=>x+1)}>{current===14?"All sections reviewed":"Continue"}</button></div><p className="mt-3 text-sm text-neutral-600">Save Draft remains available below. Final completion is blocked until all 15 sections are complete.</p></div>;
}

function Fields({index,a,setA,photos,onPhoto}:{index:number;a:A;setA:(p:A)=>void;photos:OperationalPhotoWithUrl[];onPhoto:(f:File,c:WalkthroughPhotoCategory,x:string)=>void}){
 const m=(label:string,key:string,opts:string[])=><Multi label={label} options={opts} value={arr(a[key])} onChange={v=>setA({[key]:v})}/>;
 if(index===0)return <>{m("Construction type","constructionTypes",["Full build","Remodel","Addition","Kitchen","Bathroom","Flooring","Painting","Other"])}{m("Affected areas","affectedAreas",["Whole property","Kitchen","Bathrooms","Bedrooms","Living areas","Hallways","Stairs","Garage","Balconies","Exterior"])}{arr(a.constructionTypes).includes("Other")&&<Text label="Other — explain" value={a.constructionOther} change={v=>setA({constructionOther:v})}/>}<Text label="Excluded areas (enter None if none)" value={a.excludedAreas} change={v=>setA({excludedAreas:v})}/></>;
 if(index===1)return <><Choice label="Construction stage" options={["Completely finished","Punch list remaining","Contractors active","Other"]} value={a.stage} change={v=>setA({stage:v})}/>{a.stage==="Other"&&<Text label="Other — explain" value={a.stageOther} change={v=>setA({stageOther:v})}/>}<DT label="Exclusive-access date and time" value={a.exclusiveAccessAt} change={v=>setA({exclusiveAccessAt:v})}/></>;
 if(index===2)return <><div className="grid gap-3 sm:grid-cols-2">{[["Square feet","squareFeet"],["Floors","floors"],["Bedrooms","bedrooms"],["Bathrooms","bathrooms"],["Kitchens","kitchens"],["Staircases","staircases"],["Garages","garages"],["Balconies","balconies"]].map(([l,k])=><Num key={k} label={l} value={a[k]} change={v=>setA({[k]:v})}/>)}</div>{m("Rooms and areas in scope","roomsAreas",["Kitchen","Bathrooms","Bedrooms","Living room","Dining room","Offices","Hallways","Stairs","Laundry","Garage","Balconies","Common areas"])}</>;
 if(index===3)return <><Choice label="Cleaning level" options={["Rough","Final","Final-detail turnover"]} value={a.cleaningLevel} change={v=>setA({cleaningLevel:v})}/>{m("Required surfaces","surfaces",["Horizontal surfaces","Vertical surfaces","Walls","Ceilings","Trim and baseboards","Doors and frames","Fixtures","Interior glass"])}</>;
 if(index===4)return <><Choice label="Windows and glass" options={["Not included","Interior","Exterior","Both"]} value={a.windowScope} change={v=>setA({windowScope:v})}/>{a.windowScope!=="Not included"&&<><Num label="Window quantity" value={a.windowQuantity} change={v=>setA({windowQuantity:v})}/>{m("Components and residue","windowDetails",["Tracks","Frames","Screens","Stickers","Adhesive","Paint"])}<Choice label="Ladder or special access needed?" options={["Yes","No"]} value={a.specialAccess} change={v=>setA({specialAccess:v})}/>{a.specialAccess==="Yes"&&<Text label="Describe special access" value={a.specialAccessDetails} change={v=>setA({specialAccessDetails:v})}/>}<Photo label="Add windows photo" category="Interior" caption="Windows" onPhoto={onPhoto}/></>}</>;
 if(index===5){const r=arr(a.residues),needPhoto=r.length>0&&!r.includes("None"),hasPhoto=photos.some(p=>p.caption==="Construction residue");return <>{m("Floor materials","floorTypes",["Hardwood","Tile","Stone","Vinyl","Carpet","Other"])}{arr(a.floorTypes).includes("Other")&&<Text label="Other — explain" value={a.floorOther} change={v=>setA({floorOther:v})}/>}<Multi label="Construction residue" options={["Paint","Grout haze","Adhesive","Drywall compound","None"]} value={r} onChange={v=>setA({residues:v,residuePhotoConfirmed:v.includes("None")?false:a.residuePhotoConfirmed})}/>{needPhoto&&<><Photo label="Required residue photo" category="Damage / Concern" caption="Construction residue" onPhoto={onPhoto}/><label className="mt-3 flex gap-2"><input type="checkbox" disabled={!hasPhoto} checked={a.residuePhotoConfirmed===true} onChange={e=>setA({residuePhotoConfirmed:e.target.checked})}/>Confirm residue photo added</label></>}</>}
 if(index===6)return m("Included storage surfaces","storageScope",["Cabinet interiors","Drawers","Closets","Shelving","Exteriors only","Not included"]);
 if(index===7)return <><Choice label="Appliance cleaning scope" options={["Not included","Exterior","Interior and exterior"]} value={a.applianceScope} change={v=>setA({applianceScope:v})}/>{a.applianceScope!=="Not included"&&m("Appliance types","applianceTypes",["Refrigerator","Range / oven","Cooktop","Microwave","Dishwasher","Washer","Dryer","Other"])}<Choice label="Protective film or stickers present?" options={["Yes","No"]} value={a.protectiveFilm} change={v=>setA({protectiveFilm:v})}/></>;
 if(index===8)return <><Choice label="Debris condition" options={["Cleaning waste only","Light debris","Construction debris remains"]} value={a.debrisLevel} change={v=>setA({debrisLevel:v})}/><Text label="Party responsible for debris removal" value={a.debrisResponsibleParty} change={v=>setA({debrisResponsibleParty:v})}/></>;
 if(index===9)return <>{m("Specialty surfaces","specialtySurfaces",["None","Natural stone","Marble","Quartz","Custom wood","Stainless steel","Specialty flooring","Expensive fixtures","Custom cabinetry","Glass railings","Other"])}{arr(a.specialtySurfaces).includes("Other")&&<Text label="Other — explain" value={a.specialtyOther} change={v=>setA({specialtyOther:v})}/>}<Photo label="Add specialty-surface photo" category="Other" caption="Specialty surfaces" onPhoto={onPhoto}/></>;
 if(index===10)return <div className="grid gap-3 sm:grid-cols-2">{[["Parking","parking"],["Stairs or elevator","stairsElevator"],["Gate or security","gateSecurity"],["Loading","loading"],["Equipment staging","staging"],["Water","water"],["Electricity","electricity"],["Restroom","restroom"]].map(([l,k])=><Choice key={k} label={l} options={["Available","Unavailable","Restricted"]} value={a[k]} change={v=>setA({[k]:v})}/>)}</div>;
 if(index===11)return <><DT label="Cleaning start" value={a.cleaningStart} change={v=>setA({cleaningStart:v})}/><DT label="Required completion" value={a.requiredCompletion} change={v=>setA({requiredCompletion:v})}/><Text label="Who or what arrives afterward?" value={a.arrivesAfterward} change={v=>setA({arrivesAfterward:v})}/></>;
 if(index===12)return <><Choice label="Other trades" options={["None","Working during cleaning","Returning afterward"]} value={a.tradeStatus} change={v=>setA({tradeStatus:v})}/><Text label="Party responsible for re-cleaning" value={a.recleanResponsibleParty} change={v=>setA({recleanResponsibleParty:v})}/></>;
 if(index===13)return <>{m("Site restrictions","restrictions",["None","HOA","Building hours","Quiet hours","Security","Crew-size limit","Other"])}{arr(a.restrictions).includes("Other")&&<Text label="Other — explain" value={a.restrictionOther} change={v=>setA({restrictionOther:v})}/>}</>;
 return <><Text label="Approver name" value={a.approverName} change={v=>setA({approverName:v})}/><Text label="Approver role" value={a.approverRole} change={v=>setA({approverRole:v})}/><Choice label="Acceptance standard" options={["Visual walkthrough","Written punch list","Photo approval","Other"]} value={a.acceptanceStandard} change={v=>setA({acceptanceStandard:v})}/>{a.acceptanceStandard==="Other"&&<Text label="Other — explain" value={a.acceptanceOther} change={v=>setA({acceptanceOther:v})}/>}</>;
}
function Choice({label,options,value,change}:{label:string;options:string[];value:unknown;change:(v:string)=>void}){return <fieldset className="mt-4"><legend className="font-medium">{label}</legend><div className="mt-2 flex flex-wrap gap-3">{options.map(o=><label key={o} className="flex gap-2"><input type="radio" name={label} checked={value===o} onChange={()=>change(o)}/>{o}</label>)}</div></fieldset>}
function Multi({label,options,value,onChange}:{label:string;options:string[];value:string[];onChange:(v:string[])=>void}){return <fieldset className="mt-4"><legend className="font-medium">{label}</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{options.map(o=><label key={o} className="flex gap-2"><input type="checkbox" checked={value.includes(o)} onChange={e=>onChange(e.target.checked?[...value,o]:value.filter(x=>x!==o))}/>{o}</label>)}</div></fieldset>}
function Text({label,value,change}:{label:string;value:unknown;change:(v:string)=>void}){return <label className="mt-4 block font-medium">{label}<textarea className={input} maxLength={5000} value={typeof value==="string"?value:""} onChange={e=>change(e.target.value)}/></label>}
function Num({label,value,change}:{label:string;value:unknown;change:(v:number|null)=>void}){return <label className="mt-4 block font-medium">{label}<input className={input} type="number" min="0" step="1" value={typeof value==="number"?value:""} onChange={e=>change(e.target.value===""?null:Number(e.target.value))}/></label>}
function DT({label,value,change}:{label:string;value:unknown;change:(v:string)=>void}){return <label className="mt-4 block font-medium">{label}<input className={input} type="datetime-local" value={typeof value==="string"?value:""} onChange={e=>change(e.target.value)}/></label>}
function Photo({label,category,caption,onPhoto}:{label:string;category:WalkthroughPhotoCategory;caption:string;onPhoto:(f:File,c:WalkthroughPhotoCategory,x:string)=>void}){return <label className="mt-4 block font-medium">{label}<input type="file" accept="image/*" className="mt-1 block" onChange={e=>{const f=e.target.files?.[0];if(f)onPhoto(f,category,caption);e.target.value="";}}/></label>}
const input="mt-1 block w-full rounded-lg border border-neutral-300 p-2",primary="rounded-lg bg-[#143d1a] px-4 py-2 font-bold text-white disabled:opacity-40",secondary="rounded-lg border px-4 py-2 font-bold disabled:opacity-40";
