"use client";

import { useState } from "react";
import { StandardResidentialCarryForward } from "@/components/walkthroughs/StandardResidentialFieldWalkthrough";
import type { FieldMeasurements, PropertyManagementCommonAreasFieldAssessment, StandardResidentialContext } from "@/types/fieldWalkthrough";

type Props={measurements:FieldMeasurements;context:StandardResidentialContext;includedAddons:string[];onChange:(v:FieldMeasurements)=>void};
type Value=string|string[]|number|boolean|null; type Answers=Record<string,Value>;
const sections=["Property Overview","Occupancy / Access","Overall Common-Area Condition","Entry / Lobby","Hallways / Corridors","Stairwells","Elevators","Laundry Rooms","Trash / Refuse Areas","Exterior Common Areas","Amenities","Parking / Garage","Flooring","Glass / Windows","High-Touch / Detail Areas","Pet / Resident Impact","Areas Requiring Extra Attention","Service Frequency Observation","Service Suitability","Expected Labor","Exceptions","Final Confirmation"] as const;
export function isPropertyManagementCommonAreasService(service:string|null|undefined){return service?.trim()==="Apartment Building / Complex Cleaning"}
export function propertyManagementCommonAreasCompletionIssues(m:FieldMeasurements,c:StandardResidentialContext){const a=assessment(m).answers??{};return sections.filter((_,i)=>issues(i,a,m,c).length)}

export function PropertyManagementCommonAreasFieldWalkthrough({measurements,context,includedAddons,onChange}:Props){
 const [current,setCurrent]=useState(0),a=assessment(measurements).answers??{},missing=issues(current,a,measurements,context);
 const set=(k:string,v:Value)=>onChange({...measurements,propertyManagementCommonAreasAssessment:{...measurements.propertyManagementCommonAreasAssessment,fieldWalkthrough:{answers:{...a,[k]:v}}}});
 const toggle=(k:string,v:string,exclusive="None")=>{const old=list(a[k]);set(k,old.includes(v)?old.filter(x=>x!==v):v===exclusive?[v]:[...old.filter(x=>x!==exclusive),v])};
 return <div><StandardResidentialCarryForward context={context}/><aside className="mt-3 rounded-xl bg-blue-50 p-4"><b>Included Add-ons / Scope</b><p className="mt-1 text-sm">{includedAddons.length?includedAddons.join(", "):"No included add-ons were provided."}</p></aside><div className="mt-6 flex justify-between text-sm"><b>{current+1} of {sections.length}</b><span>{Math.round((current+1)/sections.length*100)}% complete</span></div><div className="mt-2 h-2 rounded-full bg-neutral-200"><div className="h-full rounded-full bg-[#143d1a]" style={{width:`${(current+1)/sections.length*100}%`}}/></div><section className="mt-5 rounded-xl border p-4"><h3 className="text-lg font-extrabold text-[#143d1a]">{sections[current]}</h3><div className="mt-4 space-y-5">{render(current,a,measurements,includedAddons,set,toggle)}</div></section>{!!missing.length&&<div role="alert" className="mt-4 rounded-lg bg-amber-50 p-3 text-sm"><b>Before continuing:</b><ul className="list-disc pl-5">{missing.map(x=><li key={x}>{x}</li>)}</ul></div>}<div className="mt-5 flex justify-between"><button type="button" className={secondary} disabled={!current} onClick={()=>setCurrent(x=>x-1)}>Previous</button><button type="button" className={primary} disabled={!!missing.length||current===21} onClick={()=>setCurrent(x=>x+1)}>Continue</button></div></div>
}

function render(i:number,a:Answers,m:FieldMeasurements,addons:string[],set:(k:string,v:Value)=>void,toggle:(k:string,v:string,e?:string)=>void){switch(i){
case 0:return <><Quantity label="Number of units" k="unitCount" upstream={null} a={a} set={set}/><Quantity label="Number of floors" k="floorCount" upstream={m.floors} a={a} set={set}/><Quantity label="Number of buildings" k="buildingCount" upstream={null} a={a} set={set}/>{yn(["Interior corridors?","Exterior walkways?"],["interiorCorridors","exteriorWalkways"],a,set)}</>;
case 1:return <><Radio q="What is the occupancy status?" k="occupancy" values={["Fully occupied","Partially occupied","Newly opened/lease-up","Other"]} a={a} set={set}/>{yn(["Gated access?","Key or fob required?","Restricted areas?","Elevator access?","Parking restrictions?","Service-hour restrictions?"],["gatedAccess","keyFob","restrictedAreas","elevatorAccess","parkingRestrictions","serviceHourRestrictions"],a,set)}{["gatedAccess","keyFob","restrictedAreas","parkingRestrictions","serviceHourRestrictions"].some(k=>a[k]==="Yes")&&<Notes q="Describe access restrictions." k="accessNotes" a={a} set={set}/>}</>;
case 2:return <Radio q="What is the overall common-area condition?" k="overallCondition" values={levels} a={a} set={set}/>;
case 3:return <Area q="What is the entry or lobby condition?" prefix="entry" observations={["Entry glass buildup","Door or handle buildup","Floors need extra attention","High-touch buildup","Dust or debris"]} a={a} set={set}/>;
case 4:return <Area q="What is the hallway or corridor condition?" prefix="hallway" observations={["Floor buildup","Baseboard buildup","Walls or doors visibly marked","Dust or cobwebs","Trash or debris","Obstructions or access issues"]} a={a} set={set}/>;
case 5:return <Area q="What is the stairwell condition?" prefix="stairwell" observations={["Steps or landings","Handrails","Corners or edges","Dust or cobwebs","Trash or debris"]} a={a} set={set}/>;
case 6:return <Area q="What is the elevator condition?" prefix="elevator" observations={["Floors","Walls or panels","Doors or tracks","Buttons or high-touch surfaces","Mirrors or glass"]} a={a} set={set}/>;
case 7:return <Area q="What is the laundry-room condition?" prefix="laundry" observations={["Floors","Machine exteriors","Lint or dust","Counters or surfaces","Trash","Sink if present"]} a={a} set={set}/>;
case 8:return <><Area q="What is the trash or refuse-area condition?" prefix="trash" observations={["Overflowing waste","Loose debris","Significant odor","Buildup around bins","Special access issue"]} a={a} set={set}/><p className="text-xs text-neutral-500">Observational only; hazardous-waste handling is not implied.</p></>;
case 9:return <><Checks q="Which exterior common areas apply?" k="exteriorAreas" values={["Walkways","Courtyard","Patios/seating areas","Breezeways","Entry approaches","Mailbox area","Other","None"]} a={a} toggle={toggle}/><Radio q="What is their condition?" k="exteriorCondition" values={levels} a={a} set={set}/>{list(a.exteriorAreas).includes("Other")&&<Notes q="Describe the other exterior area." k="exteriorOther" a={a} set={set}/>}</>;
case 10:return <><Checks q="Which amenities apply?" k="amenities" values={["Pool area","Fitness room","Clubhouse/community room","Leasing office","Mail/package room","Recreation area","Other","None"]} a={a} toggle={toggle}/><Radio q="What is the overall amenity condition?" k="amenityCondition" values={levels} a={a} set={set}/><Notes q="Note special amenity concerns, if any." k="amenityNotes" a={a} set={set}/><p className="text-xs text-neutral-500">Pool observations cover surrounding common areas unless upstream scope explicitly includes specialized pool service.</p></>;
case 11:return <><Radio q="What parking or garage area applies?" k="parkingType" values={["Not applicable","Surface parking","Covered parking","Parking garage"]} a={a} set={set}/>{a.parkingType!=="Not applicable"&&yn(["Trash or debris?","Dust or dirt buildup?","Oil or staining observed?","Corners or edges buildup?","Access limitations?"],["parkingTrash","parkingDust","parkingOil","parkingEdges","parkingAccess"],a,set)}<p className="text-xs text-neutral-500">Observations do not imply oil removal or pressure washing unless included upstream.</p></>;
case 12:return <><Checks q="Which flooring materials are present?" k="flooring" values={["Carpet","Hardwood","Laminate","Tile","Vinyl","Concrete","Natural stone","Other"]} a={a} toggle={(k,v)=>toggle(k,v,"")}/>{yn(["Heavy buildup?","Staining or soiling?","Sticky residue?","Special precautions?"],["floorBuildup","floorStaining","floorSticky","floorPrecautions"],a,set)}{(list(a.flooring).includes("Other")||["floorBuildup","floorStaining","floorSticky","floorPrecautions"].some(k=>a[k]==="Yes"))&&<Notes q="Describe flooring conditions or precautions." k="floorNotes" a={a} set={set}/>}</>;
case 13:return <><p className="rounded-lg bg-blue-50 p-3 text-sm"><b>Upstream window scope:</b> {addons.filter(x=>/(window|glass)/i.test(x)).join(", ")||"No matching included scope provided."}</p>{yn(["Entry glass?","Interior common-area glass?","Mirrors?","Tracks or sills?","Heavy buildup?","Access limitations?"],["entryGlass","commonGlass","mirrors","tracksSills","glassBuildup","glassAccess"],a,set)}{a.glassAccess==="Yes"&&<Notes q="Describe glass access limitations." k="glassNotes" a={a} set={set}/>}</>;
case 14:return <>{yn(["Door handles?","Railings?","Elevator buttons?","Mailbox or package areas?","Shared fixtures?","Other high-touch areas?"],["touchHandles","touchRailings","touchElevator","touchMail","touchFixtures","touchOther"],a,set)}{a.touchOther==="Yes"&&<Notes q="Describe other high-touch areas." k="touchOtherNotes" a={a} set={set}/>}</>;
case 15:return <>{yn(["Pet hair in common areas?","Pet-related staining or soiling?","Resident belongings obstruct cleaning?","Recurring trash or debris concern?"],["petHair","petSoiling","residentObstruction","recurringTrash"],a,set)}{["petSoiling","residentObstruction","recurringTrash"].some(k=>a[k]==="Yes")&&<Notes q="Describe resident or pet impacts." k="residentImpactNotes" a={a} set={set}/>}</>;
case 16:return <><Checks q="Which areas require extra attention?" k="extraAttention" values={["Entry/lobby","Hallways","Stairwells","Elevators","Laundry","Trash areas","Exterior walkways","Courtyard","Amenities","Parking/garage","Glass","Floors","Other","None"]} a={a} toggle={toggle}/>{list(a.extraAttention).includes("Other")&&<Notes q="Describe the other area." k="extraAttentionOther" a={a} set={set}/>}</>;
case 17:return <><Radio q="Based only on physical condition, does the scheduled frequency appear appropriate?" k="frequencyObservation" values={["Existing/scheduled frequency appears appropriate","More frequent service may be needed","Less frequent service may be sufficient","Management review needed"]} a={a} set={set}/>{a.frequencyObservation&&a.frequencyObservation!=="Existing/scheduled frequency appears appropriate"&&<Notes q="Explain the frequency observation." k="frequencyNotes" a={a} set={set}/>}<p className="text-xs">Technicians cannot change contract frequency or pricing.</p></>;
case 18:return <><Radio q="Does Common Area Cleaning appear appropriate?" k="serviceSuitable" values={["Yes — Common Area Cleaning appears appropriate","Additional service may be required","Management review needed"]} a={a} set={set}/>{a.serviceSuitable==="Additional service may be required"&&<Checks q="Which additional service may be required?" k="recommendedServices" values={["Pressure washing","Deep cleaning","Window cleaning","Trash-area attention","Other"]} a={a} toggle={(k,v)=>toggle(k,v,"")}/>} {a.serviceSuitable&&a.serviceSuitable!=="Yes — Common Area Cleaning appears appropriate"&&<Notes q="Explain the recommendation." k="serviceNotes" a={a} set={set}/>}<p className="text-xs">Recommendation only; technicians cannot add services or change pricing.</p></>;
case 19:return <><Radio q="What is the expected labor level?" k="laborLevel" values={["Normal","Above normal","Significantly above normal"]} a={a} set={set}/><Radio q="What crew size is recommended?" k="recommendedCrew" values={["1","2","3","4+"]} a={a} set={set}/><Radio q="What is the estimated duration?" k="serviceDuration" values={["Under 2 hours","2–4 hours","4–6 hours","6–8 hours","8+ hours"]} a={a} set={set}/><p className="text-xs">Operational observations only.</p></>;
case 20:return <><Radio q="Did you observe anything else that could materially affect service?" k="materialException" values={["No","Yes"]} a={a} set={set}/>{a.materialException==="Yes"&&<Notes q="Explain the exception." k="exceptionNotes" a={a} set={set}/>}</>;
default:return <label className="flex gap-3 rounded-lg border p-3 text-sm font-semibold"><input type="checkbox" checked={a.technicianConfirmation===true} onChange={e=>set("technicianConfirmation",e.target.checked)}/>I have physically reviewed the accessible service areas and completed this walkthrough based on the property&apos;s observed condition.</label>}}

function issues(i:number,a:Answers,m:FieldMeasurements,_c:StandardResidentialContext){const out:string[]=[];const need=(k:string,l:string)=>{if(a[k]==null||a[k]===""||(Array.isArray(a[k])&&!a[k].length))out.push(l)};const area=(p:string,obs:string[])=>{need(`${p}Condition`,"Select the condition.");if(a[`${p}Condition`]!=="Not applicable")obs.forEach((_,n)=>need(`${p}Observation${n+1}`,"Complete every observation."))};switch(i){case 0:if(m.floors==null)need("floorCount","Record number of floors.");["unitCount","buildingCount","interiorCorridors","exteriorWalkways"].forEach(k=>need(k,"Complete property overview."));break;
case 1:["occupancy","gatedAccess","keyFob","restrictedAreas","elevatorAccess","parkingRestrictions","serviceHourRestrictions"].forEach(k=>need(k,"Complete occupancy and access."));if(["gatedAccess","keyFob","restrictedAreas","parkingRestrictions","serviceHourRestrictions"].some(k=>a[k]==="Yes"))need("accessNotes","Describe restrictions.");break;
case 2:need("overallCondition","Select overall condition.");break;
case 3:area("entry",["a","b","c","d","e"]);break;
case 4:area("hallway",["a","b","c","d","e","f"]);break;
case 5:area("stairwell",["a","b","c","d","e"]);break;
case 6:area("elevator",["a","b","c","d","e"]);break;
case 7:area("laundry",["a","b","c","d","e","f"]);break;
case 8:area("trash",["a","b","c","d","e"]);break;
case 9:["exteriorAreas","exteriorCondition"].forEach(k=>need(k,"Complete exterior areas."));if(list(a.exteriorAreas).includes("Other"))need("exteriorOther","Describe other exterior area.");break;
case 10:["amenities","amenityCondition"].forEach(k=>need(k,"Complete amenities."));break;
case 11:need("parkingType","Select parking type.");if(a.parkingType!=="Not applicable")["parkingTrash","parkingDust","parkingOil","parkingEdges","parkingAccess"].forEach(k=>need(k,"Complete parking observations."));break;
case 12:["flooring","floorBuildup","floorStaining","floorSticky","floorPrecautions"].forEach(k=>need(k,"Complete flooring."));if(list(a.flooring).includes("Other")||["floorBuildup","floorStaining","floorSticky","floorPrecautions"].some(k=>a[k]==="Yes"))need("floorNotes","Describe flooring.");break;
case 13:["entryGlass","commonGlass","mirrors","tracksSills","glassBuildup","glassAccess"].forEach(k=>need(k,"Complete glass observations."));if(a.glassAccess==="Yes")need("glassNotes","Describe access limitations.");break;
case 14:["touchHandles","touchRailings","touchElevator","touchMail","touchFixtures","touchOther"].forEach(k=>need(k,"Complete high-touch observations."));if(a.touchOther==="Yes")need("touchOtherNotes","Describe other areas.");break;
case 15:["petHair","petSoiling","residentObstruction","recurringTrash"].forEach(k=>need(k,"Complete resident-impact observations."));if(["petSoiling","residentObstruction","recurringTrash"].some(k=>a[k]==="Yes"))need("residentImpactNotes","Describe the impact.");break;
case 16:need("extraAttention","Select areas or None.");if(list(a.extraAttention).includes("Other"))need("extraAttentionOther","Describe other area.");break;
case 17:need("frequencyObservation","Select frequency observation.");if(a.frequencyObservation&&a.frequencyObservation!=="Existing/scheduled frequency appears appropriate")need("frequencyNotes","Explain frequency observation.");break;
case 18:need("serviceSuitable","Select suitability.");if(a.serviceSuitable==="Additional service may be required")need("recommendedServices","Select recommended service.");if(a.serviceSuitable&&a.serviceSuitable!=="Yes — Common Area Cleaning appears appropriate")need("serviceNotes","Explain recommendation.");break;
case 19:["laborLevel","recommendedCrew","serviceDuration"].forEach(k=>need(k,"Complete expected labor."));break;
case 20:need("materialException","Answer exceptions.");if(a.materialException==="Yes")need("exceptionNotes","Explain exception.");break;
case 21:if(a.technicianConfirmation!==true)out.push("Confirm the technician statement.")}return [...new Set(out)]}
function Area({q,prefix,observations,a,set}:{q:string;prefix:string;observations:string[];a:Answers;set:(k:string,v:Value)=>void}){return <><Radio q={q} k={`${prefix}Condition`} values={["Not applicable",...levels]} a={a} set={set}/>{a[`${prefix}Condition`]!=="Not applicable"&&yn(observations,observations.map((_,i)=>`${prefix}Observation${i+1}`),a,set)}</>}
function Quantity({label,k,upstream,a,set}:{label:string;k:string;upstream:number|null|undefined;a:Answers;set:(k:string,v:Value)=>void}){return upstream!=null?<p className="rounded-lg bg-[#f3f6f2] p-3 text-sm">{label}: <b>{upstream}</b> (reported upstream)</p>:<label className="block text-sm font-bold">{label}<input type="number" min="0" step="1" className={input} value={typeof a[k]==="number"?a[k]:""} onChange={e=>set(k,e.target.value===""?null:Number(e.target.value))}/></label>}
function Radio({q,k,values,a,set}:{q:string;k:string;values:string[];a:Answers;set:(k:string,v:Value)=>void}){return <fieldset><legend className="text-sm font-bold">{q}</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{values.map(v=><label key={v} className="flex gap-2 rounded-lg border p-3 text-sm"><input type="radio" name={k} checked={a[k]===v} onChange={()=>set(k,v)}/>{v}</label>)}</div></fieldset>}
function Checks({q,k,values,a,toggle}:{q:string;k:string;values:string[];a:Answers;toggle:(k:string,v:string)=>void}){return <fieldset><legend className="text-sm font-bold">{q}</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{values.map(v=><label key={v} className="flex gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={list(a[k]).includes(v)} onChange={()=>toggle(k,v)}/>{v}</label>)}</div></fieldset>}
function Notes({q,k,a,set}:{q:string;k:string;a:Answers;set:(k:string,v:Value)=>void}){return <label className="block text-sm font-bold">{q}<textarea maxLength={5000} className={textarea} value={typeof a[k]==="string"?a[k]:""} onChange={e=>set(k,e.target.value)}/></label>}
function yn(q:string[],k:string[],a:Answers,set:(k:string,v:Value)=>void){return q.map((x,i)=><Radio key={x} q={x} k={k[i]} values={["Yes","No"]} a={a} set={set}/>)}
function assessment(m:FieldMeasurements):PropertyManagementCommonAreasFieldAssessment{return m.propertyManagementCommonAreasAssessment?.fieldWalkthrough??{answers:{}}} function list(v:unknown):string[]{return Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"):[]}
const levels=["Light","Moderate","Heavy","Severe"],input="mt-2 block w-full rounded-lg border p-2",textarea="mt-2 block min-h-24 w-full rounded-lg border p-2 font-normal",primary="rounded-lg bg-[#143d1a] px-4 py-2 font-bold text-white disabled:opacity-40",secondary="rounded-lg border px-4 py-2 font-bold disabled:opacity-40";
