"use client";

import { useEffect, useState } from "react";
import { createCommunication, getClientCommunications } from "@/lib/services/clientCommunications";
import type { ClientCommunication, CommunicationChannel } from "@/types/clientCommunication";

const outcomes=["Reached","Left Voicemail","Sent Text","Sent Email","No Answer","Follow-Up Needed"] as const;
const methods=["Phone","SMS","Email"] as const;

export function SalesContactAttempts({clientId,propertyId,estimateId}:{clientId:string;propertyId:string|null;estimateId:string|null}){
  const [records,setRecords]=useState<ClientCommunication[]>([]),[method,setMethod]=useState<CommunicationChannel>("Phone"),[outcome,setOutcome]=useState<(typeof outcomes)[number]>("Reached"),[occurredAt,setOccurredAt]=useState(()=>localDateTime()),[note,setNote]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
  useEffect(()=>{void getClientCommunications(clientId).then(rows=>setRecords(rows.filter(item=>item.metadata.salesQualification===true))).catch(()=>setError("Contact history could not be loaded."))},[clientId]);
  async function save(){setSaving(true);setError(null);try{const record=await createCommunication({client_id:clientId,property_id:propertyId,estimate_id:estimateId,communication_type:"General",channel:method,direction:"Outbound",status:"Sent",subject:`Sales qualification · ${outcome}`,message_body:note.trim()||null,sent_at:new Date(occurredAt).toISOString(),metadata:{salesQualification:true,outcome}});setRecords(current=>[record,...current]);setNote("")}catch(cause){setError(cause instanceof Error?cause.message:"Contact attempt could not be saved.")}finally{setSaving(false)}}
  return <section className="rounded-2xl border border-[#143d1a]/10 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h3 className="font-extrabold text-[#143d1a]">Contact Attempts</h3><p className="mt-1 text-sm text-neutral-500">Stored in the existing client communication history.</p></div></div>{error&&<p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Field label="Method"><select value={method} onChange={event=>setMethod(event.target.value as CommunicationChannel)} className={inputClass}>{methods.map(item=><option key={item}>{item}</option>)}</select></Field><Field label="Date / time"><input type="datetime-local" value={occurredAt} onChange={event=>setOccurredAt(event.target.value)} className={inputClass}/></Field><Field label="Outcome"><select value={outcome} onChange={event=>setOutcome(event.target.value as typeof outcome)} className={inputClass}>{outcomes.map(item=><option key={item}>{item}</option>)}</select></Field><Field label="Note"><input value={note} onChange={event=>setNote(event.target.value)} className={inputClass}/></Field></div><button type="button" disabled={saving||!occurredAt} onClick={()=>void save()} className="mt-3 rounded-lg bg-[#143d1a] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving…":"Log Contact Attempt"}</button><div className="mt-4 divide-y">{records.map(item=><article key={item.id} className="py-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><b className="text-[#143d1a]">{String(item.metadata.outcome??item.subject??"Contact")}</b><span className="text-xs text-neutral-400">{new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.sent_at??item.created_at))}</span></div><p className="mt-1 text-xs text-neutral-500">{item.channel}{item.message_body?` · ${item.message_body}`:""}</p></article>)}{records.length===0&&<p className="py-4 text-sm text-neutral-500">No contact attempts logged.</p>}</div></section>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1 block text-xs font-bold text-neutral-600">{label}</span>{children}</label>}
function localDateTime(){const date=new Date(),offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16)}
const inputClass="h-11 w-full rounded-lg border border-neutral-200 bg-white px-3 text-sm";
