"use client";

import { useState } from "react";
import type { FieldMeasurements, StandardResidentialContext, StandardResidentialFieldAssessment } from "@/types/fieldWalkthrough";

type Props={measurements:FieldMeasurements;context:StandardResidentialContext;includedAddons:string[];onChange:(value:FieldMeasurements)=>void};
type AnswerValue=string|string[]|boolean|null;
type Answers=Record<string,AnswerValue>;
const sections=["Property Occupancy","Overall Current Condition","Clutter Level","Flooring","Kitchen Condition","Bathroom Condition","Dust / Surface Condition","Pet Impact","Areas Requiring Extra Attention","Special Surfaces / Items","Service-Level Check","Estimated Service Effort","Walkthrough Exceptions","Final Technician Confirmation"] as const;

export function isStandardResidentialService(service:string|null|undefined){return service?.trim()==="Standard Cleaning"}

export function standardResidentialCompletionIssues(measurements:FieldMeasurements,context:StandardResidentialContext){
  const answers=assessment(measurements).answers??{};
  return sections.filter((_,index)=>sectionIssues(index,answers,context).length);
}

export function StandardResidentialFieldWalkthrough({measurements,context,includedAddons,onChange}:Props){
  const [current,setCurrent]=useState(0),answers=assessment(measurements).answers??{},missing=sectionIssues(current,answers,context);
  const set=(key:string,value:AnswerValue)=>onChange({...measurements,standardResidentialAssessment:{...measurements.standardResidentialAssessment,fieldWalkthrough:{answers:{...answers,[key]:value}}}});
  const toggle=(key:string,value:string,exclusive?:string)=>{const selected=array(answers[key]);set(key,selected.includes(value)?selected.filter(item=>item!==value):value===exclusive?[value]:[...selected.filter(item=>item!==exclusive),value])};
  return <div>
    <StandardResidentialCarryForward context={context}/>
    <div className="mt-6 flex items-center justify-between text-sm"><b>{current+1} of {sections.length}</b><span>{Math.round(((current+1)/sections.length)*100)}% complete</span></div>
    <div className="mt-2 h-2 overflow-hidden rounded-full bg-neutral-200"><div className="h-full bg-[#143d1a]" style={{width:`${((current+1)/sections.length)*100}%`}}/></div>
    <section className="mt-5 rounded-xl border border-neutral-200 p-4"><h3 className="text-lg font-extrabold text-[#143d1a]">{sections[current]}</h3><div className="mt-4 space-y-5">{renderSection(current,answers,context,includedAddons,set,toggle)}</div></section>
    {!!missing.length&&<div role="alert" className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><b>Before continuing:</b><ul className="mt-1 list-disc pl-5">{missing.map(item=><li key={item}>{item}</li>)}</ul></div>}
    <div className="mt-5 flex justify-between"><button type="button" className={secondary} disabled={current===0} onClick={()=>setCurrent(value=>value-1)}>Previous</button><button type="button" className={primary} disabled={!!missing.length||current===sections.length-1} onClick={()=>setCurrent(value=>value+1)}>Continue</button></div>
  </div>
}

export function StandardResidentialCarryForward({context}:{context:StandardResidentialContext}){const items:Array<[string,string|number|null|undefined]>=[["Customer / Property",context.customerProperty],["Service",context.service],["Bedrooms",context.bedrooms],["Bathrooms",context.bathrooms],["Square Footage",context.squareFeet],["Pets",context.pets],["Current Cleaner / Vendor",context.currentCleanerVendor],["Major Concerns / Problem Areas",context.majorConcerns],["Property Context",context.propertyContext],["Access Considerations",context.accessConsiderations],["Customer Notes",context.customerNotes],["Walkthrough Date / Time",context.walkthroughDateTime],["Walkthrough Method",context.walkthroughMethod]];return <aside className="rounded-xl bg-[#f3f6f2] p-4"><h3 className="font-extrabold text-[#143d1a]">Carry-Forward Context</h3><p className="mt-1 text-xs text-neutral-600">Read-only information reported before the field walkthrough.</p><dl className="mt-4 grid gap-3 sm:grid-cols-2">{items.filter(([,value])=>value!==null&&value!==undefined&&value!=="").map(([label,value])=><div key={label}><dt className="text-xs font-bold text-neutral-500">{label}</dt><dd className="text-sm text-neutral-800">{String(value)}</dd></div>)}</dl></aside>}

function renderSection(index:number,a:Answers,c:StandardResidentialContext,addons:string[],set:(key:string,value:AnswerValue)=>void,toggle:(key:string,value:string,exclusive?:string)=>void){switch(index){
case 0:return <Radio q="Is the property occupied?" k="occupancy" a={a} values={["Occupied","Vacant","Partially occupied"]} set={set}/>;
case 1:return <Radio q="What is the property's overall current condition?" k="overallCondition" a={a} values={["Light","Moderate","Heavy","Severe"]} set={set}/>;
case 2:return <><Radio q="What is the clutter level?" k="clutterLevel" a={a} values={["Minimal","Moderate","Heavy","Areas inaccessible due to clutter"]} set={set}/>{a.clutterLevel==="Areas inaccessible due to clutter"&&<Notes q="Which areas are inaccessible due to clutter?" k="inaccessibleAreas" a={a} set={set}/>}</>;
case 3:return <><Checks q="Which flooring materials are present?" k="flooring" a={a} values={["Carpet","Hardwood","Laminate","Tile","Vinyl","Natural stone","Other"]} toggle={toggle}/>{array(a.flooring).includes("Other")&&<Notes q="Describe the other flooring material." k="flooringOther" a={a} set={set}/>}<Radio q="Does any flooring require special treatment or show significant buildup?" k="flooringSpecialTreatment" a={a} values={["Yes","No"]} set={set}/>{a.flooringSpecialTreatment==="Yes"&&<Notes q="Identify the flooring area and observed condition." k="flooringConditionNotes" a={a} set={set}/>}</>;
case 4:return <><Radio q="What is the kitchen condition?" k="kitchenCondition" a={a} values={["Light","Moderate","Heavy","Severe buildup"]} set={set}/>{["Heavy grease/buildup?","Dishes/excess items preventing cleaning?","Exterior appliances need extra attention?","Cabinet exteriors have significant buildup?"].map((q,i)=><Radio key={q} q={q} k={["heavyGrease","dishesBlocking","applianceExteriors","cabinetBuildup"][i]} a={a} values={["Yes","No"]} set={set}/>)}{!!addons.filter(item=>/inside|interior/i.test(item)&&/(refrigerator|fridge|oven)/i.test(item)).length&&<p className="rounded-lg bg-blue-50 p-3 text-sm">Included appliance-interior add-ons: {addons.filter(item=>/inside|interior/i.test(item)&&/(refrigerator|fridge|oven)/i.test(item)).join(", ")}</p>}</>;
case 5:return <><Radio q="What is the bathroom condition?" k="bathroomCondition" a={a} values={["Light","Moderate","Heavy","Severe"]} set={set}/>{["Heavy soap scum?","Hard-water/mineral buildup?","Visible mold/mildew-like buildup?","Toilets/tubs/showers require unusually heavy detailing?"].map((q,i)=><Radio key={q} q={q} k={["soapScum","mineralBuildup","mildewLikeBuildup","heavyBathroomDetailing"][i]} a={a} values={["Yes","No"]} set={set}/>)}<p className="text-xs text-neutral-500">Record visible conditions only; this is not a professional mold diagnosis.</p></>;
case 6:return <Radio q="What is the dust and surface condition?" k="dustCondition" a={a} values={["Light","Moderate","Heavy","Excessive"]} set={set}/>;
case 7:return c.pets==="No"?<p className="rounded-lg bg-[#f3f6f2] p-3 text-sm">Upstream assessment reports no pets. No additional pet-impact questions are required.</p>:<><p className="text-sm">Upstream Pets response: <b>{c.pets||"Not provided"}</b></p><Radio q="What is the pet hair level?" k="petHairLevel" a={a} values={["Light","Moderate","Heavy"]} set={set}/>{["Visible pet-related staining/soiling?","Pet odor concern?","Will pets need to be secured during service?"].map((q,i)=><Radio key={q} q={q} k={["petStaining","petOdor","petsSecured"][i]} a={a} values={["Yes","No"]} set={set}/>)}</>;
case 8:return <><Checks q="Which areas require extra attention?" k="extraAttention" a={a} values={["Kitchen","Bathrooms","Bedrooms","Living/common areas","Floors","Baseboards","Doors/trim","Windows/glass","High-touch surfaces","Other","None"]} toggle={(key,value)=>toggle(key,value,"None")}/>{array(a.extraAttention).includes("Other")&&<Notes q="Explain the other area requiring extra attention." k="extraAttentionOther" a={a} set={set}/>}</>;
case 9:return <><Radio q="Are there surfaces or items requiring special cleaning precautions?" k="specialPrecautions" a={a} values={["Yes","No"]} set={set}/>{a.specialPrecautions==="Yes"&&<><Checks q="Which special surfaces or items are present?" k="specialSurfaceTypes" a={a} values={["Natural stone","Delicate wood","Stainless steel","Specialty fixtures","Artwork/decor","Electronics","Other"]} toggle={toggle}/><Notes q="Describe the required cleaning precautions." k="specialSurfaceNotes" a={a} set={set}/></>}</>;
case 10:return <><Radio q="Based on the physical walkthrough, is Standard Cleaning appropriate for the property's current condition?" k="serviceAppropriate" a={a} values={["Yes","No — Deep Cleaning recommended","No — another service is recommended","Management review needed"]} set={set}/>{a.serviceAppropriate&&a.serviceAppropriate!=="Yes"&&<Notes q="Explain the recommendation for management review." k="serviceRecommendationNotes" a={a} set={set}/>}<p className="text-xs text-neutral-500">This is an operational observation only. Technicians cannot change pricing.</p></>;
case 11:return <><Radio q="What is the expected labor level?" k="laborLevel" a={a} values={["Normal","Above normal","Significantly above normal"]} set={set}/><Radio q="What crew size is recommended?" k="recommendedCrew" a={a} values={["1","2","3","4+"]} set={set}/><Radio q="What is the estimated service duration?" k="serviceDuration" a={a} values={["Under 2 hours","2–4 hours","4–6 hours","6–8 hours","8+ hours"]} set={set}/><p className="text-xs text-neutral-500">Operational observations only; no pricing or margin is calculated here.</p></>;
case 12:return <><Radio q="Did you observe anything that could materially affect the service?" k="materialException" a={a} values={["No","Yes"]} set={set}/>{a.materialException==="Yes"&&<Notes q="Explain what could materially affect the service." k="exceptionNotes" a={a} set={set}/>}</>;
default:return <label className="flex gap-3 rounded-lg border p-3 text-sm font-semibold"><input type="checkbox" checked={a.technicianConfirmation===true} onChange={e=>set("technicianConfirmation",e.target.checked)}/>I have physically reviewed the accessible service areas and completed this walkthrough based on the property&apos;s observed condition.</label>}}

function sectionIssues(i:number,a:Answers,c:StandardResidentialContext){const missing:string[]=[];const need=(key:string,label:string)=>{if(a[key]===undefined||a[key]===null||a[key]===""||(Array.isArray(a[key])&&!a[key].length))missing.push(label)};switch(i){case 0:need("occupancy","Select property occupancy.");break;case 1:need("overallCondition","Select overall current condition.");break;case 2:need("clutterLevel","Select clutter level.");if(a.clutterLevel==="Areas inaccessible due to clutter")need("inaccessibleAreas","Identify inaccessible areas.");break;case 3:need("flooring","Select at least one flooring material.");if(array(a.flooring).includes("Other"))need("flooringOther","Describe the other flooring.");need("flooringSpecialTreatment","Answer the special-treatment question.");if(a.flooringSpecialTreatment==="Yes")need("flooringConditionNotes","Describe the flooring area and condition.");break;case 4:["kitchenCondition","heavyGrease","dishesBlocking","applianceExteriors","cabinetBuildup"].forEach(key=>need(key,"Complete every kitchen condition question."));break;case 5:["bathroomCondition","soapScum","mineralBuildup","mildewLikeBuildup","heavyBathroomDetailing"].forEach(key=>need(key,"Complete every bathroom condition question."));break;case 6:need("dustCondition","Select dust and surface condition.");break;case 7:if(c.pets!=="No")["petHairLevel","petStaining","petOdor","petsSecured"].forEach(key=>need(key,"Complete every applicable pet-impact question."));break;case 8:need("extraAttention","Select an area or None.");if(array(a.extraAttention).includes("Other"))need("extraAttentionOther","Explain the other area.");break;case 9:need("specialPrecautions","Answer the special-precautions question.");if(a.specialPrecautions==="Yes"){need("specialSurfaceTypes","Select the special surfaces or items.");need("specialSurfaceNotes","Describe the precautions.")}break;case 10:need("serviceAppropriate","Select whether Standard Cleaning is appropriate.");if(a.serviceAppropriate&&a.serviceAppropriate!=="Yes")need("serviceRecommendationNotes","Explain the recommendation.");break;case 11:["laborLevel","recommendedCrew","serviceDuration"].forEach(key=>need(key,"Complete every service-effort question."));break;case 12:need("materialException","Answer the walkthrough-exceptions question.");if(a.materialException==="Yes")need("exceptionNotes","Explain the exception.");break;case 13:if(a.technicianConfirmation!==true)missing.push("Confirm the final technician statement.")}return [...new Set(missing)]}
function assessment(m:FieldMeasurements):StandardResidentialFieldAssessment{return m.standardResidentialAssessment?.fieldWalkthrough??{answers:{}}}
function array(value:unknown):string[]{return Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"):[]}
function Radio({q,k,a,values,set}:{q:string;k:string;a:Answers;values:string[];set:(key:string,value:AnswerValue)=>void}){return <fieldset><legend className="text-sm font-bold">{q}</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{values.map(value=><label key={value} className="flex gap-2 rounded-lg border p-3 text-sm"><input type="radio" name={k} checked={a[k]===value} onChange={()=>set(k,value)}/>{value}</label>)}</div></fieldset>}
function Checks({q,k,a,values,toggle}:{q:string;k:string;a:Answers;values:string[];toggle:(key:string,value:string)=>void}){const selected=array(a[k]);return <fieldset><legend className="text-sm font-bold">{q}</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{values.map(value=><label key={value} className="flex gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={selected.includes(value)} onChange={()=>toggle(k,value)}/>{value}</label>)}</div></fieldset>}
function Notes({q,k,a,set}:{q:string;k:string;a:Answers;set:(key:string,value:AnswerValue)=>void}){return <label className="block text-sm font-bold">{q}<textarea maxLength={5000} className={input} value={typeof a[k]==="string"?a[k] as string:""} onChange={e=>set(k,e.target.value)}/></label>}
const input="mt-2 block min-h-24 w-full rounded-lg border border-neutral-300 p-2 font-normal";
const primary="rounded-lg bg-[#143d1a] px-4 py-2 font-bold text-white disabled:opacity-40";
const secondary="rounded-lg border px-4 py-2 font-bold disabled:opacity-40";
