"use client";

import { useEffect, useMemo, useState } from "react";
import { createWalkthrough, getAvailableEstimates, getWalkthroughClients, getWalkthroughProperties, updateWalkthrough, WalkthroughDuplicateError } from "@/lib/services/walkthroughs";
import type { Client } from "@/types/client";
import type { AvailableEstimate, WalkthroughInput, WalkthroughMeasurements, WalkthroughRecommendation, WalkthroughScopeItem, WalkthroughStatus, WalkthroughWithRelations } from "@/types/walkthrough";
import { EMPTY_MEASUREMENTS, WALKTHROUGH_STATUSES } from "@/types/walkthrough";
import type { Property } from "@/types/property";

const scopeOptions = ["Floors", "Bathrooms", "Kitchen", "Windows", "Baseboards", "Appliances", "Common Areas", "Workstations", "Trash", "Sanitizing", "Pressure Washing", "Other"];
const recommendationOptions = ["Deep cleaning recommended", "Recurring service recommended", "Additional crew recommended", "Special equipment required", "Pressure washing recommended", "Carpet service recommended"];

type Props = { walkthrough?: WalkthroughWithRelations; initialEstimate?: AvailableEstimate; onClose: () => void; onSaved: () => void; onViewDuplicate?: (walkthrough: WalkthroughWithRelations) => void };

export function WalkthroughFormModal({ walkthrough, initialEstimate, onClose, onSaved, onViewDuplicate }: Props) {
  const [mode, setMode] = useState<"estimate" | "manual">(walkthrough?.estimate_id || initialEstimate ? "estimate" : "manual");
  const [estimates, setEstimates] = useState<AvailableEstimate[]>(initialEstimate ? [initialEstimate] : []);
  const [clients, setClients] = useState<Client[]>(walkthrough ? [walkthrough.client] : []);
  const [properties, setProperties] = useState<Property[]>(walkthrough ? [walkthrough.property] : []);
  const [estimateId, setEstimateId] = useState(walkthrough?.estimate_id ?? initialEstimate?.id ?? "");
  const [clientId, setClientId] = useState(walkthrough?.client_id ?? initialEstimate?.client_id ?? "");
  const [propertyId, setPropertyId] = useState(walkthrough?.property_id ?? initialEstimate?.property_id ?? "");
  const [estimateSearch, setEstimateSearch] = useState("");
  const [date, setDate] = useState(walkthrough?.walkthrough_date ?? "");
  const [time, setTime] = useState(walkthrough?.walkthrough_time?.slice(0, 5) ?? "");
  const [assignedTo, setAssignedTo] = useState(walkthrough?.assigned_to ?? "");
  const [notes, setNotes] = useState(walkthrough?.notes ?? "");
  const [status, setStatus] = useState<WalkthroughStatus>(walkthrough?.status ?? "New");
  const [measurements, setMeasurements] = useState<WalkthroughMeasurements>({ ...EMPTY_MEASUREMENTS, ...walkthrough?.measurements });
  const [scope, setScope] = useState<WalkthroughScopeItem[]>(walkthrough?.scope ?? []);
  const [recommendations, setRecommendations] = useState<WalkthroughRecommendation[]>(walkthrough?.recommendations ?? []);
  const [customScope, setCustomScope] = useState("");
  const [customRecommendation, setCustomRecommendation] = useState("");
  const [loading, setLoading] = useState(!initialEstimate && !walkthrough);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [duplicate, setDuplicate] = useState<WalkthroughWithRelations | null>(null);

  useEffect(() => {
    let active = true;
    void Promise.all([getAvailableEstimates(), getWalkthroughClients(), getWalkthroughProperties()])
      .then(([estimateRows, clientRows, propertyRows]) => { if (active) { setEstimates(mergeById(estimateRows, initialEstimate ? [initialEstimate] : [])); setClients(mergeById(clientRows, walkthrough ? [walkthrough.client] : [])); setProperties(mergeById(propertyRows, walkthrough ? [walkthrough.property] : [])); } })
      .catch((caught: unknown) => { console.error("Walkthrough relationship data failed to load", caught); if (active) setError(message(caught, "Estimate, client, or property information could not be loaded.")); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [initialEstimate, walkthrough]);

  const selectedEstimate = estimates.find((item) => item.id === estimateId) ?? initialEstimate;
  const selectedClient = selectedEstimate?.client ?? clients.find((item) => item.id === clientId) ?? walkthrough?.client;
  const selectedProperty = selectedEstimate?.property ?? properties.find((item) => item.id === propertyId) ?? walkthrough?.property;
  const division = selectedEstimate?.division ?? selectedProperty?.property_type ?? selectedClient?.client_type ?? "Residential";
  const filteredEstimates = useMemo(() => { const term = estimateSearch.trim().toLocaleLowerCase(); return estimates.filter((item) => !term || [item.estimate_number, displayClient(item.client), item.property.address, item.service_name].filter(Boolean).join(" ").toLocaleLowerCase().includes(term)); }, [estimateSearch, estimates]);
  const clientProperties = properties.filter((item) => item.client_id === clientId);

  function chooseEstimate(id: string) { setEstimateId(id); const found = estimates.find((item) => item.id === id); if (found) { setClientId(found.client_id); setPropertyId(found.property_id); } }
  function chooseClient(id: string) { setClientId(id); setPropertyId(""); }
  function addScope(label: string) { if (label.trim() && !scope.some((item) => item.label.toLocaleLowerCase() === label.trim().toLocaleLowerCase())) setScope([...scope, { id: crypto.randomUUID(), label: label.trim() }]); setCustomScope(""); }
  function addRecommendation(text: string) { if (text.trim() && !recommendations.some((item) => item.text.toLocaleLowerCase() === text.trim().toLocaleLowerCase())) setRecommendations([...recommendations, { id: crypto.randomUUID(), text: text.trim() }]); setCustomRecommendation(""); }

  async function save() {
    if (!clientId || !propertyId) return setError("Select a valid client and property relationship.");
    if (!date || !time) return setError("Walkthrough date and time are required.");
    if (mode === "estimate" && !estimateId) return setError("Select an estimate or choose Create Without Estimate.");
    setSaving(true); setError(null); setDuplicate(null);
    const input: WalkthroughInput = { estimate_id: mode === "estimate" ? estimateId : null, client_id: clientId, property_id: propertyId, division, walkthrough_date: date, walkthrough_time: time, status, contact_name: selectedEstimate ? customerName(selectedEstimate) : selectedClient ? displayClient(selectedClient) : null, phone: selectedEstimate?.customer_phone ?? selectedClient?.phone ?? null, email: selectedEstimate?.customer_email ?? selectedClient?.email ?? null, assigned_to: clean(assignedTo), notes: clean(notes), scope, measurements, recommendations, photos: walkthrough?.photos ?? [] };
    try { if (walkthrough) await updateWalkthrough(walkthrough.id, input); else await createWalkthrough(input); onSaved(); }
    catch (caught) { console.error("Walkthrough save failed", caught); if (caught instanceof WalkthroughDuplicateError) setDuplicate(caught.walkthrough); else setError(message(caught, "The walkthrough could not be saved.")); }
    finally { setSaving(false); }
  }

  return <div className="fixed inset-0 z-[75] overflow-y-auto bg-[#07190a]/65 p-3 backdrop-blur-[2px] sm:p-6"><section role="dialog" aria-modal="true" className="mx-auto max-w-5xl rounded-2xl bg-[#f5f6f4] shadow-2xl"><header className="sticky top-0 z-20 flex items-center justify-between rounded-t-2xl border-b border-neutral-200 bg-white px-5 py-4 sm:px-7"><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[#9a7a17]">Walkthrough workspace</p><h2 className="mt-1 text-xl font-extrabold text-[#143d1a]">{walkthrough ? "Walkthrough Details" : "New Walkthrough"}</h2></div><button type="button" onClick={onClose} disabled={saving} aria-label="Close walkthrough" className="grid size-9 place-items-center rounded-lg border border-neutral-200 text-xl text-neutral-500">×</button></header>
    <div className="space-y-5 p-4 sm:p-7">{error && <Alert text={error} />}{duplicate && <DuplicatePanel walkthrough={duplicate} cancel={() => setDuplicate(null)} view={() => onViewDuplicate?.(duplicate)} />}
      {!walkthrough && <Panel title="Link an Estimate"><div className="mb-4 grid grid-cols-2 gap-2 rounded-xl bg-[#edf1eb] p-1.5"><ModeButton active={mode === "estimate"} text="Link an Estimate" click={() => setMode("estimate")} /><ModeButton active={mode === "manual"} text="Create Without Estimate" click={() => { setMode("manual"); setEstimateId(""); setClientId(""); setPropertyId(""); }} /></div>{mode === "estimate" ? <div className="space-y-2"><input type="search" value={estimateSearch} onChange={(e) => setEstimateSearch(e.target.value)} placeholder="Search estimate, customer, property, or service" className={inputClass} /><select value={estimateId} onChange={(e) => chooseEstimate(e.target.value)} className={inputClass} disabled={loading}><option value="">Select an active estimate</option>{filteredEstimates.map((item) => <option key={item.id} value={item.id}>{item.estimate_number} — {customerName(item)} — {item.property.address} — {item.division} — {item.service_name ?? "Service"} — {currency(item.result.finalPrice)}</option>)}</select></div> : <div className="grid gap-4 sm:grid-cols-2"><Select label="Client" value={clientId} set={chooseClient} options={clients.map((item) => ({ value: item.id, label: displayClient(item) }))} placeholder="Select client" /><Select label="Property" value={propertyId} set={setPropertyId} options={clientProperties.map((item) => ({ value: item.id, label: item.address }))} placeholder={clientId ? "Select property" : "Select a client first"} disabled={!clientId} /></div>}</Panel>}
      {(selectedClient || selectedProperty) && <Panel title="Linked Information"><div className="grid gap-4 text-sm sm:grid-cols-3"><Info label="Client" value={selectedClient ? displayClient(selectedClient) : "—"} /><Info label="Property" value={selectedProperty?.address ?? "—"} /><Info label="Division" value={division} />{selectedEstimate && <><Info label="Estimate" value={selectedEstimate.estimate_number} /><Info label="Service" value={selectedEstimate.service_name ?? "—"} /><Info label="Price" value={currency(selectedEstimate.result.finalPrice)} /></>}</div></Panel>}
      <Panel title="Walkthrough Schedule"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Text label="Date" type="date" value={date} set={setDate} required /><Text label="Time" type="time" value={time} set={setTime} required /><Text label="Assigned To" value={assignedTo} set={setAssignedTo} /><Select label="Status" value={status} set={(value) => setStatus(value as WalkthroughStatus)} options={WALKTHROUGH_STATUSES.map((item) => ({ value: item, label: item }))} placeholder="Status" /></div><label className="mt-4 block"><Label text="Notes" /><textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={3} className={inputClass} /></label></Panel>
      <Assessment division={division} value={measurements} set={setMeasurements} />
      <ListEditor title="Scope" presets={scopeOptions} items={scope.map((item) => ({ id: item.id, text: item.label }))} custom={customScope} setCustom={setCustomScope} add={addScope} remove={(id) => setScope(scope.filter((item) => item.id !== id))} />
      <ListEditor title="Recommendations" presets={recommendationOptions} items={recommendations} custom={customRecommendation} setCustom={setCustomRecommendation} add={addRecommendation} remove={(id) => setRecommendations(recommendations.filter((item) => item.id !== id))} />
      <Panel title="Photos"><div className="rounded-xl border border-dashed border-[#143d1a]/20 bg-[#f8faf7] px-6 py-8 text-center"><p className="text-sm font-bold text-[#143d1a]">Photos</p><p className="mt-1 text-sm text-neutral-500">Storage integration coming in a later phase.</p></div></Panel>
      <footer className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} disabled={saving} className={secondaryClass}>Cancel</button><button type="button" onClick={() => void save()} disabled={saving || loading} className="rounded-lg bg-[#143d1a] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? "Saving…" : walkthrough ? "Save Walkthrough" : "Create Walkthrough"}</button></footer>
    </div></section></div>;
}

function Assessment({ division, value, set }: { division: "Residential" | "Commercial"; value: WalkthroughMeasurements; set: (value: WalkthroughMeasurements) => void }) { const update = <K extends keyof WalkthroughMeasurements>(key: K, item: WalkthroughMeasurements[K]) => set({ ...value, [key]: item }); return <Panel title="Property Assessment"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Select label="Overall Condition" value={value.overallCondition} set={(v) => update("overallCondition", v as WalkthroughMeasurements["overallCondition"])} options={["Light", "Average", "Heavy", "Extreme"].map((item) => ({ value: item, label: item }))} placeholder="Select condition" /><NumberInput label="Square Footage Verification" value={value.squareFeet} set={(v) => update("squareFeet", v)} /><NumberInput label="Floors" value={value.floors} set={(v) => update("floors", v)} />{division === "Residential" ? <><NumberInput label="Bedrooms" value={value.bedrooms} set={(v) => update("bedrooms", v)} /><NumberInput label="Bathrooms" value={value.bathrooms} set={(v) => update("bathrooms", v)} /><Text label="Pets" value={value.pets} set={(v) => update("pets", v)} /></> : <><NumberInput label="Restrooms" value={value.restrooms} set={(v) => update("restrooms", v)} /><NumberInput label="Kitchen / Breakroom Areas" value={value.kitchenAreas} set={(v) => update("kitchenAreas", v)} /><Text label="Specialty Areas" value={value.specialtyAreas} set={(v) => update("specialtyAreas", v)} /></>}<Text label="Access Restrictions" value={value.accessRestrictions} set={(v) => update("accessRestrictions", v)} /><Text label="Parking / Loading" value={value.parkingLoading} set={(v) => update("parkingLoading", v)} /><Text label="Water Access" value={value.waterAccess} set={(v) => update("waterAccess", v)} /><Text label="Power Access" value={value.powerAccess} set={(v) => update("powerAccess", v)} /><Text label="Security / Alarm Information" value={value.securityAlarm} set={(v) => update("securityAlarm", v)} /><Text label="Damage Observed" value={value.damageObserved} set={(v) => update("damageObserved", v)} /><Text label="Hazards Observed" value={value.hazardsObserved} set={(v) => update("hazardsObserved", v)} /><label className="flex min-h-11 items-center gap-3 rounded-lg border border-neutral-200 bg-white px-3.5 text-sm font-semibold text-neutral-700"><input type="checkbox" checked={value.heavySoilBuildup} onChange={(e) => update("heavySoilBuildup", e.target.checked)} className="size-4 accent-[#143d1a]" />Heavy Soil / Buildup</label></div></Panel>; }
function ListEditor({ title, presets, items, custom, setCustom, add, remove }: { title: string; presets: string[]; items: { id: string; text: string }[]; custom: string; setCustom: (value: string) => void; add: (value: string) => void; remove: (id: string) => void }) { return <Panel title={title}><div className="flex flex-wrap gap-2">{presets.map((item) => <button key={item} type="button" onClick={() => add(item)} className="rounded-full border border-[#143d1a]/15 bg-white px-3 py-1.5 text-xs font-bold text-[#143d1a] hover:bg-[#edf4ec]">+ {item}</button>)}</div><div className="mt-4 flex gap-2"><input value={custom} onChange={(e) => setCustom(e.target.value)} placeholder={`Add custom ${title.toLocaleLowerCase()} item`} className={inputClass} /><button type="button" onClick={() => add(custom)} className={secondaryClass}>Add</button></div><ul className="mt-4 grid gap-2 sm:grid-cols-2">{items.map((item) => <li key={item.id} className="flex items-center justify-between rounded-lg bg-[#f3f6f2] px-3 py-2 text-sm text-neutral-700"><span>{item.text}</span><button type="button" onClick={() => remove(item.id)} aria-label={`Remove ${item.text}`} className="text-lg text-neutral-400">×</button></li>)}</ul></Panel>; }
function DuplicatePanel({ walkthrough, cancel, view }: { walkthrough: WalkthroughWithRelations; cancel: () => void; view: () => void }) { return <div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-extrabold text-amber-800">A walkthrough is already linked to this estimate.</p><p className="mt-1 text-sm text-amber-700">{walkthrough.walkthrough_date ? `Scheduled for ${walkthrough.walkthrough_date}.` : "Open the existing walkthrough to continue."}</p><div className="mt-3 flex gap-2"><button type="button" onClick={cancel} className={secondaryClass}>Cancel</button><button type="button" onClick={view} className="rounded-lg bg-[#143d1a] px-4 py-2 text-sm font-bold text-white">View Walkthrough</button></div></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[#143d1a]/10 bg-white p-5 shadow-[0_8px_25px_rgba(20,61,26,.04)] sm:p-6"><h3 className="text-base font-extrabold text-[#143d1a]">{title}</h3><div className="mt-4">{children}</div></section>; }
function ModeButton({ active, text, click }: { active: boolean; text: string; click: () => void }) { return <button type="button" onClick={click} className={`rounded-lg px-3 py-2.5 text-sm font-bold ${active ? "bg-white text-[#143d1a] shadow-sm" : "text-neutral-500"}`}>{text}</button>; }
function Text({ label, value, set, type = "text", required }: { label: string; value: string; set: (value: string) => void; type?: string; required?: boolean }) { return <label><Label text={label} required={required} /><input type={type} value={value} onChange={(e) => set(e.target.value)} className={inputClass} /></label>; }
function NumberInput({ label, value, set }: { label: string; value: number | null; set: (value: number | null) => void }) { return <label><Label text={label} /><input type="number" min="0" value={value ?? ""} onChange={(e) => set(e.target.value === "" ? null : Number(e.target.value))} className={inputClass} /></label>; }
function Select({ label, value, set, options, placeholder, disabled }: { label: string; value: string; set: (value: string) => void; options: { value: string; label: string }[]; placeholder: string; disabled?: boolean }) { return <label><Label text={label} /><select value={value} onChange={(e) => set(e.target.value)} className={inputClass} disabled={disabled}><option value="">{placeholder}</option>{options.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>; }
function Label({ text, required }: { text: string; required?: boolean }) { return <span className="mb-2 block text-xs font-bold text-neutral-700">{text}{required && <span className="ml-1 text-[#9a7a17]">*</span>}</span>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-neutral-400">{label}</p><p className="mt-1 font-semibold text-neutral-700">{value}</p></div>; }
function Alert({ text }: { text: string }) { return <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{text}</div>; }
export function displayClient(client: Client): string { const name = [client.first_name, client.last_name].filter(Boolean).join(" "); return client.client_type === "Commercial" ? client.company_name || name || "Unnamed client" : name || client.company_name || "Unnamed client"; }
function customerName(estimate: AvailableEstimate): string { return [estimate.customer_first_name, estimate.customer_last_name].filter(Boolean).join(" ") || estimate.client.company_name || displayClient(estimate.client); }
function mergeById<T extends { id: string }>(primary: T[], extra: T[]): T[] { return [...new Map([...primary, ...extra].map((item) => [item.id, item])).values()]; }
function clean(value: string): string | null { return value.trim() || null; }
function currency(value: number): string { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value); }
function message(error: unknown, fallback: string): string { return error instanceof Error && error.message ? error.message : fallback; }
const inputClass = "w-full rounded-lg border border-neutral-200 bg-white px-3.5 py-2.5 text-sm text-neutral-800 outline-none transition focus:border-[#d4af37] focus:ring-2 focus:ring-[#d4af37]/15 disabled:bg-neutral-100";
const secondaryClass = "rounded-lg border border-neutral-200 bg-white px-4 py-2.5 text-sm font-bold text-neutral-600 hover:bg-neutral-50 disabled:opacity-50";
