"use client";

import { useCallback, useEffect, useState } from "react";
import {
  approveLeadCommissionPayoutBatch, createLeadCommissionPayoutAdjustment,
  discardLeadCommissionPayoutBatch, generateWeeklyLeadCommissionPayouts,
  getLeadCommissionPayoutManagement, holdLeadCommissionEntry,
  markLeadCommissionPayoutPaid, releaseLeadCommissionEntryHold,
} from "@/lib/services/leadRepresentative";
import type { LeadPayoutManagement } from "@/types/leadRepresentative";

const methods = ["Apple Pay", "Zelle", "Venmo", "Cash App", "Chime", "Debit Card", "Other"] as const;
const input = "rounded-xl border border-neutral-300 bg-white px-3 py-2 text-sm";
const primary = "rounded-xl bg-[#143d1a] px-4 py-2 text-sm font-bold text-white disabled:opacity-50";

export function LeadCommissionPayoutManagementPage() {
  const [data,setData]=useState<LeadPayoutManagement|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
  const [periodEnd,setPeriodEnd]=useState(""),[rep,setRep]=useState(""),[amount,setAmount]=useState(""),[reason,setReason]=useState("");
  const load=useCallback(async()=>{try{setData(await getLeadCommissionPayoutManagement());setError(null)}catch(cause){setError(cause instanceof Error?cause.message:"Payout management could not be loaded.")}},[]);
  useEffect(()=>{void load()},[load]);
  async function act(task:()=>Promise<unknown>){setBusy(true);setError(null);try{await task();await load()}catch(cause){setError(cause instanceof Error?cause.message:"The payout action failed.")}finally{setBusy(false)}}
  return <>
    <header className="border-b pb-7"><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#9a7a16]">Lead Representative Commissions</p><h1 className="mt-2 text-3xl font-extrabold text-[#143d1a]">Weekly Payouts</h1><p className="mt-3 text-neutral-600">Generate, approve, and record external payments using {data?.businessTimezone??"the business timezone"}.</p></header>
    {error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}
    <section className="mt-6 grid gap-5 lg:grid-cols-2">
      <form className="rounded-2xl border bg-white p-5 shadow-sm" onSubmit={event=>{event.preventDefault();void act(()=>generateWeeklyLeadCommissionPayouts(periodEnd))}}><h2 className="font-extrabold text-[#143d1a]">Generate Weekly Payouts</h2><p className="mt-1 text-sm text-neutral-500">Choose a closed Thursday. Entries are selected automatically.</p><div className="mt-4 flex gap-3"><input aria-label="Period end" className={input} type="date" required value={periodEnd} onChange={event=>setPeriodEnd(event.target.value)}/><button disabled={busy} className={primary}>Generate</button></div></form>
      <form className="rounded-2xl border bg-white p-5 shadow-sm" onSubmit={event=>{event.preventDefault();void act(()=>createLeadCommissionPayoutAdjustment(rep,Number(amount),reason)).then(()=>{setAmount("");setReason("")})}}><h2 className="font-extrabold text-[#143d1a]">Append Adjustment</h2><div className="mt-4 grid gap-3"><select aria-label="Lead Representative" required className={input} value={rep} onChange={event=>setRep(event.target.value)}><option value="">Representative</option>{data?.representatives.map(row=><option key={row.employeeId} value={row.employeeId}>{row.displayName}</option>)}</select><input aria-label="Adjustment amount" required step="0.01" className={input} type="number" value={amount} onChange={event=>setAmount(event.target.value)}/><input aria-label="Adjustment reason" required className={input} value={reason} onChange={event=>setReason(event.target.value)} placeholder="Required reason"/><button disabled={busy} className={primary}>Record adjustment</button></div></form>
    </section>
    <section className="mt-7 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-extrabold text-[#143d1a]">Payout Batches</h2><div className="mt-5 grid gap-4">{data?.batches.map(batch=><article key={batch.batchId} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-extrabold text-[#143d1a]">{batch.representativeName} · {batch.batchNumber}</h3><p className="text-sm text-neutral-500">{batch.periodStart} – {batch.periodEnd} · {batch.status}</p></div><b>${Number(batch.payoutAmount).toFixed(2)}</b></div><p className="mt-3 text-sm">Gross ${Number(batch.grossPositiveAmount).toFixed(2)} · Negative ${Number(batch.negativeActivityAmount).toFixed(2)} · Carry in ${Number(batch.carryForwardIn).toFixed(2)} · Carry out ${Number(batch.carryForwardOut).toFixed(2)}</p><div className="mt-3 grid gap-2">{batch.items?.map(item=><p key={item.itemId} className="rounded-lg bg-neutral-50 p-2 text-xs">{item.description} · ${Number(item.amount).toFixed(2)}</p>)}</div>{batch.status==="Awaiting Approval"&&<div className="mt-4 flex gap-2"><button disabled={busy} className={primary} onClick={()=>void act(()=>approveLeadCommissionPayoutBatch(batch.batchId))}>Approve</button><button disabled={busy} className={input} onClick={()=>{const value=window.prompt("Required discard reason");if(value)void act(()=>discardLeadCommissionPayoutBatch(batch.batchId,value))}}>Discard</button></div>}{batch.status==="Approved / Awaiting Payment"&&<MarkPaid batchId={batch.batchId} busy={busy} act={act}/>}</article>)}</div></section>
    <section className="mt-7 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-extrabold text-[#143d1a]">Commission Holds</h2><div className="mt-5 grid gap-3">{data?.ledgerEntries.filter(row=>!row.consumed).map(row=><article key={row.commissionId} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><span className="text-sm"><b>{row.representativeName}</b> · {row.customerName} · ${Number(row.amount).toFixed(2)} · {row.held?"Held":"Eligible"}</span><button disabled={busy} className={input} onClick={()=>{const value=window.prompt(`Required ${row.held?"release":"hold"} reason`);if(value)void act(()=>row.held?releaseLeadCommissionEntryHold(row.commissionId,value):holdLeadCommissionEntry(row.commissionId,value))}}>{row.held?"Release":"Hold"}</button></article>)}</div></section>
  </>;
}

function MarkPaid({batchId,busy,act}:{batchId:string;busy:boolean;act:(task:()=>Promise<unknown>)=>Promise<void>}) {
  const [date,setDate]=useState(""),[method,setMethod]=useState(""),[other,setOther]=useState(""),[reference,setReference]=useState(""),[note,setNote]=useState("");
  return <form className="mt-4 grid gap-2 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();void act(()=>markLeadCommissionPayoutPaid(batchId,date,method,other,reference,note))}}><input aria-label="Actual payment date" required className={input} type="date" value={date} onChange={event=>setDate(event.target.value)}/><select aria-label="Payment method" required className={input} value={method} onChange={event=>setMethod(event.target.value)}><option value="">Payment method</option>{methods.map(value=><option key={value}>{value}</option>)}</select>{method==="Other"&&<input aria-label="Other method description" required className={input} value={other} onChange={event=>setOther(event.target.value)} placeholder="Describe method"/>}<input aria-label="Confirmation reference" className={input} value={reference} onChange={event=>setReference(event.target.value)} placeholder="Optional reference"/><input aria-label="Payment note" className={input} value={note} onChange={event=>setNote(event.target.value)} placeholder="Optional note"/><button disabled={busy} className={primary}>Mark Paid</button></form>;
}
