"use client";

import { useEffect, useState } from "react";
import { PushNotificationSetup } from "@/components/pwa/PushNotificationSetup";
import { getNotificationPreferences, saveNotificationPreferences } from "@/lib/services/notificationPreferences";
import { ATTENTION_CATEGORIES, type AttentionCategory } from "@/types/attention";
import type { NotificationPreferencesInput } from "@/types/notificationPreferences";

const defaults: NotificationPreferencesInput = { disabled_attention_categories: [], direct_messages_enabled: true, announcements_enabled: true };

export function NotificationSettingsPage() {
  const [preferences,setPreferences]=useState(defaults),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
  useEffect(()=>{let active=true;void getNotificationPreferences().then((value)=>{if(active)setPreferences(value)}).catch((cause)=>{console.error("Notification preferences load failed",cause);if(active)setError("Notification preferences could not be loaded.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  function toggleCategory(category:AttentionCategory){setPreferences((current)=>({...current,disabled_attention_categories:current.disabled_attention_categories.includes(category)?current.disabled_attention_categories.filter((item)=>item!==category):[...current.disabled_attention_categories,category]}))}
  async function save(){setSaving(true);setError(null);setNotice(null);try{setPreferences(await saveNotificationPreferences(preferences));setNotice("Notification preferences saved.")}catch(cause){console.error("Notification preferences save failed",cause);setError("Notification preferences could not be saved.")}finally{setSaving(false)}}
  return <><header className="border-b pb-7"><h1 className="text-3xl font-extrabold text-[#143d1a]">Notification Settings</h1><p className="mt-3 text-neutral-600">Choose whether this browser receives StudioScrubz Attention alerts.</p></header><PushNotificationSetup className="mt-6" /><section className="mt-6 rounded-2xl border border-neutral-200 bg-white p-5 sm:p-6"><h2 className="text-xl font-extrabold text-[#143d1a]">Push Notification Preferences</h2><p className="mt-2 text-sm text-neutral-600">Choose which notifications are delivered to your subscribed browsers. Items remain visible inside StudioScrubz OS.</p>{loading?<p className="mt-5 text-sm text-neutral-500">Loading preferences...</p>:<div className="mt-5 grid gap-3 sm:grid-cols-2">{ATTENTION_CATEGORIES.map((category)=><Toggle key={category} label={category} checked={!preferences.disabled_attention_categories.includes(category)} set={()=>toggleCategory(category)}/>) }<Toggle label="Direct Messages" checked={preferences.direct_messages_enabled} set={(checked)=>setPreferences((current)=>({...current,direct_messages_enabled:checked}))}/><Toggle label="Announcements" checked={preferences.announcements_enabled} set={(checked)=>setPreferences((current)=>({...current,announcements_enabled:checked}))}/></div>}{error&&<p role="alert" className="mt-4 text-sm font-bold text-red-700">{error}</p>}{notice&&<p role="status" className="mt-4 text-sm font-bold text-green-700">{notice}</p>}<button type="button" disabled={loading||saving} onClick={()=>void save()} className="mt-5 rounded-lg bg-[#143d1a] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving...":"Save Preferences"}</button></section></>;
}

function Toggle({label,checked,set}:{label:string;checked:boolean;set:(checked:boolean)=>void}){return <label className="flex items-center justify-between gap-4 rounded-xl border border-neutral-200 px-4 py-3 text-sm font-bold text-neutral-700"><span>{label}</span><input type="checkbox" checked={checked} onChange={(event)=>set(event.target.checked)} className="size-5 accent-[#143d1a]"/></label>}
