"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useAuth } from "@/components/auth/AuthProvider";
import { calculateProspectScore } from "@/lib/prospectScoring";
import { createProspect, getProspectAssignees, getProspectEvents, getProspects, updateProspect } from "@/lib/services/prospects";
import type { Prospect, ProspectAssignee, ProspectEvent, ProspectInput, ProspectStatus, ProspectVerificationStatus } from "@/types/prospect";

const statuses: ProspectStatus[] = ["New", "Researching", "Qualified", "Contact Later", "Disqualified"];
const verificationStatuses: ProspectVerificationStatus[] = ["Unverified", "Pending", "Verified", "Invalid"];
const managementRoles = new Set(["Master Admin", "Administrator", "Manager"]);
const inputClass = "w-full rounded-lg border border-[#143d1a]/15 bg-white px-3 py-2 text-sm text-neutral-800 outline-none focus:border-[#143d1a]";
const emptyForm = (): ProspectInput => ({ company_name:"",industry:null,company_type:null,website:null,business_email:null,business_phone:null,address:null,city:null,state:null,zip:null,territory:null,services:[],recurring_potential:false,estimated_value:null,source_type:"Manual",source_url:null,discovered_at:new Date().toISOString(),verified_at:null,verification_status:"Unverified",assigned_user_id:null,status:"New",next_action:null,next_follow_up_at:null,notes:null });

export function ProspectsPage() {
  const { profile } = useAuth();
  const canManageAll = managementRoles.has(profile?.role ?? "");
  const [rows,setRows]=useState<Prospect[]>([]), [assignees,setAssignees]=useState<ProspectAssignee[]>([]), [events,setEvents]=useState<ProspectEvent[]>([]);
  const [selectedId,setSelectedId]=useState<string|null>(null), [editing,setEditing]=useState(false), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false);
  const [search,setSearch]=useState(""), [status,setStatus]=useState("All"), [territory,setTerritory]=useState("All"), [assignee,setAssignee]=useState("All"), [error,setError]=useState<string|null>(null);
  const [form,setForm]=useState<ProspectInput>(emptyForm);
  const selected=rows.find(row=>row.id===selectedId)??null;

  async function load() { setLoading(true); setError(null); try { const [prospects,nextAssignees]=await Promise.all([getProspects(),canManageAll?getProspectAssignees():Promise.resolve(profile?[{id:profile.id,display_name:profile.display_name||profile.email||"Sales User"}]:[])]); setRows(prospects);setAssignees(nextAssignees);setSelectedId(current=>current&&prospects.some(row=>row.id===current)?current:prospects[0]?.id??null); } catch(cause){setError(message(cause));} finally{setLoading(false);} }
  useEffect(()=>{void load();},[]); // RLS remains the source of truth; route access already requires an active profile.
  useEffect(()=>{if(!selectedId){setEvents([]);return;}void getProspectEvents(selectedId).then(setEvents).catch(cause=>setError(message(cause)));},[selectedId,rows]);

  const visible=useMemo(()=>rows.filter(row=>{const term=search.trim().toLocaleLowerCase();const haystack=[row.company_name,row.industry,row.company_type,row.website,row.business_email,row.business_phone,row.city,row.state,row.territory].filter(Boolean).join(" ").toLocaleLowerCase();return(!term||haystack.includes(term))&&(status==="All"||row.status===status)&&(territory==="All"||row.territory===territory)&&(assignee==="All"||row.assigned_user_id===assignee);}),[rows,search,status,territory,assignee]);
  const territories=Array.from(new Set(rows.map(row=>row.territory).filter((value):value is string=>Boolean(value)))).sort();
  const due=rows.filter(row=>row.next_follow_up_at&&new Date(row.next_follow_up_at)<=new Date()&&row.status!=="Disqualified").length;
  const preview=calculateProspectScore({territory:form.territory,industry:form.industry,recurringPotential:form.recurring_potential,verificationStatus:form.verification_status,email:form.business_email,phone:form.business_phone,estimatedValue:form.estimated_value,discoveredAt:form.discovered_at});

  function openCreate(){const next=emptyForm();next.assigned_user_id=canManageAll?null:profile?.id??null;setForm(next);setSelectedId(null);setEditing(true);}
  function openEdit(row:Prospect){setForm(toInput(row));setSelectedId(row.id);setEditing(true);}
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError(null);try{const saved=selectedId?await updateProspect(selectedId,form):await createProspect(form);setEditing(false);await load();setSelectedId(saved.id);}catch(cause){setError(message(cause));}finally{setSaving(false);}}

  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-[#143d1a]/10 pb-6"><div><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#9a7a17]">Sales workspace</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-[#143d1a]">Prospect Engine</h1><p className="mt-2 text-sm text-neutral-600">Track qualified business prospects without automated outreach.</p></div>{canManageAll&&<button type="button" onClick={openCreate} className="rounded-lg bg-[#143d1a] px-4 py-2.5 text-sm font-bold text-white">New prospect</button>}</header>
    {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <section className="grid gap-3 sm:grid-cols-4">{[["Visible",rows.length],["New",rows.filter(r=>r.status==="New").length],["Qualified",rows.filter(r=>r.status==="Qualified").length],["Follow-up due",due]].map(([label,value])=><div key={label} className="rounded-xl border border-[#143d1a]/10 bg-white p-4"><p className="text-xs font-bold uppercase text-neutral-500">{label}</p><p className="mt-1 text-2xl font-extrabold text-[#143d1a]">{value}</p></div>)}</section>
    <section className="grid gap-3 rounded-xl border border-[#143d1a]/10 bg-white p-4 md:grid-cols-4"><input className={inputClass} type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search prospects" aria-label="Search prospects"/><Select value={status} set={setStatus} options={["All",...statuses]}/><Select value={territory} set={setTerritory} options={["All",...territories]}/><Select value={assignee} set={setAssignee} options={["All",...assignees.map(a=>a.id)]} labels={new Map(assignees.map(a=>[a.id,a.display_name]))}/></section>
    {loading?<p className="text-sm text-neutral-500">Loading prospects…</p>:<div className="grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(360px,.85fr)]"><section className="overflow-hidden rounded-xl border border-[#143d1a]/10 bg-white"><div className="divide-y divide-[#143d1a]/10">{visible.map(row=><button type="button" key={row.id} onClick={()=>{setEditing(false);setSelectedId(row.id);}} className={`grid w-full gap-2 p-4 text-left sm:grid-cols-[1fr_auto] ${selectedId===row.id?"bg-[#edf4ec]":"hover:bg-neutral-50"}`}><div><p className="font-extrabold text-[#143d1a]">{row.company_name}</p><p className="text-sm text-neutral-500">{[row.industry,row.city,row.state].filter(Boolean).join(" · ")||"No business context"}</p><p className="mt-1 text-xs text-neutral-500">{row.next_action||"No next action"}</p></div><div className="sm:text-right"><span className="rounded-full bg-[#143d1a] px-2 py-1 text-xs font-bold text-white">{row.score}</span><p className="mt-2 text-xs font-bold text-neutral-500">{row.status}</p></div></button>)}{visible.length===0&&<p className="p-6 text-sm text-neutral-500">No prospects match these filters.</p>}</div></section>
      <aside className="rounded-xl border border-[#143d1a]/10 bg-white p-5">{editing?<ProspectForm form={form} setForm={setForm} assignees={assignees} canAssign={canManageAll} preview={preview} saving={saving} save={save} cancel={()=>{setEditing(false);if(!selectedId)setSelectedId(rows[0]?.id??null);}}/>:selected?<ProspectDetail row={selected} assignees={assignees} events={events} edit={()=>openEdit(selected)}/>:<p className="text-sm text-neutral-500">Select a prospect to view details.</p>}</aside></div>}
  </div>;
}

function ProspectForm({form,setForm,assignees,canAssign,preview,saving,save,cancel}:{form:ProspectInput;setForm:(value:ProspectInput)=>void;assignees:ProspectAssignee[];canAssign:boolean;preview:{score:number;explanation:string};saving:boolean;save:(event:FormEvent)=>void;cancel:()=>void}){
  const field=(key:keyof ProspectInput,value:unknown)=>setForm({...form,[key]:value});
  return <form onSubmit={save} className="space-y-4"><div><p className="text-xs font-bold uppercase text-[#9a7a17]">Prospect record</p><h2 className="text-xl font-extrabold text-[#143d1a]">{form.company_name||"New prospect"}</h2></div><div className="grid gap-3 sm:grid-cols-2">
    <Field label="Company name" required value={form.company_name} set={v=>field("company_name",v)}/><Field label="Industry" value={form.industry??""} set={v=>field("industry",nullable(v))}/><Field label="Company type" value={form.company_type??""} set={v=>field("company_type",nullable(v))}/><Field label="Territory" value={form.territory??""} set={v=>field("territory",nullable(v))}/><Field label="Website" value={form.website??""} set={v=>field("website",nullable(v))}/><Field label="Business email" type="email" value={form.business_email??""} set={v=>field("business_email",nullable(v))}/><Field label="Business phone" value={form.business_phone??""} set={v=>field("business_phone",nullable(v))}/><Field label="Address" value={form.address??""} set={v=>field("address",nullable(v))}/><Field label="City" value={form.city??""} set={v=>field("city",nullable(v))}/><Field label="State" value={form.state??""} set={v=>field("state",nullable(v))}/><Field label="ZIP" value={form.zip??""} set={v=>field("zip",nullable(v))}/><Field label="Services (comma separated)" value={form.services.join(", ")} set={v=>field("services",v.split(",").map(x=>x.trim()).filter(Boolean))}/><Field label="Estimated value" type="number" value={form.estimated_value?.toString()??""} set={v=>field("estimated_value",v===""?null:Number(v))}/><Field label="Source type" value={form.source_type} set={v=>field("source_type",v)}/><Field label="Source URL" value={form.source_url??""} set={v=>field("source_url",nullable(v))}/><Field label="Next action" value={form.next_action??""} set={v=>field("next_action",nullable(v))}/><Field label="Follow-up" type="datetime-local" value={toLocal(form.next_follow_up_at)} set={v=>field("next_follow_up_at",v?new Date(v).toISOString():null)}/><label className="text-xs font-bold text-neutral-600">Status<select className={`${inputClass} mt-1`} value={form.status} onChange={e=>field("status",e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-bold text-neutral-600">Verification<select className={`${inputClass} mt-1`} value={form.verification_status} onChange={e=>field("verification_status",e.target.value)}>{verificationStatuses.map(x=><option key={x}>{x}</option>)}</select></label>{canAssign&&<label className="text-xs font-bold text-neutral-600">Assigned Sales user<select className={`${inputClass} mt-1`} value={form.assigned_user_id??""} onChange={e=>field("assigned_user_id",nullable(e.target.value))}><option value="">Unassigned</option>{assignees.map(x=><option key={x.id} value={x.id}>{x.display_name}</option>)}</select></label>}
  </div><label className="flex items-center gap-2 text-sm font-bold text-neutral-700"><input type="checkbox" checked={form.recurring_potential} onChange={e=>field("recurring_potential",e.target.checked)}/>Recurring potential</label><label className="block text-xs font-bold text-neutral-600">Notes<textarea className={`${inputClass} mt-1 min-h-24`} value={form.notes??""} onChange={e=>field("notes",nullable(e.target.value))}/></label><div className="rounded-lg bg-[#edf4ec] p-3 text-xs text-[#143d1a]"><strong>Deterministic score preview: {preview.score}</strong><p className="mt-1">{preview.explanation}</p></div><div className="flex justify-end gap-2"><button type="button" onClick={cancel} className="rounded-lg border px-4 py-2 text-sm font-bold">Cancel</button><button disabled={saving} className="rounded-lg bg-[#143d1a] px-4 py-2 text-sm font-bold text-white">{saving?"Saving…":"Save prospect"}</button></div></form>;
}

function ProspectDetail({row,assignees,events,edit}:{row:Prospect;assignees:ProspectAssignee[];events:ProspectEvent[];edit:()=>void}){const owner=assignees.find(a=>a.id===row.assigned_user_id)?.display_name??"Unassigned";return <div className="space-y-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold uppercase text-[#9a7a17]">{row.status}</p><h2 className="text-xl font-extrabold text-[#143d1a]">{row.company_name}</h2></div><button type="button" onClick={edit} className="h-fit rounded-lg border border-[#143d1a]/20 px-3 py-2 text-xs font-bold text-[#143d1a]">Edit</button></div><dl className="grid gap-3 text-sm sm:grid-cols-2">{[["Assigned",owner],["Industry",row.industry],["Territory",row.territory],["Email",row.business_email],["Phone",row.business_phone],["Next action",row.next_action],["Follow-up",formatDate(row.next_follow_up_at)],["Verification",row.verification_status]].map(([term,value])=><div key={term}><dt className="text-xs font-bold text-neutral-500">{term}</dt><dd className="mt-0.5 text-neutral-800">{value||"—"}</dd></div>)}</dl>{row.source_url&&<a href={row.source_url} target="_blank" rel="noreferrer" className="text-sm font-bold text-[#143d1a] underline">Open source</a>}<div className="rounded-lg bg-[#edf4ec] p-3"><p className="font-extrabold text-[#143d1a]">Score {row.score}</p><p className="mt-1 text-xs text-neutral-600">{row.score_explanation}</p></div><div><h3 className="font-extrabold text-[#143d1a]">Activity</h3><div className="mt-2 space-y-2">{events.map(event=><div key={event.id} className="rounded-lg border border-[#143d1a]/10 p-3"><p className="text-sm font-bold">{event.event_type}</p><p className="text-xs text-neutral-500">{formatDate(event.created_at)}</p></div>)}{events.length===0&&<p className="text-sm text-neutral-500">No activity recorded.</p>}</div></div></div>}
function Field({label,value,set,type="text",required=false}:{label:string;value:string;set:(value:string)=>void;type?:string;required?:boolean}){return <label className="text-xs font-bold text-neutral-600">{label}<input className={`${inputClass} mt-1`} type={type} required={required} value={value} onChange={e=>set(e.target.value)}/></label>}
function Select({value,set,options,labels=new Map()}:{value:string;set:(value:string)=>void;options:string[];labels?:Map<string,string>}){return <select className={inputClass} value={value} onChange={e=>set(e.target.value)}>{options.map(option=><option key={option} value={option}>{labels.get(option)??option}</option>)}</select>}
function nullable(value:string){return value.trim()||null} function toLocal(value:string|null){return value?new Date(value).toISOString().slice(0,16):""} function formatDate(value:string|null){return value?new Date(value).toLocaleString():"—"} function message(cause:unknown){return cause instanceof Error?cause.message:"Prospect data could not be loaded."} function toInput(row:Prospect):ProspectInput{const {company_name,industry,company_type,website,business_email,business_phone,address,city,state,zip,territory,services,recurring_potential,estimated_value,source_type,source_url,discovered_at,verified_at,verification_status,assigned_user_id,status,next_action,next_follow_up_at,notes}=row;return{company_name,industry,company_type,website,business_email,business_phone,address,city,state,zip,territory,services,recurring_potential,estimated_value,source_type,source_url,discovered_at,verified_at,verification_status,assigned_user_id,status,next_action,next_follow_up_at,notes}}
