"use client";

import { useMemo, useState } from "react";
import { buildPreview, CSV_MAX_BYTES, CSV_MAX_ROWS, csvFields, parseCsv, suggestMapping } from "@/lib/prospectCsv";
import { createProspectImportBatch, importProspectRows } from "@/lib/services/prospects";
import type { Prospect, ProspectAssignee, ProspectCsvField, ProspectImportDecision, ProspectImportPreviewRow, ProspectImportResult } from "@/types/prospect";

const control="w-full rounded-lg border border-[#143d1a]/15 bg-white px-3 py-2 text-sm";
export function ProspectCsvImport({prospects,assignees,currentUserId,canAssign,close,completed}:{prospects:Prospect[];assignees:ProspectAssignee[];currentUserId:string;canAssign:boolean;close:()=>void;completed:()=>void}){
  const[file,setFile]=useState<File|null>(null),[headers,setHeaders]=useState<string[]>([]),[data,setData]=useState<string[][]>([]),[mapping,setMapping]=useState<Partial<Record<ProspectCsvField,number>>>({}),[preview,setPreview]=useState<ProspectImportPreviewRow[]>([]),[assigned,setAssigned]=useState(canAssign?"":currentUserId),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[result,setResult]=useState<ProspectImportResult|null>(null),[error,setError]=useState<string|null>(null);
  const counts=useMemo(()=>Object.fromEntries(["New","Exact duplicate","Possible duplicate","Invalid"].map(label=>[label,preview.filter(row=>row.classification===label).length])),[preview]);
  async function choose(next:File|null){setError(null);setResult(null);setPreview([]);if(!next)return;if(next.size>CSV_MAX_BYTES){setError("CSV must be 5 MB or smaller.");return;}if(!next.name.toLocaleLowerCase().endsWith(".csv")||!/^text\/csv(?:;|$)/i.test(next.type||"text/csv")){setError("Choose a UTF-8 .csv file.");return;}const bytes=new Uint8Array(await next.arrayBuffer());if(bytes.includes(0)){setError("CSV must be UTF-8 text.");return;}const text=new TextDecoder("utf-8",{fatal:true}).decode(bytes);const rows=parseCsv(text);if(rows.length<2){setError("CSV must include a header and at least one data row.");return;}if(rows.length-1>CSV_MAX_ROWS){setError("CSV cannot contain more than 2,000 data rows.");return;}setFile(next);setHeaders(rows[0]);setData(rows.slice(1));setMapping(suggestMapping(rows[0]));}
  function makePreview(){if(mapping.company_name===undefined){setError("Map the required Business name column.");return;}setError(null);setPreview(buildPreview(data,mapping,prospects));}
  function decide(index:number,decision:ProspectImportDecision|""){setPreview(current=>current.map((row,i)=>i===index?{...row,decision}:row));}
  async function run(){if(!file||!preview.length)return;const unresolved=preview.some(row=>row.classification==="Possible duplicate"&&!row.decision);if(unresolved){setError("Choose an action for every possible duplicate.");return;}setBusy(true);setError(null);try{const batchId=await createProspectImportBatch(crypto.randomUUID(),file.name,preview.length,assigned||null);let latest:ProspectImportResult={imported:0,skipped:0,failed:0,processed:0};for(let start=0;start<preview.length;start+=100){latest=await importProspectRows(batchId,preview.slice(start,start+100));setProgress(latest.processed);}setResult(latest);}catch(cause){setError(cause instanceof Error?cause.message:"CSV import failed.");}finally{setBusy(false);}}
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-3 sm:p-8"><section role="dialog" aria-modal="true" aria-labelledby="csv-title" className="mx-auto max-w-6xl rounded-2xl bg-[#f8faf7] p-4 shadow-xl sm:p-6"><header className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase text-[#9a7a17]">Controlled import</p><h2 id="csv-title" className="text-2xl font-extrabold text-[#143d1a]">Import prospects from CSV</h2><p className="mt-1 text-sm text-neutral-600">UTF-8 CSV only · 5 MB · 2,000 data rows. The uploaded file is never retained.</p></div><button type="button" onClick={close} className="rounded-lg border px-3 py-2 text-sm font-bold">Close</button></header>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="mt-5 grid gap-4 lg:grid-cols-3"><label className="text-sm font-bold text-neutral-700">CSV file<input className={`${control} mt-1`} type="file" accept=".csv,text/csv" onChange={event=>void choose(event.target.files?.[0]??null)}/></label>{canAssign&&<label className="text-sm font-bold text-neutral-700">Assign imported prospects<select className={`${control} mt-1`} value={assigned} onChange={e=>setAssigned(e.target.value)}><option value="">Unassigned</option>{assignees.map(a=><option key={a.id} value={a.id}>{a.display_name}</option>)}</select></label>}<div className="self-end text-sm text-neutral-500">{data.length?`${data.length} data rows loaded`:"Select a file to begin."}</div></div>
    {headers.length>0&&preview.length===0&&<section className="mt-6"><h3 className="font-extrabold text-[#143d1a]">Map columns</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{csvFields.map(field=><label key={field.key} className="text-xs font-bold text-neutral-600">{field.label}{field.key==="company_name"&&" *"}<select className={`${control} mt-1`} value={mapping[field.key]??""} onChange={e=>setMapping({...mapping,[field.key]:e.target.value===""?undefined:Number(e.target.value)})}><option value="">Not mapped</option>{headers.map((header,index)=><option key={`${header}-${index}`} value={index}>{header||`Column ${index+1}`}</option>)}</select></label>)}</div><button type="button" onClick={makePreview} className="mt-4 rounded-lg bg-[#143d1a] px-4 py-2.5 text-sm font-bold text-white">Preview import</button></section>}
    {preview.length>0&&<section className="mt-6"><div className="flex flex-wrap gap-2">{Object.entries(counts).map(([label,count])=><span key={label} className="rounded-full bg-white px-3 py-1 text-xs font-bold text-neutral-700">{label}: {count}</span>)}</div><div className="mt-3 max-h-[50vh] overflow-auto rounded-xl border bg-white"><table className="min-w-[850px] w-full text-left text-xs"><thead className="sticky top-0 bg-[#edf4ec]"><tr><th className="p-3">Row</th><th>Business</th><th>Contact</th><th>Classification</th><th>Match</th><th>Decision</th><th>Error</th></tr></thead><tbody>{preview.map((row,index)=><tr key={`${row.rowNumber}-${row.fingerprint}`} className="border-t"><td className="p-3">{row.rowNumber}</td><td className="font-bold">{row.values.company_name||"—"}</td><td>{row.values.business_email||row.values.business_phone||"—"}</td><td><span className="rounded-full bg-neutral-100 px-2 py-1 font-bold">{row.classification}</span></td><td>{prospects.find(p=>p.id===row.matchedProspectId)?.company_name||"—"}</td><td><select className={control} disabled={row.classification==="Invalid"} value={row.decision} onChange={e=>decide(index,e.target.value as ProspectImportDecision)}><option>Skip</option>{row.classification!=="Exact duplicate"&&<option>Import Separately</option>}{row.matchedProspectId&&<option>Merge</option>}</select></td><td className="text-red-700">{row.error||""}</td></tr>)}</tbody></table></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-neutral-600">{busy?`Processed ${progress} of ${preview.length}`:result?`Imported ${result.imported}; skipped ${result.skipped}; failed ${result.failed}.`:"Review every duplicate decision before importing."}</p><div className="flex gap-2">{result?<button type="button" onClick={completed} className="rounded-lg bg-[#143d1a] px-4 py-2.5 text-sm font-bold text-white">Done</button>:<button type="button" disabled={busy} onClick={()=>void run()} className="rounded-lg bg-[#143d1a] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy?"Importing…":"Import reviewed rows"}</button>}</div></div></section>}
  </section></div>;
}
