import "server-only";
import { createHash } from "node:crypto";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { decryptToken } from "./crypto";
import { buildEvent, deterministicEventId, uniqueAttendees, type CalendarJob } from "./event";

async function accessToken(refresh:string){const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:required("GOOGLE_CALENDAR_CLIENT_ID"),client_secret:required("GOOGLE_CALENDAR_CLIENT_SECRET"),refresh_token:refresh,grant_type:"refresh_token"})});const body=await response.json();if(!response.ok)throw new Error(body.error_description||"Google authorization refresh failed.");return body.access_token as string}
function required(name:string){const value=process.env[name];if(!value)throw new Error(`${name} is not configured.`);return value}
async function google(token:string,path:string,init?:RequestInit){const response=await fetch(`https://www.googleapis.com/calendar/v3${path}`,{...init,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...(init?.headers||{})}});if(response.status===204)return null;const body=await response.json();if(!response.ok)throw Object.assign(new Error(body?.error?.message||"Google Calendar request failed."),{status:response.status});return body}

export async function listOwnedCalendars(){const db=createSupabaseAdminClient();const {data,error}=await db.from("google_calendar_connections").select("encrypted_refresh_token").limit(1).single();if(error||!data?.encrypted_refresh_token)throw new Error("Google Calendar is not connected.");const body=await google(await accessToken(decryptToken(data.encrypted_refresh_token)),"/users/me/calendarList");return (body.items||[]).filter((x:{accessRole:string})=>x.accessRole==="owner").map((x:{id:string;summary:string;primary?:boolean})=>({id:x.id,name:x.summary,primary:Boolean(x.primary)}))}

export async function syncJobCalendar(jobId:string){const db=createSupabaseAdminClient();const {data:connection,error:ce}=await db.from("google_calendar_connections").select("*").limit(1).maybeSingle();if(ce||!connection?.encrypted_refresh_token||!connection.calendar_id)throw new Error("Google Calendar is not connected.");const {data:job,error:je}=await db.from("jobs").select("*, property:properties(*), crew:crews(*, crew_lead:employees!crews_crew_lead_id_fkey(*), members:crew_members(*, employee:employees!crew_members_employee_id_fkey(*)))").eq("id",jobId).single();if(je)throw je;
  const existing=(await db.from("job_calendar_syncs").select("*").eq("job_id",jobId).maybeSingle()).data;const token=await accessToken(decryptToken(connection.encrypted_refresh_token));const eventId=existing?.event_id||deterministicEventId(jobId);
  if(job.status==="Cancelled"&&connection.cancel_event_on_job_cancel){try{await google(token,`/calendars/${encodeURIComponent(connection.calendar_id)}/events/${eventId}?sendUpdates=${connection.send_tech_invites?"all":"none"}`,{method:"DELETE"})}catch(e){if((e as {status?:number}).status!==404)throw e}await db.from("job_calendar_syncs").upsert({job_id:jobId,connection_id:connection.id,calendar_id:connection.calendar_id,event_id:eventId,sync_status:"Cancelled",last_attempted_at:new Date().toISOString(),last_synced_at:new Date().toISOString(),last_sync_error:null},{onConflict:"job_id"});return {status:"Cancelled",warnings:[]}}
  if(!job.scheduled_date||!job.start_time){await db.from("job_calendar_syncs").upsert({job_id:jobId,connection_id:connection.id,sync_status:"Unscheduled",last_attempted_at:new Date().toISOString(),last_sync_error:null},{onConflict:"job_id"});return {status:"Unscheduled",warnings:[]}}
  const people=[job.crew?.crew_lead,...(job.crew?.members||[]).map((x:{employee:unknown})=>x.employee)].filter(Boolean) as Array<{email:string|null;first_name:string;last_name:string;employment_status:string;archived_at:string|null}>;const eligible=people.filter(x=>x.employment_status==="Active"&&!x.archived_at);const attendees=connection.send_tech_invites?uniqueAttendees(eligible.map(x=>x.email)):[];const warnings=eligible.filter(x=>!x.email).map(x=>`${x.first_name} ${x.last_name} has no email and was not invited.`);const settings=(await db.from("business_settings").select("timezone").limit(1).single()).data;if(!settings?.timezone)throw new Error("Set an IANA business timezone before syncing Calendar events.");const payload=buildEvent(job as CalendarJob,settings.timezone,connection.default_duration_minutes,attendees,process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000",job.crew?.crew_name);const hash=createHash("sha256").update(JSON.stringify(payload)).digest("hex");
  try{let remote;if(existing?.event_id){remote=await google(token,`/calendars/${encodeURIComponent(connection.calendar_id)}/events/${eventId}?sendUpdates=${connection.send_tech_invites?"all":"none"}`,{method:"PATCH",body:JSON.stringify(payload)})}else{try{remote=await google(token,`/calendars/${encodeURIComponent(connection.calendar_id)}/events?sendUpdates=${connection.send_tech_invites?"all":"none"}`,{method:"POST",body:JSON.stringify({...payload,id:eventId})})}catch(e){if((e as {status?:number}).status!==409)throw e;remote=await google(token,`/calendars/${encodeURIComponent(connection.calendar_id)}/events/${eventId}?sendUpdates=${connection.send_tech_invites?"all":"none"}`,{method:"PATCH",body:JSON.stringify(payload)})}}await db.from("job_calendar_syncs").upsert({job_id:jobId,connection_id:connection.id,calendar_id:connection.calendar_id,event_id:eventId,event_html_link:remote.htmlLink,sync_status:warnings.length?"Warning":"Synced",payload_hash:hash,attendee_warnings:warnings,last_attempted_at:new Date().toISOString(),last_synced_at:new Date().toISOString(),last_sync_error:null},{onConflict:"job_id"});return {status:warnings.length?"Warning":"Synced",warnings,eventUrl:remote.htmlLink}}
  catch(e){await db.from("job_calendar_syncs").upsert({job_id:jobId,connection_id:connection.id,calendar_id:connection.calendar_id,event_id:eventId,sync_status:"Failed",last_attempted_at:new Date().toISOString(),last_sync_error:e instanceof Error?e.message:"Google Calendar sync failed."},{onConflict:"job_id"});throw e}}
