begin;

create table public.employee_performance_reviews (
  id uuid primary key default gen_random_uuid(), employee_id uuid not null references public.employees(id) on delete restrict,
  review_period_days integer not null check (review_period_days in (30,90)), period_start date not null, period_end date not null check(period_end>=period_start),
  calculation_version text not null check(calculation_version='v1'), revision integer not null,
  status text not null default 'Draft' check(status in ('Draft','Finalized')),
  component_scores jsonb not null, evidence_snapshot jsonb not null,
  measured_points numeric not null, measured_max_points numeric not null,
  overall_score numeric check(overall_score between 0 and 100), quality_gate_triggered boolean not null default false,
  classification text not null check(classification in ('Measured','Evidence Limited','Quality Review Required','No Meaningful Participation')),
  calculated_at timestamptz not null default now(), calculated_by uuid not null references public.user_profiles(id),
  finalized_at timestamptz, finalized_by uuid references public.user_profiles(id), created_at timestamptz not null default now(),
  unique(employee_id,review_period_days,period_start,period_end,revision)
);
create index employee_performance_reviews_employee_idx on public.employee_performance_reviews(employee_id,period_end desc,revision desc);
alter table public.employee_performance_reviews enable row level security;
revoke all on public.employee_performance_reviews from public,anon,authenticated;
grant select on public.employee_performance_reviews to authenticated,service_role;
create policy "Managers or employee read performance reviews" on public.employee_performance_reviews for select to authenticated using(public.has_any_role(array['Master Admin','Administrator','Manager']) or (employee_id=public.current_employee_id() and status='Finalized'));

create function public.protect_finalized_employee_performance_review() returns trigger language plpgsql security definer set search_path='' as $$
begin if tg_op='DELETE' and old.status='Finalized' then raise exception 'Finalized performance reviews are immutable.'; end if;
 if tg_op='UPDATE' and old.status='Finalized' then raise exception 'Finalized performance reviews are immutable.'; end if; return case when tg_op='DELETE' then old else new end; end $$;
revoke all on function public.protect_finalized_employee_performance_review() from public,anon,authenticated;
create trigger protect_finalized_employee_performance_review before update or delete on public.employee_performance_reviews for each row execute function public.protect_finalized_employee_performance_review();

create function public.performance_component(p_points numeric,p_max numeric,p_count integer,p_state text,p_explanation text,p_evidence jsonb default '[]'::jsonb) returns jsonb language sql immutable set search_path='' as $$
 select jsonb_build_object('points',case when p_state='Measured' then round(greatest(0,least(p_points,p_max)),2) else null end,'maximum',p_max,'evidenceState',p_state,'evidenceCount',p_count,'explanation',p_explanation,'evidence',coalesce(p_evidence,'[]'::jsonb));
$$;
revoke all on function public.performance_component(numeric,numeric,integer,text,text,jsonb) from public,anon,authenticated;

create function public.calculate_employee_performance_review(p_employee_id uuid,p_period_days integer,p_period_end date default current_date)
returns public.employee_performance_reviews language plpgsql security definer set search_path='' as $$
declare
 start_date date; actor uuid:=auth.uid(); review public.employee_performance_reviews; revision_number integer;
 participation_count int; inspection_count int; inspection_total int; callback_count int; scope_count int; scope_total int; feedback_count int; labor_count int; attendance_count int; attendance_total int; compliance_count int; compliance_total int; teamwork_count int;
 inspection_points numeric; callback_points numeric; scope_points numeric; feedback_points numeric; labor_points numeric; attendance_points numeric; compliance_points numeric; teamwork_points numeric;
 quality_points numeric:=0; measured numeric:=0; measured_max numeric:=0; overall numeric; serious boolean:=false; all_measured boolean;
 inspection_ids jsonb; callback_ids jsonb; scope_ids jsonb; feedback_ids jsonb; labor_ids jsonb; attendance_ids jsonb; compliance_ids jsonb; teamwork_ids jsonb;
 components jsonb; evidence jsonb; inspection_state text; callback_state text; scope_state text; feedback_state text; quality_state text; labor_state text; attendance_state text; compliance_state text; teamwork_state text; final_class text;
begin
 if actor is null or not public.has_any_role(array['Master Admin','Administrator','Manager']) then raise exception 'Performance review management denied.' using errcode='42501'; end if;
 if p_period_days not in (30,90) or p_period_end is null then raise exception 'Review period must be 30 or 90 days.'; end if;
 if not exists(select 1 from public.employees e where e.id=p_employee_id and e.archived_at is null) then raise exception 'Employee is not available.'; end if;
 start_date:=p_period_end-(p_period_days-1);

 select count(distinct t.job_id) into participation_count from public.time_entries t join public.jobs j on j.id=t.job_id where t.employee_id=p_employee_id and t.entry_type='Job' and t.status in ('Completed','Approved') and t.archived_at is null and t.labor_classification='Production' and t.total_hours>0 and coalesce(j.completed_at,j.operational_ended_at)::date between start_date and p_period_end;
 if participation_count=0 then
  components:=jsonb_build_object('quality',public.performance_component(null,35,0,'Insufficient Evidence','No meaningful Production participation in this period.'),'laborEfficiency',public.performance_component(null,25,0,'Insufficient Evidence','No meaningful Production participation in this period.'),'attendance',public.performance_component(null,15,0,'Insufficient Evidence','No authoritative attendance evidence.'),'compliance',public.performance_component(null,15,0,'Insufficient Evidence','No compliance evidence.'),'teamwork',public.performance_component(null,10,0,'Insufficient Evidence','No teamwork evidence.'));
  select coalesce(max(r.revision),0)+1 into revision_number from public.employee_performance_reviews r where r.employee_id=p_employee_id and r.review_period_days=p_period_days and r.period_start=start_date and r.period_end=p_period_end;
  insert into public.employee_performance_reviews(employee_id,review_period_days,period_start,period_end,calculation_version,revision,component_scores,evidence_snapshot,measured_points,measured_max_points,overall_score,classification,calculated_by) values(p_employee_id,p_period_days,start_date,p_period_end,'v1',revision_number,components,jsonb_build_object('participatingJobCount',0),0,0,null,'No Meaningful Participation',actor) returning * into review; return review;
 end if;

 select count(*),avg(case i.result when 'Pass' then 1 when 'Needs Attention' then case i.severity when 'Minor' then .75 when 'Moderate' then .5 else .25 end when 'Fail' then case i.severity when 'Minor' then .5 when 'Moderate' then .25 else 0 end end)*15,
  coalesce(jsonb_agg(distinct q.quality_evidence_id),'[]'::jsonb),bool_or(i.severity='Major' and i.result in ('Needs Attention','Fail'))
 into inspection_count,inspection_points,inspection_ids,serious from public.job_quality_employee_attributions q join public.job_quality_inspections x on x.id=q.quality_evidence_id and q.quality_evidence_type='Inspection' and x.inspection_status='Finalized' join public.job_quality_inspection_items i on i.inspection_id=x.id join public.jobs j on j.id=q.job_id where q.active and q.attribution_target='Employee' and q.employee_id=p_employee_id and i.result<>'Not Applicable' and coalesce(j.completed_at,j.operational_ended_at)::date between start_date and p_period_end;
 serious:=coalesce(serious,false);
 select count(distinct q.quality_evidence_id) into inspection_total from public.job_quality_employee_attributions q join public.job_quality_inspections x on x.id=q.quality_evidence_id and q.quality_evidence_type='Inspection' and x.inspection_status='Finalized' join public.jobs j on j.id=q.job_id where q.active and q.attribution_target='Employee' and q.employee_id=p_employee_id and coalesce(j.completed_at,j.operational_ended_at)::date between start_date and p_period_end;
 inspection_state:=case when inspection_count>0 then 'Measured' when inspection_total>0 then 'Not Applicable' else 'Insufficient Evidence' end;

 select count(*),10-least(10,coalesce(sum(penalty),0)),coalesce(jsonb_agg(id),'[]'::jsonb),serious or coalesce(bool_or(severity='Major'),false)
 into callback_count,callback_points,callback_ids,serious from (select distinct c.id,c.severity,case c.severity when 'Minor' then 1 when 'Moderate' then 2 when 'Major' then 4 end penalty from public.job_quality_employee_attributions q join public.job_quality_callbacks c on c.id=q.quality_evidence_id and q.quality_evidence_type='Callback' join public.jobs j on j.id=q.job_id where q.active and q.attribution_target='Employee' and q.employee_id=p_employee_id and c.status<>'Invalid / Not Attributable' and c.attribution='Job Quality Attributable' and coalesce(j.completed_at,j.operational_ended_at)::date between start_date and p_period_end) callbacks;
 callback_state:=case when callback_count>0 then 'Measured' else 'Insufficient Evidence' end;

 select count(*),avg(case s.result when 'Complete' then 5 when 'Partially Complete' then 2.5 when 'Not Complete' then 0 end),coalesce(jsonb_agg(s.id),'[]'::jsonb),serious or coalesce(bool_or(s.result='Not Complete'),false)
 into scope_count,scope_points,scope_ids,serious from public.job_quality_employee_attributions q join public.job_scope_completion_records s on s.id=q.quality_evidence_id and q.quality_evidence_type='Scope Completion' join public.jobs j on j.id=q.job_id where q.active and q.attribution_target='Employee' and q.employee_id=p_employee_id and s.result<>'Not Applicable' and s.attribution='Job Execution' and coalesce(j.completed_at,j.operational_ended_at)::date between start_date and p_period_end;
 select count(*) into scope_total from public.job_quality_employee_attributions q join public.job_scope_completion_records s on s.id=q.quality_evidence_id and q.quality_evidence_type='Scope Completion' join public.jobs j on j.id=q.job_id where q.active and q.attribution_target='Employee' and q.employee_id=p_employee_id and coalesce(j.completed_at,j.operational_ended_at)::date between start_date and p_period_end;
 scope_state:=case when scope_count>0 then 'Measured' when scope_total>0 then 'Not Applicable' else 'Insufficient Evidence' end;

 select count(*),avg(job_rating)/5*5,coalesce(jsonb_agg(job_id),'[]'::jsonb) into feedback_count,feedback_points,feedback_ids from (select f.job_id,avg(f.rating) job_rating from public.job_quality_employee_attributions q join public.job_customer_feedback f on f.id=q.quality_evidence_id and q.quality_evidence_type='Customer Feedback' join public.jobs j on j.id=q.job_id where q.active and q.attribution_target='Employee' and q.employee_id=p_employee_id and coalesce(j.completed_at,j.operational_ended_at)::date between start_date and p_period_end group by f.job_id) rated;
 feedback_state:=case when feedback_count>0 then 'Measured' else 'Insufficient Evidence' end;
 quality_points:=coalesce(inspection_points,0)+coalesce(callback_points,0)+coalesce(scope_points,0)+coalesce(feedback_points,0); quality_state:=case when 'Insufficient Evidence' in (inspection_state,callback_state,scope_state,feedback_state) then 'Insufficient Evidence' when 'Measured' in (inspection_state,callback_state,scope_state,feedback_state) then 'Measured' else 'Not Applicable' end;

 with employee_jobs as (select t.job_id,sum(t.total_hours) employee_hours from public.time_entries t join public.jobs j on j.id=t.job_id where t.employee_id=p_employee_id and t.entry_type='Job' and t.status in ('Completed','Approved') and t.archived_at is null and t.labor_classification='Production' and coalesce(j.completed_at,j.operational_ended_at)::date between start_date and p_period_end group by t.job_id), ratios as (select ej.job_id,ej.employee_hours,sum(t.total_hours) filter(where t.labor_classification='Production') job_hours,greatest(s.budgeted_labor_hours+coalesce((select sum(a.labor_hours_delta) from public.job_labor_budget_adjustments a where a.job_id=ej.job_id),0),0) budget from employee_jobs ej join public.time_entries t on t.job_id=ej.job_id and t.entry_type='Job' and t.status in ('Completed','Approved') and t.archived_at is null join public.job_labor_budget_snapshots s on s.job_id=ej.job_id group by ej.job_id,ej.employee_hours,s.budgeted_labor_hours), scored as (select *,case when budget<=0 then null when job_hours/budget<=.90 then 25 when job_hours/budget<=1 then 24 when job_hours/budget<=1.10 then 21 when job_hours/budget<=1.25 then 17 when job_hours/budget<=1.50 then 10 when job_hours/budget<=2 then 5 else 0 end score from ratios)
 select count(*) filter(where score is not null),sum(score*employee_hours)/nullif(sum(employee_hours) filter(where score is not null),0),coalesce(jsonb_agg(job_id) filter(where score is not null),'[]'::jsonb) into labor_count,labor_points,labor_ids from scored;
 labor_state:=case when labor_count>0 then 'Measured' else 'Insufficient Evidence' end;

 with attendance as (select p.id,p.excused,p.current_status,coalesce((select e.metadata->>'latenessClass' from public.job_crew_presence_events e where e.presence_id=p.id and e.event_type='Arrival Confirmed' order by e.occurred_at desc limit 1),case when p.current_status in ('Present','Added After Start') then 'On Time' end) lateness from public.job_crew_presence p join public.jobs j on j.id=p.job_id where p.employee_id=p_employee_id and coalesce(j.completed_at,j.operational_ended_at)::date between start_date and p_period_end), scored as (select id,case when excused or current_status='Excused' then null when current_status in ('Absent','Absent - No Arrival','Needs Attendance Review') then 0 when current_status='Left Early' then .75 when lateness='On Time' then 1 when lateness='Minor Late' then .9 when lateness='Late' then .75 when lateness='Significant Late' then .5 else null end ratio from attendance)
 select count(*) filter(where ratio is not null),avg(ratio) filter(where ratio is not null)*15,coalesce(jsonb_agg(id) filter(where ratio is not null),'[]'::jsonb) into attendance_count,attendance_points,attendance_ids from scored;
 select count(*) into attendance_total from public.job_crew_presence p join public.jobs j on j.id=p.job_id where p.employee_id=p_employee_id and coalesce(j.completed_at,j.operational_ended_at)::date between start_date and p_period_end;
 attendance_state:=case when attendance_count>0 then 'Measured' when attendance_total>0 then 'Not Applicable' else 'Insufficient Evidence' end;

 select count(*),avg(case result when 'Compliant' then 15 when 'Non-Compliant' then 0 end),coalesce(jsonb_agg(id),'[]'::jsonb) into compliance_count,compliance_points,compliance_ids from public.job_compliance_records where employee_id=p_employee_id and ownership='Employee' and result in ('Compliant','Non-Compliant') and status='Finalized' and recorded_at::date between start_date and p_period_end;
 select count(*) into compliance_total from public.job_compliance_records where employee_id=p_employee_id and ownership='Employee' and status='Finalized' and recorded_at::date between start_date and p_period_end;
 compliance_state:=case when compliance_count>0 then 'Measured' when compliance_total>0 then 'Not Applicable' else 'Insufficient Evidence' end;

 select count(*),greatest(0,least(10,5+least(5,count(*) filter(where direction='Positive'))-least(5,2*count(*) filter(where direction='Concern')))),coalesce(jsonb_agg(id),'[]'::jsonb) into teamwork_count,teamwork_points,teamwork_ids from public.employee_teamwork_events where employee_id=p_employee_id and occurred_at::date between start_date and p_period_end;
 teamwork_state:=case when teamwork_count>0 then 'Measured' else 'Insufficient Evidence' end;

 components:=jsonb_build_object('quality',public.performance_component(quality_points,35,inspection_count+callback_count+scope_count+feedback_count,quality_state,'Inspection 15 + Callbacks 10 + Scope 5 + Feedback 5.',jsonb_build_object('inspection',public.performance_component(inspection_points,15,inspection_count,inspection_state,'Finalized explicitly attributed inspection items.',inspection_ids),'callbacks',public.performance_component(callback_points,10,callback_count,callback_state,'Valid explicitly attributed callbacks; unique penalties Minor 1, Moderate 2, Major 4.',callback_ids),'scopeCompletion',public.performance_component(scope_points,5,scope_count,scope_state,'Explicitly attributed Job Execution scope results.',scope_ids),'customerFeedback',public.performance_component(feedback_points,5,feedback_count,feedback_state,'Explicitly attributed ratings averaged once per Job.',feedback_ids))),'laborEfficiency',public.performance_component(labor_points,25,labor_count,labor_state,'Production labor only; Approved Exception time excluded. Weighted by employee Production hours.',labor_ids),'attendance',public.performance_component(attendance_points,15,attendance_count,attendance_state,'Authoritative presence and arrival evidence; excused records excluded.',attendance_ids),'compliance',public.performance_component(compliance_points,15,compliance_count,compliance_state,'Finalized employee-owned evidence; Excused/N/A/external/management/shared excluded.',compliance_ids),'teamwork',public.performance_component(teamwork_points,10,teamwork_count,teamwork_state,'Bounded documented events; disputed events remain marked in the snapshot.',teamwork_ids));
 if quality_state='Measured' then measured:=measured+quality_points;measured_max:=measured_max+35;end if; if labor_state='Measured' then measured:=measured+labor_points;measured_max:=measured_max+25;end if; if attendance_state='Measured' then measured:=measured+attendance_points;measured_max:=measured_max+15;end if; if compliance_state='Measured' then measured:=measured+compliance_points;measured_max:=measured_max+15;end if; if teamwork_state='Measured' then measured:=measured+teamwork_points;measured_max:=measured_max+10;end if;
 all_measured:=quality_state='Measured' and labor_state='Measured' and attendance_state='Measured' and compliance_state='Measured' and teamwork_state='Measured'; overall:=case when all_measured then round(measured,2) else null end; final_class:=case when serious then 'Quality Review Required' when all_measured then 'Measured' else 'Evidence Limited' end;
 evidence:=jsonb_build_object('participatingJobCount',participation_count,'inspectionIds',inspection_ids,'callbackIds',callback_ids,'scopeIds',scope_ids,'feedbackJobIds',feedback_ids,'laborJobIds',labor_ids,'attendancePresenceIds',attendance_ids,'complianceIds',compliance_ids,'teamworkIds',teamwork_ids,'disputedTeamworkCount',(select count(*) from public.employee_teamwork_events t where t.employee_id=p_employee_id and t.acknowledgement_state='Disputed' and t.occurred_at::date between start_date and p_period_end));
 select coalesce(max(r.revision),0)+1 into revision_number from public.employee_performance_reviews r where r.employee_id=p_employee_id and r.review_period_days=p_period_days and r.period_start=start_date and r.period_end=p_period_end;
 insert into public.employee_performance_reviews(employee_id,review_period_days,period_start,period_end,calculation_version,revision,component_scores,evidence_snapshot,measured_points,measured_max_points,overall_score,quality_gate_triggered,classification,calculated_by) values(p_employee_id,p_period_days,start_date,p_period_end,'v1',revision_number,components,evidence,round(measured,2),measured_max,overall,serious,final_class,actor) returning * into review; return review;
end $$;

create function public.finalize_employee_performance_review(p_review_id uuid) returns public.employee_performance_reviews language plpgsql security definer set search_path='' as $$
declare r public.employee_performance_reviews; begin if auth.uid() is null or not public.has_any_role(array['Master Admin','Administrator','Manager']) then raise exception 'Performance review finalization denied.' using errcode='42501'; end if; select * into r from public.employee_performance_reviews where id=p_review_id for update; if not found or r.status<>'Draft' then raise exception 'Only a Draft review may be finalized.'; end if; update public.employee_performance_reviews set status='Finalized',finalized_at=now(),finalized_by=auth.uid() where id=r.id returning * into r; return r; end $$;
create function public.get_employee_performance_reviews(p_employee_id uuid default null) returns setof public.employee_performance_reviews language plpgsql stable security definer set search_path='' as $$
declare target uuid:=coalesce(p_employee_id,public.current_employee_id()); begin if auth.uid() is null or target is null then raise exception 'Performance review access denied.' using errcode='42501'; end if; if not public.has_any_role(array['Master Admin','Administrator','Manager']) and target<>public.current_employee_id() then raise exception 'Performance review access denied.' using errcode='42501'; end if; return query select r.* from public.employee_performance_reviews r where r.employee_id=target and (public.has_any_role(array['Master Admin','Administrator','Manager']) or r.status='Finalized') order by r.period_end desc,r.revision desc; end $$;

revoke all on function public.calculate_employee_performance_review(uuid,integer,date),public.finalize_employee_performance_review(uuid),public.get_employee_performance_reviews(uuid) from public,anon,authenticated;
grant execute on function public.calculate_employee_performance_review(uuid,integer,date),public.finalize_employee_performance_review(uuid),public.get_employee_performance_reviews(uuid) to authenticated;
notify pgrst,'reload schema'; commit;
