begin;
alter function public.get_assigned_field_walkthroughs() rename to get_assigned_field_walkthroughs_barber_phase_20260928;
revoke all on function public.get_assigned_field_walkthroughs_barber_phase_20260928() from public,anon,authenticated;
create function public.get_assigned_field_walkthroughs() returns jsonb language sql stable security definer set search_path='' as $function$
with p as(select x.value,x.ordinality from jsonb_array_elements(public.get_assigned_field_walkthroughs_barber_phase_20260928()) with ordinality x(value,ordinality)) select coalesce(jsonb_agg(p.value||jsonb_build_object('measurements',coalesce(p.value->'measurements','{}'::jsonb)||jsonb_build_object('retailCleaningAssessment',jsonb_build_object('fieldWalkthrough',w.measurements->'retailCleaningAssessment'->'fieldWalkthrough'))) order by p.ordinality),'[]'::jsonb) from p join public.walkthroughs w on w.id=(p.value->>'id')::uuid;
$function$;
alter function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean) rename to submit_assigned_field_walkthrough_barber_phase_20260928;
revoke all on function public.submit_assigned_field_walkthrough_barber_phase_20260928(uuid,jsonb,boolean) from public,anon,authenticated;
create function public.submit_assigned_field_walkthrough(p_id uuid,p_measurements jsonb,p_complete boolean default false) returns void language plpgsql security definer set search_path='' as $function$
declare w public.walkthroughs;e uuid:=public.current_employee_id();n jsonb:=p_measurements;f jsonb;a jsonb;old jsonb;k text;v jsonb;r text;i integer;
begin
 if jsonb_typeof(n#>'{retailCleaningAssessment,fieldWalkthrough}')='null' then n:=n-'retailCleaningAssessment';end if;
 if not n?'retailCleaningAssessment' then perform public.submit_assigned_field_walkthrough_barber_phase_20260928(p_id,n,p_complete);return;end if;
 if (select auth.uid()) is null or e is null or not public.has_any_role(array['Crew Lead','Scrub Technician']) then raise exception 'Field access denied' using errcode='42501';end if;
 select * into w from public.walkthroughs where id=p_id for update;
 if not found or w.status<>'Scheduled' or w.archived_at is not null or w.assigned_employee_id is distinct from e or w.walkthrough_date is null or w.walkthrough_time is null then raise exception 'Scheduled assignment no longer available';end if;
 if coalesce(w.measurements->>'serviceType','')<>'Retail Cleaning' then raise exception 'Retail observations require COM-RETAIL';end if;
 f:=n->'retailCleaningAssessment'->'fieldWalkthrough';a:=f->'answers';
 if jsonb_typeof(n->'retailCleaningAssessment')<>'object' or jsonb_typeof(f)<>'object' or jsonb_typeof(a)<>'object' or exists(select 1 from jsonb_object_keys(n->'retailCleaningAssessment') x where x<>'fieldWalkthrough') or exists(select 1 from jsonb_object_keys(f) x where x<>'answers') then raise exception 'Invalid Retail Cleaning field walkthrough';end if;
 for k,v in select * from jsonb_each(a) loop
  if not k=any(array['retailType','retailTypeOther','operatingStatus','occupancyLimits','occupancyNotes','overallCondition','salesFloorCondition','salesTraffic','salesDust','salesSticky','salesMerchandise','salesFixtures','salesHighTouch','salesAccessNotes','displayCondition','displayObservation1','displayObservation2','displayObservation3','displayObservation4','displayObservation5','checkoutCondition','checkoutObservation1','checkoutObservation2','checkoutObservation3','checkoutObservation4','checkoutObservation5','fittingCondition','fittingObservation1','fittingObservation2','fittingObservation3','fittingObservation4','fittingObservation5','fittingObservation6','entryCondition','entryGlass','entryDoor','entryFloor','exteriorGlassScope','entrySmudging','entryAccess','entryAccessNotes','stockroomCondition','stockroomObservation1','stockroomObservation2','stockroomObservation3','stockroomObservation4','stockroomObservation5','stockroomNotes','restroomCondition','restroomObservation1','restroomObservation2','restroomObservation3','restroomObservation4','restroomObservation5','restroomObservation6','breakroomCondition','breakroomObservation1','breakroomObservation2','breakroomObservation3','breakroomObservation4','breakroomObservation5','breakroomObservation6','flooring','floorTraffic','floorStaining','floorSticky','floorScuffing','floorPrecautions','floorNotes','glassTypes','glassHeavy','glassAdhesive','glassAccess','glassNotes','trashCondition','multipleReceptacles','cardboard','packagingWaste','largeReceptacles','restrictedWaste','wasteNotes','highTouchAreas','specialPrecautions','precautionTypes','precautionNotes','extraAttention','frequencyObservation','frequencyNotes','serviceSuitable','recommendedServices','serviceNotes','laborLevel','recommendedCrew','serviceDuration','materialException','exceptionNotes','technicianConfirmation']) then raise exception 'Invalid Retail Cleaning answer: %',k;end if;
  if jsonb_typeof(v)='string' and length(v#>>'{}')>5000 then raise exception 'Retail answer is too long: %',k;end if;
  if jsonb_typeof(v)='array' and (jsonb_array_length(v)>20 or exists(select 1 from jsonb_array_elements(v)x where jsonb_typeof(x)<>'string' or length(x#>>'{}')>200)) then raise exception 'Invalid Retail selection: %',k;end if;
  if jsonb_typeof(v) not in('string','array','boolean','null') then raise exception 'Invalid Retail answer type: %',k;end if;
 end loop;
 if p_complete then
  foreach r in array array['retailType','operatingStatus','overallCondition','salesFloorCondition','salesTraffic','salesDust','salesSticky','salesMerchandise','salesFixtures','salesHighTouch','displayCondition','checkoutCondition','fittingCondition','entryCondition','entryGlass','entryDoor','entryFloor','exteriorGlassScope','entrySmudging','entryAccess','stockroomCondition','restroomCondition','breakroomCondition','flooring','floorTraffic','floorStaining','floorSticky','floorScuffing','floorPrecautions','glassTypes','glassHeavy','glassAdhesive','glassAccess','trashCondition','multipleReceptacles','cardboard','packagingWaste','largeReceptacles','restrictedWaste','highTouchAreas','specialPrecautions','extraAttention','frequencyObservation','serviceSuitable','laborLevel','recommendedCrew','serviceDuration','materialException'] loop if not a?r or a->r in('null'::jsonb,'""'::jsonb,'[]'::jsonb) then raise exception 'Required Retail answer is missing: %',r;end if;end loop;
  foreach k in array array['display','checkout','fitting','stockroom','restroom','breakroom'] loop if a->>(k||'Condition')<>'Not applicable' then for i in 1..case when k in('fitting','restroom','breakroom') then 6 else 5 end loop if nullif(btrim(a->>(k||'Observation'||i)),'') is null then raise exception 'Required % observation is missing',k;end if;end loop;end if;end loop;
  if a->>'retailType'='Other' and nullif(btrim(a->>'retailTypeOther'),'') is null then raise exception 'Other retail type is required';end if;
  if a->>'operatingStatus'<>'Closed/vacant' and nullif(btrim(a->>'occupancyLimits'),'') is null then raise exception 'Occupancy limitation answer is required';end if;
  if a->>'occupancyLimits'='Yes' and nullif(btrim(a->>'occupancyNotes'),'') is null then raise exception 'Occupancy notes are required';end if;
  if (a->>'salesMerchandise'='Yes' or a->>'salesFixtures'='Yes') and nullif(btrim(a->>'salesAccessNotes'),'') is null then raise exception 'Sales access notes are required';end if;
  if a->>'entryAccess'='Yes' and nullif(btrim(a->>'entryAccessNotes'),'') is null then raise exception 'Entry access notes are required';end if;
  if (a->>'stockroomObservation1'='Yes' or a->>'stockroomObservation5'='Yes') and nullif(btrim(a->>'stockroomNotes'),'') is null then raise exception 'Stockroom notes are required';end if;
  if (a->'flooring'?'Other' or a->>'floorTraffic'='Yes' or a->>'floorStaining'='Yes' or a->>'floorSticky'='Yes' or a->>'floorScuffing'='Yes' or a->>'floorPrecautions'='Yes') and nullif(btrim(a->>'floorNotes'),'') is null then raise exception 'Floor notes are required';end if;
  if a->>'glassAccess'='Yes' and nullif(btrim(a->>'glassNotes'),'') is null then raise exception 'Glass notes are required';end if;
  if a->>'restrictedWaste'='Yes' and nullif(btrim(a->>'wasteNotes'),'') is null then raise exception 'Waste notes are required';end if;
  if a->>'specialPrecautions'='Yes' and (a->'precautionTypes' is null or a->'precautionTypes'='[]'::jsonb or nullif(btrim(a->>'precautionNotes'),'') is null) then raise exception 'Precaution details are required';end if;
  if a->>'frequencyObservation'<>'Scheduled frequency appears appropriate' and nullif(btrim(a->>'frequencyNotes'),'') is null then raise exception 'Frequency notes are required';end if;
  if a->>'serviceSuitable'='Additional service may be required' and (a->'recommendedServices' is null or a->'recommendedServices'='[]'::jsonb) then raise exception 'Recommended services are required';end if;
  if a->>'serviceSuitable'<>'Yes — Retail Cleaning appears appropriate' and nullif(btrim(a->>'serviceNotes'),'') is null then raise exception 'Service notes are required';end if;
  if a->>'materialException'='Yes' and nullif(btrim(a->>'exceptionNotes'),'') is null then raise exception 'Exception notes are required';end if;
  if a->'technicianConfirmation' is distinct from'true'::jsonb then raise exception 'Final technician confirmation is required';end if;
 end if;
 perform public.submit_assigned_field_walkthrough_barber_phase_20260928(p_id,n-'retailCleaningAssessment',p_complete);old:=coalesce(w.measurements->'retailCleaningAssessment','{}'::jsonb);update public.walkthroughs set measurements=jsonb_set(measurements,'{retailCleaningAssessment}',jsonb_set(old,'{fieldWalkthrough}',f,true),true)where id=p_id;
end;$function$;
revoke all on function public.get_assigned_field_walkthroughs() from public,anon,authenticated;revoke all on function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean) from public,anon,authenticated;grant execute on function public.get_assigned_field_walkthroughs() to authenticated;grant execute on function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean) to authenticated;notify pgrst,'reload schema';commit;
