begin;
alter function public.get_assigned_field_walkthroughs() rename to get_assigned_field_walkthroughs_retail_phase_20260928;
revoke all on function public.get_assigned_field_walkthroughs_retail_phase_20260928() from public,anon,authenticated;
create function public.get_assigned_field_walkthroughs() returns jsonb language sql stable security definer set search_path='' as $function$
with p as(select x.value,x.ordinality from jsonb_array_elements(public.get_assigned_field_walkthroughs_retail_phase_20260928())with ordinality x(value,ordinality))select coalesce(jsonb_agg(p.value||jsonb_build_object('measurements',coalesce(p.value->'measurements','{}'::jsonb)||jsonb_build_object('eventVenueCleaningAssessment',jsonb_build_object('fieldWalkthrough',w.measurements->'eventVenueCleaningAssessment'->'fieldWalkthrough')))order by p.ordinality),'[]'::jsonb)from p join public.walkthroughs w on w.id=(p.value->>'id')::uuid;
$function$;
alter function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean) rename to submit_assigned_field_walkthrough_retail_phase_20260928;
revoke all on function public.submit_assigned_field_walkthrough_retail_phase_20260928(uuid,jsonb,boolean) from public,anon,authenticated;
create function public.submit_assigned_field_walkthrough(p_id uuid,p_measurements jsonb,p_complete boolean default false)returns void language plpgsql security definer set search_path='' as $function$
declare w public.walkthroughs;e uuid:=public.current_employee_id();n jsonb:=p_measurements;f jsonb;a jsonb;old jsonb;k text;v jsonb;r text;i integer;
begin
 if jsonb_typeof(n#>'{eventVenueCleaningAssessment,fieldWalkthrough}')='null' then n:=n-'eventVenueCleaningAssessment';end if;if not n?'eventVenueCleaningAssessment' then perform public.submit_assigned_field_walkthrough_retail_phase_20260928(p_id,n,p_complete);return;end if;
 if(select auth.uid())is null or e is null or not public.has_any_role(array['Crew Lead','Scrub Technician'])then raise exception'Field access denied'using errcode='42501';end if;select * into w from public.walkthroughs where id=p_id for update;if not found or w.status<>'Scheduled' or w.archived_at is not null or w.assigned_employee_id is distinct from e or w.walkthrough_date is null or w.walkthrough_time is null then raise exception'Scheduled assignment no longer available';end if;if coalesce(w.measurements->>'serviceType','')<>'Event Venue Cleaning' then raise exception'Event Venue observations require COM-EVENT';end if;
 f:=n->'eventVenueCleaningAssessment'->'fieldWalkthrough';a:=f->'answers';if jsonb_typeof(n->'eventVenueCleaningAssessment')<>'object' or jsonb_typeof(f)<>'object' or jsonb_typeof(a)<>'object' or exists(select 1 from jsonb_object_keys(n->'eventVenueCleaningAssessment')x where x<>'fieldWalkthrough')or exists(select 1 from jsonb_object_keys(f)x where x<>'answers')then raise exception'Invalid Event Venue field walkthrough';end if;
 for k,v in select * from jsonb_each(a)loop
  if not k=any(array['venueType','venueTypeOther','cleaningPhase','phaseNotes','venueStatus','activityLimits','activityNotes','overallCondition','mainCondition','mainFurniture','mainDebris','mainResidue','mainDecor','mainEquipment','mainHighTouch','mainNotes','seatingCondition','seatingObservation1','seatingObservation2','seatingObservation3','seatingObservation4','seatingObservation5','foodCondition','foodObservation1','foodObservation2','foodObservation3','foodObservation4','foodObservation5','foodObservation6','barCondition','barObservation1','barObservation2','barObservation3','barObservation4','barObservation5','barObservation6','restroomCondition','restroomUsage','restroomToilet','restroomFixture','restroomFloor','restroomTrash','restroomOdor','restroomSupplies','mildewLikeBuildup','flooring','floorDebris','floorSpills','floorSticky','floorStaining','floorPrecautions','floorNotes','stageCondition','stageObservation1','stageObservation2','stageObservation3','stageObservation4','stageObservation5','stageNotes','backstageCondition','backstageObservation1','backstageObservation2','backstageObservation3','backstageObservation4','backstageObservation5','entryCondition','entryObservation1','entryObservation2','entryObservation3','entryObservation4','entryObservation5','outdoorCondition','outdoorObservation1','outdoorObservation2','outdoorObservation3','outdoorObservation4','outdoorObservation5','outdoorObservation6','wasteVolume','wastePoints','largeReceptacles','wasteOverflow','foodWaste','brokenGlass','restrictedWaste','dumpsterAccess','wasteNotes','glassTypes','glassPrints','glassResidue','glassAdhesive','glassAccess','decorations','signage','adhesive','confetti','balloons','vendorBelongings','specialPrecautions','precautionTypes','precautionNotes','extraAttention','hasDeadline','deadlineNotes','serviceSuitable','recommendedServices','serviceNotes','laborLevel','recommendedCrew','serviceDuration','materialException','exceptionNotes','technicianConfirmation'])then raise exception'Invalid Event Venue answer: %',k;end if;if jsonb_typeof(v)='string'and length(v#>>'{}')>5000 then raise exception'Event Venue answer is too long: %',k;end if;if jsonb_typeof(v)='array'and(jsonb_array_length(v)>20 or exists(select 1 from jsonb_array_elements(v)x where jsonb_typeof(x)<>'string'or length(x#>>'{}')>200))then raise exception'Invalid Event Venue selection: %',k;end if;if jsonb_typeof(v)not in('string','array','boolean','null')then raise exception'Invalid Event Venue answer type: %',k;end if;end loop;
 if p_complete then
  foreach r in array array['venueType','cleaningPhase','venueStatus','overallCondition','mainCondition','mainFurniture','mainDebris','mainResidue','mainDecor','mainEquipment','mainHighTouch','seatingCondition','foodCondition','barCondition','restroomCondition','restroomUsage','restroomToilet','restroomFixture','restroomFloor','restroomTrash','restroomOdor','restroomSupplies','mildewLikeBuildup','flooring','floorDebris','floorSpills','floorSticky','floorStaining','floorPrecautions','stageCondition','backstageCondition','entryCondition','outdoorCondition','wasteVolume','wastePoints','largeReceptacles','wasteOverflow','foodWaste','brokenGlass','restrictedWaste','dumpsterAccess','glassTypes','glassPrints','glassResidue','glassAdhesive','glassAccess','decorations','signage','adhesive','confetti','balloons','vendorBelongings','specialPrecautions','extraAttention','hasDeadline','serviceSuitable','laborLevel','recommendedCrew','serviceDuration','materialException']loop if not a?r or a->r in('null'::jsonb,'""'::jsonb,'[]'::jsonb)then raise exception'Required Event Venue answer is missing: %',r;end if;end loop;
  foreach k in array array['seating','food','bar','stage','backstage','entry','outdoor']loop if a->>(k||'Condition')<>'Not applicable'then for i in 1..case when k in('food','bar','outdoor')then 6 else 5 end loop if nullif(btrim(a->>(k||'Observation'||i)),'')is null then raise exception'Required % observation is missing',k;end if;end loop;end if;end loop;
  if a->>'venueType'='Other'and nullif(btrim(a->>'venueTypeOther'),'')is null then raise exception'Other venue type is required';end if;if a->>'cleaningPhase'='Multiple phases'and nullif(btrim(a->>'phaseNotes'),'')is null then raise exception'Phase notes are required';end if;if a->>'venueStatus'<>'Empty'and nullif(btrim(a->>'activityLimits'),'')is null then raise exception'Activity limitation answer is required';end if;if a->>'activityLimits'='Yes'and nullif(btrim(a->>'activityNotes'),'')is null then raise exception'Activity notes are required';end if;if(a->>'mainDecor'='Yes'or a->>'mainEquipment'='Yes')and nullif(btrim(a->>'mainNotes'),'')is null then raise exception'Main-area access notes are required';end if;
  if(a->'flooring'?'Other'or a->>'floorDebris'='Yes'or a->>'floorSpills'='Yes'or a->>'floorSticky'='Yes'or a->>'floorStaining'='Yes'or a->>'floorPrecautions'='Yes')and nullif(btrim(a->>'floorNotes'),'')is null then raise exception'Floor notes are required';end if;if exists(select 1 from generate_series(1,5)x where a->>('stageObservation'||x)='Yes')and nullif(btrim(a->>'stageNotes'),'')is null then raise exception'Stage notes are required';end if;if a->>'restrictedWaste'='Yes'and nullif(btrim(a->>'wasteNotes'),'')is null then raise exception'Waste notes are required';end if;if a->>'specialPrecautions'='Yes'and(a->'precautionTypes'is null or a->'precautionTypes'='[]'::jsonb or nullif(btrim(a->>'precautionNotes'),'')is null)then raise exception'Precaution details are required';end if;if a->>'hasDeadline'='Yes'and nullif(btrim(a->>'deadlineNotes'),'')is null then raise exception'Deadline notes are required';end if;if a->>'serviceSuitable'='Additional service may be required'and(a->'recommendedServices'is null or a->'recommendedServices'='[]'::jsonb)then raise exception'Recommended services are required';end if;if a->>'serviceSuitable'<>'Yes — Event Venue Cleaning appears appropriate'and nullif(btrim(a->>'serviceNotes'),'')is null then raise exception'Service notes are required';end if;if a->>'materialException'='Yes'and nullif(btrim(a->>'exceptionNotes'),'')is null then raise exception'Exception notes are required';end if;if a->'technicianConfirmation'is distinct from'true'::jsonb then raise exception'Final technician confirmation is required';end if;
 end if;
 perform public.submit_assigned_field_walkthrough_retail_phase_20260928(p_id,n-'eventVenueCleaningAssessment',p_complete);old:=coalesce(w.measurements->'eventVenueCleaningAssessment','{}'::jsonb);update public.walkthroughs set measurements=jsonb_set(measurements,'{eventVenueCleaningAssessment}',jsonb_set(old,'{fieldWalkthrough}',f,true),true)where id=p_id;
end;$function$;
revoke all on function public.get_assigned_field_walkthroughs()from public,anon,authenticated;revoke all on function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean)from public,anon,authenticated;grant execute on function public.get_assigned_field_walkthroughs()to authenticated;grant execute on function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean)to authenticated;notify pgrst,'reload schema';commit;
