begin;
alter function public.get_assigned_field_walkthroughs() rename to get_assigned_field_walkthroughs_warehouse_phase_20260928;
revoke all on function public.get_assigned_field_walkthroughs_warehouse_phase_20260928() from public,anon,authenticated;
create function public.get_assigned_field_walkthroughs()returns jsonb language sql stable security definer set search_path=''as $function$ with p as(select x.value,x.ordinality from jsonb_array_elements(public.get_assigned_field_walkthroughs_warehouse_phase_20260928())with ordinality x(value,ordinality))select coalesce(jsonb_agg(p.value||jsonb_build_object('measurements',coalesce(p.value->'measurements','{}'::jsonb)||jsonb_build_object('restaurantCleaningAssessment',jsonb_build_object('fieldWalkthrough',w.measurements->'restaurantCleaningAssessment'->'fieldWalkthrough')))order by p.ordinality),'[]'::jsonb)from p join public.walkthroughs w on w.id=(p.value->>'id')::uuid;$function$;
alter function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean)rename to submit_assigned_field_walkthrough_warehouse_phase_20260928;
revoke all on function public.submit_assigned_field_walkthrough_warehouse_phase_20260928(uuid,jsonb,boolean)from public,anon,authenticated;
create function public.submit_assigned_field_walkthrough(p_id uuid,p_measurements jsonb,p_complete boolean default false)returns void language plpgsql security definer set search_path=''as $function$
declare w public.walkthroughs;e uuid:=public.current_employee_id();n jsonb:=p_measurements;f jsonb;a jsonb;old jsonb;k text;v jsonb;r text;
begin
if jsonb_typeof(n#>'{restaurantCleaningAssessment,fieldWalkthrough}')='null'then n:=n-'restaurantCleaningAssessment';end if;if not n?'restaurantCleaningAssessment'then perform public.submit_assigned_field_walkthrough_warehouse_phase_20260928(p_id,n,p_complete);return;end if;if(select auth.uid())is null or e is null or not public.has_any_role(array['Crew Lead','Scrub Technician'])then raise exception'Field access denied'using errcode='42501';end if;select * into w from public.walkthroughs where id=p_id for update;if not found or w.status<>'Scheduled'or w.archived_at is not null or w.assigned_employee_id is distinct from e or w.walkthrough_date is null or w.walkthrough_time is null then raise exception'Scheduled assignment no longer available';end if;if coalesce(w.measurements->>'serviceType','')<>'Restaurant Cleaning'then raise exception'Restaurant observations require COM-RESTAURANT';end if;
f:=n->'restaurantCleaningAssessment'->'fieldWalkthrough';a:=f->'answers';if jsonb_typeof(n->'restaurantCleaningAssessment')<>'object'or jsonb_typeof(f)<>'object'or jsonb_typeof(a)<>'object'or exists(select 1 from jsonb_object_keys(n->'restaurantCleaningAssessment')x where x<>'fieldWalkthrough')or exists(select 1 from jsonb_object_keys(f)x where x<>'answers')then raise exception'Invalid Restaurant field walkthrough';end if;
for k,v in select * from jsonb_each(a)loop if k!~'^(restaurantType|restaurantTypeOther|operatingStatus|operationLimits|operationNotes|overallCondition|dining(Condition|Observation[1-6])|kitchen(Condition|Observation[1-8])|cooking(Condition|Observation[1-5])|hoodObservation|dish(Condition|Observation[1-6])|bar(Condition|Observation[1-6])|diningFlooring|diningFloor(Debris|Sticky|Grease|Staining|Traffic|Precautions|Notes)|backFloor(Condition|Observation[1-6]|Notes)|restroom(Condition|Observation[1-7])|entry(Condition|Observation[1-6])|glassTypes|glass(Prints|Residue|Grease|Access|Notes)|foodWasteLevel|wastePoints|foodHeavyWaste|leakingWaste|largeReceptacles|dumpsterAccess|trashBuildup|restrictedWaste|dumpster(Condition|Observation[1-7])|storage(Condition|Observation[1-5])|coldStorage(Scope|Condition)|cold(Floor|Spills|Shelving|Access)|specialPrecautions|precautionTypes|precautionNotes|extraAttention|frequencyObservation|frequencyNotes|serviceSuitable|recommendedServices|serviceNotes|laborLevel|recommendedCrew|serviceDuration|materialException|exceptionNotes|technicianConfirmation)$'then raise exception'Invalid Restaurant answer: %',k;end if;if jsonb_typeof(v)='string'and length(v#>>'{}')>5000 then raise exception'Restaurant answer is too long: %',k;end if;if jsonb_typeof(v)='array'and(jsonb_array_length(v)>20 or exists(select 1 from jsonb_array_elements(v)x where jsonb_typeof(x)<>'string'or length(x#>>'{}')>200))then raise exception'Invalid Restaurant selection: %',k;end if;if jsonb_typeof(v)not in('string','array','boolean','null')then raise exception'Invalid Restaurant answer type: %',k;end if;end loop;
if p_complete then foreach r in array array['restaurantType','operatingStatus','overallCondition','diningCondition','kitchenCondition','cookingCondition','hoodObservation','dishCondition','barCondition','diningFlooring','backFloorCondition','restroomCondition','entryCondition','glassTypes','foodWasteLevel','dumpsterCondition','storageCondition','coldStorageScope','specialPrecautions','extraAttention','frequencyObservation','serviceSuitable','laborLevel','recommendedCrew','serviceDuration','materialException']loop if not a?r or a->r in('null'::jsonb,'""'::jsonb,'[]'::jsonb)then raise exception'Required Restaurant answer is missing: %',r;end if;end loop;if a->>'restaurantType'='Other'and nullif(btrim(a->>'restaurantTypeOther'),'')is null then raise exception'Other restaurant type is required';end if;if a->>'operatingStatus'<>'Closed/vacant'and nullif(btrim(a->>'operationLimits'),'')is null then raise exception'Operation limitation answer is required';end if;if a->>'operationLimits'='Yes'and nullif(btrim(a->>'operationNotes'),'')is null then raise exception'Operation notes are required';end if;if a->>'coldStorageScope'='In scope'and nullif(btrim(a->>'coldStorageCondition'),'')is null then raise exception'Cold-storage condition is required';end if;if a->>'specialPrecautions'='Yes'and(a->'precautionTypes'is null or a->'precautionTypes'='[]'::jsonb or nullif(btrim(a->>'precautionNotes'),'')is null)then raise exception'Precaution details are required';end if;if a->>'frequencyObservation'<>'Scheduled frequency appears appropriate'and nullif(btrim(a->>'frequencyNotes'),'')is null then raise exception'Frequency notes are required';end if;if a->>'serviceSuitable'='Additional service may be required'and(a->'recommendedServices'is null or a->'recommendedServices'='[]'::jsonb)then raise exception'Recommended services are required';end if;if a->>'serviceSuitable'<>'Yes — Restaurant Cleaning appears appropriate'and nullif(btrim(a->>'serviceNotes'),'')is null then raise exception'Service notes are required';end if;if a->>'materialException'='Yes'and nullif(btrim(a->>'exceptionNotes'),'')is null then raise exception'Exception notes are required';end if;if a->'technicianConfirmation'is distinct from'true'::jsonb then raise exception'Final technician confirmation is required';end if;end if;
perform public.submit_assigned_field_walkthrough_warehouse_phase_20260928(p_id,n-'restaurantCleaningAssessment',p_complete);old:=coalesce(w.measurements->'restaurantCleaningAssessment','{}'::jsonb);update public.walkthroughs set measurements=jsonb_set(measurements,'{restaurantCleaningAssessment}',jsonb_set(old,'{fieldWalkthrough}',f,true),true)where id=p_id;end;$function$;
revoke all on function public.get_assigned_field_walkthroughs()from public,anon,authenticated;revoke all on function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean)from public,anon,authenticated;grant execute on function public.get_assigned_field_walkthroughs()to authenticated;grant execute on function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean)to authenticated;notify pgrst,'reload schema';commit;
