begin;
alter function public.get_assigned_field_walkthroughs() rename to get_assigned_field_walkthroughs_event_phase_20260928;
revoke all on function public.get_assigned_field_walkthroughs_event_phase_20260928() from public,anon,authenticated;
create function public.get_assigned_field_walkthroughs()returns jsonb language sql stable security definer set search_path=''as $function$ with p as(select x.value,x.ordinality from jsonb_array_elements(public.get_assigned_field_walkthroughs_event_phase_20260928())with ordinality x(value,ordinality))select coalesce(jsonb_agg(p.value||jsonb_build_object('measurements',coalesce(p.value->'measurements','{}'::jsonb)||jsonb_build_object('warehouseCleaningAssessment',jsonb_build_object('fieldWalkthrough',w.measurements->'warehouseCleaningAssessment'->'fieldWalkthrough')))order by p.ordinality),'[]'::jsonb)from p join public.walkthroughs w on w.id=(p.value->>'id')::uuid;$function$;
alter function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean)rename to submit_assigned_field_walkthrough_event_phase_20260928;
revoke all on function public.submit_assigned_field_walkthrough_event_phase_20260928(uuid,jsonb,boolean)from public,anon,authenticated;
create function public.submit_assigned_field_walkthrough(p_id uuid,p_measurements jsonb,p_complete boolean default false)returns void language plpgsql security definer set search_path=''as $function$
declare w public.walkthroughs;e uuid:=public.current_employee_id();n jsonb:=p_measurements;f jsonb;a jsonb;old jsonb;k text;v jsonb;r text;
begin
if jsonb_typeof(n#>'{warehouseCleaningAssessment,fieldWalkthrough}')='null'then n:=n-'warehouseCleaningAssessment';end if;if not n?'warehouseCleaningAssessment'then perform public.submit_assigned_field_walkthrough_event_phase_20260928(p_id,n,p_complete);return;end if;if(select auth.uid())is null or e is null or not public.has_any_role(array['Crew Lead','Scrub Technician'])then raise exception'Field access denied'using errcode='42501';end if;select * into w from public.walkthroughs where id=p_id for update;if not found or w.status<>'Scheduled'or w.archived_at is not null or w.assigned_employee_id is distinct from e or w.walkthrough_date is null or w.walkthrough_time is null then raise exception'Scheduled assignment no longer available';end if;if coalesce(w.measurements->>'serviceType','')<>'Warehouse Cleaning'then raise exception'Warehouse observations require COM-WAREHOUSE';end if;
f:=n->'warehouseCleaningAssessment'->'fieldWalkthrough';a:=f->'answers';if jsonb_typeof(n->'warehouseCleaningAssessment')<>'object'or jsonb_typeof(f)<>'object'or jsonb_typeof(a)<>'object'or exists(select 1 from jsonb_object_keys(n->'warehouseCleaningAssessment')x where x<>'fieldWalkthrough')or exists(select 1 from jsonb_object_keys(f)x where x<>'answers')then raise exception'Invalid Warehouse field walkthrough';end if;
for k,v in select * from jsonb_each(a)loop if k!~'^(warehouseType|warehouseTypeOther|operatingStatus|operationLimits|operationNotes|overallCondition|floor(Type|Condition|Dust|Debris|Sticky|Oil|Marks|Buildup|Precautions|Notes)|aisle(Condition|Debris|Dust|Obstructions|Inventory|Markings|Traffic|Notes)|racking(Condition|Observation[1-5])|dock(Condition|Observation[1-7])|shipping(Condition|Observation[1-5])|equipment(Condition|Observation[1-6])|highDustCondition|dust(Beams|Pipes|Vents|Racking|Ceiling)|elevatedAccess|elevatedNotes|office(Condition|Observation[1-6])|restroom(Condition|Observation[1-6])|breakroom(Condition|Observation[1-6])|waste(Level|Cardboard|Plastic|Packaging|Pallets)|largeReceptacles|dumpsterAccess|restrictedWaste|spillsObserved|spillTypes|spillNotes|safety(Forklift|Machinery|Zones|Ppe|Loading|Locked|Elevated|Other|Notes)|entry(Condition|Observation[1-5])|extraAttention|frequencyObservation|frequencyNotes|serviceSuitable|recommendedServices|serviceNotes|laborLevel|recommendedCrew|serviceDuration|materialException|exceptionNotes|technicianConfirmation)$'then raise exception'Invalid Warehouse answer: %',k;end if;if jsonb_typeof(v)='string'and length(v#>>'{}')>5000 then raise exception'Warehouse answer is too long: %',k;end if;if jsonb_typeof(v)='array'and(jsonb_array_length(v)>20 or exists(select 1 from jsonb_array_elements(v)x where jsonb_typeof(x)<>'string'or length(x#>>'{}')>200))then raise exception'Invalid Warehouse selection: %',k;end if;if jsonb_typeof(v)not in('string','array','boolean','null')then raise exception'Invalid Warehouse answer type: %',k;end if;end loop;
if p_complete then foreach r in array array['warehouseType','operatingStatus','overallCondition','floorType','floorCondition','aisleCondition','rackingCondition','dockCondition','shippingCondition','equipmentCondition','highDustCondition','officeCondition','restroomCondition','breakroomCondition','wasteLevel','spillsObserved','extraAttention','frequencyObservation','serviceSuitable','laborLevel','recommendedCrew','serviceDuration','materialException']loop if not a?r or a->r in('null'::jsonb,'""'::jsonb,'[]'::jsonb)then raise exception'Required Warehouse answer is missing: %',r;end if;end loop;if a->>'warehouseType'='Other'and nullif(btrim(a->>'warehouseTypeOther'),'')is null then raise exception'Other warehouse type is required';end if;if a->>'operatingStatus'<>'Closed/vacant'and nullif(btrim(a->>'operationLimits'),'')is null then raise exception'Operation limitation answer is required';end if;if a->>'operationLimits'='Yes'and nullif(btrim(a->>'operationNotes'),'')is null then raise exception'Operation notes are required';end if;if a->>'spillsObserved'='Yes'and(a->'spillTypes'is null or a->'spillTypes'='[]'::jsonb or nullif(btrim(a->>'spillNotes'),'')is null)then raise exception'Spill details are required';end if;if a->>'frequencyObservation'<>'Scheduled frequency appears appropriate'and nullif(btrim(a->>'frequencyNotes'),'')is null then raise exception'Frequency notes are required';end if;if a->>'serviceSuitable'='Additional service may be required'and(a->'recommendedServices'is null or a->'recommendedServices'='[]'::jsonb)then raise exception'Recommended services are required';end if;if a->>'serviceSuitable'<>'Yes — Warehouse Cleaning appears appropriate'and nullif(btrim(a->>'serviceNotes'),'')is null then raise exception'Service notes are required';end if;if a->>'materialException'='Yes'and nullif(btrim(a->>'exceptionNotes'),'')is null then raise exception'Exception notes are required';end if;if a->'technicianConfirmation'is distinct from'true'::jsonb then raise exception'Final technician confirmation is required';end if;end if;
perform public.submit_assigned_field_walkthrough_event_phase_20260928(p_id,n-'warehouseCleaningAssessment',p_complete);old:=coalesce(w.measurements->'warehouseCleaningAssessment','{}'::jsonb);update public.walkthroughs set measurements=jsonb_set(measurements,'{warehouseCleaningAssessment}',jsonb_set(old,'{fieldWalkthrough}',f,true),true)where id=p_id;end;$function$;
revoke all on function public.get_assigned_field_walkthroughs()from public,anon,authenticated;revoke all on function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean)from public,anon,authenticated;grant execute on function public.get_assigned_field_walkthroughs()to authenticated;grant execute on function public.submit_assigned_field_walkthrough(uuid,jsonb,boolean)to authenticated;notify pgrst,'reload schema';commit;
