"use client";

import type { CatalogAddonSnapshot, ServiceAddon } from "@/types/serviceCatalog";

export function CatalogAddonPicker({ addons, selected, setSelected, snapshots, setSnapshots }: { addons: ServiceAddon[]; selected: string[]; setSelected: (value: string[]) => void; snapshots?: CatalogAddonSnapshot[]; setSnapshots?: (value: CatalogAddonSnapshot[]) => void }) {
  const remaining = addons.filter((addon) => !selected.includes(addon.addon_name));
  function updateSnapshot(addon:ServiceAddon,quantity:number){if(!setSnapshots)return;const pricingType=String(addon.pricing_config.pricing_type??"Flat Price"),unitName=String(addon.pricing_config.unit_name??addon.unit_label??"").trim()||null,unitPrice=Number(addon.pricing_config.unit_price??addon.price);setSnapshots([...(snapshots??[]).filter(item=>item.catalogAddonId!==addon.id),{id:addon.id,catalogAddonId:addon.id,name:addon.addon_name,description:addon.description,price:addon.price,pricingModel:addon.pricing_model,unitLabel:addon.unit_label,pricingType:pricingType==="Per Unit"?"Per Unit":"Flat Price",quantity,unitName,unitPrice,lineTotal:pricingType==="Per Unit"?quantity*unitPrice:addon.price}])}
  return <fieldset><legend className="mb-2 text-xs font-bold text-neutral-700">Catalog Add-Ons</legend>{addons.length === 0 ? <p className="rounded-lg border border-dashed bg-neutral-50 p-3 text-sm text-neutral-500">No Add-Ons configured for this service.</p> : <select value="" disabled={remaining.length === 0} onChange={(event) => { if (event.target.value && !selected.includes(event.target.value)) { const addon=addons.find(item=>item.addon_name===event.target.value);setSelected([...selected, event.target.value]);if(addon)updateSnapshot(addon,1); } }} className={inputClass}><option value="">{remaining.length === 0 ? "All available Add-Ons selected" : "Select Add-On"}</option>{remaining.map((addon) => <option key={addon.id} value={addon.addon_name}>{addon.addon_name} — {money(addon.price)}</option>)}</select>}<div className="mt-3 space-y-2">{selected.map((name) => { const addon = addons.find((item) => item.addon_name === name); const perUnit=addon&&addon.pricing_config.pricing_type==="Per Unit",snapshot=snapshots?.find(item=>item.catalogAddonId===addon?.id); return addon ? <div key={addon.id} className="flex items-start justify-between gap-4 rounded-lg border bg-neutral-50 p-3"><div><p className="text-sm font-bold text-[#143d1a]">{addon.addon_name} — {money(perUnit?Number(addon.pricing_config.unit_price??addon.price):addon.price)}</p>{perUnit&&<label className="mt-2 block text-xs font-bold text-neutral-600">Quantity ({String(addon.pricing_config.unit_name??addon.unit_label??"unit")})<input type="number" min="1" step="1" value={snapshot?.quantity??1} onChange={event=>updateSnapshot(addon,Number(event.target.value))} className={`${inputClass} mt-1`}/></label>}{addon.description && <p className="mt-1 text-xs text-neutral-500">{addon.description}</p>}<p className="mt-1 text-xs text-neutral-400">{perUnit&&snapshot?`${snapshot.quantity} ${snapshot.unitName}${snapshot.quantity===1?"":"s"} × ${money(snapshot.unitPrice??addon.price)} = ${money(snapshot.lineTotal??0)}`:addon.pricing_model}{addon.unit_label ? ` · ${addon.unit_label}` : ""}</p></div><button type="button" onClick={() => {setSelected(selected.filter((item) => item !== name));setSnapshots?.((snapshots??[]).filter(item=>item.catalogAddonId!==addon.id))}} className="text-xs font-bold text-red-700">Remove</button></div> : null; })}</div></fieldset>;
}

function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value); }
const inputClass = "w-full rounded-lg border border-neutral-200 bg-white px-3.5 py-2.5 text-sm text-neutral-800 outline-none focus:border-[#d4af37] focus:ring-2 focus:ring-[#d4af37]/15 disabled:bg-neutral-50 disabled:text-neutral-500";
