import type { Metadata } from "next";
import { ContactBand, FeatureList, PageHero, RelatedServices, SectionHeading } from "@/components/site/SiteSections";

export const metadata: Metadata = {
  title: { absolute: "Residential & House Cleaning in Los Angeles | StudioScrubz" },
  description: "Professional house and apartment cleaning, including standard, deep, move-in, move-out, and recurring home cleaning across Los Angeles County and the San Fernando Valley.",
  alternates: { canonical: "https://studioscrubz.com/residential" },
  openGraph: {
    title: "Residential & House Cleaning in Los Angeles | StudioScrubz",
    description: "Standard, deep, move-in, move-out, and recurring cleaning for homes and apartments across Los Angeles County and the San Fernando Valley.",
    url: "https://studioscrubz.com/residential",
  },
};

const residentialServices = [
  ["Standard Cleaning", "Routine maintenance of commonly used areas and surfaces, including general dusting, accessible kitchen and bathroom surfaces, mirrors, floors, trash removal, and light tidying within the confirmed scope."],
  ["Deep Cleaning", "A more detailed clean for homes that need extra attention, including the core tasks of Standard Cleaning. The confirmed scope adds attention to buildup, baseboards, doors and trim, fixtures, detailed kitchen and bathroom surfaces, and commonly overlooked areas."],
  ["Move-In / Move-Out", "Detailed cleaning for empty or mostly empty homes and apartments between occupants. We confirm kitchens, bathrooms, cabinets and drawers, floors, baseboards, fixtures, closets, and other interior surfaces in the scope to prepare the home for its next occupants."],
  ["StudioScrubz Upkeep Plan", "3 light maintenance visits per month after the appropriate initial service. The agreed recurring scope focuses on dust, dirt, and everyday buildup to maintain your home between heavier cleanings."],
] as const;

const includedServices = [
  ["Standard Cleaning", "Routine care for a fresh, maintained home.", ["General dusting", "Accessible surfaces", "Kitchen surfaces", "Bathroom cleaning", "Mirrors", "Vacuuming and floor care", "Trash removal", "Light general tidying"]],
  ["Deep Cleaning", "Core Standard Cleaning attention with added detail where needed.", ["Baseboards", "Doors and trim", "Detailed fixtures", "Heavier buildup", "Detailed kitchen surfaces", "Detailed bathroom surfaces", "Commonly overlooked areas", "Additional detail work based on condition"]],
  ["Move-In / Move-Out", "Designed for empty or mostly empty properties.", ["Kitchen surfaces", "Bathroom cleaning", "Inside accessible cabinets and drawers", "Closets", "Baseboards", "Fixtures", "Floors", "Interior surfaces", "Turnover and readiness detailing"]],
] as const;

export default function ResidentialPage(){return <>
  <PageHero eyebrow="Residential cleaning" title="Residential and House Cleaning for Homes and Apartments." copy="StudioScrubz provides professional house and apartment cleaning across Los Angeles County and the San Fernando Valley. Choose from Standard Cleaning, Deep Cleaning, Move-In / Move-Out Cleaning, or the StudioScrubz Upkeep Plan based on your home's condition, priorities, and requested service." cta="Get a Home Cleaning Estimate"/>
  <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Residential services" title="Choose the right level of home cleaning." copy="Each service has a distinct purpose, from routine cleaning of commonly used rooms and surfaces to deeper detail, residential transitions, and recurring upkeep."/><div className="mt-10 grid gap-5 md:grid-cols-2">{residentialServices.map(([title,copy])=><article id={title === "Standard Cleaning" ? "standard-cleaning" : title === "Deep Cleaning" ? "deep-cleaning" : title.startsWith("Move") ? "move-cleaning" : undefined} key={title} className="rounded-[1.6rem] border border-[#143d1a]/10 bg-[#f4f7f1] p-7"><h2 className="text-2xl font-extrabold text-[#143d1a]">{title}</h2><p className="mt-3 leading-7 text-neutral-600">{copy}</p></article>)}</div></div></section>
  <section className="bg-[#eef3ea] px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="What's included" title="Compare the level of cleaning at a glance." copy="Each service is shaped around the property and confirmed scope, with deeper detail added as the service level increases."/><div className="mt-10 grid gap-5 lg:grid-cols-3">{includedServices.map(([title,summary,items])=><article key={title} className="rounded-[1.6rem] border border-[#143d1a]/10 bg-white p-7 shadow-[0_16px_45px_rgba(20,61,26,.05)]"><h2 className="text-2xl font-extrabold text-[#143d1a]">{title}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{summary}</p><ul className="mt-6 grid gap-3">{items.map(item=><li key={item} className="flex gap-3 text-sm font-bold text-[#29472d]"><span aria-hidden="true" className="text-[#d4af37]">✦</span><span>{item}</span></li>)}</ul></article>)}</div><aside className="mt-6 rounded-[1.6rem] border border-[#143d1a]/10 bg-[#fff9e7] p-6 sm:p-7"><h2 className="text-xl font-extrabold text-[#143d1a]">StudioScrubz Upkeep Plan</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-neutral-600">Recurring upkeep includes 3 light maintenance visits per month after the appropriate initial cleaning. The service frequency and maintenance tasks are agreed around your home. Confirm available add-ons before scheduling so they are included in your estimate and service scope.</p></aside><p className="mt-6 text-sm leading-6 text-neutral-500">Final cleaning scope is based on the service selected, property condition, access, and any approved add-on services. Move-in and move-out cleaning supports a residential transition but does not guarantee a particular property-condition assessment, deposit outcome, or landlord approval.</p></div></section>
  <section id="turnovers" className="px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><SectionHeading eyebrow="Your home cleaning plan" title="Clear details from estimate to final review." copy="Tell us about your house or apartment, its condition, and your priorities for kitchens, bathrooms, bedrooms, living areas, floors, and other requested spaces. We confirm the service level, scope, and requested add-ons, using a walkthrough when needed, then provide a professional estimate. Once you confirm the details, we coordinate scheduling, complete the cleaning, and perform a final service review."/><FeatureList items={["Clear service scope","Professional estimate","Confirmed service details","Available add-on services","Professional communication","Coordinated scheduling and final review"]}/></div></section>
  <section className="bg-[#eef3ea] px-5 py-20 sm:px-8 sm:py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Service area" title="House and apartment cleaning across Los Angeles and the San Fernando Valley." copy="StudioScrubz serves homes and apartments across Los Angeles County, with a strong focus on the San Fernando Valley, including Winnetka, Canoga Park, Woodland Hills, Reseda, Chatsworth, Northridge, Van Nuys, Encino, and Tarzana. Availability in surrounding areas depends on the home, requested service, location, scope, and scheduling."/></div></section>
  <RelatedServices links={[["Airbnb / Short-Term Rental Cleaning", "/airbnb-cleaning"], ["Standard Cleaning", "#standard-cleaning"], ["Deep Cleaning", "#deep-cleaning"], ["Move-In / Move-Out", "#move-cleaning"]]}/><ContactBand title="Let's make home feel easier."/>
</>}
