import type { Metadata } from "next";
import { ContactBand, FeatureList, PageHero, SectionHeading } from "@/components/site/SiteSections";
export const metadata: Metadata = { title: { absolute: "Residential Cleaning | StudioScrubz" }, description: "Flexible residential cleaning, deep cleaning, move-in and move-out cleaning, and monthly upkeep in the Los Angeles area.", alternates: { canonical: "https://studioscrubz.com/residential" } };

const residentialServices = [
  ["Standard Cleaning", "Routine cleaning designed to keep your home fresh, comfortable, and maintained. Depending on the space, service may include general dusting, accessible surfaces, kitchen and bathroom cleaning, mirrors, floors, trash removal, and light tidying."],
  ["Deep Cleaning", "A more detailed clean for homes that need extra attention, including the core tasks of Standard Cleaning. The service focuses more closely on buildup, baseboards, doors and trim, fixtures, detailed kitchen and bathroom surfaces, and commonly overlooked areas."],
  ["Move-In / Move-Out", "Thorough cleaning designed for empty or mostly empty homes between occupants. Service may include kitchens, bathrooms, cabinets and drawers, floors, baseboards, fixtures, closets, and other interior surfaces to help prepare the property for occupancy or turnover."],
  ["Monthly Upkeep", "Recurring maintenance cleaning designed to keep your home consistently cared for from month to month. Regular visits focus on reducing dust, dirt, and everyday buildup between professional cleanings."],
] as const;

export default function ResidentialPage(){return <><PageHero eyebrow="Residential cleaning" title="A cleaner home, without the scramble." copy="Choose dependable one-time or recurring cleaning shaped around your home, priorities, and preferred rhythm."/><section className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Residential services" title="The right level of care for right now."/><div className="mt-10 grid gap-5 md:grid-cols-2">{residentialServices.map(([title,copy])=><article id={title.startsWith("Move")?"move-cleaning":undefined} key={title} className="rounded-[1.6rem] border border-[#143d1a]/10 bg-[#f4f7f1] p-7"><h2 className="text-2xl font-extrabold text-[#143d1a]">{title}</h2><p className="mt-3 leading-7 text-neutral-600">{copy}</p></article>)}</div></div></section><section id="turnovers" className="bg-[#eef3ea] px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><SectionHeading eyebrow="Built around real life" title="Flexible options. Clear communication." copy="A walkthrough helps us understand condition, occupancy, pets, add-ons, and the details that make your home unique."/><FeatureList items={["Dependable cleaning","Flexible service options","Detailed walkthrough process","Available add-on services","Professional communication","One-time or recurring frequency"]}/></div></section><ContactBand title="Let’s make home feel easier."/></>}
